Repository ROCm/MIOpen, pull requests merged in 2020-10, with the labels that each got.

#478 Workaround for SWDEV-253606
  src/batch_norm.cpp
  src/include/miopen/batch_norm.hpp
  src/ocl/batchnormocl.cpp
Labels: bug, complexity_low, priority_blocker

#471 [dynamic-igemm][fwd-xdlops]Assembly implementation of dynamic implicit-gemm generic tensor contraction for convolution-forward
  src/CMakeLists.txt
  src/include/miopen/solver.hpp
  src/kernels/dynamic_igemm/igemm_gtc_fwd/igemm_fwd_gtc_gfx908.s
  src/kernels/dynamic_igemm/igemm_gtc_fwd/igemm_fwd_gtc_gfx908_004x064.inc
  src/kernels/dynamic_igemm/igemm_gtc_fwd/igemm_fwd_gtc_gfx908_008x064.inc
  src/kernels/dynamic_igemm/igemm_gtc_fwd/igemm_fwd_gtc_gfx908_016x016.inc
  src/kernels/dynamic_igemm/igemm_gtc_fwd/igemm_fwd_gtc_gfx908_016x032.inc
  src/kernels/dynamic_igemm/igemm_gtc_fwd/igemm_fwd_gtc_gfx908_016x064.inc
  src/kernels/dynamic_igemm/igemm_gtc_fwd/igemm_fwd_gtc_gfx908_032x016.inc
  src/kernels/dynamic_igemm/igemm_gtc_fwd/igemm_fwd_gtc_gfx908_032x032.inc
  src/kernels/dynamic_igemm/igemm_gtc_fwd/igemm_fwd_gtc_gfx908_032x064.inc
  src/kernels/dynamic_igemm/igemm_gtc_fwd/igemm_fwd_gtc_gfx908_032x128.inc
  src/kernels/dynamic_igemm/igemm_gtc_fwd/igemm_fwd_gtc_gfx908_032x256.inc
  src/kernels/dynamic_igemm/igemm_gtc_fwd/igemm_fwd_gtc_gfx908_064x004.inc
  src/kernels/dynamic_igemm/igemm_gtc_fwd/igemm_fwd_gtc_gfx908_064x008.inc
  src/kernels/dynamic_igemm/igemm_gtc_fwd/igemm_fwd_gtc_gfx908_064x016.inc
  src/kernels/dynamic_igemm/igemm_gtc_fwd/igemm_fwd_gtc_gfx908_064x032.inc
  src/kernels/dynamic_igemm/igemm_gtc_fwd/igemm_fwd_gtc_gfx908_064x064.inc
  src/kernels/dynamic_igemm/igemm_gtc_fwd/igemm_fwd_gtc_gfx908_064x128.inc
  src/kernels/dynamic_igemm/igemm_gtc_fwd/igemm_fwd_gtc_gfx908_064x256.inc
  src/kernels/dynamic_igemm/igemm_gtc_fwd/igemm_fwd_gtc_gfx908_128x032.inc
  src/kernels/dynamic_igemm/igemm_gtc_fwd/igemm_fwd_gtc_gfx908_128x064.inc
  src/kernels/dynamic_igemm/igemm_gtc_fwd/igemm_fwd_gtc_gfx908_128x128.inc
  src/kernels/dynamic_igemm/igemm_gtc_fwd/igemm_fwd_gtc_gfx908_128x256.inc
  src/kernels/dynamic_igemm/igemm_gtc_fwd/igemm_fwd_gtc_gfx908_256x032.inc
  src/kernels/dynamic_igemm/igemm_gtc_fwd/igemm_fwd_gtc_gfx908_256x064.inc
  src/kernels/dynamic_igemm/igemm_gtc_fwd/igemm_fwd_gtc_gfx908_256x128.inc
  src/mlo_dir_conv.cpp
  src/solver.cpp
  src/solver/conv_asm_implicit_gemm_gtc_fwd.cpp
  test/CMakeLists.txt
Labels: priority_high

#475 Update package dependencies to rocm-clang-ocl and hip-rocclr
  CMakeLists.txt
Labels: complexity_low, quality

#454 MP_bidirect_winograd with xdlops [FP32]
  doc/src/DebugAndLogging.md
  src/include/miopen/solver.hpp
  src/kernels/xform_bidirect_winograd_code.inc
  src/mlo_dir_conv.cpp
  src/solver.cpp
  src/solver/conv_MP_bidirectional_winograd.cpp
Labels: complexity_high, enhancement, need_find_db_update, need_perf_db_update, performance, priority_middle

#404 Tensor contraction for igemm fwd
  src/CMakeLists.txt
  src/include/miopen/solver.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_forward_implicit_gemm_v4r5_xdlops_nchw_kcyx_nkhw.hpp
  src/kernels/composable_kernel/include/tensor_operation/blockwise_gemm_xdlops.hpp
  src/kernels/composable_kernel/include/tensor_operation/gridwise_gemm_xdlops_fp16_bfp16.hpp
  src/kernels/composable_kernel/src/kernel_wrapper/gridwise_convolution_forward_implicit_gemm_v4r5_xdlops_nchw_kcyx_nkhw.cpp
  src/mlo_dir_conv.cpp
  src/solver.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r5_xdlops.cpp
Labels: performance, priority_high

#444 [igemm]this kernel can support fwd resnet50 first layer
  src/CMakeLists.txt
  src/include/miopen/solver.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_forward_implicit_gemm_v4r4_xdlops_nchw_kcyx_nkhw_padded_gemm.hpp
  src/kernels/composable_kernel/src/kernel_wrapper/gridwise_convolution_forward_implicit_gemm_v4r4_xdlops_nchw_kcyx_nkhw_padded_gemm.cpp
  src/mlo_dir_conv.cpp
  src/solver.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops_padded_gemm.cpp
Labels: priority_high

#441 [dynamic-igemm][bwd-xdlops]enable asm igemm generic tensor contraction for backward_data
  src/CMakeLists.txt
  src/conv/invokers/impl_gemm_dynamic.cpp
  src/include/miopen/solver.hpp
  src/kernels/dynamic_igemm/igemm_gtc_bwd/igemm_bwd_gtc_gfx908.s
  src/kernels/dynamic_igemm/igemm_gtc_bwd/igemm_bwd_gtc_gfx908_004x064.inc
  src/kernels/dynamic_igemm/igemm_gtc_bwd/igemm_bwd_gtc_gfx908_008x064.inc
  src/kernels/dynamic_igemm/igemm_gtc_bwd/igemm_bwd_gtc_gfx908_016x032.inc
  src/kernels/dynamic_igemm/igemm_gtc_bwd/igemm_bwd_gtc_gfx908_016x064.inc
  src/kernels/dynamic_igemm/igemm_gtc_bwd/igemm_bwd_gtc_gfx908_016x128.inc
  src/kernels/dynamic_igemm/igemm_gtc_bwd/igemm_bwd_gtc_gfx908_016x256.inc
  src/kernels/dynamic_igemm/igemm_gtc_bwd/igemm_bwd_gtc_gfx908_032x016.inc
  src/kernels/dynamic_igemm/igemm_gtc_bwd/igemm_bwd_gtc_gfx908_032x032.inc
  src/kernels/dynamic_igemm/igemm_gtc_bwd/igemm_bwd_gtc_gfx908_032x064.inc
  src/kernels/dynamic_igemm/igemm_gtc_bwd/igemm_bwd_gtc_gfx908_032x128.inc
  src/kernels/dynamic_igemm/igemm_gtc_bwd/igemm_bwd_gtc_gfx908_032x256.inc
  src/kernels/dynamic_igemm/igemm_gtc_bwd/igemm_bwd_gtc_gfx908_064x004.inc
  src/kernels/dynamic_igemm/igemm_gtc_bwd/igemm_bwd_gtc_gfx908_064x008.inc
  src/kernels/dynamic_igemm/igemm_gtc_bwd/igemm_bwd_gtc_gfx908_064x016.inc
  src/kernels/dynamic_igemm/igemm_gtc_bwd/igemm_bwd_gtc_gfx908_064x032.inc
  src/kernels/dynamic_igemm/igemm_gtc_bwd/igemm_bwd_gtc_gfx908_064x064.inc
  src/kernels/dynamic_igemm/igemm_gtc_bwd/igemm_bwd_gtc_gfx908_064x128.inc
  src/kernels/dynamic_igemm/igemm_gtc_bwd/igemm_bwd_gtc_gfx908_064x256.inc
  src/kernels/dynamic_igemm/igemm_gtc_bwd/igemm_bwd_gtc_gfx908_128x016.inc
  src/kernels/dynamic_igemm/igemm_gtc_bwd/igemm_bwd_gtc_gfx908_128x032.inc
  src/kernels/dynamic_igemm/igemm_gtc_bwd/igemm_bwd_gtc_gfx908_128x064.inc
  src/kernels/dynamic_igemm/igemm_gtc_bwd/igemm_bwd_gtc_gfx908_128x128.inc
  src/kernels/dynamic_igemm/igemm_gtc_bwd/igemm_bwd_gtc_gfx908_128x256.inc
  src/kernels/dynamic_igemm/igemm_gtc_bwd/igemm_bwd_gtc_gfx908_256x016.inc
  src/kernels/dynamic_igemm/igemm_gtc_bwd/igemm_bwd_gtc_gfx908_256x032.inc
  src/kernels/dynamic_igemm/igemm_gtc_bwd/igemm_bwd_gtc_gfx908_256x064.inc
  src/kernels/dynamic_igemm/igemm_gtc_bwd/igemm_bwd_gtc_gfx908_256x128.inc
  src/mlo_dir_conv.cpp
  src/solver.cpp
  src/solver/conv_asm_implicit_gemm_gtc_bwd.cpp
  test/CMakeLists.txt
Labels: priority_high

#307 GPU'less compile
  src/binary_cache.cpp
  src/hip/handlehip.cpp
  src/hipoc/hipoc_kernel.cpp
  src/hipoc/hipoc_program.cpp
  src/include/miopen/device_name.hpp
  src/include/miopen/generic_search.hpp
  src/include/miopen/hipoc_kernel.hpp
  src/include/miopen/oclkernel.hpp
  src/kernel_cache.cpp
  src/ocl/convolutionocl.cpp
  src/ocl/handleocl.cpp
  src/ocl_kernel.cpp
Labels: priority_blocker

#486 Comment out undef of __AMDGCN__
  src/kernels/MIOpenBatchNormFwdTrainSpatial.cl
Labels: complexity_low, quality

#487 Remove deprecated iGEMM xdlops solver and kernels
  src/CMakeLists.txt
  src/conv/invokers/impl_gemm.cpp
  src/include/miopen/solver.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_backward_data_implicit_gemm_v1r1_xdlops_fp16_bfp16_gnchw_gkcyx_gnkhw.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_backward_data_implicit_gemm_v1r1_xdlops_fp16_bfp16_nchw_kcyx_nkhw.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_backward_data_implicit_gemm_v1r1_xdlops_nchw_kcyx_nkhw.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_backward_data_implicit_gemm_v4r1_xdlops_fp16_bfp16_gnchw_gkcyx_gnkhw.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_backward_data_implicit_gemm_v4r1_xdlops_fp16_bfp16_nchw_kcyx_nkhw.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_backward_data_implicit_gemm_v4r1_xdlops_gnchw_gkcyx_gnkhw.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_backward_data_implicit_gemm_v4r1_xdlops_nchw_kcyx_nkhw.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_forward_implicit_gemm_v4r4_xdlops_nchw_kcyx_nkhw.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_implicit_gemm_v4_fp16_bfp16_nchw_kcyx_nkhw_lds_double_buffer.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_implicit_gemm_v4r1_nchw_kcyx_nkhw_lds_double_buffer_deprecated.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_implicit_gemm_v4r4_gen_xdlops_fp16_bfp16_fwd_gnchw_gkcyx_gnkhw_lds_double_buffer.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_implicit_gemm_v4r4_gen_xdlops_fp16_bfp16_fwd_nchw_kcyx_nkhw_lds_double_buffer.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_implicit_gemm_v4r4_gen_xdlops_fp16_bfp16_wrw_gnchw_gkcyx_gnkhw_lds_double_buffer.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_implicit_gemm_v4r4_gen_xdlops_fp16_bfp16_wrw_nchw_kcyx_nkhw_lds_double_buffer.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_implicit_gemm_v4r4_gen_xdlops_fwd_fp32_gnchw_gkcyx_gnkhw_lds_double_buffer.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_implicit_gemm_v4r4_gen_xdlops_fwd_fp32_nchw_kcyx_nkhw_lds_double_buffer.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_implicit_gemm_v4r4_gen_xdlops_gnchw_gkcyx_gnkhw_lds_double_buffer.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_implicit_gemm_v4r4_gen_xdlops_nchw_kcyx_nkhw_lds_double_buffer.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_implicit_gemm_v4r4_gen_xdlops_wrw_fp32_nchw_kcyx_nkhw_lds_double_buffer.hpp
  src/kernels/composable_kernel/src/kernel_wrapper/gridwise_convolution_backward_data_implicit_gemm_v1r1_xdlops_gnchw_gkcyx_gnkhw.cpp
  src/kernels/composable_kernel/src/kernel_wrapper/gridwise_convolution_backward_data_implicit_gemm_v4r1_xdlops_gnchw_gkcyx_gnkhw.cpp
  src/kernels/composable_kernel/src/kernel_wrapper/gridwise_convolution_backward_data_implicit_gemm_v4r1_xdlops_nchw_kcyx_nkhw.cpp
  src/kernels/composable_kernel/src/kernel_wrapper/gridwise_convolution_implicit_gemm_v4r4_gen_xdlops_fwd_fp32_gnchw_gkcyx_gnkhw_lds_double_buffer.cpp
  src/kernels/composable_kernel/src/kernel_wrapper/gridwise_convolution_implicit_gemm_v4r4_gen_xdlops_fwd_fp32_nchw_kcyx_nkhw_lds_double_buffer.cpp
  src/kernels/composable_kernel/src/kernel_wrapper/gridwise_convolution_implicit_gemm_v4r4_gen_xdlops_gnchw_gkcyx_gnkhw_lds_double_buffer.cpp
  src/kernels/composable_kernel/src/kernel_wrapper/gridwise_convolution_implicit_gemm_v4r4_gen_xdlops_wrw_fp32_nchw_kcyx_nkhw_lds_double_buffer.cpp
  src/mlo_dir_conv.cpp
  src/solver.cpp
  src/solver/conv_hip_implicit_gemm_bwd_data_v4r1_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_v4r4_gen_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_v4r4_gen_xdlops_fwd_fp32.cpp
  src/solver/conv_hip_implicit_gemm_v4r4_gen_xdlops_wrw_fp32.cpp
Labels: priority_high

#499 Passing HIP compiler version to composable kernel
  src/include/miopen/hip_build_utils.hpp
  src/kernels/composable_kernel/include/utility/amd_buffer_addressing.hpp
  src/kernels/composable_kernel/include/utility/config.hpp
  src/kernels/composable_kernel/include/utility/in_memory_operation.hpp
  src/solver/conv_hip_implicit_gemm_bwd_data_v1r1.cpp
  src/solver/conv_hip_implicit_gemm_bwd_data_v4r1.cpp
  src/solver/conv_hip_implicit_gemm_bwd_data_v4r1_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v1r1_xdlops_nchw_kcyx_nkhw.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops_padded_gemm.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r5_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_v4r1.cpp
  src/solver/conv_hip_implicit_gemm_v4r4.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_wrw_weights_v4r4.cpp
  src/solver/implicitgemm_util.hpp
Labels: priority_blocker

#497 Add ConvHipImplicitGemmForwardV4R4Xdlops_Padded_Gemm in solver list
  src/mlo_dir_conv.cpp
Labels: bug

#343 [igemm] Adding flexible layout support
  driver/conv_driver.hpp
  driver/tensor_driver.hpp
  src/conv/problem_description.cpp
  src/hipoc/hipoc_program.cpp
  src/include/miopen/conv/problem_description.hpp
  src/include/miopen/problem_description.hpp
  src/include/miopen/tensor.hpp
  src/problem_description.cpp
  src/solver/conv_MP_bidirectional_winograd.cpp
  src/solver/conv_asm_1x1u.cpp
  src/solver/conv_asm_1x1u_stride2.cpp
  src/solver/conv_asm_3x3u.cpp
  src/solver/conv_asm_5x10u2v2b1.cpp
  src/solver/conv_asm_5x10u2v2f1.cpp
  src/solver/conv_asm_7x7c3h224w224k64u2v2p3q3f1.cpp
  src/solver/conv_asm_dir_BwdWrW1x1.cpp
  src/solver/conv_asm_dir_BwdWrW3x3.cpp
  src/solver/conv_bin_wino3x3U.cpp
  src/solver/conv_bin_winoRxS.cpp
  src/solver/conv_multipass_wino3x3WrW.cpp
  src/solver/conv_winoRxS_f2x3.cpp
  src/solver/conv_winoRxS_f3x2.cpp
  src/solver/implicitgemm_util.hpp
Labels: complexity_middle, enhancement, priority_high

#501 Enlarge tuning range of ConvHipImplicitGemmWrwV4R4Xdlops
  src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops.cpp
Labels: bug, priority_high

#515 Fix "Workaround for SWDEV-255735" (PR 505)
  src/comgr.cpp
  src/include/miopen/gcn_asm_utils.hpp
  src/ocl/gcn_asm_utils.cpp
Labels: bug, priority_blocker

#510 fix bug about wrw atomic add
  src/include/miopen/solver.hpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops.cpp
Labels: bug, need_perf_db_update

#539 [rocm-3.10.x-staging] Fix for: W/A: disable ConvAsmBwdWrW3x3 for stride >= 2 && gfx9
  src/solver/conv_asm_dir_BwdWrW3x3.cpp
Labels: urgency_blocker

#529 [COMGR] OCL builds: fix for sram-ecc feature for gfx900
  src/comgr.cpp
Labels: urgency_blocker

#535 Add spare in the tuning of V4R5
  src/include/miopen/solver.hpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r5_xdlops.cpp
Labels: urgency_medium

#530 revise int8 conv test validation check based on latest conv host
  test/conv_common.hpp
Labels: bug, complexity_low, testing, value_high

#534 [WORKAROUND] Disable ConvAsmBwdWrW3x3 for stride >= 2 && gfx9
  src/solver/conv_asm_dir_BwdWrW3x3.cpp
Labels: urgency_blocker

#527 Fix for huge pooling workspace (library) and for huge tensors (driver)
  driver/tensor_driver.hpp
  src/pooling_api.cpp
Labels: value_high

#547 Fixed iGemm v4r5 tuning
  src/kernels/composable_kernel/include/tensor_operation/gridwise_gemm_xdlops_fp16_bfp16.hpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r5_xdlops.cpp
Labels: bug

#523 Release notes for ROCm 3.9 MIOpen 2.8 (date tentative)
  doc/src/releasenotes.md
Labels: on_hold

#491 MP_bidirect_winograd FP16 support
  doc/src/DebugAndLogging.md
  src/include/miopen/solver.hpp
  src/kernels/xform_bidirect_winograd_code.inc
  src/solver/conv_MP_bidirectional_winograd.cpp
Labels: urgency_unknown

#531 [igemm]fix issue 427(don't drop small kpack*kperblock for all cases)
  src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops.cpp
Labels: need_perf_db_update

#536 [COMGR] Disable unnecesssary assembler detection
  src/include/miopen/gcn_asm_utils.hpp
  src/ocl/gcn_asm_utils.cpp
Labels: bug, value_high

#538 Added missing checks for new iGemm solvers so they obey the ASM & HIP kernel on/off controls.
  src/solver/conv_asm_implicit_gemm_bwd_v4r1_dynamic.cpp
  src/solver/conv_asm_implicit_gemm_gtc_bwd.cpp
  src/solver/conv_asm_implicit_gemm_gtc_fwd.cpp
  src/solver/conv_asm_implicit_gemm_v4r1_dynamic.cpp
  src/solver/conv_asm_implicit_gemm_wrw_gtc_dynamic_xdlops.cpp
  src/solver/conv_asm_implicit_gemm_wrw_v4r1_dynamic.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v1r1_xdlops_nchw_kcyx_nkhw.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops_padded_gemm.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r5_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops.cpp
Labels: bug, value_middle

#504 Dynamic convbwdbias
  src/kernels/MIOpenConvBwdBias.cl
  src/ocl/convolutionocl.cpp
Labels: value_high

#508 post review for asm igemm generic tensor contraction
  src/CMakeLists.txt
  src/conv/invokers/impl_gemm_dynamic.cpp
  src/include/miopen/conv/asm_implicit_gemm.hpp
  src/include/miopen/solver.hpp
  src/solver/conv_asm_implicit_gemm_gtc_bwd.cpp
  src/solver/conv_asm_implicit_gemm_gtc_fwd.cpp
  src/solver/conv_asm_implicit_gemm_wrw_gtc_dynamic_xdlops.cpp
Labels: quality, urgency_high

#139 MIOpenTensile Part1 : Add MIOpenTensile in GEMM path
  CMakeLists.txt
  Dockerfile
  Jenkinsfile
  README.md
  doc/src/DebugAndLogging.md
  hip-clang.docker
  include/miopen/config.h.in
  requirements.txt
  src/CMakeLists.txt
  src/gemm_v2.cpp
  src/include/miopen/gemm_v2.hpp
  src/ocl/convolutionocl.cpp
  src/solver/conv_multipass_wino3x3WrW.cpp
  test/CMakeLists.txt
  test/conv_common.hpp
Labels: value_high
