Repository ROCm/MIOpen, pull requests merged in 2020-08, with the labels that each got.

#317 dynamic igemm wrw
  src/CMakeLists.txt
  src/include/miopen/solver.hpp
  src/kernels/dynamic_igemm/igemm_v4r1_wrw_dynamic.s
  src/kernels/dynamic_igemm/wrw_reduction_hip.cpp
  src/mlo_dir_conv.cpp
  src/solver.cpp
  src/solver/conv_asm_implicit_gemm_wrw_v4r1_dynamic.cpp
  test/CMakeLists.txt
Labels: initial iteration time

#313 Embed binary databases
  CMakeLists.txt
  Jenkinsfile
  cmake/ClangTidy.cmake
  cmake/embed.cmake
  include/miopen/config.h.in
  src/CMakeLists.txt
  src/include/miopen/sqlite_db.hpp
  src/sqlite/CMakeLists.txt
  src/sqlite/memvfs.cpp
  src/sqlite_db.cpp
  test/CMakeLists.txt
  test/embed_sqlite.cpp
  test/sqlite_perfdb.cpp
Labels: priority_high

#370 Dynamic igemm wrw update
  src/solver/conv_asm_implicit_gemm_wrw_v4r1_dynamic.cpp
  test/CMakeLists.txt
Labels: bug, priority_high

#361 Embed Find DB
  Jenkinsfile
  src/CMakeLists.txt
  src/include/miopen/readonlyramdb.hpp
  src/readonlyramdb.cpp
  test/embed_sqlite.cpp
Labels: priority_high

#364 Embed Binary Cache
  CMakeLists.txt
  cmake/embed.cmake
  src/CMakeLists.txt
  src/binary_cache.cpp
  test/CMakeLists.txt
Labels: priority_high

#323 Refactored XdlopsGemm for M/N Repeats
  src/kernels/composable_kernel/include/tensor_operation/blockwise_gemm_xdlops.hpp
  src/kernels/composable_kernel/include/tensor_operation/gridwise_gemm_xdlops_fp16_bfp16.hpp
  src/kernels/composable_kernel/include/tensor_operation/xdlops_gemm.hpp
  src/kernels/composable_kernel/include/tensor_operation/xdlops_gemm_inline_asm.hpp
  src/kernels/composable_kernel/include/utility/amd_xdlops.hpp
  src/kernels/composable_kernel/include/utility/amd_xdlops_inline_asm.hpp
  src/kernels/composable_kernel/include/utility/common_header.hpp
  src/solver/implicitgemm_util.hpp
Labels: new feature, priority_high

#368 refactor fwd v4r1 dynamic solver to be non-tunable.
  src/include/miopen/solver.hpp
  src/solver/conv_asm_implicit_gemm_v4r1_dynamic.cpp
Labels: bug, priority_high

#326 Fast Hybrid mode of iGEMM
  doc/src/find_and_immediate.md
  src/convolution.cpp
  src/find_controls.cpp
  src/include/miopen/execution_context.hpp
  src/include/miopen/find_controls.hpp
  src/ocl/convolutionocl.cpp
  src/solver/conv_hip_implicit_gemm_bwd_data_v1r1.cpp
  src/solver/conv_hip_implicit_gemm_bwd_data_v4r1.cpp
  src/solver/conv_hip_implicit_gemm_bwd_data_v4r1_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v1r1_xdlops_nchw_kcyx_nkhw.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_v4r1.cpp
  src/solver/conv_hip_implicit_gemm_v4r4.cpp
  src/solver/conv_hip_implicit_gemm_v4r4_gen_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_v4r4_gen_xdlops_fwd_fp32.cpp
  src/solver/conv_hip_implicit_gemm_v4r4_gen_xdlops_wrw_fp32.cpp
  src/solver/conv_hip_implicit_gemm_wrw_weights_v4r4.cpp
Labels: enhancement, initial iteration time, priority_high

#382 [Fix] workspace size calc of gemm for group_conv
  src/ocl/convolutionocl.cpp
Labels: bug, priority_blocker

#402 fix pooling bwd index error
  src/kernels/MIOpenPoolingBwd.cl
Labels: bug

#401 Updated release notes for MIOpen 2.7
  doc/src/releasenotes.md
Labels: documentation
