Repository ROCm/MIOpen, pull requests merged in 2020-11, with the labels that each got.

#533 Fix for distinct compile/evaluate
  src/include/miopen/generic_search.hpp
Labels: bug

#507 Dynamic transpose kernels
  src/include/miopen/oclkernel.hpp
  src/kernels/MIOpenUtilKernels4.cl
  src/ocl/convolutionocl.cpp
  src/ocl/utilocl.cpp
  src/ocl_kernel.cpp
Labels: value_high

#566 fix nan while training by conditionally clear input gradient tensor before launch bwd kernel
  src/conv/invokers/impl_gemm_dynamic.cpp
Labels: bug, urgency_blocker

#577 [WORKAROUND] All MP Bidirect Winograd Solvers disabled by default.
  src/solver/conv_MP_bidirectional_winograd.cpp
Labels: urgency_blocker, workaround

#580 Compile only env var check fix
  src/include/miopen/generic_search.hpp
Labels: bug

#568 Fix ConvHipImplicitGemmWrwV4R4Xdlops_Padded_Gemm performance parameter calculation issue
  src/conv/invokers/impl_gemm.cpp
  src/include/miopen/solver.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_backward_weights_implicit_gemm_v4r4_xdlops_nchw_kcyx_nkhw.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_backward_weights_implicit_gemm_v4r4_xdlops_nchw_kcyx_nkhw_padded_gemm.hpp
  src/kernels/composable_kernel/src/kernel_wrapper/gridwise_convolution_backward_weights_implicit_gemm_v4r4_xdlops_nchw_kcyx_nkhw.cpp
  src/kernels/composable_kernel/src/kernel_wrapper/gridwise_convolution_backward_weights_implicit_gemm_v4r4_xdlops_nchw_kcyx_nkhw_padded_gemm.cpp
  src/solver/conv_hip_implicit_gemm_bwd_data_v4r1_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v1r1_xdlops_nchw_kcyx_nkhw.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops_padded_gemm.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r5_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops_padded_gemm.cpp
Labels: bug, urgency_blocker

#595 Remove wrong error message in HIP-iGEMM
  src/solver/conv_hip_implicit_gemm_bwd_data_v4r1_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v1r1_xdlops_nchw_kcyx_nkhw.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops_padded_gemm.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r5_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops.cpp
Labels: urgency_blocker

#602 [COv4] Fix code object v4 support
  src/hipoc/hipoc_program.cpp
Labels: bug, enhancement, urgency_blocker

#587 Make Winograd RxS f2x3 non-tunable for n_groups == 1
  doc/src/DebugAndLogging.md
  src/include/miopen/solver.hpp
  src/mlo_dir_conv.cpp
  src/solver.cpp
  src/solver/conv_winoRxS_f2x3.cpp
Labels: performance, urgency_high

#544 Check dynamic mode before applicability. Do not use non-dymanic or slow/narrow Winograds when cutting corners.
  src/convolution.cpp
  src/include/miopen/execution_context.hpp
  src/include/miopen/find_solution.hpp
  src/include/miopen/mlo_internal.hpp
  src/ocl/convolutionocl.cpp
Labels: initial iteration time, urgency_high, value_high

#613 [tests] Reduce of workload for "test_sqlite_perfdb --all"
  test/sqlite_perfdb.cpp
Labels: testing, urgency_high, value_high, workaround

#589 [Jenkins] Remove low precision OpenCL/GCC tests. Unify stage names. Remove W/A for Vega10 COMGR problem.
  Jenkinsfile
Labels: quality, testing, value_middle

#489 Find Mode API
  doc/src/perfdatabase.md
  driver/conv_driver.hpp
  src/convolution.cpp
  src/convolution_api.cpp
  src/find_controls.cpp
  src/include/miopen/convolution.hpp
  src/include/miopen/find_controls.hpp
  src/include/miopen/miopen_internal.h
  src/ocl/convolutionocl.cpp
  test/find_db.cpp
Labels: enhancement, value_high
