Repository ROCm/MIOpen, pull requests merged in 2020-06, with the labels that each got.

#240 Fix Jenkins issue
  CMakeLists.txt
  Jenkinsfile
  src/binary_cache.cpp
  src/include/miopen/binary_cache.hpp
  src/include/miopen/load_file.hpp
  src/include/miopen/solver.hpp
  src/load_file.cpp
  src/solver/conv_hip_implicit_gemm_bwd_data_v4r1_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_v4r4_gen_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_v4r4_gen_xdlops_wrw_fp32.cpp
  src/solver/conv_ocl_dir2D_bwdWrW_53.cpp
  test/CMakeLists.txt
  test/ctc.cpp
  test/lstm_common.hpp
  test/rnn_vanilla_common.hpp
  test/soft_max.cpp
  test/sqlite_perfdb.cpp
Labels: priority_blocker

#253 Tidy fix in ConvHipImplicitGemmV4R4WrW
  src/include/miopen/solver.hpp
  src/solver/conv_hip_implicit_gemm_wrw_weights_v4r4.cpp
Labels: priority_blocker

#252 MPWinogradWRW solver update
  src/solver/conv_multipass_wino3x3WrW.cpp
Labels: need_perf_db_update, priority_unknown

#245 prevent v4r4 wrw use for backward data
  src/solver/conv_hip_implicit_gemm_wrw_weights_v4r4.cpp
Labels: bug, priority_blocker

#182 Add script to install kernels package
  CMakeLists.txt
  utils/CMakeLists.txt
  utils/install_precompiled_kernels.sh
Labels: priority_high

#177 [comgr] Attach comgr and use it to build OpenCL kernels for HIP BE
  CMakeLists.txt
  Jenkinsfile
  include/miopen/config.h.in
  src/CMakeLists.txt
  src/comgr.cpp
  src/hip/handlehip.cpp
  src/hipoc/hipoc_program.cpp
  src/include/miopen/comgr.hpp
  src/include/miopen/stringutils.hpp
  src/include/miopen/write_file.hpp
  test/handle_test.cpp
Labels: enhancement, priority_blocker

#251 Make UserDb optional
  CMakeLists.txt
  include/miopen/config.h.in
  src/find_db.cpp
  src/include/miopen/db.hpp
  src/include/miopen/find_db.hpp
  test/find_db.cpp
  test/perfdb.cpp
  test/sqlite_perfdb.cpp
Labels: priority_blocker

#267 Fixed warning on insufficient workspace in find to be more clear on nullptr
  src/ocl/convolutionocl.cpp
Labels: priority_middle, quality

#265 Rename hipcompiler igemm flag
  src/solver/conv_hip_implicit_gemm_bwd_data_v4r1_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_v4r4_gen_xdlops_fwd_fp32.cpp
  src/solver/conv_hip_implicit_gemm_v4r4_gen_xdlops_wrw_fp32.cpp
Labels: quality

#166 [dynamic-igemm] add v4r1 dynamic kernel and solver, fwd fp32
  src/CMakeLists.txt
  src/conv/invokers/impl_gemm_dynamic.cpp
  src/include/miopen/conv/invokers/impl_gemm_dynamic.hpp
  src/include/miopen/solver.hpp
  src/kernels/dynamic_igemm/igemm_v4r1_dynamic.s
  src/mlo_dir_conv.cpp
  src/solver.cpp
  src/solver/conv_asm_implicit_gemm_v4r1_dynamic.cpp
  test/CMakeLists.txt
Labels: priority_high

#276 [fix] Remove pure fp16 Winograd kernels
  src/CMakeLists.txt
  src/kernels/Conv_Winograd_v21_1_0_gfx9_fp16_pk_dilation2.inc
  src/kernels/Conv_Winograd_v21_1_0_gfx9_fp16_pk_dilation2.s
  src/kernels/Conv_Winograd_v21_1_0_gfx9_fp16_pk_dilation2_group.inc
  src/kernels/Conv_Winograd_v21_1_0_gfx9_fp16_pk_dilation2_group.s
  src/kernels/Conv_Winograd_v21_1_0_gfx9_fp16_pk_stride1.inc
  src/kernels/Conv_Winograd_v21_1_0_gfx9_fp16_pk_stride1.s
  src/kernels/Conv_Winograd_v21_1_0_gfx9_fp16_pk_stride1_group.inc
  src/kernels/Conv_Winograd_v21_1_0_gfx9_fp16_pk_stride1_group.s
  src/kernels/Conv_Winograd_v21_1_0_gfx9_fp16_pk_stride2.inc
  src/kernels/Conv_Winograd_v21_1_0_gfx9_fp16_pk_stride2.s
  src/kernels/Conv_Winograd_v21_1_0_gfx9_fp16_pk_stride2_group.inc
  src/kernels/Conv_Winograd_v21_1_0_gfx9_fp16_pk_stride2_group.s
  src/solver/conv_winoRxS_f2x3.cpp
Labels: priority_high, quality

#283 CMake flag and envvar to disable HIP kernels
  CMakeLists.txt
  doc/src/DebugAndLogging.md
  include/miopen/config.h.in
  src/execution_context.cpp
  src/include/miopen/execution_context.hpp
  src/solver/conv_hip_implicit_gemm_bwd_data_v1r1.cpp
  src/solver/conv_hip_implicit_gemm_bwd_data_v1r1_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_bwd_data_v4r1.cpp
  src/solver/conv_hip_implicit_gemm_bwd_data_v4r1_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_v4.cpp
  src/solver/conv_hip_implicit_gemm_v4r1.cpp
  src/solver/conv_hip_implicit_gemm_v4r4.cpp
  src/solver/conv_hip_implicit_gemm_v4r4_gen_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_v4r4_gen_xdlops_fwd_fp32.cpp
  src/solver/conv_hip_implicit_gemm_v4r4_gen_xdlops_wrw_fp32.cpp
  src/solver/conv_hip_implicit_gemm_v4r4_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_wrw_weights_v4r4.cpp
Labels: enhancement, priority_blocker

#257 [comgr] Pass output CO via memory
  src/hip/handlehip.cpp
  src/hipoc/hipoc_program.cpp
  src/include/miopen/gcn_asm_utils.hpp
  src/include/miopen/hipoc_kernel.hpp
  src/include/miopen/hipoc_program.hpp
  src/ocl/clhelper.cpp
  src/ocl/gcn_asm_utils.cpp
Labels: enhancement, priority_blocker

#286 Reactivate static build tests.
  Jenkinsfile
Labels: testing

#292 [Hotfix] fix vector_load in v4r4_gen solver for dilation_w > 1
  src/solver/conv_hip_implicit_gemm_v4r4_gen_xdlops.cpp
Labels: bug, priority_high

#297 Re-enable SQLite binary cache
  CMakeLists.txt
  src/binary_cache.cpp
  src/include/miopen/binary_cache.hpp
Labels: priority_high

#295 Igemm Remove old static_assert from v4r4_gen kernel
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_implicit_gemm_v4r4_gen_xdlops_gnchw_gkcyx_gnkhw_lds_double_buffer.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_implicit_gemm_v4r4_gen_xdlops_nchw_kcyx_nkhw_lds_double_buffer.hpp
Labels: bug, priority_blocker

#289 [comgr] HIP support
  src/comgr.cpp
  src/hipoc/hipoc_program.cpp
  src/include/miopen/comgr.hpp
  src/include/miopen/kernel.hpp
  src/include/miopen/stringutils.hpp
  src/kernels/kernel_includes.cpp.in
  test/handle_test.cpp
Labels: complexity_high, priority_high

#294 Fix readonlyramdb MT issue
  src/readonlyramdb.cpp
Labels: bug, priority_blocker

#296 [driver] Fix wrong WS passed to Backward and WrW Find() calls.
  driver/conv_driver.hpp
Labels: priority_blocker, testing

#178 Hybrid as default Find mode
  Jenkinsfile
  doc/src/find_and_immediate.md
  src/include/miopen/find_controls.hpp
  test/main.cpp
Labels: complexity_low, enhancement, priority_high

#243 Refactor implicit GEMM forward v4r4 xdlops solver and kernel
  src/CMakeLists.txt
  src/hip/hip_build_utils.cpp
  src/include/miopen/hip_build_utils.hpp
  src/include/miopen/solver.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_forward_implicit_gemm_v4r4_xdlops_nchw_kcyx_nkhw.hpp
  src/kernels/composable_kernel/include/tensor_operation/blockwise_gemm_xdlops.hpp
  src/kernels/composable_kernel/include/tensor_operation/blockwise_generic_tensor_slice_copy.hpp
  src/kernels/composable_kernel/include/tensor_operation/gridwise_gemm_xdlops.hpp
  src/kernels/composable_kernel/include/tensor_operation/gridwise_gemm_xdlops_fp16_bfp16.hpp
  src/kernels/composable_kernel/include/tensor_operation/xdlops_gemm.hpp
  src/kernels/composable_kernel/include/utility/amd_buffer_addressing.hpp
  src/kernels/composable_kernel/include/utility/common_header.hpp
  src/kernels/composable_kernel/include/utility/config.hpp
  src/kernels/composable_kernel/include/utility/float_type.hpp
  src/kernels/composable_kernel/include/utility/in_memory_operation.hpp
  src/kernels/composable_kernel/include/utility/synchronization.hpp
  src/kernels/composable_kernel/src/kernel_wrapper/gridwise_convolution_forward_implicit_gemm_v4r4_xdlops_nchw_kcyx_nkhw.cpp
  src/mlo_dir_conv.cpp
  src/solver.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_v4r4_gen_xdlops_fwd_fp32.cpp
  src/solver/implicitgemm_util.hpp
Labels: priority_high

#293 [comgr] Build ASM kernels
  src/comgr.cpp
  src/hipoc/hipoc_program.cpp
  src/include/miopen/comgr.hpp
Labels: enhancement, priority_blocker

#310 [WORKAROUND] Disabled ConvHipImplicitGemmBwdDataV1R1 for BF16.
  src/solver/conv_hip_implicit_gemm_bwd_data_v1r1.cpp
Labels: priority_blocker, workaround

#308 [driver] Verification fixes
  driver/conv_driver.hpp
Labels: priority_blocker, testing

#315 [comgr] Utilize new action for OCL builds
  include/miopen/config.h.in
  src/comgr.cpp
Labels: enhancement, priority_blocker

#287 Set cost for tests and run parallel tests serially
  test/CMakeLists.txt
  test/perfdb.cpp
  test/sqlite_perfdb.cpp
Labels: complexity_high, enhancement, priority_high, testing

#316 Activate NORMAL Find mode when auto-tuning is ENFORCEd
  src/convolution.cpp
  src/find_controls.cpp
  src/include/miopen/find_controls.hpp
  src/ocl/convolutionocl.cpp
Labels: complexity_middle, enhancement, priority_high

#233 igemm WrW invokers
  src/conv/invokers/impl_gemm.cpp
  src/find_db.cpp
  src/ocl/convolutionocl.cpp
  src/solver/conv_hip_implicit_gemm_v4.cpp
  src/solver/conv_hip_implicit_gemm_v4r1.cpp
  src/solver/conv_hip_implicit_gemm_v4r4_gen_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_v4r4_gen_xdlops_wrw_fp32.cpp
  src/solver/conv_hip_implicit_gemm_v4r4_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_wrw_weights_v4r4.cpp
Labels: enhancement, priority_high
