Repository ROCm/MIOpen, pull requests merged in 2020-09, with the labels that each got.

#357 Winograd WrW invokers
  src/conv/problem_description.cpp
  src/find_db.cpp
  src/include/miopen/conv/data_invoke_params.hpp
  src/include/miopen/conv/wrw_invoke_params.hpp
  src/include/miopen/convolution.hpp
  src/include/miopen/handle.hpp
  src/include/miopen/solver.hpp
  src/invoker_cache.cpp
  src/ocl/convolutionocl.cpp
  src/problem_description.cpp
  src/solver/conv_bin_winoRxS.cpp
  src/solver/conv_multipass_wino3x3WrW.cpp
  src/solver/conv_winoRxS_f2x3.cpp
  src/solver/conv_winoRxS_f3x2.cpp
Labels: priority_high

#409 Workaround for the failure of ConvHipImplicitGemmV4R4GenWrWXdlops
  src/solver/conv_hip_implicit_gemm_v4r4_gen_xdlops.cpp
  src/solver/implicitgemm_util.hpp
Labels: bug, priority_blocker, workaround

#403 Refactored Xdlops gemm for vector type output
  src/kernels/composable_kernel/include/tensor_operation/blockwise_gemm_xdlops.hpp
  src/kernels/composable_kernel/include/tensor_operation/gridwise_gemm_xdlops.hpp
  src/kernels/composable_kernel/include/tensor_operation/gridwise_gemm_xdlops_fp16_bfp16.hpp
  src/kernels/composable_kernel/include/tensor_operation/xdlops_gemm.hpp
  src/kernels/composable_kernel/include/utility/amd_xdlops.hpp
  src/kernels/composable_kernel/include/utility/float_type.hpp
  src/solver/implicitgemm_util.hpp
Labels: complexity_high, priority_high

#415 [fix] Context configuration in GetWorkSpaceSize
  src/convolution.cpp
Labels: bug, priority_blocker

#416 Add workaround to disable MIOpenDriver
  CMakeLists.txt
Labels: non-miopen-bug, priority_blocker, workaround

#385 Disable faulty compiler option for global addressing using SGPR
  src/hip/hip_build_utils.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops.cpp
  src/solver/implicitgemm_util.hpp
Labels: bug, on_hold

#421 Set the CC compiler to /opt/rocm/llvm/bin/clang if available
  install_deps.cmake
Labels: complexity_low, priority_high

#405 Dynamic OpenCL batch normalization inference.
  src/kernels/MIOpenBatchNormFwdInferPerAct.cl
  src/kernels/MIOpenBatchNormFwdInferSpatial.cl
  src/kernels/reduction_functions.h
  src/ocl/batchnormocl.cpp
Labels: initial iteration time

#417 DYNAMIC_HYBRID Find mode
  doc/src/find_and_immediate.md
  src/convolution.cpp
  src/find_controls.cpp
  src/include/miopen/execution_context.hpp
  src/include/miopen/find_controls.hpp
  src/include/miopen/find_solution.hpp
  src/include/miopen/solver.hpp
  src/ocl/convolutionocl.cpp
Labels: enhancement, performance, priority_high

#425 Batch Norm Dynamic Batch size 1 and 2
  src/batch_norm.cpp
  src/include/miopen/batch_norm.hpp
  src/kernels/MIOpenBatchNormFwdTrainSpatial.cl
  src/kernels/batchnorm_functions.h
  src/ocl/batchnormocl.cpp
Labels: initial iteration time, priority_high

#440 Fixed vector load length calculation in the ConvHipImplicitGemmV4R1WrW solver
  src/solver/conv_hip_implicit_gemm_v4r1.cpp
Labels: bug, priority_blocker

#443 [COMGR] Added HIP PCH functionality.
  src/comgr.cpp
  src/kernels/composable_kernel/include/utility/config.hpp
Labels: priority_blocker

#450 Update documentation with embed instructions.
  doc/src/embed.md
  doc/src/index.rst
Labels: documentation

#452 [COMGR] Enabled HIP PCH functionality.
  src/comgr.cpp
Labels: priority_blocker

#419 [igemm]V4r1 bwd xdlops
  src/include/miopen/solver.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_backward_data_implicit_gemm_v4r1_xdlops_fp16_bfp16_gnchw_gkcyx_gnkhw.hpp
  src/kernels/composable_kernel/src/kernel_wrapper/gridwise_convolution_backward_data_implicit_gemm_v4r1_xdlops_gnchw_gkcyx_gnkhw.cpp
  src/solver/conv_hip_implicit_gemm_bwd_data_v4r1_xdlops.cpp
Labels: need_find_db_update, need_perf_db_update, priority_blocker, tuning

#466 Fixed EuristicInit function in BwdDataV4R1Xdlops solver
  src/mlo_dir_conv.cpp
  src/solver/conv_hip_implicit_gemm_bwd_data_v4r1_xdlops.cpp
Labels: bug, priority_high

#457 [Workaround] Disable bwd v1r1 xdlops due to compiler issues
  src/solver/conv_hip_implicit_gemm_bwd_v1r1_xdlops_nchw_kcyx_nkhw.cpp
Labels: bug, priority_blocker, workaround

#463 [igemm]fix bwd-data-v1r1 bug that call GetGemmSize() of a wrong solver
  src/solver/conv_hip_implicit_gemm_bwd_v1r1_xdlops_nchw_kcyx_nkhw.cpp
Labels: bug

#442 [dynamic-igemm][wrw-xdlops]create dynamic igemm for wrw path with fp32 xdlops instruction
  src/CMakeLists.txt
  src/include/miopen/solver.hpp
  src/kernels/dynamic_igemm/igemm_wrw_gtc_gfx908/igemm_wrw_gtc_gfx908.s
  src/kernels/dynamic_igemm/igemm_wrw_gtc_gfx908/igemm_wrw_gtc_gfx908_004x064.inc
  src/kernels/dynamic_igemm/igemm_wrw_gtc_gfx908/igemm_wrw_gtc_gfx908_016x032.inc
  src/kernels/dynamic_igemm/igemm_wrw_gtc_gfx908/igemm_wrw_gtc_gfx908_032x032.inc
  src/kernels/dynamic_igemm/igemm_wrw_gtc_gfx908/igemm_wrw_gtc_gfx908_064x016.inc
  src/kernels/dynamic_igemm/igemm_wrw_gtc_gfx908/igemm_wrw_gtc_gfx908_064x032.inc
  src/kernels/dynamic_igemm/igemm_wrw_gtc_gfx908/igemm_wrw_gtc_gfx908_064x064.inc
  src/kernels/dynamic_igemm/igemm_wrw_gtc_gfx908/igemm_wrw_gtc_gfx908_064x128.inc
  src/kernels/dynamic_igemm/igemm_wrw_gtc_gfx908/igemm_wrw_gtc_gfx908_064x256.inc
  src/kernels/dynamic_igemm/igemm_wrw_gtc_gfx908/igemm_wrw_gtc_gfx908_128x032.inc
  src/kernels/dynamic_igemm/igemm_wrw_gtc_gfx908/igemm_wrw_gtc_gfx908_128x064.inc
  src/kernels/dynamic_igemm/igemm_wrw_gtc_gfx908/igemm_wrw_gtc_gfx908_128x128.inc
  src/kernels/dynamic_igemm/igemm_wrw_gtc_gfx908/igemm_wrw_gtc_gfx908_256x032.inc
  src/kernels/dynamic_igemm/igemm_wrw_gtc_gfx908/igemm_wrw_gtc_gfx908_256x064.inc
  src/kernels/dynamic_igemm/igemm_wrw_gtc_gfx908/igemm_wrw_gtc_gfx908_256x128.inc
  src/mlo_dir_conv.cpp
  src/solver.cpp
  src/solver/conv_asm_implicit_gemm_wrw_gtc_dynamic_xdlops.cpp
  test/CMakeLists.txt
Labels: priority_high
