Repository ROCm/MIOpen, pull requests merged in 2020-05, with the labels that each got.

#188 Resolve SQLite Out of memory error
  src/include/miopen/sqlite_db.hpp
  src/kern_db.cpp
  src/sqlite_db.cpp
Labels: priority_blocker

#145 Implicit GEMM data invokers
  src/CMakeLists.txt
  src/conv/invokers/impl_gemm.cpp
  src/find_db.cpp
  src/include/miopen/conv/invokers/impl_gemm.hpp
  src/include/miopen/conv/problem_description.hpp
  src/ocl/convolutionocl.cpp
  src/ocl/utilocl.cpp
  src/solver/conv_hip_implicit_gemm_bwd_data_v1r1.cpp
  src/solver/conv_hip_implicit_gemm_bwd_data_v1r1_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_bwd_data_v4r1.cpp
  src/solver/conv_hip_implicit_gemm_v4.cpp
  src/solver/conv_hip_implicit_gemm_v4r1.cpp
  src/solver/conv_hip_implicit_gemm_v4r4.cpp
  src/solver/conv_hip_implicit_gemm_v4r4_gen_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_v4r4_gen_xdlops_fwd_fp32.cpp
  src/solver/conv_hip_implicit_gemm_v4r4_xdlops.cpp
Labels: priority_high

#194 Fix empty path in perf db
  src/include/miopen/execution_context.hpp
  src/include/miopen/sqlite_db.hpp
Labels: priority_blocker

#195 Moving SQLite calls to cpp files
  src/include/miopen/kern_db.hpp
  src/include/miopen/sqlite_db.hpp
  src/kern_db.cpp
  src/sqlite_db.cpp
  test/sqlite_perfdb.cpp
Labels: priority_blocker

#191 Workaround for SWDEV-233338
  Jenkinsfile
  src/ocl/convolutionocl.cpp
  src/ocl/gcn_asm_utils.cpp
  test/find_db.cpp
Labels: enhancement, priority_blocker

#204 Doc updates for 2.4.0
  README.md
  doc/src/DebugAndLogging.md
  doc/src/cache.md
  doc/src/find_and_immediate.md
  doc/src/releasenotes.md
Labels: documentation

#152 Refactored igemm kernel and solver for xdlops wrw fp32
  src/CMakeLists.txt
  src/include/miopen/solver.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_implicit_gemm_v4r4_gen_xdlops_wrw_fp32_nchw_kcyx_nkhw_lds_double_buffer.hpp
  src/kernels/composable_kernel/src/kernel_wrapper/gridwise_convolution_implicit_gemm_v4r4_gen_xdlops_wrw_fp32_nchw_kcyx_nkhw_lds_double_buffer.cpp
  src/mlo_dir_conv.cpp
  src/solver.cpp
  src/solver/conv_hip_implicit_gemm_v4r4_gen_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_v4r4_gen_xdlops_wrw_fp32.cpp
  src/solver/implicitgemm_util.hpp
Labels: need_find_db_update, need_perf_db_update, performance

#196 [BUILD_DEV] DNU version tweak in text-based DB filenames for develop builds.
  CMakeLists.txt
Labels: priority_middle, testing

#200 Fix backward weight igemm kernel time bug
  src/ocl/convolutionocl.cpp
Labels: bug, priority_high

#215 Update CMakeLists.txt: : rocm-opencl-devel to rocm-opencl-dev for RPM Requires
  CMakeLists.txt
Labels: priority_high

#167 add igemm bwd v4r1 xdlops kernel
  CMakeLists.txt
  src/CMakeLists.txt
  src/conv/invokers/impl_gemm.cpp
  src/include/miopen/execution_context.hpp
  src/include/miopen/solver.hpp
  src/include/miopen/sqlite_db.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_backward_data_implicit_gemm_v4r1_xdlops_nchw_kcyx_nkhw.hpp
  src/kernels/composable_kernel/src/kernel_wrapper/gridwise_convolution_backward_data_implicit_gemm_v4r1_xdlops_nchw_kcyx_nkhw.cpp
  src/mlo_dir_conv.cpp
  src/ocl/convolutionocl.cpp
  src/solver.cpp
  src/solver/conv_hip_implicit_gemm_bwd_data_v4r1_xdlops.cpp
Labels: need_find_db_update, need_perf_db_update

#228 Disabled 2 configs.
  test/CMakeLists.txt
Labels: priority_blocker

#205 [igemm 3d]back weights
  driver/conv_driver.hpp
  src/CMakeLists.txt
  src/include/miopen/solver.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_backward_weights_implicit_gemm_v4r4_ncdhw_kczyx_nkdhw.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_backward_weights_implicit_gemm_v4r4_nchw_kcyx_nkhw.hpp
  src/kernels/composable_kernel/src/kernel_wrapper/gridwise_convolution_backward_weights_implicit_gemm_v4r4_ncdhw_kczyx_nkdhw.cpp
  src/kernels/composable_kernel/src/kernel_wrapper/gridwise_convolution_backward_weights_implicit_gemm_v4r4_nchw_kcyx_nkhw.cpp
  src/mlo_dir_conv.cpp
  src/solver.cpp
  src/solver/conv_hip_implicit_gemm_wrw_weights_v4r4.cpp
Labels: need_find_db_update, need_perf_db_update

#192 iGemm: Reduce address calculation for stride > 1
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_implicit_gemm_v4r4_gen_xdlops_fp16_bfp16_fwd_gnchw_gkcyx_gnkhw_lds_double_buffer.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_implicit_gemm_v4r4_gen_xdlops_fp16_bfp16_fwd_nchw_kcyx_nkhw_lds_double_buffer.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_implicit_gemm_v4r4_gen_xdlops_fp16_bfp16_wrw_gnchw_gkcyx_gnkhw_lds_double_buffer.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_implicit_gemm_v4r4_gen_xdlops_fp16_bfp16_wrw_nchw_kcyx_nkhw_lds_double_buffer.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_implicit_gemm_v4r4_gen_xdlops_fwd_fp32_gnchw_gkcyx_gnkhw_lds_double_buffer.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_implicit_gemm_v4r4_gen_xdlops_fwd_fp32_nchw_kcyx_nkhw_lds_double_buffer.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_implicit_gemm_v4r4_gen_xdlops_gnchw_gkcyx_gnkhw_lds_double_buffer.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_implicit_gemm_v4r4_gen_xdlops_wrw_fp32_nchw_kcyx_nkhw_lds_double_buffer.hpp
  src/kernels/composable_kernel/include/tensor_operation/blockwise_generic_tensor_slice_copy.hpp
  src/kernels/composable_kernel/include/tensor_operation/gridwise_gemm_fp16_bfp16.hpp
  src/kernels/composable_kernel/include/tensor_operation/gridwise_gemm_xdlops.hpp
  src/kernels/composable_kernel/include/tensor_operation/gridwise_gemm_xdlops_fp16_bfp16.hpp
  src/kernels/composable_kernel/include/tensor_operation/threadwise_generic_tensor_slice_copy.hpp
  src/kernels/composable_kernel/include/utility/in_memory_operation.hpp
  src/mlo_dir_conv.cpp
  src/solver/conv_hip_implicit_gemm_v4r4_gen_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_v4r4_gen_xdlops_fwd_fp32.cpp
  src/solver/conv_hip_implicit_gemm_v4r4_gen_xdlops_wrw_fp32.cpp
Labels: performance
