Repository ROCm/MIOpen, pull requests merged in 2020-12, with the labels that each got.

#424 Improve Immediate mode Fallback
  src/convolution.cpp
  src/convolution_api.cpp
  src/include/miopen/any_solver.hpp
  src/include/miopen/convolution.hpp
  src/include/miopen/solver.hpp
  src/include/miopen/solver_id.hpp
  src/ocl/convolutionocl.cpp
  src/solver.cpp
  src/solver/conv_MP_bidirectional_winograd.cpp
  src/solver/conv_asm_1x1u.cpp
  src/solver/conv_asm_1x1u_stride2.cpp
  src/solver/conv_asm_3x3u.cpp
  src/solver/conv_asm_dir_BwdWrW1x1.cpp
  src/solver/conv_asm_dir_BwdWrW3x3.cpp
  src/solver/conv_bin_wino3x3U.cpp
  src/solver/conv_hip_implicit_gemm_wrw_weights_v4r4.cpp
  src/solver/conv_ocl_dir2D_bwdWrW_1x1.cpp
  src/solver/conv_ocl_dir2D_bwdWrW_2.cpp
  src/solver/conv_ocl_dir2Dfwd.cpp
  src/solver/conv_ocl_dir2Dfwd1x1.cpp
  src/solver/conv_winoRxS_f3x2.cpp
  test/conv_common.hpp
Labels: enhancement, performance, urgency_blocker, value_middle

#605 Fix iGEMM wrw v4r4 tuning failure on gfx908
  src/include/miopen/solver.hpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops.cpp
Labels: bug

#627 [COMGR] Fixes for HIP PCH
  src/comgr.cpp
  src/execution_context.cpp
  src/include/miopen/execution_context.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/reduction_functions.hpp
  src/kernels/composable_kernel/include/utility/reduction_operator.hpp
  src/kernels/dynamic_igemm/wrw_reduction_hip.cpp
  test/handle_test.cpp
Labels: bug, urgency_blocker

#641 Fix potential bwd immediate crash by add missing setStream() call to context
  src/ocl/convolutionocl.cpp
Labels: bug, urgency_blocker

#607 Disable AsmConv1x1U for gfx8 to resolve #135
  src/solver/conv_asm_1x1u.cpp
Labels: READY TO MERGE, bug, value_middle

#633 Workaround for SWDEV-262823
  src/hip/handlehip.cpp
  src/include/miopen/device_name.hpp
  src/ocl/handleocl.cpp
Labels: READY TO MERGE, enhancement, workaround

#617 Fix kernel hit miss
  src/solver/conv_ocl_dir2Dfwd.cpp
  src/solver/conv_ocl_dir2Dfwd_exhaustive_search.cpp
Labels: READY TO MERGE, performance, quality, value_low

#642 Removed ConvOclDirectFwd3x3
  doc/src/DebugAndLogging.md
  src/CMakeLists.txt
  src/include/miopen/solver.hpp
  src/kernels/MIOpenConvD3x3.cl
  src/mlo_dir_conv.cpp
  src/solver.cpp
  src/solver/conv_ocl_dir2D3x3.cpp
Labels: bug, urgency_blocker

#643 ConvAsm3x3U: limit i/o buffers to 4GiB
  src/solver/conv_asm_3x3u.cpp
Labels: bug, urgency_blocker

#628 [NFC] Unify FFT solver usage
  src/include/miopen/convolution.hpp
  src/ocl/convolutionocl.cpp
Labels: READY TO MERGE, quality, urgency_high

#555 Follow up to PR#343: Fix problem description Get*Size()
  src/include/miopen/conv/problem_description.hpp
Labels: READY TO MERGE, quality

#640 Immediate Mode Fallback: Implement & use GetWti for Winograd v21_1_1 and GEMM
  src/include/miopen/convolution.hpp
  src/include/miopen/problem_description.hpp
  src/include/miopen/solver.hpp
  src/ocl/convolutionocl.cpp
  src/solver/conv_bin_wino3x3U.cpp
  src/solver/conv_winoRxS_f2x3.cpp
Labels: READY TO MERGE, urgency_high, value_middle

#638 [Driver] Allow arbitrary solver id in `-S`. Support symbolic solver names.
  driver/conv_driver.hpp
Labels: READY TO MERGE, enhancement, testing, urgency_high, value_high

#626 Winograd RxSf2x3 solver V21_1_2 update
  src/CMakeLists.txt
  src/kernels/Conv_Winograd_v21_1_0_gfx9_fp16_dot2_edc_dilation2.inc
  src/kernels/Conv_Winograd_v21_1_0_gfx9_fp16_dot2_edc_dilation2_group.inc
  src/kernels/Conv_Winograd_v21_1_0_gfx9_fp16_dot2_edc_stride1.inc
  src/kernels/Conv_Winograd_v21_1_0_gfx9_fp16_dot2_edc_stride1_group.inc
  src/kernels/Conv_Winograd_v21_1_0_gfx9_fp16_dot2_edc_stride2.inc
  src/kernels/Conv_Winograd_v21_1_0_gfx9_fp16_dot2_edc_stride2_group.inc
  src/kernels/Conv_Winograd_v21_1_0_gfx9_fp32_dilation2.inc
  src/kernels/Conv_Winograd_v21_1_0_gfx9_fp32_dilation2_group.inc
  src/kernels/Conv_Winograd_v21_1_0_gfx9_fp32_stride1.inc
  src/kernels/Conv_Winograd_v21_1_0_gfx9_fp32_stride1_group.inc
  src/kernels/Conv_Winograd_v21_1_0_gfx9_fp32_stride2.inc
  src/kernels/Conv_Winograd_v21_1_0_gfx9_fp32_stride2_group.inc
  src/kernels/Conv_Winograd_v21_1_2_gfx9_fp16_dot2_edc_dilation2.inc
  src/kernels/Conv_Winograd_v21_1_2_gfx9_fp16_dot2_edc_dilation2.s
  src/kernels/Conv_Winograd_v21_1_2_gfx9_fp16_dot2_edc_dilation2_group.inc
  src/kernels/Conv_Winograd_v21_1_2_gfx9_fp16_dot2_edc_dilation2_group.s
  src/kernels/Conv_Winograd_v21_1_2_gfx9_fp16_dot2_edc_stride1.inc
  src/kernels/Conv_Winograd_v21_1_2_gfx9_fp16_dot2_edc_stride1.s
  src/kernels/Conv_Winograd_v21_1_2_gfx9_fp16_dot2_edc_stride1_group.inc
  src/kernels/Conv_Winograd_v21_1_2_gfx9_fp16_dot2_edc_stride1_group.s
  src/kernels/Conv_Winograd_v21_1_2_gfx9_fp16_dot2_edc_stride2.inc
  src/kernels/Conv_Winograd_v21_1_2_gfx9_fp16_dot2_edc_stride2.s
  src/kernels/Conv_Winograd_v21_1_2_gfx9_fp16_dot2_edc_stride2_group.inc
  src/kernels/Conv_Winograd_v21_1_2_gfx9_fp16_dot2_edc_stride2_group.s
  src/kernels/Conv_Winograd_v21_1_2_gfx9_fp32_dilation2.inc
  src/kernels/Conv_Winograd_v21_1_2_gfx9_fp32_dilation2.s
  src/kernels/Conv_Winograd_v21_1_2_gfx9_fp32_dilation2_group.inc
  src/kernels/Conv_Winograd_v21_1_2_gfx9_fp32_dilation2_group.s
  src/kernels/Conv_Winograd_v21_1_2_gfx9_fp32_stride1.inc
  src/kernels/Conv_Winograd_v21_1_2_gfx9_fp32_stride1.s
  src/kernels/Conv_Winograd_v21_1_2_gfx9_fp32_stride1_group.inc
  src/kernels/Conv_Winograd_v21_1_2_gfx9_fp32_stride1_group.s
  src/kernels/Conv_Winograd_v21_1_2_gfx9_fp32_stride2.inc
  src/kernels/Conv_Winograd_v21_1_2_gfx9_fp32_stride2.s
  src/kernels/Conv_Winograd_v21_1_2_gfx9_fp32_stride2_group.inc
  src/kernels/Conv_Winograd_v21_1_2_gfx9_fp32_stride2_group.s
  src/kernels/Conv_Winograd_v21_1_2_metadata.inc
  src/solver/conv_winoRxS_f2x3.cpp
Labels: READY TO MERGE

#657 [iGemm] Workaround a tuning issue of non-xdlops gemm
  src/solver/conv_hip_implicit_gemm_nonxdlops_common.cpp
Labels: bug
