Repository ROCm/MIOpen, pull requests merged in 2020-04, with the labels that each got.

#140 Change workgroup launch pattern for fp16 fwd
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_backward_data_implicit_gemm_v1r1_xdlops_fp16_bfp16_gnchw_gkcyx_gnkhw.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_backward_data_implicit_gemm_v1r1_xdlops_fp16_bfp16_nchw_kcyx_nkhw.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_implicit_gemm_v4r4_gen_xdlops_fp16_bfp16_fwd_nchw_kcyx_nkhw_lds_double_buffer.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_implicit_gemm_v4r4_gen_xdlops_fp16_bfp16_gnchw_gkcyx_gnkhw_lds_double_buffer.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_implicit_gemm_v4r4_gen_xdlops_fp16_bfp16_wrw_nchw_kcyx_nkhw_lds_double_buffer.hpp
  src/kernels/composable_kernel/include/tensor_operation/gridwise_gemm_xdlops_fp16_bfp16.hpp
  src/kernels/composable_kernel/include/utility/config.hpp
  src/kernels/composable_kernel/src/kernel_wrapper/gridwise_convolution_implicit_gemm_v4r4_gen_xdlops_nchw_kcyx_nkhw_lds_double_buffer.cpp
Labels: need_find_db_update, need_perf_db_update, performance

#162 Merge Fast/Hybrid Find modes into develop
  driver/conv_driver.hpp
  driver/dropout_driver.hpp
  src/convolution.cpp
  src/find_controls.cpp
  src/include/miopen/find_controls.hpp
  src/include/miopen/handle.hpp
  src/ocl/convolutionocl.cpp
Labels: enhancement, performance, priority_high

#146 Implicit GEMM 3D backward data V4R1 and V1R1
  driver/conv_driver.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_backward_data_implicit_gemm_v1r1_ncdhw_kczyx_nkdhw.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_backward_data_implicit_gemm_v4r1_ncdhw_kczyx_nkdhw.hpp
  src/kernels/composable_kernel/src/kernel_wrapper/gridwise_convolution_backward_data_implicit_gemm_v1r1_ncdhw_kczyx_nkdhw.cpp
  src/kernels/composable_kernel/src/kernel_wrapper/gridwise_convolution_backward_data_implicit_gemm_v4r1_ncdhw_kczyx_nkdhw.cpp
  src/ocl/convolutionocl.cpp
  src/solver/conv_hip_implicit_gemm_bwd_data_v1r1.cpp
  src/solver/conv_hip_implicit_gemm_bwd_data_v4r1.cpp
Labels: need_find_db_update, need_perf_db_update, priority_middle

#164 Change kpack extraction for fp16 bfp16 group conv fwd
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_implicit_gemm_v4r4_gen_xdlops_fp16_bfp16_fwd_gnchw_gkcyx_gnkhw_lds_double_buffer.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_implicit_gemm_v4r4_gen_xdlops_fp16_bfp16_wrw_gnchw_gkcyx_gnkhw_lds_double_buffer.hpp
  src/kernels/composable_kernel/src/kernel_wrapper/gridwise_convolution_implicit_gemm_v4r4_gen_xdlops_gnchw_gkcyx_gnkhw_lds_double_buffer.cpp
  src/solver/conv_hip_implicit_gemm_v4r4_gen_xdlops.cpp
Labels: need_find_db_update, need_perf_db_update, performance

#158 [NFC] Removed redundant `@struct` from miopen.h
  doc/src/convolution.rst
  include/miopen/miopen.h
Labels: documentation, priority_middle, quality

#179 Disabling ConvOclBwdWrW2 for asymmetric padding
  src/include/miopen/conv/problem_description.hpp
  src/include/miopen/problem_description.hpp
  src/solver/conv_ocl_dir2D_bwdWrW_2.cpp
Labels: need_find_db_update
