Repository ROCm/MIOpen, pull requests merged in 2020-07, with the labels that each got.

#314 Refactored xdlops validation in the iGemm solver
  src/kernels/composable_kernel/include/tensor_operation/blockwise_gemm_xdlops.hpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops.cpp
  src/solver/implicitgemm_util.hpp
Labels: bug, priority_high

#328 Fix SQLite `std::logic_error`
  src/sqlite_db.cpp
Labels: bug, priority_high

#256 remove refs to sqlite db if disabled in CMake
  CMakeLists.txt
  src/CMakeLists.txt
  src/binary_cache.cpp
  src/include/miopen/execution_context.hpp
  src/include/miopen/kern_db.hpp
  src/include/miopen/sqlite_db.hpp
  test/cache.cpp
  test/sqlite_perfdb.cpp
Labels: priority_high

#331 [igemm]prevent v1r1 bwd 3d fp16 until we use v2 gridwise
  src/solver/conv_hip_implicit_gemm_bwd_data_v1r1.cpp
Labels: bug, complexity_low, priority_high

#327 Cmake embedded flag
  CMakeLists.txt
Labels: complexity_low, priority_high

#329 Disable installation of system DB and convert associated warnings to Info
  CMakeLists.txt
  include/miopen/config.h.in
  src/CMakeLists.txt
  src/binary_cache.cpp
  src/db.cpp
  src/find_db.cpp
  src/include/miopen/sqlite_db.hpp
  src/readonlyramdb.cpp
Labels: priority_high

#338 [Embedded] Disable workaround for ROCm-CompilerSupport#30
  include/miopen/config.h.in
  src/hip/handlehip.cpp
Labels: priority_blocker

#339 Updated release notes for MIOpen 2.6
  README.md
  doc/src/find_and_immediate.md
  doc/src/releasenotes.md
Labels: documentation

#341 Prevent UB in all ASM & OCL kernels that do not anticipate asymmetric padding
  src/solver/conv_asm_1x1u.cpp
  src/solver/conv_asm_1x1u_stride2.cpp
  src/solver/conv_asm_3x3u.cpp
  src/solver/conv_asm_5x10u2v2b1.cpp
  src/solver/conv_asm_5x10u2v2f1.cpp
  src/solver/conv_asm_7x7c3h224w224k64u2v2p3q3f1.cpp
  src/solver/conv_asm_dir_BwdWrW1x1.cpp
  src/solver/conv_asm_dir_BwdWrW3x3.cpp
  src/solver/conv_ocl_dir2D11x11.cpp
  src/solver/conv_ocl_dir2D3x3.cpp
  src/solver/conv_ocl_dir2D_bwdWrW_1x1.cpp
  src/solver/conv_ocl_dir2D_bwdWrW_53.cpp
  src/solver/conv_ocl_dir2Dfwd.cpp
  src/solver/conv_ocl_dir2Dfwd1x1.cpp
  src/solver/conv_ocl_dir2Dfwdgen.cpp
Labels: priority_high

#350 [CI Fast test stages] Improve stabitility of COMGR tests. Accelerate Dynamic iGemm tests.
  Jenkinsfile
  test/CMakeLists.txt
Labels: priority_blocker

#346 Instrument code for logging compilation time.
  src/hip/handlehip.cpp
  src/include/miopen/generic_search.hpp
  src/include/miopen/timer.hpp
  src/ocl/handleocl.cpp
  src/solver.cpp
Labels: initial iteration time

#354 add direction check to ConvOclBwdWrW53 IsApplicable
  src/solver/conv_ocl_dir2D_bwdWrW_53.cpp
Labels: bug, priority_unknown

#351 [CI testing][WORKAROUND] Disable COMGR tests on Vega10
  Jenkinsfile
Labels: priority_blocker, workaround

#344 Guard atomic fadd, so only hardware having support will see it
  src/kernels/composable_kernel/include/utility/amd_buffer_addressing.hpp
  src/kernels/composable_kernel/include/utility/config.hpp
Labels: bug

#349 Dynamic kernel: optensor
  src/kernels/MIOpenTensorKernels.cl
  src/ocl/rnn_util_ocl.cpp
  src/ocl/tensorocl.cpp
Labels: initial iteration time

#305 Refactor igemm bwd xdlops v1r1
  Jenkinsfile
  src/CMakeLists.txt
  src/conv/invokers/impl_gemm.cpp
  src/include/miopen/solver.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_backward_data_implicit_gemm_v1r1_xdlops_gnchw_gkcyx_gnkhw.hpp
  src/kernels/composable_kernel/include/tensor_operation/gridwise_gemm.hpp
  src/kernels/composable_kernel/include/tensor_operation/gridwise_gemm_fp16_bfp16.hpp
  src/kernels/composable_kernel/include/tensor_operation/gridwise_gemm_xdlops_fp16_bfp16.hpp
  src/kernels/composable_kernel/src/kernel_wrapper/gridwise_convolution_backward_data_implicit_gemm_v1r1_xdlops_gnchw_gkcyx_gnkhw.cpp
  src/kernels/composable_kernel/src/kernel_wrapper/gridwise_convolution_backward_data_implicit_gemm_v1r1_xdlops_nchw_kcyx_nkhw.cpp
  src/mlo_dir_conv.cpp
  src/solver/conv_hip_implicit_gemm_bwd_data_v1r1.cpp
  src/solver/conv_hip_implicit_gemm_bwd_data_v1r1_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v1r1_xdlops_nchw_kcyx_nkhw.cpp
  test/conv_common.hpp
Labels: complexity_middle, enhancement, need_find_db_update, need_perf_db_update, work_in_progress

#272 [igemm_dynamic] v4r1 bwd dynamic kernel
  src/CMakeLists.txt
  src/conv/invokers/impl_gemm_dynamic.cpp
  src/include/miopen/conv/invokers/impl_gemm_dynamic.hpp
  src/include/miopen/numeric.hpp
  src/include/miopen/solver.hpp
  src/kernels/dynamic_igemm/igemm_bwd_gtc_dynamic.s
  src/mlo_dir_conv.cpp
  src/solver.cpp
  src/solver/conv_asm_implicit_gemm_bwd_v4r1_dynamic.cpp
  src/solver/conv_asm_implicit_gemm_v4r1_dynamic.cpp
  test/CMakeLists.txt
Labels: initial iteration time

#342 Disable sys/user db for file based kernel cache
  src/binary_cache.cpp
Labels: bug

#362 Fix nan issue in bwd v1r1 kernel
  src/conv/invokers/impl_gemm.cpp
Labels: bug, priority_high
