Repository ROCm/MIOpen, pull requests merged in 2021-12, with the labels that each got.

#1320 [HOTFIX][gfx90a][FP16] Disable ConvCkIgemmFwdV6r1DlopsNchw when "ALT FP16" kernel is required
  src/solver/conv_ck_igemm_fwd_v6r1_dlops_nchw.cpp
Labels: bug, urgency_blocker, TESTING_CI_PASSED

#1324 [NCHW][SWDEV-312112] fix local buffer alignment bug on transpose+nhwc kernel's solver
  src/conv/invokers/impl_gemm_dynamic.cpp
  src/solver/conv_asm_implicit_gemm_gtc_bwd_nhwc.cpp
  src/solver/conv_asm_implicit_gemm_gtc_fwd_nhwc.cpp
  src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp
Labels: bug, value_high, urgency_blocker, complexity_middle, TESTING_CI_PASSED

#1312 [Batchnorm][ASM] Disabling ASM kernel for unsupported target (gfx940)
  src/solver/batchnorm/backward_spatial_single.cpp
Labels: complexity_low, urgency_normal, TESTING_CI_PASSED

#1332 [TESTS][OCL][MI100][MI200] Fix OpenCL Full tests to run on MI100/200
  Jenkinsfile
Labels: quality, testing, urgency_normal, TESTING_CI_PASSED

#1329 [WORKAROUND][Navi21][SWDEV-292187] Globally disable OCL- and HIP-based convolutions. Also disable OCL convolution solvers on individual basis.
  src/execution_context.cpp
  src/include/miopen/execution_context.hpp
  src/include/miopen/target_properties.hpp
  src/solver/conv_ocl_dir2D11x11.cpp
  src/solver/conv_ocl_dir2D_bwdWrW_1x1.cpp
  src/solver/conv_ocl_dir2D_bwdWrW_2.cpp
  src/solver/conv_ocl_dir2D_bwdWrW_53.cpp
  src/solver/conv_ocl_dir2Dfwd.cpp
  src/solver/conv_ocl_dir2Dfwd1x1.cpp
  src/solver/conv_ocl_dir2Dfwdgen.cpp
  test/CMakeLists.txt
  test/handle_test.cpp
Labels: urgency_blocker, workaround, TESTING_CI_PASSED

#1338 [HIP][COMGR] Fixed "-mllvm" options handling. Added WORKAROUND_ISSUE_1257.
  src/comgr.cpp
  src/include/miopen/stringutils.hpp
Labels: non-miopen-bug, urgency_blocker, workaround, TESTING_CI_PASSED

#1339 [HIP][COMGR] Re-enable PCH starting from 5.0 (SWDEV-308265 is fixed in ROCClr)
  src/comgr.cpp
Labels: non-miopen-bug, urgency_blocker

#1336 [HOTFIX][Navi21][SWDEV-292187] Use WAVE64 mode for all OpenCL kernels. Add FP16 test. Narrow W/A for #1148.
  Jenkinsfile
  src/hipoc/hipoc_program.cpp
  src/ocl/clhelper.cpp
  test/CMakeLists.txt
Labels: bug, urgency_blocker, TESTING_CI_PASSED

#1345 [ROCm4.5] Fix: Use `use_hip_kernels` and `use_asm_kernels` in Naive convolution Solvers
  src/include/miopen/solver/conv_direct_naive_conv.hpp
  src/solver/conv_direct_naive_conv.cpp
  src/solver/conv_direct_naive_conv_bwd.cpp
  src/solver/conv_direct_naive_conv_fwd.cpp
  src/solver/conv_direct_naive_conv_wrw.cpp
Labels: bug, urgency_blocker

#1344 [HOTFIX][Navi21][SWDEV-292187] Do not enforce WAVE64 mode for all OpenCL kernels by default. Restored W/A for #1148.
  src/hipoc/hipoc_program.cpp
  src/ocl/clhelper.cpp
  test/CMakeLists.txt
Labels: urgency_blocker, TESTING_CI_PASSED

#1352 [tests] Disable test_regression_opencl_float_mi100 if WORKAROUND_ISSUE_1317 is set.
  test/CMakeLists.txt
Labels: urgency_blocker, testing, TESTING_CI_PASSED

#1340 [NFC][addkernels] Fix compiler warnings [-Wreserved-identifier]
  addkernels/addkernels.cpp
  src/CMakeLists.txt
Labels: quality, urgency_high, TESTING_CI_PASSED

#1341 [NFC] Reduce compiler warnings [-Wreserved-identifier]
  driver/calcerr.hpp
  driver/conv_verify.hpp
  driver/mloConvHost.hpp
  driver/mloNeuronHost.hpp
  driver/mloNormHost.hpp
  driver/mloPoolingHost.hpp
  src/include/miopen/mlo_internal.hpp
Labels: urgency_blocker, quality, TESTING_CI_PASSED

#1346 [NFC][solvers] Fix compiler warnings [-Wreserved-identifier]
  src/solver/conv_asm_1x1u.cpp
  src/solver/conv_ocl_dir2D_bwdWrW_2.cpp
Labels: quality, urgency_high, TESTING_CI_PASSED

#1328 [MLIR] Disable gfx900 from non-xdlops solver
  requirements.txt
  src/solver/conv_mlir_igemm_bwd.cpp
  src/solver/conv_mlir_igemm_fwd.cpp
  src/solver/conv_mlir_igemm_wrw.cpp
  test/CMakeLists.txt
Labels: value_high, complexity_low, urgency_normal, TESTING_CI_PASSED

#1300 [conv] Optimize performance of GWSS
  src/include/miopen/any_solver.hpp
  src/include/miopen/find_solution.hpp
  src/include/miopen/solver.hpp
  src/mlo_dir_conv.cpp
  src/ocl/convolutionocl.cpp
Labels: value_low, performance, urgency_normal, TESTING_CI_PASSED

#1244 [NHWC] Enable batch norm by refactoring OCL kernel
  src/include/miopen/batchnorm/problem_description.hpp
  src/kernels/MIOpenBatchNormBwdSpatial.cl
  src/kernels/MIOpenBatchNormFwdTrainSpatial.cl
  src/solver/batchnorm/backward_spatial_multiple.cpp
  src/solver/batchnorm/backward_spatial_single.cpp
  src/solver/batchnorm/forward_spatial_multiple.cpp
  src/solver/batchnorm/forward_spatial_single.cpp
  test/bn_spatial_nhwc_test.cpp
Labels: enhancement, complexity_middle, urgency_high, TESTING_CI_PASSED

#1358 Deprecate FAST_HYBRID Find mode
  doc/src/find_and_immediate.md
  src/convolution.cpp
  src/find_controls.cpp
  src/include/miopen/execution_context.hpp
  src/include/miopen/find_controls.hpp
  src/include/miopen/miopen_internal.h
  src/ocl/convolutionocl.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v1r1.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v1r1_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v4r1.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v4r1_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r1.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops_padded_gemm.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r5_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops_padded_gemm.cpp
Labels: quality

#1327 [OCL][MI100][MI200] Fix iGemm ASM GTC XDLOPS failures with OCL backend (Staging 95b58f72f) (#1317) and Implement abstraction for multi-buffer workspace (#1326)
  src/buffer_info.cpp
  src/conv/invokers/impl_gemm_dynamic.cpp
  src/include/miopen/buffer_info.hpp
  src/include/miopen/conv/asm_implicit_gemm.hpp
  src/solver/conv_asm_implicit_gemm_gtc_bwd_nhwc.cpp
  src/solver/conv_asm_implicit_gemm_gtc_fwd_nhwc.cpp
  src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp
  test/CMakeLists.txt
Labels: need_find_db_update, urgency_normal, TESTING_CI_PASSED

#1360 [WORKAROUND][COMGR] W/A for issue 1359: Use hipModuleLoad with interim file instead of hipModuleLoadData. By-product: Better names for tempfiles.
  src/hipoc/hipoc_program.cpp
  src/include/miopen/temp_file.hpp
  src/ocl/gcn_asm_utils.cpp
  src/temp_file.cpp
  test/perfdb.cpp
Labels: bug, urgency_blocker, TESTING_CI_PASSED

#1361 Fix for PR 1221. After tuning, remove benchmarked Programs only (related to: SWDEV-304151)
  src/binary_cache.cpp
  src/hip/handlehip.cpp
  src/include/miopen/binary_cache.hpp
  src/include/miopen/generic_search.hpp
  src/include/miopen/handle.hpp
  src/include/miopen/kernel_cache.hpp
  src/kernel_cache.cpp
  src/nogpu/handle.cpp
  src/ocl/handleocl.cpp
Labels: bug, urgency_high, TESTING_CI_PASSED

#1250 Non templated SolverBase
  src/include/miopen/activ/solvers.hpp
  src/include/miopen/batchnorm/solvers.hpp
  src/include/miopen/find_solution.hpp
  src/include/miopen/pooling/solvers.hpp
  src/include/miopen/solver.hpp
  src/solver/conv_MP_bidirectional_winograd.cpp
  src/solver/conv_multipass_wino3x3WrW.cpp
  src/solver/conv_ocl_dir2D_bwdWrW_2.cpp
  test/solver.cpp
Labels: enhancement, value_high, urgency_high, TESTING_CI_PASSED

#1348 Allow setting the default FIND_MODE at CMake configuration phase
  Jenkinsfile
  include/miopen/config.h.in
  src/CMakeLists.txt
  src/find_controls.cpp
  src/include/miopen/find_controls.hpp
  src/include/miopen/miopen_internal.h
Labels: complexity_middle, urgency_low, TESTING_CI_PASSED
