Repository ROCm/MIOpen, pull requests merged in 2021-03, with the labels that each got.

#759 [CI] Resolve issues after upgrading to ROCm 3.7. Switch to hip-clang in all tests that use GPU.
  CMakeLists.txt
  Jenkinsfile
  hip-clang.docker
Labels: testing, urgency_blocker, value_high

#727 Implementation of four additional generic tensor reduction operations (AVG, AMAX, NORM1, NORM2)
  driver/miopen_Reduction.hpp
  driver/reduce_driver.hpp
  include/miopen/miopen.h
  src/kernel_warnings.cpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_generic_2d_reduction_blockwise.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_generic_2d_reduction_direct_threadwise.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_generic_2d_reduction_direct_warpwise.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_generic_2d_reduction_multiblock.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_generic_reduction.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/reduction_functions.hpp
  src/kernels/composable_kernel/include/utility/reduction_common.hpp
  src/kernels/composable_kernel/include/utility/reduction_operator.hpp
  src/kernels/composable_kernel/src/kernel_wrapper/gridwise_generic_reduction.cpp
  src/reducetensor.cpp
  test/cpu_reduce_util.hpp
  test/reduce_test.cpp
Labels: enhancement, urgency_blocker

#766 [CI] Select image names and docker build args to get rid of useless image rebuilds. [tests][FP16][MI100] Remove useless tests.
  Jenkinsfile
  test/CMakeLists.txt
Labels: testing, urgency_blocker, value_high

#750 [tests] Remove useless tests from low-precision stages.
  Jenkinsfile
  test/CMakeLists.txt
Labels: testing, urgency_high

#775 [tests] Disable HIP kernels in MIOpenTensile tests. Disable xDLOPs specific tests for gfx900/906.
  Jenkinsfile
  test/CMakeLists.txt
Labels: testing, value_high

#776 [Jenkins] information about current node
  Jenkinsfile
Labels: testing

#777 [WORKAROUND][HOTFIX][ROCm3.7] Fix memory access fault in MIOpenGEMM
  src/ocl/convolutionocl.cpp
Labels: non-miopen-bug, urgency_blocker

#778 [CI][WORKAROUND][tests][ROCm3.7] W/A HIP compiler crash with MI100
  test/conv_common.hpp
Labels: non-miopen-bug, urgency_blocker

#762 Reverting Batchnorm implementation vector processing changes
  src/kernels/MIOpenBatchNormBwdSpatial.cl
  src/kernels/MIOpenBatchNormFwdTrainSpatial.cl
Labels: bug, urgency_blocker

#779 [CI][HOTFIX][Jenkinsfile] Fix "Packages" stage for hip-clang docker
  Jenkinsfile
Labels: testing, urgency_blocker

#554 Remove dummy_memset for rocblas timing
  driver/gemm_driver.hpp
  src/gemm_v2.cpp
  src/include/miopen/gemm_v2.hpp
  src/ocl/convolutionocl.cpp
  src/ocl/rnnocl.cpp
  src/solver/conv_MP_bidirectional_winograd.cpp
  src/solver/conv_multipass_wino3x3WrW.cpp
Labels: bug, value_high

#764 [WORKAROUND] test_mdgraph: skip unsupported algo for gfx1030
  test/mdgraph.cpp
Labels: workaround

#741 Remove outdated (and now wrong & harmful) workaround for apple
  src/kernel_cache.cpp
Labels: CI TESTS PASSED, performance, urgency_high

#794 Adapt "hipv4" fix for unbundler for ROCm 4.1 RC3
  src/hip/hip_build_utils.cpp
Labels: urgency_blocker

#739 [Workaround] Disable MIOpenConv1x1J1 on Gfx10
  src/solver/conv_ocl_dir2Dfwd1x1.cpp
Labels: non-miopen-bug, workaround

#793 [CI] Optimize out unnecessary image rebuilds that affect Static checks. Add explicit notion of "default image name".
  Jenkinsfile
Labels: enhancement, testing

#787 [OCL BE][HIP] Use "hipv4" for unbundler in 4.1 and in 4.2 starting from 21072.
  src/hip/hip_build_utils.cpp
Labels: enhancement, urgency_blocker

#748 Winograd binaries to sources
  src/CMakeLists.txt
  src/kernels/Conv_Winograd_v13_3_12_fp16dot_stride1.inc
  src/kernels/Conv_Winograd_v13_3_12_fp16dot_stride2_dec.inc
  src/kernels/Conv_Winograd_v13_3_12_fp16dot_stride2_dil.inc
  src/kernels/Conv_Winograd_v14_3_3_fp16dot_stride1.inc
  src/kernels/Conv_Winograd_v14_3_3_fp16dot_stride2_dec.inc
  src/kernels/Conv_Winograd_v14_3_3_fp16dot_stride2_dil.inc
  src/kernels/Conv_Winograd_v16_5_0_stride1.inc
  src/kernels/Conv_Winograd_v21_1_2_gfx10_fp16_dot2_edc_dilation2.inc
  src/kernels/Conv_Winograd_v21_1_2_gfx10_fp16_dot2_edc_dilation2_group.inc
  src/kernels/Conv_Winograd_v21_1_2_gfx10_fp16_dot2_edc_stride1.inc
  src/kernels/Conv_Winograd_v21_1_2_gfx10_fp16_dot2_edc_stride1_group.inc
  src/kernels/Conv_Winograd_v21_1_2_gfx10_fp16_dot2_edc_stride2.inc
  src/kernels/Conv_Winograd_v21_1_2_gfx10_fp16_dot2_edc_stride2_group.inc
  src/kernels/Conv_Winograd_v21_1_2_gfx9_fp16_dot2_edc_dilation2.inc
  src/kernels/Conv_Winograd_v21_1_2_gfx9_fp16_dot2_edc_dilation2_group.inc
  src/kernels/Conv_Winograd_v21_1_2_gfx9_fp16_dot2_edc_stride1.inc
  src/kernels/Conv_Winograd_v21_1_2_gfx9_fp16_dot2_edc_stride1_group.inc
  src/kernels/Conv_Winograd_v21_1_2_gfx9_fp16_dot2_edc_stride2.inc
  src/kernels/Conv_Winograd_v21_1_2_gfx9_fp16_dot2_edc_stride2_group.inc
  src/kernels/conv_3x3_wheel_alpha_v3_0b.inc
  src/kernels/conv_3x3_wheel_alpha_v7_0_3b.inc
  src/kernels/conv_3x3_wheel_alpha_v9_0_15.inc
  src/kernels/conv_3x3_wheel_alpha_v9_0_15.s
  src/kernels/conv_3x3_wheel_alpha_v9_0_15_gfx8.inc
  src/kernels/conv_3x3_wheel_alpha_v9_0_15_gfx8_stride_2_dec.inc
  src/kernels/conv_3x3_wheel_alpha_v9_0_15_gfx8_stride_2_dil.inc
  src/kernels/conv_3x3_wheel_alpha_v9_0_15_gfx9.inc
  src/kernels/conv_3x3_wheel_alpha_v9_0_15_gfx9_stride_2_dec.inc
  src/kernels/conv_3x3_wheel_alpha_v9_0_15_gfx9_stride_2_dil.inc
  src/kernels/conv_3x3_wheel_alpha_v9_0_15_stride_2_dec.inc
  src/kernels/conv_3x3_wheel_alpha_v9_0_15_stride_2_dec.s
  src/kernels/conv_3x3_wheel_alpha_v9_0_15_stride_2_dil.inc
  src/kernels/conv_3x3_wheel_alpha_v9_0_15_stride_2_dil.s
  src/kernels/conv_3x3_wheel_alpha_v9_2_7.inc
  src/kernels/conv_3x3_wheel_alpha_v9_2_7.s
  src/kernels/conv_3x3_wheel_alpha_v9_2_7_gfx8.inc
  src/kernels/conv_3x3_wheel_alpha_v9_2_7_gfx8_stride_2_dec.inc
  src/kernels/conv_3x3_wheel_alpha_v9_2_7_gfx9.inc
  src/kernels/conv_3x3_wheel_alpha_v9_2_7_gfx9_stride_2_dec.inc
  src/kernels/conv_3x3_wheel_alpha_v9_2_7_stride_2_dec.inc
  src/kernels/conv_3x3_wheel_alpha_v9_2_7_stride_2_dec.s
Labels: CI TESTS PASSED, urgency_high

#798 [rocm-4.1.x][HOTFIX][WORKAROUND][OCL] Disable MIOpenGEMM for failing configs. Backup GEMM with Naive Direct Solvers for Immediate Fallback.
  src/include/miopen/rocm_features.hpp
  src/include/miopen/solver.hpp
  src/ocl/convolutionocl.cpp
  src/solver/conv_direct_naive_conv_bwd.cpp
  src/solver/conv_direct_naive_conv_fwd.cpp
  src/solver/conv_direct_naive_conv_wrw.cpp
Labels: non-miopen-bug, urgency_blocker, workaround

#799 [HOTFIX][4.1.x] Logging Warning->Info when PerfConfigs from db can't be deserialized (SWDEV-276830)
  src/include/miopen/db_record.hpp
Labels: urgency_blocker, workaround

#761 Tidy update
  .clang-tidy
  CMakeLists.txt
  Dockerfile
  Jenkinsfile
  addkernels/include_inliner.cpp
  cmake/ClangTidy.cmake
  hip-clang.docker
  src/conv/invokers/impl_gemm_dynamic.cpp
  src/find_controls.cpp
  src/find_db.cpp
  src/hip/handlehip.cpp
  src/hip/hip_build_utils.cpp
  src/hipoc/hipoc_kernel.cpp
  src/include/miopen/common.hpp
  src/include/miopen/env.hpp
  src/include/miopen/find_controls.hpp
  src/include/miopen/find_db.hpp
  src/include/miopen/handle_lock.hpp
  src/include/miopen/hipoc_kernel.hpp
  src/include/miopen/lock_file.hpp
  src/include/miopen/logger.hpp
  src/include/miopen/manage_ptr.hpp
  src/include/miopen/md_graph.hpp
  src/include/miopen/mlo_internal.hpp
  src/include/miopen/mlo_utils.hpp
  src/include/miopen/solver.hpp
  src/include/miopen/sqlite_db.hpp
  src/include/miopen/type_name.hpp
  src/lock_file.cpp
  src/logger.cpp
  src/md_graph.cpp
  src/ocl/convolutionocl.cpp
  src/ocl/gcn_asm_utils.cpp
  src/ocl/oclerrors.cpp
  src/readonlyramdb.cpp
  src/solver.cpp
  src/solver/conv_asm_1x1u.cpp
  src/solver/conv_asm_implicit_gemm_gtc_fwd.cpp
  src/solver/conv_asm_implicit_gemm_wrw_gtc_dynamic_xdlops.cpp
  src/solver/conv_direct_naive_conv.cpp
  src/solver/conv_ocl_dir2D_bwdWrW_2.cpp
  src/solver/conv_winoRxS_f2x3.cpp
  src/target_properties.cpp
  test/cbna_inference.cpp
  test/driver.hpp
  test/get_handle.hpp
  test/gpu_reference_kernel.cpp
  test/perfdb.cpp
  test/pooling_common.hpp
  test/reduce_test.cpp
  test/solver.cpp
  test/sqlite_perfdb.cpp
Labels: CI TESTS PASSED, testing, value_middle

#805 Add latest rocblas api flag (SWDEV-275854)
  src/gemm_v2.cpp
Labels: non-miopen-bug, urgency_blocker

#615 [Find] Parallel build of all found solutions
  src/include/miopen/conv_solution.hpp
  src/include/miopen/convolution.hpp
  src/include/miopen/par_for.hpp
  src/ocl/convolutionocl.cpp
  src/solver.cpp
Labels: CI TESTS PASSED, enhancement, performance

#728 [NHWC] add gpu reference kernel for nhwc
  driver/conv_driver.hpp
  driver/tensor_driver.hpp
  src/convolution_api.cpp
  src/include/miopen/problem_description.hpp
  src/kernels/gpu_reference_kernel/naive_conv.cpp
  src/problem_description.cpp
  src/solver/conv_direct_naive_conv.cpp
  src/solver/conv_direct_naive_conv_bwd.cpp
  src/solver/conv_direct_naive_conv_fwd.cpp
  src/solver/conv_direct_naive_conv_wrw.cpp
  test/gpu_reference_kernel.cpp
  test/tensor_layout.hpp
Labels: complexity_high, value_high

#806 [Jenkinsfile] Improvements and simplifications
  Jenkinsfile
Labels: CI TESTS PASSED, testing, urgency_high

#808 [CI] Remove huge generated kernel headers from tidy checks. Accelerate parallel library builds.
  src/CMakeLists.txt
  src/kernels/kernel.cpp.in
  src/kernels/kernel_includes.cpp.in
Labels: enhancement, testing, urgency_blocker

#810 [HIP build] Do not write unnecessary files to disk.
  src/hip/hip_build_utils.cpp
Labels: performance, urgency_high

#772 Adding Winograd v21 fused
  src/CMakeLists.txt
  src/fusion.cpp
  src/include/miopen/solver.hpp
  src/kernels/conv_3x3_wheel_alpha_v9_2_7.s
  src/kernels/conv_3x3_wheel_alpha_v9_2_7_gfx9.inc
  src/kernels/conv_3x3_wheel_alpha_v9_2_7_gfx9_stride_2_dec.inc
  src/kernels/conv_3x3_wheel_alpha_v9_2_7_stride_2_dec.s
  src/md_graph.cpp
  src/ocl/fusionopbiasbnactivocl.cpp
  src/solver/conv_winoRxS_f2x3.cpp
  test/mdgraph.cpp
Labels: CI TESTS PASSED, bug, enhancement

#814 [CI] Fix & refactor build/install directory handling.
  Jenkinsfile
Labels: bug, testing, urgency_blocker

#811 Making MLIR solver obtain launch params from API
  Dockerfile
  src/hip/handlehip.cpp
  src/hipoc/hipoc_program.cpp
  src/include/miopen/mlir_build.hpp
  src/include/miopen/solver.hpp
  src/mlir_build.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v1r1.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4.cpp
  src/solver/conv_hip_implicit_gemm_mlir_cpp_bwd.cpp
  src/solver/conv_hip_implicit_gemm_mlir_cpp_fwd.cpp
  src/solver/conv_hip_implicit_gemm_mlir_cpp_wrw.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4.cpp
Labels: CI TESTS PASSED

#813 [tests] test_mdgraph: skip unsupported arch
  test/mdgraph.cpp
Labels: urgency_high

#834 [ROCm3.7...4.0][MI100][HIP compiler] W/A for correctness problems in PerformanceImplicitGemmForwardV4R4Xdlops_Padded_Gemm due to compiler issue.
  src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops_padded_gemm.cpp
Labels: non-miopen-bug, urgency_blocker, workaround
