Repository ROCm/MIOpen, pull requests merged in 2021-07, with the labels that each got.

#1017 [Tuna] Updated solver id to include primitive.
  src/include/miopen/solver_id.hpp
  src/ocl/convolutionocl.cpp
  src/solver.cpp
Labels: TESTING_CI_PASSED, tuning, urgency_blocker

#783 [MIOpenTensile] Remove transpose flag
  Dockerfile
  src/gemm_v2.cpp
Labels: TESTING_CI_PASSED

#1021 [HOTFIX] Fix incorrect registration of ActivFwdSolver1 due to desync between #1017 and #967
  src/solver.cpp
Labels: urgency_blocker

#147 Reshuffle and reduce test cases
  Jenkinsfile
  src/ocl/batchnormocl.cpp
  test/CMakeLists.txt
  test/conv2d.cpp
  test/conv3d.cpp
  test/conv_common.hpp
  test/driver.hpp
  test/immed_conv2d.cpp
  test/immed_conv3d.cpp
  test/network_data.hpp
  test/pooling2d.cpp
  test/pooling3d.cpp
Labels: TESTING_CI_PASSED, testing, value_high

#997 [TESTS] Add regression test for SWDEV-291202
  test/CMakeLists.txt
Labels: quality, testing, urgency_high

#1024 [TESTS] Detection of GPU type (SWDEV-290980)
  CMakeLists.txt
  Dockerfile
  Jenkinsfile
  test/CMakeLists.txt
Labels: TESTING_CI_PASSED, enhancement, urgency_high

#1030 [Tuna] Removed the old gemm solver::Id record
  src/solver.cpp
Labels: TESTING_CI_PASSED

#1033 [NFC] ConvolutionContext made accessible in SetNextValue()
  src/include/miopen/generic_search.hpp
  src/include/miopen/solver.hpp
  src/solver/conv_asm_1x1u.cpp
  src/solver/conv_asm_1x1u_stride2.cpp
  src/solver/conv_asm_3x3u.cpp
  src/solver/conv_asm_dir_BwdWrW1x1.cpp
  src/solver/conv_asm_dir_BwdWrW3x3.cpp
  src/solver/conv_asm_implicit_gemm_gtc_bwd_nhwc.cpp
  src/solver/conv_asm_implicit_gemm_gtc_fwd_nhwc.cpp
  src/solver/conv_asm_implicit_gemm_gtc_perf_config.cpp
  src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v1r1.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v1r1_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v4r1.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v4r1_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops_padded_gemm.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r5_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_nonxdlops_common.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops_padded_gemm.cpp
  src/solver/conv_hip_implicit_gemm_xdlops_common.cpp
  src/solver/conv_ocl_dir2D_bwdWrW_2.cpp
  src/solver/conv_winoRxS_f2x3.cpp
  src/solver/conv_winoRxS_f3x2.cpp
Labels: enhancement, urgency_high

#1032 Fix: Remove 1x1 applicable from OclDirectFused
  src/md_graph.cpp
Labels: bug

#1034 [NFC] Activation backward solver 1
  src/CMakeLists.txt
  src/include/miopen/activ/problem_description.hpp
  src/include/miopen/activ/solvers.hpp
  src/ocl/activ_ocl.cpp
  src/solver.cpp
  src/solver/activ/bwd_1.cpp
Labels: TESTING_CI_PASSED, TESTING_PERFORMANCE_REQUIRED, complexity_middle, enhancement, urgency_high

#1046 [HOTFIX][WORKAROUND] Revert #916 -- W/A for FP32 SSD convergency issue (SWDEV-293780), partial W/A for FP16 SSD issue (model explosion in SWDEV-295434)
  driver/bn_driver.hpp
  src/kernels/MIOpenBatchNormBwdSpatial.cl
  src/ocl/batchnormocl.cpp
Labels: TESTING_CI_PASSED, bug, urgency_blocker

#1048 [HOTFIX][WORKAROUND] Revert #982 -- partial W/A for FP16 SSD issue (memory access fault in SWDEV-295434)
  src/solver/conv_asm_implicit_gemm_wrw_gtc_dynamic_xdlops.cpp
Labels: bug, urgency_blocker

#1040 [ASM iGEMM][NHWC] Fix for potential Memory Access Fault or NaN result (added v_flag missed during merging)
  src/kernels/dynamic_igemm/igemm_gtc_xdlops_nhwc/fwd_fp16/igemm_fwd_gtcx_nhwc_fp16_bx0_ex1_bt256x32x8_wt64x16x4_ws1x1_wr2x1_ta1x1x8x1_1x8x1x32_tb1x1x1x1_1x8x1x32_me.s
  src/kernels/dynamic_igemm/igemm_gtc_xdlops_nhwc/fwd_fp32/igemm_fwd_gtcx_nhwc_fp32_bx0_ex1_bt128x32x4_wt64x32x1_ws1x1_wr1x1_ta1x1x4x1_1x4x1x32_tb1x1x1x1_1x4x1x32_me.s
  src/kernels/dynamic_igemm/igemm_gtc_xdlops_nhwc/fwd_fp32/igemm_fwd_gtcx_nhwc_fp32_bx0_ex1_bt128x32x8_wt32x32x2_ws1x1_wr1x1_ta1x1x4x1_1x8x1x32_tb1x1x1x1_1x8x1x32_me.s
  src/kernels/dynamic_igemm/igemm_gtc_xdlops_nhwc/fwd_fp32/igemm_fwd_gtcx_nhwc_fp32_bx0_ex1_bt128x64x4_wt64x32x1_ws1x1_wr1x1_ta1x1x2x1_1x4x1x64_tb1x1x1x1_1x4x1x64_me.s
  src/kernels/dynamic_igemm/igemm_gtc_xdlops_nhwc/fwd_fp32/igemm_fwd_gtcx_nhwc_fp32_bx0_ex1_bt256x32x4_wt64x32x1_ws1x1_wr2x1_ta1x1x8x1_1x4x1x32_tb1x1x1x1_1x4x1x32_me.s
  src/kernels/dynamic_igemm/igemm_gtc_xdlops_nhwc/fwd_fp32/igemm_fwd_gtcx_nhwc_fp32_bx0_ex1_bt256x32x8_wt32x32x2_ws1x1_wr2x1_ta1x1x8x1_1x8x1x32_tb1x1x1x1_1x8x1x32_me.s
  src/kernels/dynamic_igemm/igemm_gtc_xdlops_nhwc/fwd_fp32/igemm_fwd_gtcx_nhwc_fp32_bx0_ex1_bt256x64x4_wt64x16x1_ws1x1_wr2x2_ta1x1x4x1_1x4x1x64_tb1x1x1x1_1x4x1x64_me.s
  test/CMakeLists.txt
Labels: TESTING_CI_PASSED, bug, urgency_high

#1042 [FP16] Winograd f3x2 fp16 support
  src/CMakeLists.txt
  src/kernels/Conv_Winograd_v21_1_2_f3x2_fp16_dot2_edc_stride1_group.s
  src/kernels/Conv_Winograd_v21_1_2_gfx10_f3x2_fp16_dot2_edc_stride1_group.inc
  src/kernels/Conv_Winograd_v21_1_2_gfx9_f3x2_fp16_dot2_edc_stride1_group.inc
  src/solver/conv_winoRxS_f3x2.cpp
Labels: enhancement, performance, value_high

#1045 [asm iGemm][MI100] Reverted #1048 and fixed changes introduced in #982 (part 2/2 of the real fix for SWDEV-295434)
  src/solver/conv_asm_implicit_gemm_wrw_gtc_dynamic_xdlops.cpp
  test/CMakeLists.txt
Labels: TESTING_CI_PASSED, bug, urgency_blocker

#1038 [CI][TESTS][Navi21] Basic support for Navi21
  Jenkinsfile
  test/CMakeLists.txt
Labels: TESTING_CI_PASSED, enhancement, testing, urgency_high

#1016 [MLIR] Remove gemm size checks from ConvMlirIgemmBwd and ConvMlirIgemmBwdXdlops
  Dockerfile
  src/solver/conv_mlir_igemm_bwd.cpp
  src/solver/conv_mlir_igemm_bwd_xdlops.cpp
Labels: TESTING_CI_PASSED, enhancement, urgency_medium, value_middle

#1052 [MLIR] Added support for TargetId. [TESTS] Upgrade from ROCm 3.7 to 4.2 for MLIR testing.
  Dockerfile
  src/solver/mlir_common.cpp
Labels: TESTING_CI_PASSED, urgency_high, value_high

#1065 [Navi21][HOTFIX] Fix kernel build issues introduced in PR #1037
  src/kernels/batchnorm_functions.h
  src/kernels/reduction_functions.h
Labels: TESTING_CI_PASSED, urgency_blocker

#1066 [gfx908][TESTS] Adding a number of tests
  test/CMakeLists.txt
Labels: TESTING_CI_PASSED
