Repository ROCm/MIOpen, pull requests merged in 2021-01, with the labels that each got.

#663 Post_PR657: Add workaround comment
  src/solver/conv_hip_implicit_gemm_nonxdlops_common.cpp
Labels: READY TO MERGE, urgency_blocker

#644 [igemm]fix tuning paramter of spare(issue 598 and issue 636)
  src/include/miopen/solver.hpp
  src/solver/conv_hip_implicit_gemm_bwd_v4r1_xdlops.cpp
Labels: READY TO MERGE, bug, need_perf_db_update, urgency_blocker

#671 fix issue 650 for develop
  src/kernels/composable_kernel/include/utility/amd_buffer_addressing.hpp
Labels: bug

#661 Use versioned rocm-cmake that comes with ROCm
  hip-clang.docker
Labels: testing

#685 [HIP backend] Remove fat binary unbundling
  src/hip/hip_build_utils.cpp
Labels: performance, quality, urgency_high, value_high

#623 Backoff in SQLite and WAL journal mode
  CMakeLists.txt
  include/miopen/config.h.in
  src/include/miopen/exp_backoff.hpp
  src/include/miopen/sqlite_db.hpp
  src/sqlite_db.cpp
Labels: READY TO MERGE, bug, complexity_middle, urgency_medium

#690 [HOTFIX][TargetID] Unblock MIOpen for ROCm 4.0 and 4.0.1 RC. Possibility for unblock for mainline.
  CMakeLists.txt
  include/miopen/config.h.in
  src/hip/hip_build_utils.cpp
  src/hipoc/hipoc_program.cpp
Labels: bug, urgency_blocker

#583 [gpu_reference_kernel] add gpu reference convolution
  driver/conv_driver.hpp
  src/CMakeLists.txt
  src/include/miopen/solver.hpp
  src/kernels/gpu_reference_kernel/naive_conv.cpp
  src/kernels/gpu_reference_kernel/naive_conv_gcn.s
  src/mlo_dir_conv.cpp
  src/solver.cpp
  src/solver/conv_direct_naive_conv.cpp
  src/solver/conv_direct_naive_conv.hpp
  src/solver/conv_direct_naive_conv_bwd.cpp
  src/solver/conv_direct_naive_conv_fwd.cpp
  src/solver/conv_direct_naive_conv_wrw.cpp
  test/gpu_reference_kernel.cpp
Labels: enhancement, value_high

#699 [gfx908] Auto-detect return type of "llvm.amdgcn.buffer.atomic.fadd.f32" intrinsic
  src/CMakeLists.txt
  src/hip/hip_build_utils.cpp
  src/kernels/composable_kernel/include/utility/amd_buffer_addressing.hpp
  src/kernels/composable_kernel/include/utility/config.hpp
  src/kernels/detect_llvm_amdgcn_buffer_atomic_fadd_f32_float.cpp
Labels: enhancement, urgency_blocker

#696 Update clang-ocl & rocm-cmake version
  requirements.txt
Labels: urgency_blocker

#682 Get work space sizes update
  src/convolution.cpp
  src/include/miopen/convolution.hpp
  src/include/miopen/find_solution.hpp
  src/include/miopen/mlo_internal.hpp
  src/mlo_dir_conv.cpp
Labels: enhancement, performance, urgency_high, value_middle

#687 Adding applicable filter to consider layout to existing kernels
  src/solver/conv_MP_bidirectional_winograd.cpp
  src/solver/conv_asm_implicit_gemm_bwd_v4r1_dynamic.cpp
  src/solver/conv_asm_implicit_gemm_gtc_bwd.cpp
  src/solver/conv_asm_implicit_gemm_gtc_fwd.cpp
  src/solver/conv_asm_implicit_gemm_v4r1_dynamic.cpp
  src/solver/conv_asm_implicit_gemm_wrw_gtc_dynamic_xdlops.cpp
  src/solver/conv_asm_implicit_gemm_wrw_v4r1_dynamic.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v1r1.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v1r1_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v4r1.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v4r1_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r1.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops_padded_gemm.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r5_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops_padded_gemm.cpp
  src/solver/conv_multipass_wino3x3WrW.cpp
  src/solver/conv_ocl_dir2D11x11.cpp
  src/solver/conv_ocl_dir2D_bwdWrW_1x1.cpp
  src/solver/conv_ocl_dir2D_bwdWrW_2.cpp
  src/solver/conv_ocl_dir2D_bwdWrW_53.cpp
  src/solver/conv_ocl_dir2Dfwd.cpp
  src/solver/conv_ocl_dir2Dfwd1x1.cpp
  src/solver/conv_ocl_dir2Dfwdgen.cpp
  src/solver/conv_winoRxS_f3x2.cpp
  src/solver/fft.cpp
Labels: enhancement, urgency_medium

#695 Fixed invalid compilation params for fused ConvBiasActivAsm1x1U
  src/exec_utils.cpp
  src/hipoc/hipoc_program.cpp
  src/include/miopen/conv/context.hpp
  src/include/miopen/generic_search.hpp
  src/solver/conv_asm_1x1u_bias_activ.cpp
  test/CMakeLists.txt
Labels: READY TO MERGE, bug, urgency_high

#681 No GPU backend for Tuna
  CMakeLists.txt
  Jenkinsfile
  include/miopen/config.h.in
  src/CMakeLists.txt
  src/include/miopen/nogpu/handle_impl.hpp
  src/kernels/migrate_db.py
  src/nogpu/handle.cpp
Labels: READY TO MERGE

#705 [HOTFIX] Fix miopenCreateWithStream for OCL BE (issue 703)
  src/ocl/handleocl.cpp
  test/get_handle.hpp
  test/handle_test.cpp
Labels: bug, urgency_blocker
