Repository ROCm/MIOpen, pull requests merged in 2021-11, with the labels that each got.

#1249 [MLIR] Separate small MLIR tests to smoke stages
  Jenkinsfile
  test/CMakeLists.txt
Labels: value_high, testing, complexity_low, urgency_high, TESTING_CI_PASSED

#1234 [NFC] Bnorm inference solver
  src/CMakeLists.txt
  src/batchnorm/problem_description.cpp
  src/include/miopen/batchnorm/invoke_params.hpp
  src/include/miopen/batchnorm/problem_description.hpp
  src/include/miopen/batchnorm/solvers.hpp
  src/ocl/batchnormocl.cpp
  src/solver.cpp
  src/solver/batchnorm/forward_inference.cpp
  test/bn_spatial_test.cpp
Labels: enhancement, complexity_middle, urgency_normal, TESTING_CI_PASSED

#1253 [HIP][COMGR] Use COMGR by default for HIP backend
  CMakeLists.txt
  Jenkinsfile
  src/comgr.cpp
Labels: urgency_high, TESTING_CI_PASSED

#1247 [Enhancement] xdlops NCHW support by transpose
  src/CMakeLists.txt
  src/conv/invokers/impl_gemm_dynamic.cpp
  src/hip/batched_transpose_sol.cpp
  src/hip/handlehip.cpp
  src/include/miopen/batched_transpose_sol.hpp
  src/include/miopen/conv/invokers/impl_gemm_dynamic.hpp
  src/include/miopen/handle.hpp
  src/include/miopen/magic_div.hpp
  src/include/miopen/util_sol.hpp
  src/kernels/gpu_batched_transpose_kernel/batched_transpose.cpp
  src/nogpu/handle.cpp
  src/ocl/handleocl.cpp
  src/solver/conv_asm_implicit_gemm_gtc_bwd_nhwc.cpp
  src/solver/conv_asm_implicit_gemm_gtc_fwd_nhwc.cpp
  src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp
  test/gpu_nchw_nhwc_transpose.cpp
Labels: urgency_blocker, complexity_high, TESTING_CI_PASSED

#1233 [Enhancement] Simplify dependencies to build
  Dockerfile
  README.md
  dev-requirements.txt
  install_deps.cmake
  min-requirements.txt
  mlir-requirements.txt
  rbuild.ini
  requirements.txt
Labels: enhancement, value_high, urgency_blocker

#1258 [gfx90a][FP16] Disable Solvers that unable to comply the "ALT FP16" attribute
  src/include/miopen/conv/problem_description.hpp
  src/solver/conv_asm_1x1u.cpp
  src/solver/conv_asm_1x1u_stride2.cpp
  src/solver/conv_asm_dir_BwdWrW1x1.cpp
  src/solver/conv_asm_dir_BwdWrW3x3.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v1r1.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v1r1_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v4r1_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r1.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops_padded_gemm.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r5_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops_padded_gemm.cpp
  src/solver/conv_winoRxS_f2x3.cpp
  src/solver/conv_winoRxS_f3x2.cpp
Labels: urgency_blocker

#1262 [BugFix] CBAInfer verification
  driver/CBAInferFusion_driver.hpp
  driver/conv_driver.hpp
  driver/driver.hpp
  driver/miopen_ConvBatchNormActivHost.hpp
Labels: bug, complexity_middle, urgency_high, TESTING_CI_PASSED

#1261 [gfx90a][FP16][rocBLAS] Enable Gemm solver for Alt Impl
  src/gemm_v2.cpp
  src/include/miopen/gemm_v2.hpp
  src/solver/gemm.cpp
  src/solver/gemm_bwd.cpp
  src/solver/gemm_wrw.cpp
Labels: urgency_blocker

#1265 Guard hip header for COMGR PCH
  src/kernels/gpu_batched_transpose_kernel/batched_transpose.cpp
Labels: bug, TESTING_CI_PASSED

#1264 Fix HIP builds for the upcoming HIP compiler (SWDEV-310166)
  src/comgr.cpp
  src/hip/hip_build_utils.cpp
  src/kernels/static_composable_kernel/include/utility/static_kernel_amd_buffer_addressing.hpp
Labels: bug, urgency_blocker, TESTING_CI_PASSED

#1248 [NFC] Post review of #1230: Asm igemm nhwc native bf16 kernel on gfx90a
  src/include/miopen/solver.hpp
  src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp
Labels: quality, complexity_middle, urgency_high, TESTING_CI_PASSED

#1273 [HIP][COMGR] Abstain from COMGR by default for HIP backend (revert #1253). Add regression test for issue-internal #4
  CMakeLists.txt
  Jenkinsfile
  test/CMakeLists.txt
Labels: bug, non-miopen-bug, urgency_blocker

#1267 [BugFix] asm igemm heuristic init, for fwd/bwd/wrw
  src/solver/conv_asm_implicit_gemm_gtc_bwd_nhwc.cpp
  src/solver/conv_asm_implicit_gemm_gtc_fwd_nhwc.cpp
  src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp
Labels: urgency_blocker, TESTING_CI_PASSED

#1278 [HOTFIX] Fix issue: Custom tests that do not have MLIR_ENABLED are disabled by default
  test/CMakeLists.txt
Labels: bug, value_high, urgency_blocker, testing

#1279 [gfx90a]Fix an issue in the Asm IGEMM dynamic solvers Perf Config
  src/include/miopen/solver.hpp
  src/solver/conv_asm_implicit_gemm_gtc_bwd_nhwc.cpp
  src/solver/conv_asm_implicit_gemm_gtc_fwd_nhwc.cpp
  src/solver/conv_asm_implicit_gemm_gtc_perf_config.cpp
  src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp
Labels: bug, urgency_blocker, complexity_middle, TESTING_CI_PASSED

#1283 [HOTFIX][WORKAROUND] W/A for rocBLAS 2.42 API changes.
  src/gemm_v2.cpp
Labels: urgency_blocker, workaround

#1276 [NFC] Cleaned-up batchnorm and activation
  src/include/miopen/find_solution.hpp
  src/ocl/activ_ocl.cpp
  src/ocl/batchnormocl.cpp
Labels: enhancement, quality, complexity_low

#1280 [CI][Tests] add unit test for asm igemm when K=2x
  test/CMakeLists.txt
Labels: value_high, testing, urgency_normal, TESTING_CI_PASSED

#1275 [gfx90a][tuning] Fix build errors during tuning in Direct conv1x1 kernels
  src/kernels/conv1x1u.s
  src/kernels/conv1x1u_bias_activ.s
  src/kernels/conv1x1u_stride2.s
  src/kernels/conv1x1wrw.s
Labels: bug, urgency_normal, TESTING_CI_PASSED

#1284 Pooling forward solvers (except GetWorkspaceSize)
  src/CMakeLists.txt
  src/include/miopen/datatype.hpp
  src/include/miopen/pooling.hpp
  src/include/miopen/pooling/invoke_params.hpp
  src/include/miopen/pooling/problem_description.hpp
  src/include/miopen/pooling/solvers.hpp
  src/include/miopen/solver_id.hpp
  src/ocl/pooling_ocl.cpp
  src/pooling/problem_description.cpp
  src/solver.cpp
  src/solver/pooling/forward2d.cpp
  src/solver/pooling/forwardNd.cpp
Labels: enhancement, complexity_middle, urgency_normal, TESTING_CI_PASSED

#1228 [MLIR] Making MIOpen build and test MLIR by default
  CMakeLists.txt
  Dockerfile
  Jenkinsfile
  mlir-requirements.txt
  requirements.txt
  test/CMakeLists.txt
Labels: value_high, complexity_middle, urgency_high, TESTING_CI_PASSED

#1299 [MLIR] Adding misc optimizations
  CMakeLists.txt
  src/solver/conv_mlir_igemm_bwd.cpp
  src/solver/conv_mlir_igemm_fwd.cpp
  src/solver/conv_mlir_igemm_wrw.cpp
  test/CMakeLists.txt
Labels: complexity_low, urgency_low, TESTING_CI_PASSED

#1289 [Enhancement] Use recipe instead of raw url to install sqlite3
  requirements.txt
Labels: enhancement, value_middle, urgency_low, TESTING_CI_PASSED

#1294 [Fin] Update Fin subtree to match with Fin repo develop
  fin/Dockerfile
  fin/src/include/conv_fin.hpp
  fin/src/main.cpp
  fin/src/tests/fin_input_find_compile2.json
Labels: value_high, complexity_low, urgency_high, TESTING_CI_PASSED
