Repository ROCm/MIOpen, pull requests merged in 2021-10, with the labels that each got.

#1197 [Enhancement] remove recursive dir iterator
  Jenkinsfile
  src/find_db.cpp
  src/include/miopen/execution_context.hpp
Labels: enhancement, TESTING_CI_PASSED

#1201 [NFC] Last backward bnorm solver and backward bnorm clean-up.
  src/CMakeLists.txt
  src/include/miopen/batchnorm/solvers.hpp
  src/ocl/batchnormocl.cpp
  src/solver.cpp
  src/solver/batchnorm/backward_per_activation.cpp
Labels: enhancement, TESTING_CI_PASSED

#1205 [HOTFIX] Revert some temp commits accidentaly merged from #1197 "[Enhancement] remove recursive dir iterator"
  Jenkinsfile
Labels: urgency_blocker

#1199 [MLIR] Deprecate MLIR CPP backend - step 2 of 2
  src/CMakeLists.txt
  src/conv/invokers/impl_gemm.cpp
  src/hip/handlehip.cpp
  src/hip/hip_build_utils.cpp
  src/hipoc/hipoc_program.cpp
  src/include/miopen/hip_build_utils.hpp
  src/include/miopen/mlir_build.hpp
  src/include/miopen/solver.hpp
  src/mlir_build.cpp
  src/mlo_dir_conv.cpp
  src/nogpu/handle.cpp
  src/solver.cpp
  src/solver/conv_hip_implicit_gemm_mlir_cpp_bwd.cpp
  src/solver/conv_hip_implicit_gemm_mlir_cpp_fwd.cpp
  src/solver/conv_hip_implicit_gemm_mlir_cpp_wrw.cpp
Labels: enhancement, complexity_low, urgency_low, TESTING_CI_PASSED

#1207 [HOTFIX][WORKAROUND] W/A for issue 1206. Disable ConvHipImplicitGemmBwdDataV4R1Xdlops by default.
  src/solver/conv_hip_implicit_gemm_bwd_v4r1_xdlops.cpp
Labels: urgency_blocker, workaround

#1208 [HOTFIX][WORKAROUND] #1207 ported to develop: W/A for issue 1206. Disable ConvHipImplicitGemmBwdDataV4R1Xdlops by default
  src/solver/conv_hip_implicit_gemm_bwd_v4r1_xdlops.cpp
Labels: urgency_blocker, workaround

#1176 [SWDEV-287843] Remove absolute paths from MIOpen
  CMakeLists.txt
  src/CMakeLists.txt
  src/db_path.cpp.in
  src/find_db.cpp
Labels: enhancement, value_high, TESTING_CI_PASSED

#1217 Add support for MIOPEN_DEBUG_CONV_IMPLICIT_GEMM_HIP_BWD_V4R1_XDLOPS_PERF_VALS
  src/solver/conv_hip_implicit_gemm_bwd_v4r1_xdlops.cpp
Labels: enhancement, value_middle, TESTING_CI_PASSED, debugging

#1200 [MLIR] Enable OpenCL backend
  Dockerfile
  Jenkinsfile
  src/conv/invokers/mlir_impl_gemm.cpp
  src/ocl/clhelper.cpp
Labels: complexity_middle, new feature, urgency_normal, TESTING_CI_PASSED
