Repository ROCm/MIOpen, pull requests merged in 2021-02, with the labels that each got.

#660 Disable the using of llvm instrinsic for Generic-Reduction Kernels on gfx1030
  src/reducetensor.cpp
Labels: READY TO MERGE, urgency_blocker, workaround

#678 [OCL] Disable DIRECT_OCL_WRW1X1 to workaround failures for Navi21
  src/solver/conv_ocl_dir2D_bwdWrW_1x1.cpp
Labels: READY TO MERGE

#622 Add compile time enabled timer function
  CMakeLists.txt
  include/miopen/config.h.in
  src/include/miopen/logger.hpp
  src/include/miopen/timer.hpp
Labels: READY TO MERGE

#677 Report CU count instead of WGP for gfx10 winograd RxSf2x3 solver
  src/include/miopen/handle.hpp
  src/solver/conv_winoRxS_f2x3.cpp
Labels: performance, value_high

#709 [CI] Improved error logs. Eliminated some false failures.
  Jenkinsfile
  src/fusion.cpp
  src/md_graph.cpp
  src/ocl/convolutionocl.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v1r1_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v4r1_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops_padded_gemm.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r5_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops_padded_gemm.cpp
Labels: READY TO MERGE, testing, urgency_blocker

#711 [Fusions] Selection of fused asm 1x1 kernel restricted to appropriate targets.
  src/md_graph.cpp
Labels: bug

#713 [HIP BE] Use hipDeviceProp_t.gcnArchName instead of gcnArch
  src/CMakeLists.txt
  src/hip/handlehip.cpp
  src/include/miopen/ocldeviceinfo.hpp
  src/include/miopen/rocm_features.hpp
  src/ocl/clhelper.cpp
  src/ocl/handleocl.cpp
  src/target_properties.cpp
Labels: enhancement, urgency_high

#722 [CI] Dismiss Fiji from CI testing.
  Jenkinsfile
Labels: CI TESTS PASSED, testing

#720 Feature jenkinsfile
  Jenkinsfile
Labels: CI TESTS PASSED

#714 [OCL BE] Fix ROCM 4.0 build warnings. [COMGR] Use OpenCL 1.2
  include/miopen/miopen.h
  src/comgr.cpp
  src/include/miopen/mlo_internal.hpp
Labels: CI TESTS PASSED, complexity_middle, quality, value_low

#665 ConvAsm3x3U big tensor support
  src/kernels/conv3x3.s
  src/solver/conv_asm_3x3u.cpp
Labels: enhancement, performance, urgency_medium

#735 [NFC][SQLite perf-db] Less spam at log level 5
  src/db_record.cpp
Labels: debugging

#733 [OCL BE][NFC] Dump md5 hash instead of MIOpenGEMM kernels source at log level 6
  src/binary_cache.cpp
Labels: debugging, quality

#734 [NFC][MIOpenDriver] Fix build warnings with ROCm 4.0
  driver/CBAInferFusion_driver.hpp
  driver/activ_driver.hpp
  driver/bn_driver.hpp
  driver/conv_driver.hpp
  driver/ctc_driver.hpp
  driver/dropout_driver.hpp
  driver/gemm_driver.hpp
  driver/lrn_driver.hpp
  driver/pool_driver.hpp
  driver/reduce_driver.hpp
  driver/rnn_driver.hpp
  driver/softmax_driver.hpp
  driver/tensorop_driver.hpp
Labels: CI TESTS PASSED, debugging, quality

#736 [OCL BE] Fix: Restore llvm-specific HIP build options to reclaim GPU performance.
  CMakeLists.txt
Labels: CI TESTS PASSED, bug, urgency_high, value_high

#474 [BN] Update kernel to stabilize variance calculation.
  src/kernels/MIOpenBatchNormBwdPerAct.cl
  src/kernels/MIOpenBatchNormFwdTrainPerAct.cl
  src/ocl/batchnormocl.cpp
  test/bn_peract_test.cpp
Labels: bug, complexity_low, value_low

#746 [HOTFIX][4.1.x] Lower logging level from Warning to Info for incorrect PerfConfigs loaded from db
  src/include/miopen/find_solution.hpp
  src/include/miopen/logger.hpp
Labels: urgency_blocker, workaround

#753 [HOTFIX] Do not reserve xnack mask SGPR in the 3x3 asm kernel.
  src/kernels/conv3x3.s
Labels: bug, urgency_blocker

#740 Add missing amdhsa directive for Conv_Winograd_v21_1_2 metadata
  src/kernels/Conv_Winograd_v21_1_2_metadata.inc
Labels: bug

#758 [Jenkinsfile] Fix path for clinfo when ROCm >= 3.7
  Jenkinsfile
Labels: urgency_blocker
