Repository ROCm/MIOpen, pull requests merged in 2021-08, with the labels that each got.

#1072 [Driver] Fix LogCmdRedux() for double reduction
  driver/reduce_driver.hpp
  src/reducetensor_api.cpp
Labels: TESTING_CI_PASSED, urgency_medium

#1068 [MI100][TESTS] Fix issue 995 and 954: add some fp16 only test cases for asm igemm wrw/fwd nchw and remove W/A
  test/CMakeLists.txt
Labels: TESTING_CI_PASSED, testing, urgency_blocker

#1079 [Jenkins] update ROCm gpg key to permanent location
  Dockerfile
Labels: TESTING_CI_PASSED, complexity_low, urgency_blocker, urgency_high

#1076 Bump up the MIOpen version to 2.14 (after cutting the rocm-rel-4.4 branch)
  CMakeLists.txt
Labels: complexity_low, urgency_low

#1070 Remove WORKAROUND_ISSUE_2298
  src/solver/conv_ocl_dir2Dfwd1x1.cpp
  test/CMakeLists.txt
Labels: quality, testing, urgency_high, TESTING_CI_PASSED

#1081 [NOGPU] Fix #1080 enable MIOpen builds on GPU-less
  test/CMakeLists.txt
Labels: value_middle, complexity_low, urgency_low, TESTING_CI_PASSED

#1044 [Tuna] Add fin to MIOpen CI
  CMakeLists.txt
  Dockerfile
  Jenkinsfile
  fin/.clang-format
  fin/CMakeLists.txt
  fin/Dockerfile
  fin/Jenkinsfile
  fin/LICENSE
  fin/cmake/Analyzers.cmake
  fin/cmake/ClangTidy.cmake
  fin/cmake/CppCheck.cmake
  fin/cmake/DoxygenDoc.cmake
  fin/cmake/EnableCompilerWarnings.cmake
  fin/cmake/FindOpenCL.cmake
  fin/cmake/MainDoc.cmake
  fin/cmake/SphinxDoc.cmake
  fin/cmake/TargetFlags.cmake
  fin/cmake/hip-config.cmake
  fin/cmake/mingw-toolchain.cmake
  fin/cmake/rocm-path.cmake
  fin/install_deps.cmake
  fin/requirements.txt
  fin/src/CMakeLists.txt
  fin/src/base64.cpp
  fin/src/fin.cpp
  fin/src/include/base64.hpp
  fin/src/include/config.h.in
  fin/src/include/conv_fin.hpp
  fin/src/include/error.hpp
  fin/src/include/fin.hpp
  fin/src/include/gpu_mem.hpp
  fin/src/include/random.hpp
  fin/src/include/tensor.hpp
  fin/src/main.cpp
  fin/src/tensor.cpp
  fin/src/tests/fin_input.json
  fin/src/tests/fin_input_applicability.json
  fin/src/tests/fin_input_find_compile.json
  fin/src/tests/fin_input_find_eval.json
  fin/src/tests/fin_output.json
  fin/src/tests/fin_output_find_compile.json
  fin/src/tests/fin_output_find_eval.json
  fin/src/tests/fin_solvers_only.json
Labels: complexity_middle, new feature, urgency_high, TESTING_CI_PASSED

#1084 [ArchLinux][GCC-11][OCL] Add missing limits header fix #1083
  src/include/miopen/float_equal.hpp
Labels: complexity_low, urgency_high

#1051 make doc: switch to python 3
  Dockerfile
  doc/requirements.txt
  doc/src/conf.py
Labels: value_unknown

#1090 Fix the timing for reduction kernels
  src/reducetensor.cpp
Labels: value_middle, complexity_low, urgency_high, TESTING_CI_PASSED

#1088 Improve the compiling of reduction kernels
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_generic_2d_reduction_blockwise.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_generic_2d_reduction_direct_threadwise.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_generic_2d_reduction_direct_warpwise.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_generic_2d_reduction_multiblock.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_generic_reduction.hpp
  src/kernels/composable_kernel/src/kernel_wrapper/gridwise_generic_reduction_first_call.cpp
  src/kernels/composable_kernel/src/kernel_wrapper/gridwise_generic_reduction_second_call.cpp
  src/reducetensor.cpp
Labels: value_high, urgency_high, TESTING_CI_PASSED

#1082 [Test][CI][gfx90a] Basic support for gfx90a: Jenkinsfile, dockerfile, unit tests
  Dockerfile
  Jenkinsfile
  test/CMakeLists.txt
Labels: value_high, urgency_blocker, testing, TESTING_CI_PASSED

#1098 Copy of "[Test][CI][gfx90a] Basic support for gfx90a: Jenkinsfile, dockerfile, unit tests (#1082)"
  Dockerfile
  Jenkinsfile
  test/CMakeLists.txt
Labels: urgency_blocker, testing, complexity_middle

#1100 [typo]fix typo in ctest is_anabled->is_enabled
  Jenkinsfile
  test/CMakeLists.txt
Labels: complexity_low, urgency_medium, TESTING_CI_PASSED

#1111 Some cppcheck fixes
  src/ocl/convolutionocl.cpp
  src/reducetensor.cpp
  src/solver/activ/bwd_0.cpp
  src/solver/conv_ocl_dir2D_bwdWrW_2.cpp
  test/conv_common.hpp
  test/tensor_transform.cpp
Labels: bug, enhancement, value_high, urgency_blocker, TESTING_CI_PASSED

#1125 [CI] Upgrade to ROCm 4.3.1 [WORKAROUND] Disable dynamic reduction by default for HIP backend && ROCm 4.3
  Dockerfile
  src/reducetensor.cpp
Labels: bug, urgency_blocker, TESTING_CI_PASSED

#1127 [WORKAROUND] Fix W/A in PR #1125 that disables dynamic reduction by default for HIP backend && ROCm 4.3
  src/reducetensor.cpp
Labels: bug, complexity_low, workaround, urgency_high, TESTING_CI_PASSED
