Repository ROCm/MIOpen, pull requests merged in 2021-04, with the labels that each got.

#774 Generic-Reduction follow-up
  driver/miopen_Reduction.hpp
  driver/reduce_driver.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_generic_2d_reduction_blockwise.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_generic_2d_reduction_direct_threadwise.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_generic_2d_reduction_direct_warpwise.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_generic_reduction.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/reduction_functions.hpp
  src/kernels/composable_kernel/include/utility/reduction_operator.hpp
  test/cpu_reduce_util.hpp
  test/reduce_test.cpp
Labels: urgency_blocker

#842 [Nv21][HOTFIX][TargetId] Support features disabled on target (SWDEV-278900)
  src/comgr.cpp
  src/hipoc/hipoc_program.cpp
  src/include/miopen/gcn_asm_utils.hpp
  src/include/miopen/hip_build_utils.hpp
  src/include/miopen/target_properties.hpp
  src/ocl/clhelper.cpp
  src/ocl/gcn_asm_utils.cpp
  src/target_properties.cpp
Labels: CI TESTS PASSED, non-miopen-bug, urgency_blocker

#843 [rocm-4.2.x][HOTFIX][WORKAROUND][OCL] Disable MIOpenGEMM for failing configs. Backup GEMM with Naive Direct Solvers for Immediate Fallback.
  src/include/miopen/rocm_features.hpp
  src/include/miopen/solver.hpp
  src/ocl/convolutionocl.cpp
Labels: bug, urgency_blocker

#844 [COMGR][MI100] Fix passing the CK_AMD_BUFFER_ATOMIC_FADD_RETURNS_FLOAT macro (SWDEV-280049)
  src/comgr.cpp
  src/include/miopen/rocm_features.hpp
  src/include/miopen/solver/implicitgemm_util.hpp
Labels: performance, urgency_medium

#837 add param to control CI stages
  Jenkinsfile
Labels: complexity_low, design, testing, urgency_blocker

#836 Enable xldops igmmm on gfx90a
  src/include/miopen/solver/implicitgemm_util.hpp
Labels: urgency_high

#849 Fix issue 846 - Make GEMM Fwd/Bwd solvers non-applicable when MAX_MEM_ALLOC_SZ exceeded
  src/solver/gemm.cpp
  src/solver/gemm_bwd.cpp
Labels: bug, urgency_blocker

#765 [NHWC] support nhwc in ctest
  driver/tensor_driver.hpp
  src/CMakeLists.txt
  src/conv/problem_description.cpp
  src/convolution.cpp
  src/include/miopen/conv/problem_description.hpp
  src/include/miopen/convolution.hpp
  src/include/miopen/tensor.hpp
  src/include/miopen/tensor_layout.hpp
  src/pooling.cpp
  src/tensor.cpp
  test/conv2d.cpp
  test/conv3d.cpp
  test/conv_common.hpp
  test/gpu_reference_kernel.cpp
  test/immed_conv2d.cpp
  test/immed_conv3d.cpp
Labels: CI TESTS PASSED, urgency_high

#850 [Jenkinsfile] Don't disable inline asm for non-XDLOPs targets. Disable Codecov.
  Jenkinsfile
Labels: quality, testing, urgency_high

#792 Fix scale initials in lrn driver (SWDEV-274378)
  driver/lrn_driver.hpp
Labels: bug, urgency_high

#861 [CI] Individual controls for different kinds of tests
  Jenkinsfile
Labels: enhancement, testing

#860 [WORKAROUND][OCL] Disable MIOpenGEMM for failing configs.
  src/include/miopen/rocm_features.hpp
  src/include/miopen/solver.hpp
  src/solver/gemm.cpp
Labels: non-miopen-bug, urgency_blocker

#556 MIOpenTensile Part2 : Support low precision types
  Dockerfile
  Jenkinsfile
  requirements.txt
  src/gemm_v2.cpp
  src/ocl/convolutionocl.cpp
  src/solver/conv_MP_bidirectional_winograd.cpp
  src/solver/conv_multipass_wino3x3WrW.cpp
  src/solver/gemm.cpp
  src/solver/gemm_bwd.cpp
  test/CMakeLists.txt
Labels: value_high

#795 Additions to the HIPNOGPU backend
  src/hipoc/hipoc_program.cpp
  src/include/miopen/convolution.hpp
  src/include/miopen/hipoc_program.hpp
  src/include/miopen/hipoc_program_impl.hpp
  src/nogpu/handle.cpp
Labels: enhancement, tuning, urgency_high

#864 [CI] MIOpenTensile: Switch OFF full tests by default, add smoke tests.
  Jenkinsfile
Labels: CI TESTS PASSED, enhancement, testing, urgency_blocker

#858 [HOTFIX] Made kernel sources inlined as multiple files (full fix for SWDEV-281476)
  addkernels/addkernels.cpp
  cmake/ClangTidy.cmake
  src/CMakeLists.txt
  src/kernels/kernel.cpp.in
  src/kernels/kernels_batch.cpp.in
Labels: bug, urgency_blocker

#875 [WORKAROUND][CI] Issue 874, failures of test_conv_embed_db
  test/CMakeLists.txt
Labels: testing, urgency_blocker

#841 Implement mlir binary backend - step 1: fwd path
  Dockerfile
  src/CMakeLists.txt
  src/conv/invokers/mlir_impl_gemm.cpp
  src/hip/handlehip.cpp
  src/hipoc/hipoc_program.cpp
  src/include/miopen/conv/invokers/mlir_impl_gemm.hpp
  src/include/miopen/memref.hpp
  src/include/miopen/mlir_build.hpp
  src/include/miopen/solver.hpp
  src/mlir_build.cpp
  src/mlo_dir_conv.cpp
  src/nogpu/handle.cpp
  src/solver.cpp
  src/solver/conv_hip_implicit_gemm_mlir_bin_fwd.cpp
  test/CMakeLists.txt
Labels: CI TESTS PASSED, urgency_high, value_high

#882 Fixed reg allocation for k-reduction in xdlops gemm
  src/kernels/composable_kernel/include/tensor_operation/xdlops_gemm.hpp
Labels: quality, urgency_medium

#878 Handle missing file when embedded build of MIOpen (SWDEV-282133)
  src/binary_cache.cpp
  src/include/miopen/sqlite_db.hpp
  src/sqlite_db.cpp
Labels: CI TESTS PASSED, complexity_low, urgency_blocker, value_middle

#888 Direct Asm 1x1 stride2 fixes for gfx90a
  src/kernels/conv1x1u_stride2.s
Labels: CI TESTS PASSED, bug

#865 rename EuristicInit to HeuristicInit
  src/include/miopen/solver.hpp
  src/include/miopen/solver/implicitgemm_util.hpp
  src/solver/conv_asm_1x1u.cpp
  src/solver/conv_asm_1x1u_bias_activ.cpp
  src/solver/conv_asm_1x1u_stride2.cpp
  src/solver/conv_asm_3x3u.cpp
  src/solver/conv_asm_dir_BwdWrW1x1.cpp
  src/solver/conv_asm_dir_BwdWrW3x3.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v1r1.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v1r1_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v4r1.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v4r1_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops_padded_gemm.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r5_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_nonxdlops_common.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops_padded_gemm.cpp
  src/solver/conv_hip_implicit_gemm_xdlops_common.cpp
  src/solver/conv_ocl_dir2D_bwdWrW_2.cpp
  src/solver/conv_winoRxS_f2x3.cpp
Labels: quality

#887 [OCL] Fix build error when MIOpenGEMM is not used
  src/solver/gemm_bwd.cpp
Labels: CI TESTS PASSED

#893 [COMGR] Fix UB: reference binding to null pointer of type 'char'
  src/comgr.cpp
Labels: CI TESTS PASSED, bug, urgency_medium

#885 [CI] Remove user db leftovers. [Jenkinsfile] Remove useless code.
  Jenkinsfile
Labels: testing, urgency_medium

#891 [OCL][FP16] Fix: Disable GEMM/MIOpenGEMM. [Immediate Mode] Always use Naive Direct in Fallback.
  src/include/miopen/solver.hpp
  src/ocl/convolutionocl.cpp
  src/solver/gemm.cpp
  src/solver/gemm_bwd.cpp
Labels: CI TESTS PASSED, bug, urgency_medium

#886 [CTC] Fix undefined behavior
  test/ctc.cpp
Labels: CI TESTS PASSED, urgency_medium

#892 Imlement mlir binary backend - step 3: wrw path
  src/CMakeLists.txt
  src/conv/invokers/mlir_impl_gemm.cpp
  src/include/miopen/conv/invokers/mlir_impl_gemm.hpp
  src/include/miopen/solver.hpp
  src/mlo_dir_conv.cpp
  src/solver.cpp
  src/solver/conv_hip_implicit_gemm_mlir_bin_wrw.cpp
  test/CMakeLists.txt
Labels: CI TESTS PASSED, urgency_high, value_high

#879 Deprecate MLIR CPP solver, step 1
  src/solver/conv_hip_implicit_gemm_mlir_cpp_bwd.cpp
  src/solver/conv_hip_implicit_gemm_mlir_cpp_fwd.cpp
  src/solver/conv_hip_implicit_gemm_mlir_cpp_wrw.cpp
  test/CMakeLists.txt
Labels: CI TESTS PASSED, urgency_high
