Repository ROCm/MIOpen, pull requests merged in 2021-05, with the labels that each got.

#896 Misc update to igemm mlir solvers and invokers
  src/CMakeLists.txt
  src/conv/invokers/mlir_impl_gemm.cpp
  src/include/miopen/solver.hpp
  src/mlo_dir_conv.cpp
  src/solver.cpp
  src/solver/conv_mlir_igemm_bwd.cpp
  src/solver/conv_mlir_igemm_fwd.cpp
  src/solver/conv_mlir_igemm_wrw.cpp
  test/CMakeLists.txt
Labels: CI TESTS PASSED, urgency_high

#899 [HOTFIX][CI][ROCm 3.7] Fix typo in PR 834
  src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops_padded_gemm.cpp
Labels: CI TESTS PASSED, urgency_blocker

#897 [NFC][ROCm 4.2] Workarounds for OpenCL build errors in DEV builds (SWDEV-270602)
  src/hipoc/hipoc_program.cpp
  src/include/miopen/kernel_warnings.hpp
  src/kernel_warnings.cpp
  src/ocl/clhelper.cpp
Labels: CI TESTS PASSED, non-miopen-bug

#905 IsWinograd3x3SupportedAndFast() changed to obey MIOPEN_DEBUG_FIND_ONLY_SOLVER
  src/convolution.cpp
Labels: CI TESTS PASSED, testing, urgency_high

#903 remove duplicated gcd() and remove src/include/miopen/numeric.hpp
  src/CMakeLists.txt
  src/conv/invokers/impl_gemm_dynamic.cpp
  src/include/miopen/conv/invokers/impl_gemm_dynamic.hpp
  src/include/miopen/numeric.hpp
  src/solver/conv_asm_implicit_gemm_bwd_v4r1_dynamic.cpp
Labels: CI TESTS PASSED

#900 Change gcd() implementation to avoid too deep recursion
  src/include/miopen/solver/implicitgemm_util.hpp
Labels: CI TESTS PASSED

#902 Implement mlir binary backend - step 4 group/fp16/NHWC support
  Dockerfile
  Jenkinsfile
  src/conv/invokers/mlir_impl_gemm.cpp
  src/include/miopen/memref.hpp
  src/include/miopen/solver/implicitgemm_util.hpp
  src/include/miopen/solver/mlir_util.hpp
  src/solver/conv_mlir_igemm_bwd.cpp
  src/solver/conv_mlir_igemm_fwd.cpp
  src/solver/conv_mlir_igemm_wrw.cpp
  test/CMakeLists.txt
Labels: TESTING_CI_PASSED, urgency_high, value_high

#909 [HOTFIX] Fix build error due to missing `Miir.h` when MIOPEN_USE_MLIR=0 and MLIR library is not available
  src/CMakeLists.txt
  src/conv/invokers/mlir_impl_gemm.cpp
Labels: bug, complexity_low, urgency_blocker

#914 Use FP32 scaling factors in ReduceTensor, regardless of the tensor data type (SWDEV-284921).
  driver/miopen_Reduction.hpp
  driver/reduce_driver.hpp
  src/reducetensor.cpp
  test/reduce_test.cpp
Labels: bug, urgency_blocker

#922 Install deps using cget instead of cmake-get
  install_deps.cmake
Labels: TESTING_CI_PASSED, urgency_blocker

#920 [CI][rocm-4.2.x][BF16] Disable V4R4 padded_gemm Solvers for BF16 with ROCm 3.7 due to fatal HIP compiler errors.
  src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops_padded_gemm.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops_padded_gemm.cpp
Labels: TESTING_CI_PASSED, non-miopen-bug, workaround

#929 [WORKAROUND][MI100][BF16] Disable V4R4 padded_gemm Solvers for BF16 with ROCm 3.7 due to fatal HIP compiler errors.
  src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops_padded_gemm.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops_padded_gemm.cpp
Labels: non-miopen-bug, urgency_blocker, workaround

#926 [MIOpenDriver] 3d conv set default layout as NCDHW
  driver/InputFlags.cpp
  driver/InputFlags.hpp
  driver/conv_driver.hpp
Labels: TESTING_CI_PASSED, complexity_low, enhancement

#931 Fix .max_flat_workgroup_size (SWDEV-277901, SWDEV-286069)
  src/kernels/conv5x10u2v2b1.s
  src/kernels/conv5x10u2v2f1.s
  src/kernels/conv7x7c3h224w224k64u2v2p3q3f1.s
Labels: bug, complexity_high, urgency_blocker

#925 Add driver logging to Reduction
  src/reducetensor_api.cpp
Labels: TESTING_CI_PASSED, complexity_low, enhancement, urgency_medium, value_middle

#927 [MLIR] Binary backend - step 6 - Introduce GetKernelCount API
  Dockerfile
  src/include/miopen/mlir_build.hpp
  src/mlir_build.cpp
  src/solver/conv_mlir_igemm_bwd.cpp
  src/solver/conv_mlir_igemm_fwd.cpp
  src/solver/conv_mlir_igemm_wrw.cpp
  src/solver/conv_mlir_igemm_wrw_xdlops.cpp
Labels: TESTING_CI_PASSED, complexity_low, urgency_high, value_high

#935 [MLIR] Binary backend - step 7 - Implement v4r1 algorithm for bwd solvers
  src/conv/invokers/mlir_impl_gemm.cpp
  src/include/miopen/solver/mlir_common.hpp
  src/solver/conv_mlir_igemm_bwd.cpp
  src/solver/conv_mlir_igemm_bwd_xdlops.cpp
  src/solver/conv_mlir_igemm_fwd.cpp
  src/solver/conv_mlir_igemm_fwd_xdlops.cpp
  src/solver/conv_mlir_igemm_wrw.cpp
  src/solver/conv_mlir_igemm_wrw_xdlops.cpp
  src/solver/mlir_common.cpp
Labels: urgency_medium, value_high

#933 Fix restrictions for vecload condition (iGemm v4r1 Bwd, 1x1)
  src/solver/conv_hip_implicit_gemm_bwd_v4r1.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v4r1_xdlops.cpp
  test/CMakeLists.txt
Labels: bug, urgency_blocker

#945 [HOTFIX] Workaround for SWDEV-286774. Disable ConvAsmImplicitGemmGTCDynamicBwdXdlops.
  src/solver/conv_asm_implicit_gemm_gtc_bwd.cpp
Labels: urgency_blocker, workaround

#947 [HOTFIX][WORKAROUND] Disable ConvAsmImplicitGemmGTCDynamicWrwXdlops for FP16
  src/solver/conv_asm_implicit_gemm_wrw_gtc_dynamic_xdlops.cpp
  test/CMakeLists.txt
Labels: bug, urgency_blocker, workaround

#949 Restrict workaround for SWDEV-286774 for FP16 only. Fix MIOPEN_DEBUG_FIND_ONLY_SOLVER in test_conv_igemm_dynamic* tests
  src/solver/conv_asm_implicit_gemm_gtc_bwd.cpp
  test/CMakeLists.txt
Labels: bug, performance, urgency_blocker

#932 Adding MIOpen Contributing Guide
  CONTRIBUTING.md
Labels: help wanted, request_for_comments

#953 Fix missing padding of the transformed 2d-src and 1d-dst tensors in Generic-Tensor Reduction (SWDEV-284291)
  src/kernels/composable_kernel/include/kernel_algorithm/gridwise_generic_reduction.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/reduction_kernel_simple_configurator.hpp
  src/kernels/composable_kernel/src/kernel_wrapper/gridwise_generic_reduction.cpp
  src/reducetensor.cpp
  test/reduce_test.cpp
Labels: TESTING_CI_PASSED, urgency_blocker

#951 [MI100][Dynamic Asm iGemm WrW] Fix kernel selection error for c or k padding cases with single batch, remove W/A for issue 946
  src/solver/conv_asm_implicit_gemm_wrw_gtc_dynamic_xdlops.cpp
  test/CMakeLists.txt
Labels: performance, urgency_high

#952 Fix NCHW bwd asm igemm solver. Remove WORKAROUND_SWDEV_286774.
  src/solver/conv_asm_implicit_gemm_gtc_bwd.cpp
  test/CMakeLists.txt
Labels: urgency_high

#944 [TESTS] Detect all failures of custom tests (issue #943)
  test/CMakeLists.txt
Labels: bug, testing
