Repository ROCm/MIOpen, pull requests merged in 2021-06, with the labels that each got.

#963 [HOTFIX] Made kernel includes inlined as multiple files (fix for SWDEV-284637)
  addkernels/addkernels.cpp
  src/CMakeLists.txt
  src/kernels/kernel.cpp.in
  src/kernels/kernel_includes.cpp.in
  src/ocl/gcn_asm_utils.cpp
Labels: TESTING_CI_PASSED, enhancement, non-miopen-bug, urgency_blocker

#470 remove workaround for issue #2335
  test/dropout.cpp
Labels: TESTING_CI_PASSED, urgency_medium

#937 [TESTS] Encapsulate Jenkins runDockerJob
  Jenkinsfile
Labels: TESTING_CI_PASSED, urgency_blocker, urgency_unknown

#950 Fix for PR #775. Disable xdlops for non gfx908
  test/CMakeLists.txt
Labels: TESTING_CI_PASSED, bug, testing

#916 Fix batchnorm precision
  driver/bn_driver.hpp
  src/kernels/MIOpenBatchNormBwdSpatial.cl
  src/ocl/batchnormocl.cpp
Labels: bug, complexity_high, urgency_medium

#934 Generic Tensor Reduction for Double (SWDEV-284915)
  driver/driver.hpp
  driver/main.cpp
  driver/miopen_Reduction.hpp
  driver/reduce_driver.hpp
  include/miopen/miopen.h
  src/gemm_v2.cpp
  src/include/miopen/conv/problem_description.hpp
  src/include/miopen/datatype.hpp
  src/include/miopen/tensor.hpp
  src/include/miopen/visit_float.hpp
  src/kernels/composable_kernel/include/kernel_algorithm/reduction_functions.hpp
  src/ocl/tensorocl.cpp
  src/reducetensor.cpp
  src/solver/conv_asm_1x1u.cpp
  src/tensor.cpp
  test/CMakeLists.txt
  test/driver.hpp
  test/reduce_test.cpp
  test/tensor_holder.hpp
  test/tensor_vec.cpp
Labels: new feature, urgency_blocker

#969 [HOTFIX][HIP iGemm][NFC] Rename type.hpp -> ck_utils_type.hpp (another W/A for SWDEV-284637)
  Dockerfile
  Jenkinsfile
  src/kernels/composable_kernel/include/utility/ck_utils_type.hpp
  src/kernels/composable_kernel/include/utility/common_header.hpp
  src/kernels/composable_kernel/include/utility/functional.hpp
  src/kernels/composable_kernel/include/utility/math.hpp
  src/kernels/composable_kernel/include/utility/sequence.hpp
  src/kernels/composable_kernel/include/utility/tuple.hpp
Labels: TESTING_CI_PASSED, non-miopen-bug, urgency_high

#971 Fix for tidy failures when branch name contains 'hpp'
  CMakeLists.txt
Labels: TESTING_CI_PASSED, bug, testing, urgency_high

#884 Change default find mode to Dynamic Hybrid
  src/include/miopen/find_controls.hpp
  src/include/miopen/miopen_internal.h
Labels: TESTING_CI_PASSED, enhancement, urgency_high, value_high

#956 Fix fp16 precision issue in ConvOclDirectFwd1x1
  src/kernels/MIOpenConv1x1S.cl
  test/CMakeLists.txt
Labels: urgency_high

#982 [MI100]fix issue 980-fix kernel selection logic for k-padding cases
  src/solver/conv_asm_implicit_gemm_wrw_gtc_dynamic_xdlops.cpp
  test/CMakeLists.txt
Labels: urgency_blocker

#984 Bump up the MIOpen version to 2.13 (after cutting the rocm-rel-4.3 branch)
  CMakeLists.txt
Labels: complexity_low

#955 [MLIR] Remove redundant solver local applicable checks
  src/solver/conv_mlir_igemm_fwd.cpp
  src/solver/conv_mlir_igemm_fwd_xdlops.cpp
  src/solver/conv_mlir_igemm_wrw.cpp
  src/solver/conv_mlir_igemm_wrw_xdlops.cpp
Labels: complexity_low

#974 Adding missing test vectors which caused failures (partial fix for SWDEV-291891)
  test/network_data.hpp
Labels: urgency_high

#987 [HOTFIX] Fix bug ConvHipImplicitGemmBwdDataV4R1Xdlops (SWDEV-291202)
  src/solver/conv_hip_implicit_gemm_bwd_v4r1_xdlops.cpp
Labels: bug, urgency_blocker

#989 [HOTFIX] Remove duplicated group divide when calculation k per group (SWDEV-291574)
  src/solver/conv_asm_implicit_gemm_gtc_bwd.cpp
Labels: bug, urgency_blocker

#978 [MLIR] Binary backend - step 8/of 8 - Bring up and enable bwd solvers
  Dockerfile
  src/conv/invokers/mlir_impl_gemm.cpp
  src/solver/conv_mlir_igemm_bwd.cpp
  src/solver/conv_mlir_igemm_bwd_xdlops.cpp
  test/CMakeLists.txt
Labels: complexity_middle, urgency_blocker, value_high

#994 [HOTFIX][WORKAROUND] Disable test_reduce_double (SWDEV-291479)
  test/CMakeLists.txt
Labels: urgency_blocker, workaround

#961 boost cmake version for Tensile 4.2
  Dockerfile
  Jenkinsfile
Labels: TESTING_CI_PASSED, urgency_high

#991 [TESTS][FP16][WORKAROUND] Fix test_conv_igemm_dynamic_xdlops* and test_regression_half_vega. W/A for #995 and #996
  Jenkinsfile
  test/CMakeLists.txt
Labels: TESTING_CI_PASSED, quality, testing, urgency_blocker, workaround

#1001 [vega][fp32]fix vega asm igemmwrw kernel selection bug
  src/solver/conv_asm_implicit_gemm_wrw_v4r1_dynamic.cpp
  test/CMakeLists.txt
Labels: TESTING_CI_PASSED, bug, urgency_high

#910 [NFC] First activation solver
  src/CMakeLists.txt
  src/activ/problem_description.cpp
  src/include/miopen/activ/invoke_params.hpp
  src/include/miopen/activ/problem_description.hpp
  src/include/miopen/activ/solvers.hpp
  src/include/miopen/execution_context.hpp
  src/include/miopen/find_solution.hpp
  src/include/miopen/handle.hpp
  src/ocl/activ_ocl.cpp
  src/ocl/convolutionocl.cpp
  src/solver.cpp
  src/solver/activ/fwd_0.cpp
Labels: TESTING_CI_PASSED

#981 Remove W/A for SWDEV-225285
  src/binary_cache.cpp
  src/expanduser.cpp
  src/hip/handlehip.cpp
  src/hipoc/hipoc_program.cpp
  src/include/miopen/expanduser.hpp
  src/include/miopen/stringutils.hpp
Labels: TESTING_CI_PASSED, bug, performance, quality, urgency_high

#998 [WORKAROUND] Generic-Reduction: Partially resolve SWDEV-291479. W/A for SWDEV-274384.
  src/kernels/composable_kernel/include/kernel_algorithm/reduction_functions.hpp
  src/kernels/composable_kernel/include/utility/reduction_common.hpp
  src/kernels/composable_kernel/include/utility/reduction_operator.hpp
  src/reducetensor.cpp
  test/CMakeLists.txt
  test/reduce_test.cpp
Labels: non-miopen-bug, urgency_blocker, workaround

#1004 [TESTS] Add regression tests for SWDEV-291574
  test/CMakeLists.txt
Labels: quality, testing, urgency_high

#970 Jenkins ci rocm 4.2
  CMakeLists.txt
  Dockerfile
  Jenkinsfile
  addkernels/addkernels.cpp
  driver/CBAInferFusion_driver.hpp
  driver/InputFlags.cpp
  driver/bn_driver.hpp
  driver/conv_driver.hpp
  driver/ctc_driver.hpp
  driver/driver.hpp
  driver/gemm_driver.hpp
  driver/lrn_driver.hpp
  driver/main.cpp
  driver/pool_driver.hpp
  driver/random.hpp
  driver/rnn_driver.hpp
  driver/tensorop_driver.hpp
  speedtests/sequences.cpp
  src/include/miopen/env.hpp
  src/include/miopen/generic_search.hpp
  src/kernels/gpu_reference_kernel/naive_conv.cpp
  src/solver/conv_ocl_dir2Dfwd_exhaustive_search.cpp
  test/CMakeLists.txt
  test/bn_3d_peract_test.cpp
  test/bn_3d_spatial_test.cpp
  test/bn_peract_test.cpp
  test/bn_spatial_test.cpp
  test/cache.cpp
  test/cba_inference.cpp
  test/cbna_inference.cpp
  test/conv_common.hpp
  test/ctc.cpp
  test/dropout.cpp
  test/find_db.cpp
  test/gpu_reference_kernel.cpp
  test/gru.cpp
  test/gru_common.hpp
  test/lstm.cpp
  test/lstm_common.hpp
  test/main.cpp
  test/na_inference.cpp
  test/random.hpp
  test/reduce_test.cpp
  test/rnn_util.hpp
  test/rnn_vanilla.cpp
  test/rnn_vanilla_common.hpp
Labels: TESTING_CI_PASSED

#1014 [ASM IGEMM][MI100] refactor solver, remove duplicated copy of pointers
  src/include/miopen/conv/invokers/impl_gemm_dynamic.hpp
  src/solver/conv_asm_implicit_gemm_wrw_gtc_dynamic_xdlops.cpp
Labels: TESTING_CI_PASSED, enhancement, performance

#1011 [Navi21] Fix generic reduction kernels by removing __llvm_amdgcn_s_barrier (SWDEV-274384)
  src/kernels/composable_kernel/include/utility/synchronization.hpp
Labels: TESTING_CI_PASSED

#1019 [TESTS] Resolve PR #970 review comments
  CMakeLists.txt
  driver/CBAInferFusion_driver.hpp
  test/CMakeLists.txt
  test/random.hpp
Labels: TESTING_CI_PASSED

#968 Fix: Explicitly remove temp dirs (avoid leftovers when the user's app exits abnormally)
  src/hip/handlehip.cpp
  src/hipoc/hipoc_program.cpp
  src/include/miopen/hipoc_program.hpp
Labels: TESTING_CI_PASSED, bug, urgency_medium, value_middle
