Repository ROCm/MIOpen, pull requests merged in 2022-02, with the labels that each got.

#1398 [Navi21] Remove W/A for SWDEV-292187
  src/execution_context.cpp
  src/include/miopen/execution_context.hpp
  src/include/miopen/target_properties.hpp
  src/solver/conv_ocl_dir2D11x11.cpp
  src/solver/conv_ocl_dir2D_bwdWrW_1x1.cpp
  src/solver/conv_ocl_dir2D_bwdWrW_2.cpp
  src/solver/conv_ocl_dir2D_bwdWrW_53.cpp
  src/solver/conv_ocl_dir2Dfwd.cpp
  src/solver/conv_ocl_dir2Dfwd1x1.cpp
  src/solver/conv_ocl_dir2Dfwdgen.cpp
  test/CMakeLists.txt
  test/handle_test.cpp
Labels: performance, workaround, urgency_high, TESTING_CI_PASSED

#1395 Revert incorrect change to `ConvBiasActivAsm1x1U` solver search method
  src/solver/conv_asm_1x1u_bias_activ.cpp
Labels: urgency_high, TESTING_CI_PASSED

#1400 [Quality] Fix potential verify error with NaN - IEEE-754 comparison rule
  driver/conv_driver.hpp
  driver/lrn_driver.hpp
  driver/reduce_driver.hpp
  driver/softmax_driver.hpp
Labels: value_middle, complexity_low, urgency_normal, TESTING_CI_PASSED

#1397 [Jenkins] Fix "clang-format" stage
  Jenkinsfile
  driver/InputFlags.cpp
  driver/conv_driver.hpp
  src/comgr.cpp
  src/conv/invokers/impl_gemm_dynamic.cpp
  src/gemm_v2.cpp
  src/include/miopen/activ/solvers.hpp
  src/include/miopen/batchnorm/solvers.hpp
  src/include/miopen/conv/asm_implicit_gemm.hpp
  src/include/miopen/generic_search.hpp
  src/include/miopen/solver.hpp
  src/include/miopen/sqlite_db.hpp
  src/include/miopen/tensor_layout.hpp
  src/kernels/MIOpenBatchNormBwdSpatial.cl
  src/kernels/MIOpenBatchNormFwdTrainSpatial.cl
  src/ocl/batchnormocl.cpp
  src/solver/batchnorm/backward_spatial_single.cpp
  src/solver/conv_asm_implicit_gemm_gtc_bwd_nhwc.cpp
  src/solver/conv_asm_implicit_gemm_gtc_fwd_nhwc.cpp
  src/solver/conv_asm_implicit_gemm_gtc_perf_config.cpp
  test/bn_spatial_nhwc_test.cpp
  test/ford.hpp
  test/solver.cpp
Labels: quality, TESTING_CI_PASSED

#1323 Fix: Use `use_hip_kernels` and `use_asm_kernels` in Naive convolution Solvers
  src/include/miopen/solver/conv_direct_naive_conv.hpp
  src/solver/conv_direct_naive_conv.cpp
  src/solver/conv_direct_naive_conv_bwd.cpp
  src/solver/conv_direct_naive_conv_fwd.cpp
  src/solver/conv_direct_naive_conv_wrw.cpp
Labels: bug, urgency_normal

#1386 [Navi21] Fixing Batchnorm backward precision issues by adjusting workgroup size (SWDEV-292187, SWDEV-319919)
  src/solver/batchnorm/backward_spatial_single.cpp
Labels: value_high, urgency_blocker

#1288 [HIP][COMGR] Use COMGR by default for HIP backend.
  CMakeLists.txt
  Jenkinsfile
Labels: enhancement, urgency_blocker, TESTING_CI_PASSED

#1409 [SWDEV-321331] Fix ONNX runtime unit tests for reductions
  src/composable_kernel/composable_kernel/src/kernel_wrapper/gridwise_generic_reduction_second_call_threadwise_reduce_all_dims.cpp
  src/reducetensor.cpp
  test/CMakeLists.txt
Labels: value_high, urgency_blocker

#1406 [NFC] Fix typo: workspce -> workspace.
  fin/src/include/conv_fin.hpp
  src/conv/invokers/gcn_asm_1x1u_ss.cpp
  src/conv/invokers/gcn_asm_1x1u_us.cpp
  src/convolution.cpp
  src/include/miopen/conv/invokers/gcn_asm_1x1u_ss.hpp
  src/include/miopen/conv/invokers/gcn_asm_1x1u_us.hpp
  src/include/miopen/conv_solution.hpp
  src/include/miopen/generic_search.hpp
  src/include/miopen/mlo_internal.hpp
  src/ocl/convolutionocl.cpp
  src/ocl/mloNorm.cpp
  src/solver/conv_MP_bidirectional_winograd.cpp
  src/solver/conv_asm_1x1u.cpp
  src/solver/conv_asm_1x1u_stride2.cpp
  src/solver/conv_asm_dir_BwdWrW1x1.cpp
  src/solver/conv_asm_dir_BwdWrW3x3.cpp
  src/solver/conv_asm_implicit_gemm_gtc_bwd_nhwc.cpp
  src/solver/conv_asm_implicit_gemm_gtc_fwd_nhwc.cpp
  src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp
  src/solver/conv_asm_implicit_gemm_wrw_gtc_dynamic_xdlops.cpp
  src/solver/conv_asm_implicit_gemm_wrw_v4r1_dynamic.cpp
  src/solver/conv_ck_igemm_fwd_v6r1_dlops_nchw.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v1r1.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v1r1_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v4r1_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops_padded_gemm.cpp
  src/solver/conv_multipass_wino3x3WrW.cpp
  src/solver/conv_ocl_dir2D_bwdWrW_1x1.cpp
  src/solver/conv_ocl_dir2D_bwdWrW_2.cpp
  src/solver/conv_ocl_dir2D_bwdWrW_53.cpp
  src/solver/fft.cpp
  src/solver/gemm.cpp
  src/solver/gemm_bwd.cpp
  src/solver/gemm_wrw.cpp
Labels: quality, TESTING_CI_PASSED

#1377 [MI100][MI200] iGemm ASM GTC XDLOPS: Support for deterministic results (SWDEV-316705)
  src/include/miopen/convolution.hpp
  src/solver/conv_asm_implicit_gemm_gtc_bwd_nhwc.cpp
  src/solver/conv_asm_implicit_gemm_gtc_fwd_nhwc.cpp
  src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp
Labels: enhancement, urgency_blocker

#1407 [Navi21][COMGR][OpenCL] Disabled wavefrontsize=64 for OCL on COMGR path. [Quality] Fixed build warnings with ROCm mainline. [CK][NFC] Some simplification.
  src/comgr.cpp
  src/composable_kernel/composable_kernel/include/tensor_description/tensor_descriptor.hpp
  src/gemm_v2.cpp
  src/include/miopen/handle_lock.hpp
  src/kernels/MIOpenConvDirBatchNormActiv.cl
  src/kernels/MIOpenConvDirUni.cl
  src/kernels/MIOpenConvDirUni_Vec2.cl
  src/kernels/MIOpenConvFwd_LxL_11.cl
  src/kernels/MIOpenLRNFwd.cl
  src/kernels/detect_llvm_amdgcn_buffer_atomic_fadd_f32_float.cpp
  src/kernels/gpu_reference_kernel/naive_conv.cpp
  test/args.hpp
  test/gpu_nchw_nhwc_transpose.cpp
Labels: bug, value_high, quality, TESTING_CI_PASSED

#1394 Replace deprecated HIP API (SWDEV-318154)
  cmake/EnableCompilerWarnings.cmake
  src/hip/handlehip.cpp
  src/hipoc/hipoc_kernel.cpp
Labels: TESTING_CI_PASSED

#1415 [Tests] add test_reduce_test and follow up PR #1409
  test/CMakeLists.txt
  test/reduce_test.cpp
Labels: bug, testing, TESTING_CI_PASSED

#1402 [SWDEV-274378][LRN] Fix in local response normalization layer to synchronize local memory access within workgroup
  src/kernels/MIOpenLRNBwd.cl
Labels: value_high, urgency_high, TESTING_CI_PASSED

#1414 [Jenkinsfile][NOGPU] Do not use clinfo and do not reboot nodes.
  Jenkinsfile
Labels: enhancement, testing, TESTING_CI_PASSED

#1425 [Tests][Navi21][FP16] W/A #1423 bypass large tensor reduce test
  test/CMakeLists.txt
Labels: urgency_blocker, TESTING_CI_PASSED

#1408 [Quality] Fix more verify error with NaNs and Inf
  driver/bn_driver.hpp
  driver/conv_driver.hpp
  driver/ctc_driver.hpp
  driver/dropout_driver.hpp
  driver/gemm_driver.hpp
  driver/lrn_driver.hpp
  driver/pool_driver.hpp
  driver/reduce_driver.hpp
  driver/rnn_driver.hpp
  driver/softmax_driver.hpp
Labels: value_middle, quality, urgency_normal, TESTING_CI_PASSED

#1237 Enable HIPRTC support as default from ROCm 5.0
  CMakeLists.txt
  include/miopen/config.h.in
  src/comgr.cpp
  src/composable_kernel/composable_kernel/include/utility/array.hpp
  src/composable_kernel/composable_kernel/include/utility/data_type.hpp
  src/composable_kernel/composable_kernel/include/utility/type.hpp
  src/hipoc/hipoc_program.cpp
  src/include/miopen/comgr.hpp
  src/include/miopen/kernel.hpp
  src/kernels/kernel_includes.cpp.in
  src/kernels/static_composable_kernel/include/utility/static_kernel_ck_utils_type.hpp
  src/kernels/static_composable_kernel/include/utility/static_kernel_tuple.hpp
Labels: enhancement, urgency_blocker, complexity_high, TESTING_CI_PASSED

#1428 [DOC] [NFC] Update MI200 specific documentation
  doc/src/MI200AlternateImplementation.md
  doc/src/index.rst
Labels: specification, documentation
