Repository ROCm/MIOpen, pull requests merged in 2022-10, with the labels that each got.

#1784 [Solvers] ConvAsm1x1U, ConvBiasActivAsm1x1U: split ConvolutionContext and ProblemDescription (stage 2)
  src/include/miopen/generic_search.hpp
  src/include/miopen/solver.hpp
  src/solver/conv_asm_1x1u.cpp
  src/solver/conv_asm_1x1u_bias_activ.cpp
Labels: enhancement, quality, TESTING_CI_PASSED

#1799 [Solvers] ConvAsmImplicitGemmGTCDynamicFwdDlopsNCHWC: split ConvolutionContext and ProblemDescription (stage 2)
  src/conv/invokers/impl_gemm_dynamic.cpp
  src/include/miopen/conv/invokers/impl_gemm_dynamic.hpp
  src/include/miopen/solver.hpp
  src/solver/conv_asm_implicit_gemm_gtc_fwd_nchwc.cpp
Labels: enhancement, quality, TESTING_CI_PASSED

#1795 [Solvers] ConvAsmBwdWrW1x1, ConvAsmBwdWrW3x3: split ConvolutionContext and ProblemDescription (stage 2)
  src/include/miopen/solver.hpp
  src/solver/conv_asm_dir_BwdWrW1x1.cpp
  src/solver/conv_asm_dir_BwdWrW3x3.cpp
Labels: enhancement, quality, TESTING_CI_PASSED

#1798 [Solvers] ConvAsmImplicitGemmGTCDynamicBwdXdlopsNHWC: split ConvolutionContext and ProblemDescription (stage 2)
  src/conv/invokers/impl_gemm_dynamic.cpp
  src/include/miopen/conv/invokers/impl_gemm_dynamic.hpp
  src/include/miopen/solver.hpp
  src/solver/conv_asm_implicit_gemm_gtc_bwd_nhwc.cpp
Labels: enhancement, quality, TESTING_CI_PASSED

#1791 Fixed find 2.0 to work correctly with transposed convolution
  src/include/miopen/problem.hpp
  src/include/miopen/solution.hpp
  src/problem.cpp
  src/solution.cpp
  test/find_2_conv.cpp
  test/reduce_test.cpp
  test/tensor_holder.hpp
Labels: bug, value_high, complexity_low, urgency_high, TESTING_CI_PASSED

#1802 [Solvers] ConvAsmImplicitGemmGTCDynamicFwdXdlopsNHWC: split ConvolutionContext and ProblemDescription (stage 2)
  src/conv/invokers/impl_gemm_dynamic.cpp
  src/include/miopen/conv/invokers/impl_gemm_dynamic.hpp
  src/include/miopen/solver.hpp
  src/solver/conv_asm_implicit_gemm_gtc_fwd_nhwc.cpp
Labels: enhancement, quality, TESTING_CI_PASSED

#1752 bg/LWPMIOPEN-40 : Dump out input/output and weights tensor when a NaN/Inf occurs in Convolution
  driver/conv_verify.hpp
  src/hip/handlehip.cpp
  src/include/miopen/convolution.hpp
  src/include/miopen/handle.hpp
  src/nogpu/handle.cpp
  src/ocl/convolutionocl.cpp
  src/ocl/handleocl.cpp
  test/gtest/CMakeLists.txt
  test/gtest/dumpTensorTest.cpp
Labels: TESTING_CI_PASSED, debugging

#1811 [Solvers] ConvHipImplicitGemm solvers: prepare for splitting ConvolutionContext and ProblemDescription (stage 2)
  src/conv/invokers/impl_gemm.cpp
  src/include/miopen/conv/invokers/impl_gemm.hpp
  src/include/miopen/solver.hpp
  src/include/miopen/solver/implicitgemm_util.hpp
  src/solver/conv_hip_implicit_gemm_bwd_v1r1.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v1r1_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v4r1.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v4r1_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r1.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops_padded_gemm.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r5_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_fwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_nonxdlops_common.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops_padded_gemm.cpp
  src/solver/conv_hip_implicit_gemm_xdlops_common.cpp
Labels: enhancement, quality, TESTING_CI_PASSED

#1816 [Workaround] bug in the llvm::msgpack when N is recognized as "false", a boolean type instead of string type.
  src/kernels/Conv_Winograd_v13_3_12_epilogue.inc
  src/kernels/Conv_Winograd_v16_5_0_epilogue.inc
  src/kernels/Conv_Winograd_v21_1_3_metadata.inc
  src/kernels/conv1x1u.s
  src/kernels/conv1x1u_bias_activ.s
  src/kernels/conv1x1u_stride2.s
  src/kernels/conv1x1wrw.s
  src/kernels/conv3x3wrw.s
  src/kernels/conv_3x3_wheel_alpha_v3_0b_epilogue.inc
  src/kernels/conv_3x3_wheel_alpha_v7_0_3b_epilogue.inc
  src/kernels/conv_3x3_wheel_alpha_v9_0_15_epilogue.inc
  src/kernels/conv_3x3_wheel_alpha_v9_2_7_epilogue.inc
  src/kernels/xform_bidirect_winograd_code.inc
  src/kernels/xform_metadata.inc
Labels: non-miopen-bug, urgency_high

#1814 [Solvers] ConvBinWinoRxS, ConvBinWinogradRxSf2x3g1, ConvBinWinogradRxSf2x3g1Fused: split ConvolutionContext and ProblemDescription (stage 2)
  src/include/miopen/solver.hpp
  src/solver/conv_winoRxS.cpp
Labels: enhancement, quality, TESTING_CI_PASSED

#1808 [Solvers] ConvCkIgemmFwdV6r1DlopsNchw: split ConvolutionContext and ProblemDescription (stage 2)
  src/include/miopen/solver.hpp
  src/include/miopen/solver/ck_utility_common.hpp
  src/solver/conv_ck_igemm_fwd_v6r1_dlops_nchw.cpp
Labels: enhancement, quality, TESTING_CI_PASSED

#1806 [Solvers] ConvAsmImplicitGemmGTCDynamicWrwXdlopsNHWC: split ConvolutionContext and ProblemDescription (stage 2)
  src/include/miopen/solver.hpp
  src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp
Labels: enhancement, quality, TESTING_CI_PASSED

#1813 [Solvers] ConvMlirIgemm solvers: split ConvolutionContext and ProblemDescription (stage 2)
  src/conv/invokers/mlir_impl_gemm.cpp
  src/include/miopen/conv/invokers/mlir_impl_gemm.hpp
  src/include/miopen/solver.hpp
  src/include/miopen/solver/mlir_common.hpp
  src/solver/conv_mlir_igemm_bwd.cpp
  src/solver/conv_mlir_igemm_bwd_xdlops.cpp
  src/solver/conv_mlir_igemm_fwd.cpp
  src/solver/conv_mlir_igemm_fwd_xdlops.cpp
  src/solver/conv_mlir_igemm_wrw.cpp
  src/solver/conv_mlir_igemm_wrw_xdlops.cpp
  src/solver/mlir_common.cpp
Labels: enhancement, quality, TESTING_CI_PASSED

#1817 [DOC] Fixed table formatting at footer of MIOpen_Porting_Guide
  doc/src/MIOpen_Porting_Guide.md
  doc/src/index.rst
Labels: documentation

#1803 [CK API] 2d forward convolution composable kernel integration (multi-datatype)
  src/include/miopen/solver.hpp
  src/solver/conv_hip_implicit_gemm_fwd_xdlops.cpp
Labels: TESTING_CI_PASSED

#1821 [Solvers] ConvHipImplicitGemmBwdDataV1R1Xdlops: split ConvolutionContext and ProblemDescription (stage 2)
  src/include/miopen/solver.hpp
  src/include/miopen/solver/implicitgemm_util.hpp
  src/solver/conv_hip_implicit_gemm_bwd_v1r1_xdlops.cpp
Labels: enhancement, quality, TESTING_CI_PASSED

#1827 [SWDEV-358495] Exclude gtest from all Target
  test/CMakeLists.txt
Labels: urgency_blocker

#1829 [ROCm 5.4] Update CK Commit
  requirements.txt
Labels: urgency_blocker

#1831 [Solvers] ConvHipImplicitGemmBwdDataV4R1: split ConvolutionContext and ProblemDescription (stage 2)
  src/include/miopen/solver.hpp
  src/solver/conv_hip_implicit_gemm_bwd_v4r1.cpp
Labels: enhancement, quality, TESTING_CI_PASSED

#1834 [Solvers] ConvHipImplicitGemmForwardV4R4Xdlops: split ConvolutionContext and ProblemDescription (stage 2)
  src/include/miopen/solver.hpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops.cpp
Labels: enhancement, quality, TESTING_CI_PASSED

#1832 [Solvers] ConvHipImplicitGemmV4R1Fwd, ConvHipImplicitGemmV4R1WrW: split ConvolutionContext and ProblemDescription (stage 2)
  src/include/miopen/solver.hpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r1.cpp
  src/solver/conv_hip_implicit_gemm_nonxdlops_common.cpp
Labels: enhancement, quality, TESTING_CI_PASSED

#1835 [Solvers] ConvHipImplicitGemmV4R1Fwd: split ConvolutionContext and ProblemDescription (stage 2)
  src/include/miopen/solver.hpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4.cpp
Labels: enhancement, quality, TESTING_CI_PASSED

#1833 [Solvers] ConvHipImplicitGemmForwardV4R4Xdlops_Padded_Gemm: split ConvolutionContext and ProblemDescription (stage 2)
  src/include/miopen/solver.hpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops_padded_gemm.cpp
Labels: enhancement, quality, TESTING_CI_PASSED

#1836 [Solvers] ConvHipImplicitGemmForwardV4R5Xdlops: split ConvolutionContext and ProblemDescription (stage 2)
  src/include/miopen/solver.hpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r5_xdlops.cpp
Labels: enhancement, quality, TESTING_CI_PASSED

#1845 [Solvers] ConvHipImplicitGemmFwdXdlops: split ConvolutionContext and ProblemDescription (stage 2)
  src/include/miopen/solver.hpp
  src/solver/conv_hip_implicit_gemm_fwd_xdlops.cpp
Labels: enhancement, quality, TESTING_CI_PASSED

#1781 Extended applicability of ConvBinWinoRxS
  src/solver/conv_winoRxS.cpp
Labels: tuning, urgency_high, TESTING_CI_PASSED

#1853 [HotFix] Fix Tidy Issue bugprone-implicit-widening-of-multiplication-result
  src/solver/conv_winoRxS.cpp
Labels: urgency_blocker

#1844 [docs] Fixed RNN datatype description plus more. [tests] Fix: Use test_convXd_find2 just like test_convXd. Removed MIOPENTENSILE.
  include/miopen/miopen.h
  test/CMakeLists.txt
Labels: testing, urgency_normal, TESTING_CI_PASSED, documentation

#1846 [Solvers] ConvHipImplicitGemmWrwV4R4Xdlops_Padded_Gemm: split ConvolutionContext and ProblemDescription (stage 2)
  src/include/miopen/solver.hpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops_padded_gemm.cpp
Labels: enhancement, quality, TESTING_CI_PASSED

#1847 [Solvers] ConvHipImplicitGemmWrwV4R4Xdlops: split ConvolutionContext and ProblemDescription (stage 2)
  src/include/miopen/solver.hpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops.cpp
Labels: enhancement, quality, TESTING_CI_PASSED

#1840 [tests] Added smoke tests for conv solvers (ConvAsm5x10u2v2f1 and more). Fix potential issue in ImplicitGemm tests. Some refactorings.
  test/CMakeLists.txt
Labels: urgency_blocker, testing, TESTING_CI_PASSED

#1848 [Solvers] ConvHipImplicitGemmV4R4WrW: split ConvolutionContext and ProblemDescription (stage 2)
  src/include/miopen/solver.hpp
  src/include/miopen/solver/implicitgemm_util.hpp
  src/solver/conv_hip_implicit_gemm_bwd_v4r1_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4.cpp
Labels: enhancement, quality, TESTING_CI_PASSED

#1849 [Solvers] ConvOclBwdWrW2, ConvOclBwdWrW2NonTunable: split ConvolutionContext and ProblemDescription (stage 2)
  src/include/miopen/solver.hpp
  src/solver/conv_ocl_dir2D_bwdWrW_2.cpp
Labels: enhancement, quality, TESTING_CI_PASSED
