Repository ROCm/MIOpen, pull requests merged in 2022-11, with the labels that each got.

#1855 [Solvers] ConvMPBidirectWinograd, ConvMPBidirectWinograd_xdlops: split ConvolutionContext and ProblemDescription (stage 2)
  src/include/miopen/solver.hpp
  src/solver/conv_MP_bidirectional_winograd.cpp
Labels: enhancement, quality, TESTING_CI_PASSED

#1856 [Solvers] Remove unused PerformanceImplicitGemmXdlops
  src/CMakeLists.txt
  src/include/miopen/solver.hpp
  src/solver/conv_hip_implicit_gemm_xdlops_common.cpp
Labels: quality, TESTING_CI_PASSED

#1859 [Legacy][NFC] Remove unused mlo_construct_neuron
  src/CMakeLists.txt
  src/include/miopen/mlo_internal.hpp
  src/ocl/mloNeuron.cpp
Labels: quality, TESTING_CI_PASSED

#1861 [tests] Fix test_activation and remove W/A for issue 1334.
  test/CMakeLists.txt
  test/activation.cpp
Labels: bug, testing, urgency_high, TESTING_CI_PASSED

#1857 [Solvers] ConvOclDirectFwd solvers: split ConvolutionContext and ProblemDescription (stage 2)
  src/include/miopen/solver.hpp
  src/solver/conv_ocl_dir2Dfwd.cpp
  src/solver/conv_ocl_dir2Dfwd1x1.cpp
  src/solver/conv_ocl_dir2Dfwd_exhaustive_search.cpp
Labels: enhancement, quality, TESTING_CI_PASSED

#1867 [Find 2.0] Added missing SetupFloats call to miopenRunSolution
  src/solution.cpp
Labels: bug, urgency_high, TESTING_CI_PASSED

#1865 [Clang-16][D131307] suppress -Wenum-constexpr-conversion
  requirements.txt
  src/comgr.cpp
Labels: value_middle, quality, urgency_high, TESTING_CI_PASSED

#1872 Fix for identifying LegacySolver
  src/include/miopen/any_solver.hpp
Labels: bug, urgency_high, TESTING_CI_PASSED

#1879 [DEBUG] Fix incorrect assert
  src/include/miopen/tensor.hpp
Labels: urgency_normal, debugging

#1884 [HOTFIX][tests] Fixed defect in #1844 which results in omission of all custom tests
  test/CMakeLists.txt
Labels: bug, urgency_blocker, testing, TESTING_CI_PASSED
