Repository ROCm/MIOpen, pull requests merged in 2022-04, with the labels that each got.

#1496 [Bug fix][SWDEV-329914] fix stride compute bug in asm igemm bwd fwd and wrw
  src/conv/invokers/impl_gemm_dynamic.cpp
  src/solver/conv_asm_implicit_gemm_gtc_bwd.cpp
  src/solver/conv_asm_implicit_gemm_gtc_bwd_nhwc.cpp
  src/solver/conv_asm_implicit_gemm_gtc_fwd.cpp
  src/solver/conv_asm_implicit_gemm_gtc_fwd_nhwc.cpp
  src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp
  src/solver/conv_asm_implicit_gemm_wrw_gtc_dynamic_xdlops.cpp
  test/CMakeLists.txt
Labels: bug, urgency_high, TESTING_CI_PASSED

#1502 [GFX90A] Winograd 21_1_3 minor updates
  src/kernels/Conv_Winograd_v21_1_3_gfx90a_f3x2_fp16_dot2_edc_stride1_group.inc
  src/kernels/Conv_Winograd_v21_1_3_gfx90a_f3x2_fp32_stride1_group.inc
  src/kernels/Conv_Winograd_v21_1_3_gfx90a_fp16_dot2_edc_dilation2.inc
  src/kernels/Conv_Winograd_v21_1_3_gfx90a_fp16_dot2_edc_dilation2_group.inc
  src/kernels/Conv_Winograd_v21_1_3_gfx90a_fp16_dot2_edc_stride1.inc
  src/kernels/Conv_Winograd_v21_1_3_gfx90a_fp16_dot2_edc_stride1_group.inc
  src/kernels/Conv_Winograd_v21_1_3_gfx90a_fp16_dot2_edc_stride2.inc
  src/kernels/Conv_Winograd_v21_1_3_gfx90a_fp16_dot2_edc_stride2_group.inc
  src/kernels/Conv_Winograd_v21_1_3_gfx90a_fp32_dilation2.inc
  src/kernels/Conv_Winograd_v21_1_3_gfx90a_fp32_dilation2_group.inc
  src/kernels/Conv_Winograd_v21_1_3_gfx90a_fp32_stride1.inc
  src/kernels/Conv_Winograd_v21_1_3_gfx90a_fp32_stride1_group.inc
  src/kernels/Conv_Winograd_v21_1_3_gfx90a_fp32_stride2.inc
  src/kernels/Conv_Winograd_v21_1_3_gfx90a_fp32_stride2_group.inc
Labels: urgency_normal, TESTING_CI_PASSED

#1435 [mlir] Adding heuristic init request to perfdb
  src/include/miopen/solver.hpp
  src/solver/conv_mlir_igemm_fwd.cpp
  src/solver/conv_mlir_igemm_fwd_xdlops.cpp
Labels: bug, value_middle, tuning, urgency_high, TESTING_CI_PASSED

#1501 [MLIR] Bumping release to ROCm 5.2
  requirements.txt
  test/CMakeLists.txt
Labels: urgency_high

#1492 [SWDEV-329485] Remove clang-ocl dependency for miopen-hip
  CMakeLists.txt
Labels: complexity_middle, urgency_normal

#1478 [tests] Enabled PCH for testing builds that have COMGR enabled (removed WORKAROUND_ISSUE_898)
  test/CMakeLists.txt
Labels: urgency_high

#1487 [Solvers] Single performance config for all ConvBiasActivAsm1x1U methods
  src/include/miopen/solver.hpp
  src/solver/conv_asm_1x1u_bias_activ.cpp
Labels: TESTING_CI_PASSED

#1498 [Bug fix] Passing "--weight" flag to filter_dims.
  test/conv_common.hpp
Labels: TESTING_CI_PASSED

#1481 [Tensor reorder][Quality][#issue 1476] Improve naming style and CTest design
  src/conv/invokers/impl_gemm_dynamic.cpp
  src/hip/batched_transpose_sol.cpp
  src/hip/general_tensor_reorder_sol.cpp
  src/include/miopen/batched_transpose_sol.hpp
  src/include/miopen/general_tensor_reorder_sol.hpp
  src/include/miopen/tensor_reorder_util.hpp
  src/kernels/gpu_general_tensor_reorder_kernel/general_tensor_reorder.cpp
  src/kernels/gpu_general_tensor_reorder_kernel/order.hpp
  src/solver/conv_asm_implicit_gemm_gtc_bwd_nhwc.cpp
  src/solver/conv_asm_implicit_gemm_gtc_fwd_nhwc.cpp
  src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp
  test/gpu_nchw_nhwc_transpose.cpp
  test/tensor_reorder.cpp
Labels: urgency_blocker, TESTING_CI_PASSED

#1505 [MLIR] Querying all sub-kernels applicability
  src/solver/conv_mlir_igemm_fwd.cpp
  src/solver/conv_mlir_igemm_fwd_xdlops.cpp
Labels: bug, urgency_high, TESTING_CI_PASSED

#1514 Updated rocm cmake version requirement
  dev-requirements.txt
  requirements.txt
Labels: urgency_blocker

#1515 [Tensor reorder][Quality][#issue 1476] Split kernel file & resolve unsolved issues
  src/hip/general_tensor_reorder_sol.cpp
  src/include/miopen/general_tensor_reorder_sol.hpp
  src/include/miopen/tensor_reorder_util.hpp
  src/kernels/gpu_general_tensor_reorder_kernel/general_tensor_reorder.cpp
  src/kernels/gpu_general_tensor_reorder_kernel/general_tensor_reorder_16x256_byte.cpp
  src/kernels/gpu_general_tensor_reorder_kernel/general_tensor_reorder_16x256_dword.cpp
  src/kernels/gpu_general_tensor_reorder_kernel/general_tensor_reorder_16x256_dwordx2.cpp
  src/kernels/gpu_general_tensor_reorder_kernel/general_tensor_reorder_16x256_half.cpp
  src/kernels/gpu_general_tensor_reorder_kernel/general_tensor_reorder_1x256_byte.cpp
  src/kernels/gpu_general_tensor_reorder_kernel/general_tensor_reorder_1x256_dword.cpp
  src/kernels/gpu_general_tensor_reorder_kernel/general_tensor_reorder_1x256_dwordx2.cpp
  src/kernels/gpu_general_tensor_reorder_kernel/general_tensor_reorder_1x256_half.cpp
  src/kernels/gpu_general_tensor_reorder_kernel/general_tensor_reorder_2x256_byte.cpp
  src/kernels/gpu_general_tensor_reorder_kernel/general_tensor_reorder_2x256_dword.cpp
  src/kernels/gpu_general_tensor_reorder_kernel/general_tensor_reorder_2x256_dwordx2.cpp
  src/kernels/gpu_general_tensor_reorder_kernel/general_tensor_reorder_2x256_half.cpp
  src/kernels/gpu_general_tensor_reorder_kernel/general_tensor_reorder_4x256_byte.cpp
  src/kernels/gpu_general_tensor_reorder_kernel/general_tensor_reorder_4x256_dword.cpp
  src/kernels/gpu_general_tensor_reorder_kernel/general_tensor_reorder_4x256_dwordx2.cpp
  src/kernels/gpu_general_tensor_reorder_kernel/general_tensor_reorder_4x256_half.cpp
  src/kernels/gpu_general_tensor_reorder_kernel/general_tensor_reorder_8x256_byte.cpp
  src/kernels/gpu_general_tensor_reorder_kernel/general_tensor_reorder_8x256_dword.cpp
  src/kernels/gpu_general_tensor_reorder_kernel/general_tensor_reorder_8x256_dwordx2.cpp
  src/kernels/gpu_general_tensor_reorder_kernel/general_tensor_reorder_8x256_half.cpp
  src/kernels/gpu_general_tensor_reorder_kernel/general_tensor_reorder_kernel_util.hpp
  src/kernels/gpu_general_tensor_reorder_kernel/order.hpp
  test/tensor_reorder.cpp
Labels: urgency_high, TESTING_CI_PASSED

#1508 [tests] [by Artem] Enabled PCH for testing builds that have COMGR enabled (removed WORKAROUND_ISSUE_898)
  src/kernels/gpu_general_tensor_reorder_kernel/general_tensor_reorder_kernel_util.hpp
  test/CMakeLists.txt
Labels: urgency_blocker, TESTING_CI_PASSED

#1521 Update parsing of CMake flags to handle generator expressions
  CMakeLists.txt
  cmake/TargetFlags.cmake
  src/hip/hip_build_utils.cpp
Labels: urgency_blocker, TESTING_CI_PASSED

#1469 [Navi21][COMGR][HIPRTC][WORKAROUND] W/A for `warpSize` issue when PCH is used.
  src/CMakeLists.txt
  src/comgr.cpp
  src/composable_kernel/composable_kernel/include/tensor_operation/gridwise_generic_2d_reduction_direct_warpwise.hpp
  src/composable_kernel/composable_kernel/include/tensor_operation/reduction_functions_warpwise.hpp
  src/composable_kernel/composable_kernel/src/kernel_wrapper/gridwise_generic_reduction_first_call_warpwise_reduce_all_dims.cpp
  src/composable_kernel/composable_kernel/src/kernel_wrapper/gridwise_generic_reduction_first_call_warpwise_reduce_partial_dims.cpp
  src/composable_kernel/composable_kernel/src/kernel_wrapper/gridwise_generic_reduction_second_call_warpwise_reduce_all_dims.cpp
  src/composable_kernel/composable_kernel/src/kernel_wrapper/gridwise_generic_reduction_second_call_warpwise_reduce_partial_dims.cpp
  src/kernels/workaround_issue_1431.hpp
  src/reducetensor.cpp
  test/CMakeLists.txt
Labels: help wanted, value_high, urgency_blocker

#1504 [CI] Update to ROCm 5.1 in dockerfile and remove miopentensile stage
  CMakeLists.txt
  Dockerfile
  Jenkinsfile
  cmake/EnableCompilerWarnings.cmake
  cmake/FindOpenCL.cmake
  cmake/embed.cmake
  fin/cmake/EnableCompilerWarnings.cmake
  include/miopen/miopen.h
  src/composable_kernel/cmake/EnableCompilerWarnings.cmake
  src/include/miopen/handle_lock.hpp
  src/include/miopen/solver/implicitgemm_util.hpp
  src/include/miopen/utility/transposing_solver.hpp
  src/ocl/handleocl.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v1r1_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v4r1.cpp
  src/solver/gemm_wrw.cpp
  test/CMakeLists.txt
  test/ford.hpp
  test/rnn_vanilla_common.hpp
Labels: help wanted, value_high, urgency_high, TESTING_CI_PASSED

#1520 [kernel references List]Development kernel and kernel include batches
  src/CMakeLists.txt
Labels: enhancement, complexity_low, urgency_high, TESTING_CI_PASSED, debugging

#1518 Make int8 convolution default output type to be int32
  driver/conv_driver.hpp
  driver/main.cpp
Labels: complexity_low, TESTING_CI_PASSED, correctness
