Repository ROCm/MIOpen, pull requests merged in 2022-05, with the labels that each got.

#1525 [ROCm-cmake] Enable Origin header file dump option for wrapper
  dev-requirements.txt
  requirements.txt
  src/CMakeLists.txt
Labels: urgency_high, TESTING_CI_PASSED

#1531 Unofficially support gfx1031.
  src/composable_kernel/composable_kernel/include/utility/config.hpp
  src/include/miopen/solver/ck_utility_common.hpp
  src/include/miopen/solver/implicitgemm_util.hpp
  src/kernels/MIOpenBatchNormActivBwdPerAct.cl
  src/kernels/MIOpenBatchNormActivBwdSpatial.cl
  src/kernels/MIOpenBatchNormActivFwdTrainSpatial.cl
  src/kernels/MIOpenBatchNormBwdSpatial.cl
  src/kernels/MIOpenBatchNormFwdTrainSpatial.cl
  src/kernels/batchnorm_functions.h
  src/md_graph.cpp
  src/ocl/fusionopbiasbnactivocl.cpp
  src/solver/batchnorm/backward_per_activation.cpp
  src/solver/batchnorm/backward_spatial_multiple.cpp
  src/solver/batchnorm/backward_spatial_single.cpp
  src/solver/batchnorm/forward_inference.cpp
  src/solver/batchnorm/forward_per_activation.cpp
  src/solver/batchnorm/forward_spatial_multiple.cpp
  src/solver/batchnorm/forward_spatial_single.cpp
  test/CMakeLists.txt
  test/handle_test.cpp
  test/mdgraph.cpp
Labels: enhancement, value_high, urgency_normal, TESTING_CI_PASSED

#1433 [Solvers] Base class for tunable solvers
  src/include/miopen/any_solver.hpp
  src/include/miopen/find_solution.hpp
  src/include/miopen/generic_search.hpp
  src/include/miopen/solver.hpp
  src/solver/conv_MP_bidirectional_winograd.cpp
  src/solver/conv_asm_1x1u.cpp
  src/solver/conv_asm_1x1u_bias_activ.cpp
  src/solver/conv_asm_1x1u_stride2.cpp
  src/solver/conv_asm_3x3u.cpp
  src/solver/conv_asm_dir_BwdWrW1x1.cpp
  src/solver/conv_asm_dir_BwdWrW3x3.cpp
  src/solver/conv_asm_implicit_gemm_gtc_bwd_nhwc.cpp
  src/solver/conv_asm_implicit_gemm_gtc_fwd_nhwc.cpp
  src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp
  src/solver/conv_ck_igemm_fwd_v6r1_dlops_nchw.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v1r1.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v1r1_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v4r1.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v4r1_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r1.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops_padded_gemm.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r5_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops_padded_gemm.cpp
  src/solver/conv_mlir_igemm_bwd.cpp
  src/solver/conv_mlir_igemm_bwd_xdlops.cpp
  src/solver/conv_mlir_igemm_fwd.cpp
  src/solver/conv_mlir_igemm_fwd_xdlops.cpp
  src/solver/conv_mlir_igemm_wrw.cpp
  src/solver/conv_mlir_igemm_wrw_xdlops.cpp
  src/solver/conv_ocl_dir2D_bwdWrW_2.cpp
  src/solver/conv_ocl_dir2Dfwd.cpp
  src/solver/conv_ocl_dir2Dfwd_exhaustive_search.cpp
  src/solver/conv_winoRxS_f2x3.cpp
  src/solver/conv_winoRxS_f3x2.cpp
  test/solver.cpp
Labels: enhancement, quality, urgency_high, TESTING_CI_PASSED

#1296 [API change] Pooling backward solvers (except GetWorkspaceSize)
  driver/mloConvHost.hpp
  driver/mloPoolingHost.hpp
  driver/pool_driver.hpp
  include/miopen/miopen.h
  src/CMakeLists.txt
  src/include/miopen/conv/problem_description.hpp
  src/include/miopen/mlo_internal.hpp
  src/include/miopen/pooling.hpp
  src/include/miopen/pooling/invoke_params.hpp
  src/include/miopen/pooling/solvers.hpp
  src/include/miopen/tensor.hpp
  src/ocl/mloPooling.cpp
  src/ocl/pooling_ocl.cpp
  src/pooling_api.cpp
  src/solver.cpp
  src/solver/pooling/backward2d.cpp
  src/solver/pooling/backwardNd.cpp
Labels: enhancement, complexity_middle, urgency_normal, TESTING_CI_PASSED, IMPACTS_API

#1539 [MLIR] Adding int8 support and test to ConvMlirIgemmFwdXdlops solver
  requirements.txt
  src/conv/invokers/mlir_impl_gemm.cpp
  src/include/miopen/conv/problem_description.hpp
  src/include/miopen/problem_description.hpp
  src/mlo_dir_conv.cpp
  src/ocl/convolutionocl.cpp
  src/solver/mlir_common.cpp
  test/CMakeLists.txt
  test/conv_common.hpp
Labels: value_high, complexity_middle, urgency_high, TESTING_CI_PASSED

#1544 GPU reference convolution kernel refactor and int8 support
  driver/conv_driver.hpp
  src/include/miopen/conv/problem_description.hpp
  src/include/miopen/solver/conv_direct_naive_conv.hpp
  src/kernels/gpu_reference_kernel/naive_conv.cpp
  src/kernels/gpu_reference_kernel/naive_conv_gcn.s
  src/ocl/convolutionocl.cpp
  src/solver/conv_direct_naive_conv.cpp
  src/solver/conv_direct_naive_conv_bwd.cpp
  src/solver/conv_direct_naive_conv_fwd.cpp
  src/solver/conv_direct_naive_conv_wrw.cpp
  test/cpu_conv.hpp
  test/gpu_reference_kernel.cpp
Labels: TESTING_CI_PASSED

#1543 [Boost][JP-Ellis&Artem] Update Boost version to 1.79
  include/miopen/config.h.in
  requirements.txt
  src/exec_utils.cpp
  src/execution_context.cpp
  src/gemm_v2.cpp
  src/hip/handlehip.cpp
  src/hip/hip_build_utils.cpp
  src/hipoc/hipoc_program.cpp
  src/include/miopen/find_db.hpp
  src/include/miopen/handle.hpp
  src/include/miopen/mdg_expr.hpp
  src/include/miopen/mlo_internal.hpp
  src/include/miopen/op_kernel_args.hpp
  src/mlo_dir_conv.cpp
  src/ocl/convolutionocl.cpp
  src/ocl/fusionopbiasbnactivocl.cpp
  src/pooling.cpp
  src/readonlyramdb.cpp
  src/softmax_api.cpp
  src/solver/conv_bin_winoRxS.cpp
  src/solver/conv_ocl_dir2D11x11.cpp
Labels: value_middle, urgency_high, TESTING_CI_PASSED

#1545 Enable hipRTC as default
  CMakeLists.txt
Labels: value_high, urgency_normal, TESTING_CI_PASSED

#1553 [SWDEV-337356] Workaround for Kernel Online Compilation Warning
  src/kernel_warnings.cpp
Labels: TESTING_CI_PASSED

#1556 [HotFix] Resolve int8_t type with hipRTC workaround
  src/kernels/gpu_reference_kernel/naive_conv.cpp
Labels: urgency_blocker, complexity_low, workaround, TESTING_CI_PASSED

#1533 [enhancement] ConvBinWinogradRxSf2x3 / f3x2 solvers merge
  src/CMakeLists.txt
  src/include/miopen/solver.hpp
  src/mlo_dir_conv.cpp
  src/solver.cpp
  src/solver/conv_winoRxS.cpp
Labels: complexity_middle, urgency_normal, TESTING_CI_PASSED

#1532 [API] NCHWc tensor layout support
  driver/conv_driver.hpp
  driver/driver.hpp
  driver/tensor_driver.hpp
  include/miopen/miopen.h
  src/conv/problem_description.cpp
  src/convolution.cpp
  src/gemm_v2.cpp
  src/include/miopen/conv/problem_description.hpp
  src/include/miopen/datatype.hpp
  src/include/miopen/magic_div.hpp
  src/include/miopen/problem_description.hpp
  src/include/miopen/tensor.hpp
  src/include/miopen/tensor_extra.hpp
  src/include/miopen/tensor_layout.hpp
  src/ocl/convolutionocl.cpp
  src/problem_description.cpp
  src/tensor.cpp
  src/tensor_api.cpp
  test/CMakeLists.txt
  test/conv2d.cpp
  test/conv_common.hpp
  test/cpu_conv.hpp
  test/tensor_holder.hpp
  test/tensor_test.cpp
Labels: value_high, complexity_low, urgency_high, TESTING_CI_PASSED, IMPACTS_API

#1561 [#1537][#1557] Explicitly require MIOpenGEMM for OpenCL and Fix tensor_ops.cpp debug issue
  CMakeLists.txt
  README.md
  test/tensor_ops.cpp
Labels: value_middle, complexity_low, urgency_normal

#1552 [SWDEV-334271] Palamida scan remediation
  LICENSE.txt
  fin/LICENSE
Labels: complexity_low, urgency_normal, TESTING_CI_PASSED, documentation
