Repository ROCm/MIOpen, pull requests merged in 2022-09, with the labels that each got.

#1692 Composable kernels integration & Small Fix in GEMM Solver
  CMakeLists.txt
  Dockerfile
  Jenkinsfile
  include/miopen/config.h.in
  src/CMakeLists.txt
  src/convolution.cpp
  src/include/miopen/solver.hpp
  src/mlo_dir_conv.cpp
  src/ocl/convolutionocl.cpp
  src/solver.cpp
  src/solver/conv_hip_implicit_gemm_fwd_xdlops.cpp
  src/solver/gemm.cpp
  test/CMakeLists.txt
  test/conv2d.cpp
  test/conv_common.hpp
  test/tensor_cast.cpp
  test/tensor_holder.hpp
Labels: urgency_blocker, TESTING_CI_PASSED

#1728 [NFC] Fix file encoding (UTF-8 -> ANSI)
  src/ocl/handleocl.cpp
Labels: urgency_high, TESTING_CI_PASSED

#1724 Added support for reading and dumping buffers in pooling driver.
  driver/pool_driver.hpp
Labels: TESTING_CI_PASSED

#1734 [HotFix] Fix build issues with #1732 and #1733
  src/kernels/MIOpenPoolingBwd.cl
  src/solver/conv_hip_implicit_gemm_fwd_xdlops.cpp
Labels: bug, urgency_blocker, TESTING_CI_PASSED

#1729 [tests] Fix for DEV builds. Fix testing on 16GB GPUs.
  src/hip/handlehip.cpp
  src/hip/hiperrors.cpp
  test/handle_test.cpp
Labels: urgency_high

#1723 Fixed pooling 3d validation
  driver/mloConvHost.hpp
  driver/mloPoolingHost.hpp
Labels: TESTING_CI_PASSED

#1663 PerfDB entry fallback
  src/include/miopen/any_solver.hpp
  src/include/miopen/find_solution.hpp
  src/include/miopen/solver.hpp
Labels: urgency_high, TESTING_CI_PASSED

#1736 [HotFix] Post merge fix for ConvolutionContext/Problem Split
  src/include/miopen/any_solver.hpp
  src/include/miopen/find_solution.hpp
Labels: urgency_blocker, complexity_low

#1714 [CI] Update dockerfile ROCm version and bump MIOpen version
  CMakeLists.txt
  Dockerfile
  Jenkinsfile
  README.md
  src/include/miopen/oclkernel.hpp
Labels: complexity_low, urgency_high, TESTING_CI_PASSED

#1735 [Proactive][Fix][Performance] Winograd applicability for WrW direction
  src/solver/conv_winoRxS.cpp
Labels: performance, urgency_high

#1730 [NFC] Removed miopen::ConvolutionUserBuffers
  fin/src/include/conv_fin.hpp
  src/include/miopen/conv/context.hpp
  src/include/miopen/convolution.hpp
  src/include/miopen/mlo_internal.hpp
  src/include/miopen/solver.hpp
  src/ocl/convolutionocl.cpp
  src/solver/conv_ocl_dir2Dfwd_exhaustive_search.cpp
Labels: value_high, urgency_normal, TESTING_CI_PASSED

#1645 Deprecate `clang-ocl` and replace with `clang`
  CMakeLists.txt
  README.md
  src/hipoc/hipoc_program.cpp
Labels: value_high, IMPACTS_FIND_DB, complexity_middle, TESTING_CI_PASSED

#1744 [CI] fix dockerfile for Ubuntu 20.04 support
  Dockerfile
  src/comgr.cpp
  test/CMakeLists.txt
Labels: value_middle, urgency_blocker, workaround, TESTING_CI_PASSED

#1701 [Solvers] ConvAsm5x10u2v2f1: split ConvolutionContext and ProblemDescription (stage 2)
  src/include/miopen/solver.hpp
  src/solver/conv_asm_5x10u2v2f1.cpp
Labels: enhancement, quality, TESTING_CI_PASSED

#1708 [Solvers] ConvAsm5x10u2v2b1: split ConvolutionContext and ProblemDescription (stage 2)
  src/include/miopen/solver.hpp
  src/solver/conv_asm_5x10u2v2b1.cpp
Labels: enhancement, quality, TESTING_CI_PASSED

#1710 [Solvers] ConvAsm7x7c3h224w224k64u2v2p3q3f1: split ConvolutionContext and ProblemDescription (stage 2)
  src/include/miopen/solver.hpp
  src/solver/conv_asm_7x7c3h224w224k64u2v2p3q3f1.cpp
Labels: enhancement, quality, TESTING_CI_PASSED

#1711 [Solvers] ConvOclDirectFwd11x11: split ConvolutionContext and ProblemDescription (stage 2)
  src/include/miopen/solver.hpp
  src/solver/conv_ocl_dir2D11x11.cpp
Labels: enhancement, quality, TESTING_CI_PASSED

#1712 [Solvers] ConvOclDirectFwdGen: split ConvolutionContext and ProblemDescription (stage 2)
  src/include/miopen/solver.hpp
  src/solver/conv_ocl_dir2Dfwdgen.cpp
Labels: enhancement, quality, TESTING_CI_PASSED

#1737 [CK] Fix Composable Kernel dependency building and Enable by default
  CMakeLists.txt
  Dockerfile
  Jenkinsfile
  requirements.txt
  src/include/miopen/any_solver.hpp
Labels: urgency_high, TESTING_CI_PASSED

#1741 [Solvers] ConvAsmImplicitGemmV4R1DynamicFwd: split ConvolutionContext and ProblemDescription (stage 2)
  src/conv/invokers/impl_gemm_dynamic.cpp
  src/include/miopen/conv/invokers/impl_gemm_dynamic.hpp
  src/include/miopen/solver.hpp
  src/include/miopen/solver/implicitgemm_util.hpp
  src/solver/conv_asm_implicit_gemm_gtc_fwd.cpp
  src/solver/conv_asm_implicit_gemm_v4r1_dynamic.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v1r1.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r1.cpp
  src/solver/conv_hip_implicit_gemm_nonxdlops_common.cpp
  src/solver/conv_hip_implicit_gemm_xdlops_common.cpp
Labels: enhancement, quality, TESTING_CI_PASSED

#1754 [Solvers] ConvAsmImplicitGemmV4R1DynamicBwd, ConvAsmImplicitGemmGTCDynamicBwdXdlops: split ConvolutionContext and ProblemDescription (stage 2)
  src/conv/invokers/impl_gemm_dynamic.cpp
  src/include/miopen/conv/invokers/impl_gemm_dynamic.hpp
  src/include/miopen/solver.hpp
  src/solver/conv_asm_implicit_gemm_bwd_v4r1_dynamic.cpp
  src/solver/conv_asm_implicit_gemm_gtc_bwd.cpp
Labels: enhancement, quality, TESTING_CI_PASSED

#1751 [Solvers] ConvAsmImplicitGemmGTCDynamicWrwXdlops: split ConvolutionContext and ProblemDescription (stage 2)
  src/include/miopen/solver.hpp
  src/solver/conv_asm_implicit_gemm_wrw_gtc_dynamic_xdlops.cpp
Labels: enhancement, quality, TESTING_CI_PASSED

#1774 [HotFix][ROCm5.3.0] Patch MIOpen dependency on MLIR for sha256 verification
  requirements.txt
Labels: non-miopen-bug, workaround, urgency_high

#1772 [Solvers] ConvDirectNaiveConv solvers: split ConvolutionContext and ProblemDescription (stage 2)
  src/include/miopen/solver.hpp
  src/include/miopen/solver/conv_direct_naive_conv.hpp
  src/solver/conv_direct_naive_conv.cpp
  src/solver/conv_direct_naive_conv_bwd.cpp
  src/solver/conv_direct_naive_conv_fwd.cpp
  src/solver/conv_direct_naive_conv_wrw.cpp
Labels: enhancement, quality, TESTING_CI_PASSED

#1762 [Solvers] ConvBinWinograd3x3U, ConvBinWinogradRxS, ConvBinWinogradRxSFused: split ConvolutionContext and ProblemDescription (stage 2)
  src/include/miopen/conv/compiled_in_parameters.hpp
  src/include/miopen/solver.hpp
  src/solver/conv_asm_1x1u.cpp
  src/solver/conv_asm_1x1u_stride2.cpp
  src/solver/conv_asm_dir_BwdWrW1x1.cpp
  src/solver/conv_asm_dir_BwdWrW3x3.cpp
  src/solver/conv_bin_wino3x3U.cpp
  src/solver/conv_bin_winoRxS.cpp
  src/solver/conv_multipass_wino3x3WrW.cpp
  src/solver/conv_winoRxS.cpp
Labels: enhancement, urgency_blocker, quality, TESTING_CI_PASSED

#1758 [Solvers] Replace ConvolutionContextInterpreter with ProblemInterpreter
  src/include/miopen/solver/ck_utility_common.hpp
  src/include/miopen/solver/convolution_context_interpreter.hpp
  src/include/miopen/solver/implicitgemm_util.hpp
  src/include/miopen/solver/problem_description_interpreter.hpp
  src/solver/conv_asm_implicit_gemm_bwd_v4r1_dynamic.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v1r1.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v1r1_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v4r1.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v4r1_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops_padded_gemm.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r5_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_fwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops_padded_gemm.cpp
  src/solver/conv_hip_implicit_gemm_xdlops_common.cpp
  src/solver/mlir_common.cpp
Labels: enhancement, urgency_blocker, quality, TESTING_CI_PASSED

#1688 Default config from GetPerfCfgParams
  src/include/miopen/any_solver.hpp
Labels: urgency_normal

#1773 [Solvers] ConvAsmImplicitGemmGTCDynamicFwdXdlops: split ConvolutionContext and ProblemDescription (stage 2)
  src/include/miopen/solver.hpp
  src/solver/conv_asm_implicit_gemm_gtc_fwd.cpp
Labels: enhancement, quality, TESTING_CI_PASSED

#1768 [Solvers] FFT: split ConvolutionContext and ProblemDescription (stage 2)
  src/include/miopen/solver.hpp
  src/solver/fft.cpp
Labels: enhancement, quality, TESTING_CI_PASSED

#1767 [Solvers] ConvOclBwdWrW1x1: split ConvolutionContext and ProblemDescription (stage 2)
  src/include/miopen/solver.hpp
  src/solver/conv_ocl_dir2D_bwdWrW_1x1.cpp
Labels: enhancement, quality, TESTING_CI_PASSED

#1763 [Solvers] ConvOclBwdWrW53: split ConvolutionContext and ProblemDescription (stage 2)
  src/include/miopen/solver.hpp
  src/solver/conv_ocl_dir2D_bwdWrW_53.cpp
Labels: enhancement, quality, TESTING_CI_PASSED

#1749 [API] Dedicated API for Conv+Bias+Activ Fusion
  include/miopen/miopen.h
  src/fused_api.cpp
  src/fusion.cpp
  src/include/miopen/fusion.hpp
  test/cba_inference.cpp
  test/cbna_inference.cpp
  test/driver.hpp
  test/fusionHost.hpp
  test/gtest/CMakeLists.txt
  test/gtest/api_convbiasactiv.cpp
  test/na_inference.cpp
  test/na_train.cpp
  test/tensor_holder.hpp
Labels: value_high, urgency_blocker, complexity_middle, TESTING_CI_PASSED

#1759 [HotFix] Fix MIOpen dependencies build issues and sync CK version
  install_deps.cmake
  rbuild.ini
  requirements.txt
Labels: value_middle, urgency_blocker, workaround, TESTING_CI_PASSED

#1778 Fix for GetPerfCfgParams call
  src/include/miopen/any_solver.hpp
Labels: tuning, urgency_high

#1785 handle.hpp: fix include guard name
  src/include/miopen/handle.hpp
Labels: TESTING_CI_PASSED, correctness

#1789 [SWDEV-358495] Exclude GTest from install
  test/CMakeLists.txt
  test/gtest/hello_gtest.cpp
Labels: urgency_high, TESTING_CI_PASSED

#1755 [bg/LWPTUNA-63] : Log MIOpenDriver commands when Find is called
  src/convolution_api.cpp
  test/gtest/CMakeLists.txt
  test/gtest/log_test.cpp
  test/gtest/log_test_helper.cpp
  test/gtest/log_test_helper.hpp
  test/gtest/log_test_neg.cpp
Labels: urgency_high, TESTING_CI_PASSED, debugging

#1792 [Solvers] ConvWinograd3x3MultipassWrW: fix implicit conversion
  src/include/miopen/conv/context.hpp
  src/include/miopen/solver.hpp
  src/solver/conv_multipass_wino3x3WrW.cpp
Labels: performance, urgency_high, TESTING_CI_PASSED

#1761 Make c++17 standard, update MIOpen for the new CK API
  CMakeLists.txt
  cmake/EnableCompilerWarnings.cmake
  cmake/googletest.cmake
  requirements.txt
  src/CMakeLists.txt
  src/include/miopen/sequences.hpp
  src/mlo_dir_conv.cpp
  src/solver/conv_hip_implicit_gemm_fwd_xdlops.cpp
  test/cpu_reduce_util.hpp
  test/reduce_test.cpp
  test/tensor_reorder.cpp
Labels: urgency_blocker, TESTING_CI_PASSED

#1673 [mlir] Use find_package() to locate MLIR static library
  CMakeLists.txt
  Jenkinsfile
  requirements.txt
  src/CMakeLists.txt
Labels: urgency_blocker, complexity_low, tuning, TESTING_CI_PASSED
