Repository ROCm/MIOpen, pull requests merged in 2022-08, with the labels that each got.

#1524 Composable Kernel Integration
  CMakeLists.txt
  Dockerfile
  Jenkinsfile
  include/miopen/config.h.in
  src/CMakeLists.txt
  src/convolution.cpp
  src/include/miopen/solver.hpp
  src/mlo_dir_conv.cpp
  src/solver/conv_hip_implicit_gemm_fwd_xdlops.cpp
  src/solver/conv_mlir_igemm_fwd_xdlops.cpp
  src/solver/gemm.cpp
  test/CMakeLists.txt
  test/conv2d.cpp
  test/conv_common.hpp
  test/tensor_cast.cpp
Labels: value_high, IMPACTS_PERFORMANCE_DB, IMPACTS_FIND_DB, urgency_blocker, complexity_middle, TESTING_CI_PASSED

#1664 Add OpenCL deprecation Message
  src/ocl/handleocl.cpp
Labels: urgency_blocker

#1655 [Enhancement] Tensor op changes when beta is zero
  src/kernels/MIOpenTensorKernels.cl
Labels: enhancement, urgency_normal, TESTING_CI_PASSED

#1671 [tests][pooling][2d] Added asymmetric tests (regression test for #1642) and W/A for #1670. [tests][general] Added support for multiple datasets.
  test/CMakeLists.txt
  test/driver.hpp
  test/pooling2d.cpp
  test/pooling_common.hpp
Labels: value_high, urgency_high, TESTING_CI_PASSED

#1649 [Tests][Enhancement] Fix pooling command printing
  src/pooling_api.cpp
Labels: value_high, urgency_high

#1679 [TensorDescriptor][BugFix] Change vectorLength datatype to std::size_t
  driver/tensor_driver.hpp
  src/include/miopen/tensor.hpp
  src/include/miopen/tensor_extra.hpp
  src/tensor.cpp
  src/tensor_api.cpp
  test/CMakeLists.txt
Labels: bug, urgency_blocker

#1677 [Enhancement][Tests] GPU based verification for convolutions
  src/include/miopen/convolution.hpp
  src/ocl/convolutionocl.cpp
  test/conv_common.hpp
  test/gpu_conv.hpp
Labels: enhancement, value_high, urgency_high, TESTING_CI_PASSED

#1689 [Documentation] Add a section about Git LFS in readme
  README.md
Labels: urgency_normal, documentation

#1693 [CI] Make OpenCL stages optional and add retry
  Jenkinsfile
  test/CMakeLists.txt
Labels: value_high, urgency_blocker

#1682 [WORKAROUND][HOTFIX] W/A for #1681, "Performance drops after PR #1634"
  src/solver/conv_winoRxS.cpp
Labels: bug, performance, urgency_blocker, workaround

#1695 [Solvers] Remove unused performance configs
  src/include/miopen/solver.hpp
Labels: enhancement, quality, urgency_normal, TESTING_CI_PASSED

#1683 [FP32] [miopengemm][Workaround] Disabled GemmBwd1x1_stride1
  src/include/miopen/solver.hpp
  src/solver/gemm_bwd.cpp
Labels: urgency_blocker, TESTING_CI_PASSED

#1696 [CI] Remove multiple install prefixes
  Jenkinsfile
Labels: value_high, urgency_high, TESTING_CI_PASSED

#1630 [MLIR] Switch the ABI to use bare pointers and not memrefs
  src/conv/invokers/mlir_impl_gemm.cpp
Labels: tuning, TESTING_CI_PASSED

#1611 Sl/google test
  CMakeLists.txt
  Dockerfile
  cmake/googletest.cmake
  test/CMakeLists.txt
  test/gtest/CMakeLists.txt
  test/gtest/hello_test.cpp
Labels: enhancement, value_high, urgency_high, TESTING_CI_PASSED
