Repository ROCm/MIOpen, pull requests merged in 2022-12, with the labels that each got.

#1876 [Find-2.0] Serialize kernel perf configs
  fin/CMakeLists.txt
  fin/src/include/conv_fin.hpp
  src/include/miopen/any_solver.hpp
  src/include/miopen/find_solution.hpp
  src/include/miopen/solution.hpp
  src/problem.cpp
  src/solution.cpp
Labels: value_high, urgency_blocker, TESTING_CI_PASSED

#1900 [SWDEV-358170][Workaround] Specify -std=c++14 so boost builds using latest Clang and devtoolset-7
  requirements.txt
Labels: non-miopen-bug, urgency_blocker, workaround

#1825 [MLIR]Reuse one tuning parameters
  src/solver/conv_mlir_igemm_fwd_xdlops.cpp
Labels: performance, IMPACTS_PERFORMANCE_DB, urgency_blocker

#1897 [mlir] Enable gfx103x for mlir non-xdlops tests
  requirements.txt
  test/CMakeLists.txt
Labels: IMPACTS_PERFORMANCE_DB, urgency_blocker
