Repository ROCm/MIOpen, pull requests merged in 2022-07, with the labels that each got.

#1551 [API] Add the deterministic attribute to the convolution descriptor
  include/miopen/miopen.h
  src/convolution.cpp
  src/gemm_v2.cpp
  src/include/miopen/convolution.hpp
  src/include/miopen/gemm_v2.hpp
  src/ocl/rnnocl.cpp
  src/solver/conv_MP_bidirectional_winograd.cpp
  src/solver/conv_asm_implicit_gemm_gtc_bwd_nhwc.cpp
  src/solver/conv_asm_implicit_gemm_gtc_fwd_nhwc.cpp
  src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp
  src/solver/conv_asm_implicit_gemm_wrw_gtc_dynamic_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v1r1.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v1r1_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v4r1.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v4r1_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r1.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops_padded_gemm.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r5_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops_padded_gemm.cpp
  src/solver/conv_mlir_igemm_bwd.cpp
  src/solver/conv_mlir_igemm_bwd_xdlops.cpp
  src/solver/conv_mlir_igemm_fwd.cpp
  src/solver/conv_mlir_igemm_fwd_xdlops.cpp
  src/solver/conv_mlir_igemm_wrw.cpp
  src/solver/conv_mlir_igemm_wrw_xdlops.cpp
  src/solver/conv_multipass_wino3x3WrW.cpp
  src/solver/gemm.cpp
  src/solver/gemm_bwd.cpp
  src/solver/gemm_wrw.cpp
  test/conv2d.cpp
  test/conv_common.hpp
  test/deterministic_conv_api.cpp
Labels: urgency_high, TESTING_CI_PASSED

#1627 SWDEV-303880 : updated copyright notice in miopen documentation
  doc/src/conf.py
Labels: documentation

#1614 [MLIR] Bumping release tag to rocm-5.3.0
  requirements.txt
Labels: TESTING_CI_PASSED

#1605 [MLIR] Enable nonxdlops conv fwd tests for int8
  test/CMakeLists.txt
Labels: enhancement, complexity_low, TESTING_CI_PASSED

#1639 [HOTFIX] disable ctest for ConvAsmImplicitGemmGTCDynamicFwdXdlops
  test/CMakeLists.txt
Labels: urgency_blocker

#1637 [NFC][SWDEV-257567] Update distribution list maintainer/contact
  CMakeLists.txt
Labels: value_low, urgency_normal

#1618 [SWDEV-330460] Improve workaround for ConvAsmBwdWrw3x3
  src/solver/conv_asm_dir_BwdWrW3x3.cpp
Labels: value_high, urgency_high, TESTING_CI_PASSED

#1646 [tests][Navi21] Disable WORKAROUND_ISSUE_1053 as issue is not reproducible.
  test/CMakeLists.txt
Labels: enhancement

#1594 [Enhancement] Fix potential issues in MT environments. Resolve warning and code clean ups.
  src/find_db.cpp
  src/include/miopen/find_db.hpp
  src/include/miopen/md_graph.hpp
  src/include/miopen/mlo_internal.hpp
  src/include/miopen/mlo_utils.hpp
  src/include/miopen/type_name.hpp
  src/md_graph.cpp
  src/mlo_dir_conv.cpp
  src/ocl/mloNeuron.cpp
  src/ocl/mloNorm.cpp
  src/readonlyramdb.cpp
  src/solver/conv_ocl_dir2D_bwdWrW_2.cpp
  src/solver/conv_ocl_dir2Dfwd_exhaustive_search.cpp
  src/target_properties.cpp
  test/conv_common.hpp
  test/find_db.cpp
  test/get_handle.hpp
  test/gpu_reference_kernel.cpp
  test/solver.cpp
Labels: enhancement, value_high, urgency_normal, TESTING_CI_PASSED

#1597 [Solvers] Base class for performance configs
  src/CMakeLists.txt
  src/include/miopen/any_solver.hpp
  src/include/miopen/legacy_exhaustive_search.hpp
  src/include/miopen/performance_config.hpp
  src/include/miopen/serializable.hpp
  src/include/miopen/solver.hpp
  src/performance_config.cpp
  src/solver/conv_asm_1x1u.cpp
  src/solver/conv_asm_1x1u_stride2.cpp
  src/solver/conv_asm_3x3u.cpp
  src/solver/conv_asm_dir_BwdWrW1x1.cpp
  src/solver/conv_asm_dir_BwdWrW3x3.cpp
  src/solver/conv_asm_implicit_gemm_gtc_perf_config.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v1r1.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v1r1_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v4r1.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v4r1_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops_padded_gemm.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r5_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_nonxdlops_common.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops_padded_gemm.cpp
  src/solver/conv_hip_implicit_gemm_xdlops_common.cpp
  src/solver/conv_mlir_igemm_fwd.cpp
  src/solver/conv_mlir_igemm_fwd_xdlops.cpp
  src/solver/conv_ocl_dir2D_bwdWrW_2.cpp
  src/solver/conv_winoRxS.cpp
  test/solver.cpp
Labels: enhancement, quality, urgency_normal, TESTING_CI_PASSED

#1650 [WORKAROUND] [hipRTC] Warning issues with hipRTC_header.h
  src/comgr.cpp
Labels: value_high, urgency_blocker, TESTING_CI_PASSED

#1644 [BugFix] MIOpenIm2d2Col.cl kernel: fix address calculation
  src/kernels/MIOpenIm2d2Col.cl
  src/ocl/utilocl.cpp
Labels: bug, urgency_high, TESTING_CI_PASSED

#1659 [SWDEV-345750] Fix Tensorflow pooling test failure
  src/solver/pooling/backward2d.cpp
Labels: bug, urgency_blocker

#1657 [Hotfix] Issue 1653, Inappropriate Host API usage
  driver/conv_driver.hpp
Labels: bug, urgency_high

#1643 [tests][Navi21][BN] Leftover of #1386 - add regression tests
  test/CMakeLists.txt
Labels: value_high, testing, urgency_normal, TESTING_CI_PASSED

#1633 [SWDEV-303880] relocate and add MIOpen Porting Guide
  README.md
  doc/src/MIOpen_Porting_Guide.md
Labels: documentation
