Repository ROCm/MIOpen, pull requests merged in 2022-03, with the labels that each got.

#1446 [API] Implement miopenSet4dTensorDescriptorEx for cuDNN parity
  include/miopen/miopen.h
  src/tensor_api.cpp
  test/tensor_api.cpp
Labels: enhancement, value_middle, complexity_low, urgency_normal, TESTING_CI_PASSED, IMPACTS_API

#1453 [HOTFIX] fix miopen.h clang-format-10
  include/miopen/miopen.h
Labels: urgency_blocker

#1443 [MLIR] Add workspace to MLIR wrw solver in case needed.
  requirements.txt
  src/conv/invokers/mlir_impl_gemm.cpp
  src/include/miopen/conv/invokers/mlir_impl_gemm.hpp
  src/include/miopen/mlir_build.hpp
  src/include/miopen/solver.hpp
  src/mlir_build.cpp
  src/solver/conv_mlir_igemm_wrw.cpp
  src/solver/conv_mlir_igemm_wrw_xdlops.cpp
  test/CMakeLists.txt
Labels: value_high, urgency_high, TESTING_CI_PASSED

#1457 [issue 1458]reduce multi-buffer size
  src/buffer_info.cpp
Labels: urgency_normal, TESTING_CI_PASSED

#1448 Eliminate dependency to SetTensor/CastTensor in MLIR XDLOPS wrw solver.
  requirements.txt
  src/conv/invokers/mlir_impl_gemm.cpp
  src/solver/conv_mlir_igemm_wrw_xdlops.cpp
Labels: value_middle, urgency_high, TESTING_CI_PASSED

#1454 File/Folder Reorg Changes
  CMakeLists.txt
  dev-requirements.txt
  driver/CMakeLists.txt
  requirements.txt
  src/CMakeLists.txt
  utils/CMakeLists.txt
Labels: urgency_normal

#1419 [Tensor reorder] Universal tensor transform feature, a fallback of batched transpose kernel
  src/CMakeLists.txt
  src/hip/general_tensor_reorder_sol.cpp
  src/include/miopen/general_tensor_reorder_sol.hpp
  src/include/miopen/tensor_reorder_util.hpp
  src/kernels/gpu_general_tensor_reorder_kernel/general_tensor_reorder.cpp
  src/kernels/gpu_general_tensor_reorder_kernel/order.hpp
  test/tensor_reorder.cpp
Labels: urgency_normal, TESTING_CI_PASSED

#1465 [gfx1030][CI] enforce test_conv_ck_igemm_fwd_v6r1_dlops_nchw run serial
  test/CMakeLists.txt
Labels: workaround, urgency_high, TESTING_CI_PASSED, value_unknown

#1450 [MLIR] Remove dependency to SetZero in MLIR bwd invoker.
  requirements.txt
  src/conv/invokers/mlir_impl_gemm.cpp
Labels: value_middle, urgency_blocker, TESTING_CI_PASSED

#1475 [BN] Fixed numeric checks for valid nullptr buffers
  src/ocl/batchnormocl.cpp
Labels: bug, urgency_high, debugging
