Repository ROCm/MIOpen, pull requests merged in 2022-01, with the labels that each got.

#1364 Bump up MIOpen version to 2.16 (after cutting rocm-rel-5.0)
  CMakeLists.txt
Labels: urgency_high

#1350 [Quality][tidy] Add missing headers to MIOpen_source
  src/CMakeLists.txt
Labels: quality

#1282 [driver] jira_1235_string case insensitive
  driver/InputFlags.cpp
  driver/InputFlags.hpp
  driver/conv_driver.hpp
Labels: enhancement, TESTING_CI_PASSED, value_unknown, correctness

#1369 [Tidy][Quality] MIOpen_Source to exclude header files
  src/CMakeLists.txt
Labels: value_low, complexity_low, urgency_low, TESTING_CI_PASSED

#1370 [HOTFIX][WORKAROUND] Resolve SWDEV-317745
  src/hip/hip_build_utils.cpp
Labels: non-miopen-bug, urgency_blocker, workaround, TESTING_CI_PASSED

#1363 [solvers] Move SolverDbId() into solvers
  src/include/miopen/activ/solvers.hpp
  src/include/miopen/any_solver.hpp
  src/include/miopen/batchnorm/solvers.hpp
  src/include/miopen/find_solution.hpp
  src/include/miopen/generic_search.hpp
  src/include/miopen/pooling/solvers.hpp
  src/include/miopen/solver.hpp
  src/mlo_dir_conv.cpp
  src/solver.cpp
  src/solver/conv_asm_implicit_gemm_gtc_bwd_nhwc.cpp
  src/solver/conv_asm_implicit_gemm_gtc_fwd_nhwc.cpp
  src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp
  src/solver/conv_winoRxS_f2x3.cpp
  test/solver.cpp
Labels: quality, urgency_normal, TESTING_CI_PASSED

#1376 [TUNA] FIN subtree updates JSON versioning
  fin/requirements.txt
  fin/src/include/conv_fin.hpp
Labels: enhancement, urgency_normal

#1380 [host code]fix a host static for loop bug
  test/ford.hpp
Labels: bug, value_high, quality, complexity_low, urgency_high

#1313 Pooling driver command-line update
  driver/InputFlags.cpp
  driver/InputFlags.hpp
  driver/driver.hpp
  driver/pool_driver.hpp
  driver/random.hpp
  driver/tensor_driver.hpp
Labels: enhancement, quality, complexity_middle, urgency_high, TESTING_CI_PASSED

#1367 [SWDEV-316198] add split_4g_func in asm igemm bwd solver
  src/conv/invokers/impl_gemm_dynamic.cpp
  src/include/miopen/conv/asm_implicit_gemm.hpp
  src/solver/conv_asm_implicit_gemm_gtc_bwd_nhwc.cpp
  src/solver/conv_asm_implicit_gemm_gtc_fwd_nhwc.cpp
  src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp
  test/CMakeLists.txt
Labels: value_high, urgency_blocker, TESTING_CI_PASSED

#1375 [BUG] Resolve the compilation error of conv3x3.s
  src/kernels/conv3x3.s
Labels: bug, value_high, urgency_high, TESTING_CI_PASSED

#1379 [driver] #1379 - Post Merge Review Update
  driver/InputFlags.cpp
  driver/InputFlags.hpp
Labels: Review Required

#1316 layout_flag_error_handle
  driver/conv_driver.hpp
  src/include/miopen/tensor_layout.hpp
Labels: enhancement, TESTING_CI_PASSED

#1388 [5.0][Navi21] Fixing Batchnorm backward precision issues by adjusting workgroup size (SWDEV-292187, SWDEV-319919)
  src/solver/batchnorm/backward_spatial_single.cpp
Labels: bug, ON_HOLD, urgency_blocker, TESTING_CI_PASSED

#1390 [5.0][Navi21] Remove W/A for SWDEV-292187
  src/execution_context.cpp
  src/include/miopen/execution_context.hpp
  src/include/miopen/target_properties.hpp
  src/solver/conv_ocl_dir2D11x11.cpp
  src/solver/conv_ocl_dir2D_bwdWrW_1x1.cpp
  src/solver/conv_ocl_dir2D_bwdWrW_2.cpp
  src/solver/conv_ocl_dir2D_bwdWrW_53.cpp
  src/solver/conv_ocl_dir2Dfwd.cpp
  src/solver/conv_ocl_dir2Dfwd1x1.cpp
  src/solver/conv_ocl_dir2Dfwdgen.cpp
  test/CMakeLists.txt
  test/handle_test.cpp
Labels: urgency_unknown, performance, ON_HOLD, workaround, TESTING_CI_PASSED

#1381 Pooling trasposed forward solvers and transposed solver core
  driver/mloPoolingHost.hpp
  driver/pool_driver.hpp
  src/CMakeLists.txt
  src/hipoc/hipoc_kernel.cpp
  src/include/miopen/activ/solvers.hpp
  src/include/miopen/batchnorm/solvers.hpp
  src/include/miopen/datatype.hpp
  src/include/miopen/find_solution.hpp
  src/include/miopen/invoke_params.hpp
  src/include/miopen/pooling/problem_description.hpp
  src/include/miopen/pooling/solvers.hpp
  src/include/miopen/solver.hpp
  src/include/miopen/subbuffers.hpp
  src/include/miopen/utility/transposing_solver.hpp
  src/kernels/UniversalTranspose.cl
  src/ocl/handleocl.cpp
  src/ocl/pooling_ocl.cpp
  src/pooling.cpp
  src/solver.cpp
  src/solver/pooling/forward2d.cpp
  src/solver/pooling/forwardNd.cpp
  src/subbuffers.cpp
Labels: value_high, urgency_normal, TESTING_CI_PASSED

#1396 [Release][5.0] Revert incorrect change to ConvBiasActivAsm1x1U solver search method
  src/solver/conv_asm_1x1u_bias_activ.cpp
Labels: urgency_blocker
