Repository ROCm/MIOpen, pull requests merged in 2023-11, with the labels that each got.

#2480 Fix builds with rocBLAS that does not support F8
  src/gemm_v2.cpp
Labels: value_high, quality, TESTING_CI_PASSED

#2497 workaround SWDEV_423713 by disabling the unit test case in wrw solver
  src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp
Labels: urgency_blocker, TESTING_CI_PASSED

#2507 Workaround for issue #2492 - disable ConvBinWinoRxS when granularity loss is huge
  src/solver/conv_winoRxS.cpp
Labels: workaround, urgency_high, TESTING_CI_PASSED

#2510 Workaround for issue #2492 part 2 (improvement)
  driver/conv_driver.hpp
  src/execution_context.cpp
  src/include/miopen/execution_context.hpp
  src/solver/conv_winoRxS.cpp
  test/gtest/db_sync.cpp
Labels: value_high, urgency_blocker, quality, debugging

#2466 Find 2.0 problem fusing
  include/miopen/miopen.h
  src/api/find2_0_commons.cpp
  src/include/miopen/problem.hpp
  src/problem.cpp
Labels: urgency_blocker, complexity_low, TESTING_CI_PASSED, IMPACTS_API

#2515 fix for end of line issue on Windows
  src/db.cpp
Labels: TESTING_CI_PASSED, windows

#2352 cmake: strip mingw32 support and cross-compilation out
  CMakeLists.txt
  cmake/mingw-toolchain.cmake
  src/CMakeLists.txt
  src/include/miopen/float_equal.hpp
  src/include/miopen/par_for.hpp
  test/CMakeLists.txt
  test/ford.hpp
  test/main.cpp
Labels: windows

#2349 cmake: cleanup outdated code
  CMakeLists.txt
  src/CMakeLists.txt
  src/composable_kernel/host/host_tensor/CMakeLists.txt
Labels: TESTING_CI_PASSED, windows

#2351 cmake: make building tests optional
  CMakeLists.txt
  test/CMakeLists.txt
  test/gtest/CMakeLists.txt
Labels: TESTING_CI_PASSED, windows

#2512 [Tests] Relocate Googletest to dev requirements
  cmake/gtest.cmake
  dev-requirements.txt
  test/gtest/CMakeLists.txt
Labels: quality, urgency_normal, TESTING_CI_PASSED, value_unknown, dependencies

#2528 [Tests] Limit layernorm CK test applicability
  test/gtest/layernorm.cpp
Labels: urgency_blocker, testing

#2357 cmake: a few fixes for multi-config generators
  CMakeLists.txt
  cmake/EnableCompilerWarnings.cmake
  src/CMakeLists.txt
  src/sqlite/CMakeLists.txt
Labels: TESTING_CI_PASSED, windows

#2535 [Tests] split teardown to runtest and verify in layernorm gtest
  test/gtest/layernorm.cpp
  test/gtest/layernorm.hpp
Labels: urgency_blocker, testing, external_collaborator

#2538 [conv] Remove clamping to MAX from CastTensor used in Bwd and WrW
  src/conv/invokers/impl_gemm.cpp
  src/conv/invokers/impl_gemm_dynamic.cpp
  src/conv/invokers/mlir_impl_gemm.cpp
  src/include/miopen/tensor_ops.hpp
  src/kernels/MIOpenSubTensorOpWithCastTensorKernel.cl
  src/ocl/tensorocl.cpp
  src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp
  src/solver/conv_asm_implicit_gemm_wrw_gtc_dynamic_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops_padded_gemm.cpp
  src/solver/gemm.cpp
  test/tensor_cast.cpp
Labels: value_high, urgency_blocker, TESTING_CI_PASSED, correctness

#2353 cmake: use built in operator to component-wise version comparison
  CMakeLists.txt
  test/CMakeLists.txt
Labels: TESTING_CI_PASSED, windows

#2549 [Hotfix] when MLIR is not used in MIOpen
  test/CMakeLists.txt
Labels: bug, urgency_blocker, TESTING_CI_PASSED

#2548 Standardize documentation for ReadtheDocs
  .github/dependabot.yml
  .readthedocs.yaml
  Dockerfile
  README.md
  docs/.sphinx/_toc.yml
  docs/.sphinx/_toc.yml.in
  docs/.sphinx/requirements.in
  docs/conf.py
  docs/doxygen/Doxyfile
  docs/license.md
  docs/sphinx/_toc.yml.in
  docs/sphinx/requirements.in
  docs/sphinx/requirements.txt
Labels: TESTING_CI_PASSED, documentation

#2546 ConvOclDirectFwdGen: Fixed out-of-bounds memory access
  src/find_controls.cpp
  src/kernels/MIOpenConvDirGenFwd.cl
  src/kernels/MIOpenConvDirGenFwd_Vec2.cl
  src/solver/conv_ocl_dir2Dfwdgen.cpp
Labels: bug, urgency_high, TESTING_CI_PASSED, correctness

#2486 Find 2.0 fusion
  src/conv/solver_finders.cpp
  src/fusion.cpp
  src/generic_search.cpp
  src/include/miopen/conv/solver_finders.hpp
  src/include/miopen/find_controls.hpp
  src/include/miopen/find_solution.hpp
  src/include/miopen/fusion.hpp
  src/include/miopen/fusion_plan.hpp
  src/include/miopen/generic_search.hpp
  src/include/miopen/problem.hpp
  src/include/miopen/search_options.hpp
  src/include/miopen/solution.hpp
  src/problem.cpp
  src/solution.cpp
  test/gtest/cba_find2.hpp
  test/gtest/cba_find2_infer.cpp
Labels: value_high, urgency_blocker, complexity_high, TESTING_CI_PASSED

#2558 [Test] fix gemm driver dataType initialization
  driver/gemm_driver.hpp
Labels: bug, testing, urgency_high, TESTING_CI_PASSED

#2526 Use split CK libraries.
  CMakeLists.txt
  requirements.txt
  src/CMakeLists.txt
  src/solver/conv_hip_implicit_gemm_3d_grouped_fwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_grouped_fwd_xdlops.cpp
Labels: value_high, urgency_blocker

#2525 [Find 2.0] Bias for Find 2.0 fusion
  include/miopen/miopen.h
  src/api/find2_0_commons.cpp
  src/include/miopen/problem.hpp
  src/problem.cpp
  src/solution.cpp
  test/gtest/cba_find2.hpp
  test/gtest/cba_find2_infer.cpp
Labels: value_high, complexity_middle, TESTING_CI_PASSED, IMPACTS_API
