Repository ROCm/MIOpen, pull requests merged in 2023-05, with the labels that each got.

#2118 [pooling] Fix FP16 precision issues (averaging mode) plus more
  driver/calcerr.hpp
  driver/mloConvHost.hpp
  driver/mloPoolingHost.hpp
  driver/pool_driver.hpp
  src/include/miopen/target_properties.hpp
  src/kernels/MIOpenPooling.cl
  src/kernels/MIOpenPoolingBwd.cl
  src/kernels/MIOpenPoolingBwdND.cl
  src/kernels/MIOpenPoolingND.cl
  src/kernels/float_types.h
  src/kernels/pooling_functions.h
  src/solver/pooling/forward2d.cpp
  src/target_properties.cpp
  test/CMakeLists.txt
Labels: bug, urgency_blocker, correctness

#2053 Standardize MIOpen Documentation
  .github/dependabot.yml
  .readthedocs.yaml
  CMakeLists.txt
  Dockerfile
  README.md
  cmake/DoxygenDoc.cmake
  cmake/MainDoc.cmake
  cmake/SphinxDoc.cmake
  doc/CMakeLists.txt
  doc/README.md
  doc/classification-map.xml
  doc/src/conf.py
  docs/.doxygen/Doxyfile
  docs/.sphinx/_toc.yml
  docs/.sphinx/_toc.yml.in
  docs/.sphinx/requirements.in
  docs/.sphinx/requirements.txt
  docs/CMakeLists.txt
  docs/DebugAndLogging.md
  docs/Getting_Started_FusionAPI.md
  docs/MI200AlternateImplementation.md
  docs/MIOpen_Porting_Guide.md
  docs/README.md
  docs/activation.rst
  docs/apireference.rst
  docs/batchnorm.rst
  docs/cache.md
  docs/citation.md
  docs/conf.py
  docs/convolution.rst
  docs/data/cba.png
  docs/data/driverTableCrop.png
  docs/data/fp16fusions.png
  docs/data/fp32fusions.png
  docs/data/na.png
  docs/datatypes.md
  docs/driver.md
  docs/dropout.rst
  docs/embed.md
  docs/find_and_immediate.md
  docs/finddb.md
  docs/fusion.rst
  docs/handle.rst
  docs/index.rst
  docs/install.md
  docs/loss.rst
  docs/lrn.rst
  docs/perfdatabase.md
  docs/pooling.rst
  docs/reduction.rst
  docs/releasenotes.md
  docs/rnn.rst
  docs/softmax.rst
  docs/tensor.rst
  driver/README.md
Labels: documentation

#2039 [tests] Test for #1928: [TensorDescriptor] Add input parameters validation
  src/include/miopen/logger.hpp
  src/tensor_api.cpp
  test/gtest/tensor_api.cpp
  test/tensor_api.cpp
Labels: testing, urgency_high, TESTING_CI_PASSED

#2128 [tests][HotFix] Remove `doc` target after #2053
  Jenkinsfile
Labels: bug, value_high, urgency_blocker, complexity_low

#2124 [WA] AMD MLIR lld conflicts with conda
  requirements.txt
Labels: TESTING_CI_PASSED

#2142 Fix LSTM perf when stream is null
  src/hip/handlehip.cpp
  src/ocl/rnnocl.cpp
Labels: performance, urgency_high, TESTING_CI_PASSED

#2108 Fix MIOPEN_ENABLE_SQLITE=Off
  src/CMakeLists.txt
  src/binary_cache.cpp
  src/include/miopen/activ/problem_description.hpp
  src/include/miopen/batchnorm/problem_description.hpp
  src/include/miopen/conv/problem_description.hpp
  src/include/miopen/execution_context.hpp
  src/include/miopen/fusion/problem_description.hpp
  src/include/miopen/mlo_internal.hpp
  src/include/miopen/pooling/problem_description.hpp
  src/include/miopen/problem_description.hpp
  src/include/miopen/sqlite_db.hpp
  src/pooling/problem_description.cpp
  test/CMakeLists.txt
  test/cache.cpp
  test/sqlite.cpp
  test/sqlite_perfdb.cpp
Labels: bug, TESTING_CI_PASSED

#2111 Fixes for conv_asm perf config validity check.
  src/solver/conv_asm_implicit_gemm_gtc_bwd_nhwc.cpp
  src/solver/conv_asm_implicit_gemm_gtc_fwd_nchwc.cpp
  src/solver/conv_asm_implicit_gemm_gtc_fwd_nhwc.cpp
  src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp
Labels: value_high, complexity_middle, urgency_high, TESTING_CI_PASSED

#2150 [CI][Jenkins] Remove OpenCL CI Stages
  Jenkinsfile
Labels: TESTING_CI_PASSED
