Repository ROCm/MIOpen, pull requests merged in 2023-12, with the labels that each got.

#2531 Forward, backward data and backward weight convolution solver with fp8/bfp8 compute datatype.
  src/CMakeLists.txt
  src/include/miopen/solver.hpp
  src/mlo_dir_conv.cpp
  src/solver.cpp
  src/solver/conv_hip_implicit_gemm_f16f8f16_bwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_f16f8f16_fwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_f16f8f16_wrw_xdlops.cpp
  test/gtest/conv_f8_bwd.cpp
  test/gtest/conv_f8_fwd.cpp
  test/gtest/conv_f8_wrw.cpp
  test/gtest/f8_cast_util.hpp
Labels: TESTING_CI_PASSED

#2577 [hot fix] Disable f8 gtest cases that might cause CI fails.
  test/gtest/conv_f8_bwd.cpp
  test/gtest/conv_f8_fwd.cpp
  test/gtest/conv_f8_wrw.cpp
Labels: bug, urgency_blocker

#2581 [CK] Bump CK commit hash for staging
  requirements.txt
Labels: value_middle, complexity_low, urgency_normal

#2586 Fix the f8 reference kernel issue that failed CI
  src/kernels/hip_f8_impl.hpp
  test/gtest/conv_f8_bwd.cpp
  test/gtest/conv_f8_fwd.cpp
  test/gtest/conv_f8_wrw.cpp
Labels: quality, TESTING_CI_PASSED

#2585 [DOC] swdev-410525 : Doxygen change
  docs/doxygen/Doxyfile
  include/miopen/miopen.h
Labels: TESTING_CI_PASSED, documentation

#2537 [Documentation] Add documentations for non-packed tensors convolution
  include/miopen/miopen.h
Labels: enhancement, documentation

#2493 Tests for RNN seq API
  driver/rnn_seq_driver.hpp
  src/ocl/rnnocl.cpp
  src/rnn/rnn_util.cpp
  src/seq_tensor.cpp
  test/cpu_lstm.hpp
  test/cpu_rnn.hpp
  test/driver.hpp
  test/lstm_common.hpp
  test/rnn_seq_api.cpp
  test/rnn_seq_api.hpp
  test/rnn_util.hpp
  test/seq_tensor_holder.hpp
  test/tensor_holder.hpp
  test/verify.hpp
Labels: value_high, quality, urgency_high, TESTING_CI_PASSED

#2598 Fix build with disabled CK (after #2523)
  src/solver/conv_hip_implicit_gemm_f16f8f16_fwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_grouped_fwd_xdlops.cpp
Labels: urgency_high, windows

#2592 [MIOpenDriver] Enabled gemmfp16. [tests] Added smoke test for fp16 and fp32 gemm.
  driver/driver.hpp
  driver/gemm_driver.hpp
  driver/main.cpp
  test/CMakeLists.txt
Labels: enhancement, urgency_high

#2597 Fix URLs (ROCmSoftwarePlatform -> ROCm) in the documentation and in comments in the source code. + more
  CMakeLists.txt
  README.md
  docs/DebugAndLogging.md
  docs/Getting_Started_FusionAPI.md
  docs/cache.md
  docs/driver.md
  docs/find_and_immediate.md
  docs/finddb.md
  docs/index.rst
  docs/install.md
  docs/perfdatabase.md
  docs/releasenotes.md
  driver/dropout_gpu_emulator.hpp
  include/miopen/config.h.in
  src/comgr.cpp
  src/composable_kernel/external/rocm/include/bfloat16_dev.hpp
  src/include/miopen/batchnorm/solvers.hpp
  src/include/miopen/bfloat16.hpp
  src/include/miopen/conv/asm_implicit_gemm.hpp
  src/include/miopen/solver.hpp
  src/include/miopen/sqlite_db.hpp
  src/kernels/MIOpenDropout.cl
  src/kernels/bfloat16_dev.hpp
  src/ocl/handleocl.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v4r1_xdlops.cpp
  src/solver/conv_mlir_igemm_bwd.cpp
  src/solver/conv_mlir_igemm_fwd.cpp
  src/solver/conv_mlir_igemm_wrw.cpp
  src/solver/conv_ocl_dir2D_bwdWrW_2.cpp
  src/solver/conv_winoRxS.cpp
  src/solver/conv_winoRxS_fused.cpp
  src/solver/gemm_common.cpp
  src/solver/pooling/backwardNd.cpp
  src/solver/pooling/forwardNaive.cpp
  test/CMakeLists.txt
  test/dropout_util.hpp
Labels: bug, urgency_high, documentation

#2574 use find_package() for Eigen and frugally-deep
  src/CMakeLists.txt
  test/gtest/CMakeLists.txt
Labels: windows

#2570 enable compilation on Windows
  CMakeLists.txt
  driver/CMakeLists.txt
  speedtests/sequences.cpp
  src/CMakeLists.txt
  src/hipoc/hipoc_program.cpp
  src/include/miopen/type_name.hpp
  test/CMakeLists.txt
  test/find_db.cpp
  test/gtest/CMakeLists.txt
  utils/CMakeLists.txt
Labels: windows

#2560 Bug fix for 3D Group Conv Backward data and weight update. Failure noticed when pads and strides are not 1
  src/solver/conv_hip_implicit_gemm_3d_grouped_bwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_3d_grouped_wrw_xdlops.cpp
  test/gtest/group_conv3d_bwd.hpp
  test/gtest/group_conv3d_wrw.hpp
Labels: urgency_blocker

#2610 fix find_package(... GLOBAL) for CMake < 3.24
  CMakeLists.txt
  src/CMakeLists.txt
Labels: urgency_high

#2609 [HotFix][atamazov] multiple undefined behavior discovered with -fsanitize=undefined in DEV builds
  driver/gemm_driver.hpp
  src/activ_api.cpp
  src/api/find2_0_commons.cpp
  src/convolution_api.cpp
  src/ctc_api.cpp
  src/dropout_api.cpp
  src/fused_api.cpp
  src/include/miopen/gemm_v2.hpp
  src/lrn_api.cpp
  src/pooling_api.cpp
  src/reducetensor_api.cpp
  src/rnn_api.cpp
  src/sum_api.cpp
  src/tensor_api.cpp
Labels: TESTING_CI_PASSED

#2612 explicitly link with hipRTC
  CMakeLists.txt
  src/CMakeLists.txt
Labels: urgency_high

#2524 Standardize workspace abstraction
  src/ocl/convolutionocl.cpp
  test/conv_common.hpp
  test/ctc.cpp
  test/find_2_conv.cpp
  test/find_db.cpp
  test/gru_common.hpp
  test/gtest/conv_api_strided_tensors.cpp
  test/gtest/solver_bwd.hpp
  test/gtest/solver_fwd.hpp
  test/gtest/solver_wrw.hpp
  test/lstm_common.hpp
  test/main.cpp
  test/pooling_common.hpp
  test/reduce_test.cpp
  test/rnn_vanilla_common.hpp
  test/tensor_reorder.cpp
  test/workspace.hpp
Labels: urgency_blocker, TESTING_CI_PASSED

#2580 [gtest] conversion for code coverage tests
  test/CMakeLists.txt
  test/conv3d.hpp
  test/driver.hpp
  test/gtest/CMakeLists.txt
  test/gtest/conv3d_codecov.cpp
  test/gtest/conv_2d.hpp
  test/gtest/conv_igemm_mlir_xdlops.cpp
  test/gtest/immed_conv2d_codecov.cpp
  test/gtest/immed_conv3d_codecov.cpp
  test/gtest/pooling2d_asymmetric.cpp
  test/gtest/pooling2d_codecov.cpp
  test/gtest/pooling2d_wide.cpp
  test/immed_conv3d.cpp
  test/pooling2d.hpp
Labels: TESTING_CI_PASSED

#2616 [HotFix] revert #2580 and re-enable smoke tests
  .github/workflows/update_develop_nightly.yml
  Jenkinsfile
  test/CMakeLists.txt
  test/driver.hpp
  test/gtest/CMakeLists.txt
  test/gtest/conv3d_codecov.cpp
  test/gtest/conv_2d.hpp
  test/gtest/conv_igemm_mlir_xdlops.cpp
  test/gtest/immed_conv2d_codecov.cpp
  test/gtest/immed_conv3d_codecov.cpp
  test/gtest/pooling2d_asymmetric.cpp
  test/gtest/pooling2d_codecov.cpp
  test/gtest/pooling2d_wide.cpp
  test/immed_conv2d.cpp
  test/immed_conv3d.cpp
  test/pooling2d.cpp
Labels: ON_HOLD

#2564 use find_package() for SQLite3
  CMakeLists.txt
  src/CMakeLists.txt
  src/sqlite/CMakeLists.txt
Labels: TESTING_CI_PASSED, windows

#2565 use official ZStd package from Facebook
  cmake/Findzstd.cmake
  requirements.txt
Labels: windows

#2499 Remove MIOpenGEMM and MIOpenTensile leftovers
  Dockerfile
  Jenkinsfile
  README.md
  docs/DebugAndLogging.md
  docs/install.md
  include/miopen/config.h.in
  src/CMakeLists.txt
  src/anyramdb.cpp
  src/binary_cache.cpp
  src/db.cpp
  src/gemm_v2.cpp
  src/hip/handlehip.cpp
  src/hipoc/hipoc_program.cpp
  src/include/miopen/binary_cache.hpp
  src/include/miopen/clhelper.hpp
  src/include/miopen/gemm_geometry.hpp
  src/include/miopen/generic_search.hpp
  src/include/miopen/handle.hpp
  src/include/miopen/hipoc_program.hpp
  src/include/miopen/hipoc_program_impl.hpp
  src/include/miopen/kernel_cache.hpp
  src/include/miopen/kernel_warnings.hpp
  src/include/miopen/miopengemm.hpp
  src/include/miopen/rocm_features.hpp
  src/include/miopen/solver.hpp
  src/include/miopen/solver/gemm_common.hpp
  src/kernel_cache.cpp
  src/kernel_warnings.cpp
  src/nogpu/handle.cpp
  src/ocl/clhelper.cpp
  src/ocl/handleocl.cpp
  src/ramdb.cpp
  src/solver.cpp
  src/solver/gemm.cpp
  src/solver/gemm_bwd.cpp
  src/solver/gemm_common.cpp
  src/solver/gemm_wrw.cpp
  src/sqlite_db.cpp
  test/CMakeLists.txt
  test/conv_common.hpp
  test/gtest/cache.cpp
  test/gtest/db_sync.cpp
  test/handle_test.cpp
Labels: ON_HOLD, quality, TESTING_CI_PASSED

#2622 [Jenkins] Add NOMLIR stage. [Workaround] Limit usage of gfx908 nodes in non-nightly builds
  Jenkinsfile
Labels: TESTING_CI_PASSED

#2613 Get rid of legacy 2GiB offset limits in CallGemm*() and transpose*() internal APIs and kernels.
  src/gemm_v2.cpp
  src/include/miopen/gemm_v2.hpp
  src/include/miopen/util.hpp
  src/kernels/MIOpenUtilKernels4.cl
  src/ocl/utilocl.cpp
Labels: bug, urgency_high, TESTING_CI_PASSED, correctness

#2619 Proper fix for backward passes bwd/wrw for CK group conv 3d
  src/solver/conv_hip_implicit_gemm_3d_grouped_bwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_3d_grouped_wrw_xdlops.cpp
  test/gtest/group_conv3d_bwd.cpp
  test/gtest/group_conv3d_bwd.hpp
  test/gtest/group_conv3d_wrw.cpp
  test/gtest/group_conv3d_wrw.hpp
Labels: bug, urgency_blocker, TESTING_CI_PASSED

#2517 Fused solver for Fwd Convolution with Residual add, Bias add and then activation function
  requirements.txt
  src/CMakeLists.txt
  src/fusion.cpp
  src/include/miopen/fusion.hpp
  src/include/miopen/fusion/fusion_invoke_params.hpp
  src/include/miopen/fusion/solvers.hpp
  src/include/miopen/fusion_ops.hpp
  src/ocl/fusionopbiasbnactivocl.cpp
  src/solver.cpp
  src/solver/conv_ck_igemm_fwd_bias_res_add_activ_fused.cpp
  test/gtest/api_convbiasactiv.cpp
  test/gtest/fused_conv_bias_res_add_activ.cpp
Labels: complexity_middle, urgency_high, TESTING_CI_PASSED

#2519 Bump MIOpen version to 3.1.0 and update CI docker
  CMakeLists.txt
  Dockerfile
  dev-requirements.txt
  docs/DebugAndLogging.md
  requirements.txt
  src/CMakeLists.txt
  src/comgr.cpp
  src/composable_kernel/.clang-tidy
  src/composable_kernel/cmake/ClangTidy.cmake
  src/composable_kernel/external/rocm/include/bfloat16_dev.hpp
  src/convolution.cpp
  src/kernels/bfloat16_dev.hpp
  src/kernels/float_types.h
  src/kernels/hip_f8_impl.hpp
  src/kernels/hip_float8.hpp
  src/rnn_api.cpp
  test/handle_test.cpp
  test/na_train.cpp
Labels: value_high, urgency_high, TESTING_CI_PASSED

#2629 [HotFix] resolve unknown type issue after #2517
  src/solver/conv_ck_igemm_fwd_bias_res_add_activ_fused.cpp
Labels: bug, urgency_blocker, complexity_low

#2630 [HOTFIX] Fix build with -DMIOPEN_USE_COMPOSABLEKERNEL=Off after #2517.
  src/solver/conv_ck_igemm_fwd_bias_res_add_activ_fused.cpp
Labels: bug, urgency_blocker

#2631 [Jenkins][Tests] Add stage with -DMIOPEN_USE_COMPOSABLEKERNEL=Off after #2517 #2630.
  Jenkinsfile
  test/gtest/CMakeLists.txt
Labels: complexity_low, urgency_high, TESTING_CI_PASSED

#2405 rocblas: disable Beta API on Windows for HIP < 5.7
  src/gemm_v2.cpp
Labels: TESTING_CI_PASSED, windows

#2635 [HOTFIX][tests] Limit applicability of ConvFwdBiasActivAPI/ConvFwdBiasResAddActivTest.ConvFusedAPI
  test/gtest/fused_conv_bias_res_add_activ.cpp
Labels: bug, urgency_blocker, testing

#2605 helper for evn variables update for gtest
  src/include/miopen/env.hpp
  test/gtest/gtest_common.hpp
Labels: complexity_middle, urgency_high, TESTING_CI_PASSED

#2568 fix compilation of math functions on Windows
  src/include/miopen/float_equal.hpp
  test/rnn_vanilla_common.hpp
  test/verify.hpp
Labels: windows

#2569 fix printf type incompatibility between type specifiers
  driver/rnn_seq_driver.hpp
Labels: TESTING_CI_PASSED, windows

#2508 Fix miopen package dependency roctracer etc
  CMakeLists.txt
  Dockerfile
  include/miopen/config.h.in
  src/CMakeLists.txt
  src/include/miopen/logger.hpp
Labels: enhancement, urgency_normal, TESTING_CI_PASSED, value_unknown

#2566 make BZip2 a required package
  CMakeLists.txt
  src/CMakeLists.txt
  test/gtest/CMakeLists.txt
Labels: windows

#2556 add missing symbol export
  src/activ_api.cpp
  src/execution_context.cpp
  src/find_controls.cpp
  src/find_db.cpp
  src/include/miopen/conv_algo_name.hpp
  src/include/miopen/convolution.hpp
  src/include/miopen/execution_context.hpp
  src/include/miopen/find_controls.hpp
  src/include/miopen/find_db.hpp
  src/include/miopen/gemm_v2.hpp
  src/include/miopen/handle.hpp
  src/include/miopen/logger.hpp
  src/include/miopen/pooling.hpp
  src/include/miopen/solver.hpp
  src/include/miopen/solver_id.hpp
  src/include/miopen/tensor.hpp
  src/logger.cpp
  src/solver/conv_direct_naive_conv.cpp
  test/gpu_conv.hpp
Labels: TESTING_CI_PASSED, windows

#2637 [ROCm 6.1 RC] Fix build failures. [quality] Reorg standard includes in HIP sources.
  CMakeLists.txt
  driver/random.hpp
  src/CMakeLists.txt
  src/comgr.cpp
  src/composable_kernel/composable_kernel/include/utility/array.hpp
  src/composable_kernel/composable_kernel/include/utility/config.hpp
  src/composable_kernel/composable_kernel/include/utility/data_type.hpp
  src/composable_kernel/composable_kernel/include/utility/enable_if.hpp
  src/composable_kernel/composable_kernel/include/utility/magic_division.hpp
  src/composable_kernel/composable_kernel/include/utility/type.hpp
  src/gemm_v2.cpp
  src/kernels/MIOpenCheckNumerics.cpp
  src/kernels/gpu_batched_transpose_kernel/batched_transpose.cpp
  src/kernels/gpu_general_tensor_reorder_kernel/general_tensor_reorder_kernel_util.hpp
  src/kernels/gpu_reference_kernel/fp8_naive_conv.cpp
  src/kernels/gpu_reference_kernel/naive_conv.cpp
  src/kernels/hip_f8_impl.hpp
  src/kernels/hip_float8.hpp
  src/kernels/miopen_cstdint.hpp
  src/kernels/miopen_limits.hpp
  src/kernels/miopen_type_traits.hpp
  src/kernels/miopen_utility.hpp
  src/kernels/static_composable_kernel/include/utility/static_kernel_ck_utils_type.hpp
  src/kernels/static_composable_kernel/include/utility/static_kernel_reduction_operator.hpp
  src/kernels/static_composable_kernel/include/utility/static_kernel_tuple.hpp
  src/kernels/stride_array.hpp
  test/CMakeLists.txt
  test/gtest/CMakeLists.txt
  test/handle_test.cpp
Labels: enhancement, value_high, urgency_blocker, specification, TESTING_CI_PASSED

#2225 [WORKAROUND] Disable W/A for issue #1359 starting from ROCm 5.4.3.
  src/hipoc/hipoc_program.cpp
Labels: non-miopen-bug, urgency_high

#2640 [Dep] Bump CK commit hash for staging
  requirements.txt
Labels: dependencies

#2365 default paths to user and system db files on Windows
  CMakeLists.txt
  src/db_path.cpp.in
  src/expanduser.cpp
Labels: TESTING_CI_PASSED, windows

#2641 [ROCm 6.0.1] Adaptation for HIPRTC changes in 6.0.1
  CMakeLists.txt
  Dockerfile
  dev-requirements.txt
  docs/DebugAndLogging.md
  driver/CMakeLists.txt
  driver/driver.hpp
  driver/random.hpp
  speedtests/CMakeLists.txt
  src/CMakeLists.txt
  src/comgr.cpp
  src/composable_kernel/.clang-tidy
  src/composable_kernel/cmake/ClangTidy.cmake
  src/composable_kernel/composable_kernel/include/utility/array.hpp
  src/composable_kernel/composable_kernel/include/utility/config.hpp
  src/composable_kernel/composable_kernel/include/utility/data_type.hpp
  src/composable_kernel/composable_kernel/include/utility/enable_if.hpp
  src/composable_kernel/composable_kernel/include/utility/magic_division.hpp
  src/composable_kernel/composable_kernel/include/utility/type.hpp
  src/composable_kernel/external/rocm/include/bfloat16_dev.hpp
  src/convolution.cpp
  src/gemm_v2.cpp
  src/include/miopen/hip_f8_impl.hpp
  src/include/miopen/hip_float8.hpp
  src/kernels/MIOpenCheckNumerics.cpp
  src/kernels/MIOpenLayerNorm.cpp
  src/kernels/bfloat16_dev.hpp
  src/kernels/float_types.h
  src/kernels/gpu_batched_transpose_kernel/batched_transpose.cpp
  src/kernels/gpu_general_tensor_reorder_kernel/general_tensor_reorder_kernel_util.hpp
  src/kernels/gpu_reference_kernel/fp8_naive_conv.cpp
  src/kernels/gpu_reference_kernel/naive_conv.cpp
  src/kernels/hip_f8_impl.hpp
  src/kernels/hip_float8.hpp
  src/kernels/miopen_cstdint.hpp
  src/kernels/miopen_limits.hpp
  src/kernels/miopen_type_traits.hpp
  src/kernels/miopen_utility.hpp
  src/kernels/static_composable_kernel/include/utility/static_kernel_ck_utils_type.hpp
  src/kernels/static_composable_kernel/include/utility/static_kernel_config.hpp
  src/kernels/static_composable_kernel/include/utility/static_kernel_reduction_operator.hpp
  src/kernels/static_composable_kernel/include/utility/static_kernel_tuple.hpp
  src/kernels/stride_array.hpp
  src/rnn_api.cpp
  test/CMakeLists.txt
  test/cpu_conv.hpp
  test/gtest/CMakeLists.txt
  test/gtest/solver_bwd.hpp
  test/gtest/solver_fwd.hpp
  test/gtest/solver_wrw.hpp
  test/handle_test.cpp
  test/na_train.cpp
  test/tensor_holder.hpp
  test/verify.hpp
Labels: enhancement, value_high, urgency_unknown

#2645 Fix COMgr dependency in MIOpen package
  CMakeLists.txt
Labels: complexity_low, urgency_high
