Repository ROCm/MIOpen, pull requests merged in 2023-07, with the labels that each got.

#2241 bg/LWMIOPEN-189 : use DataInvokeParams for non-fused solver - fix tuning of legacy OCL solvers
  src/solver/conv_ocl_dir2Dfwd_exhaustive_search.cpp
  src/solver/conv_ocl_dir2Dfwd_fused.cpp
Labels: bug, urgency_blocker

#2206 [Tests] Convert conv_igemm_mlir_xdlops_fwd bwd wrw from CTest to gTest
  src/include/miopen/env.hpp
  test/CMakeLists.txt
  test/gtest/CMakeLists.txt
  test/gtest/conv_2d.hpp
  test/gtest/conv_igemm_mlir_xdlops.cpp
Labels: TESTING_CI_PASSED

#2203 Add API to get the number of convolution groups
  docs/convolution.rst
  include/miopen/miopen.h
  src/convolution_api.cpp
Labels: TESTING_CI_PASSED, External_Collaborator

#2168 test_conv_embed_db (ctest -> gtest)
  docs/conf.py
  test/CMakeLists.txt
  test/conv2d.cpp
  test/conv2d.hpp
  test/gtest/conv_embed_db.cpp
Labels: testing, TESTING_CI_PASSED

#2252 [Tests] tensor operations tests improvements.
  test/tensor_ops.cpp
Labels: testing, urgency_normal

#2260 bg/LWPMIOPEN-191: Gracefully exit if search mode is not supported during fusion's compile stage.
  src/fusion.cpp
  test/gtest/bad_fusion_plan.cpp
Labels: urgency_blocker, TESTING_CI_PASSED

#2266 Do not fail the generic search if n_runs_total is zero; turns warnings into infos
  src/include/miopen/generic_search.hpp
Labels: urgency_high

#2262 OpTensor1d improvement
  src/CMakeLists.txt
  src/kernels/MIOpenTensorKernels.cl
  src/kernels/MIOpenTensorKernelsHip.cpp
  src/ocl/tensorocl.cpp
Labels: performance, quality, correctness

#2263 [FIX SW 396203] check launch kernel grid size not beyond 32bit integer
  src/solver/conv_asm_implicit_gemm_gtc_bwd_nhwc.cpp
  src/solver/conv_asm_implicit_gemm_gtc_fwd_nhwc.cpp
  src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp
Labels: bug, value_high, urgency_blocker

#2279 Properly failing FindSoluions on exceptions
  src/include/miopen/find_solution.hpp
  src/include/miopen/generic_search.hpp
Labels: bug, complexity_low, TESTING_CI_PASSED

#2281 fix a bug in legacy fwd/bwd hip igemm solver. They didn't support group conv at all
  src/solver/conv_hip_implicit_gemm_bwd_data_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_fwd_xdlops.cpp
Labels: value_high, urgency_blocker

#2211 Add convolution base test boilerplate class.
  test/gtest/cba.hpp
  test/gtest/conv_test_base.hpp
  test/gtest/kernel_tuning_net.cpp
  test/gtest/solver.hpp
  test/gtest/solver_convasm3x3u.cpp
  test/gtest/tuna_net.cpp
Labels: TESTING_CI_PASSED

#2234 Improve GET_RAND() performance
  driver/random.hpp
Labels: TESTING_CI_PASSED

#2276 Fix CMake search for unzipper
  CMakeLists.txt
Labels: bug, urgency_normal
