Repository ROCm/MIOpen, pull requests merged in 2023-09, with the labels that each got.

#2338 Post Merg Fixes for 2305: Cache CK conv_ptr as a shared_ptr. Clean up by moving common code into functions
  src/solver/conv_hip_implicit_gemm_fwd_xdlops.cpp
Labels: performance, quality, TESTING_CI_PASSED

#2370 FIX:single element copy and workspace size bugs
  src/include/miopen/tensor_ops.hpp
  src/rnn/Solutions/rnn_transformer.cpp
Labels: bug, complexity_low, TESTING_CI_PASSED

#2376 [HOTFIX] Restore safe implementation of MIOPEN_THROW
  src/include/miopen/errors.hpp
  src/seq_tensor.cpp
Labels: bug, urgency_blocker

#2189 bg/LWPMIOPEN-149 : now able to log fusion cmd
  src/CMakeLists.txt
  src/batch_norm_api.cpp
  src/convolution_api.cpp
  src/driver_arguments.cpp
  src/fusion.cpp
  src/include/miopen/driver_arguments.hpp
  test/gtest/CMakeLists.txt
  test/gtest/log.cpp
  test/gtest/log.hpp
  test/gtest/log_test.cpp
  test/gtest/log_test_helper.cpp
  test/gtest/log_test_neg.cpp
Labels: TESTING_CI_PASSED

#2369 Fix perf config search and serialization/deserialization
  src/include/miopen/solver.hpp
  src/solver/conv_hip_implicit_gemm_fwd_xdlops.cpp
Labels: bug, urgency_blocker, quality, TESTING_CI_PASSED

#2381 [5.7.0 docs] Set min rocm-docs-core version to 0.24.0
  docs/.sphinx/requirements.in
  docs/.sphinx/requirements.txt
Labels: documentation, dependencies

#2358 cmake: set the C++ standard version in a portable way
  CMakeLists.txt
Labels: windows

#2373 3D group backward data convolution solver
  requirements.txt
  src/CMakeLists.txt
  src/include/miopen/solver.hpp
  src/mlo_dir_conv.cpp
  src/solver.cpp
  src/solver/conv_hip_implicit_gemm_3d_grouped_bwd_xdlops.cpp
  test/conv_common.hpp
  test/gtest/group_conv3d_bwd.cpp
  test/gtest/group_conv3d_bwd.hpp
Labels: TESTING_CI_PASSED

#2379 Ck kernels invocation refactoring
  src/include/miopen/solver.hpp
  src/include/miopen/solver/implicitgemm_ck_util.hpp
  src/solver/conv_hip_implicit_gemm_3d_grouped_fwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_bwd_data_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_fwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_grouped_fwd_xdlops.cpp
Labels: performance, quality, TESTING_CI_PASSED

#2354 Fix parameter truncation for CK solvers
  src/include/miopen/performance_config.hpp
  src/include/miopen/solver.hpp
Labels: TESTING_CI_PASSED

#2377 3D group backward weight convolution solver
  requirements.txt
  src/CMakeLists.txt
  src/include/miopen/solver.hpp
  src/mlo_dir_conv.cpp
  src/solver.cpp
  src/solver/conv_hip_implicit_gemm_3d_grouped_wrw_xdlops.cpp
  test/conv_common.hpp
  test/gtest/group_conv3d_wrw.cpp
  test/gtest/group_conv3d_wrw.hpp
Labels: urgency_blocker, TESTING_CI_PASSED

#2271 bg/lwpmiopen 194 : Integrate CK's batch norm inference into Non-tunable MIOpen solver.
  src/CMakeLists.txt
  src/include/miopen/batchnorm/problem_description.hpp
  src/include/miopen/batchnorm/solvers.hpp
  src/ocl/batchnormocl.cpp
  src/solver.cpp
  src/solver/batchnorm/forward_inference.cpp
  src/solver/batchnorm/forward_inference_ck.cpp
  test/fusionHost.hpp
  test/gtest/bn.hpp
  test/gtest/bn_infer.cpp
  test/gtest/bn_test_data.hpp
  test/gtest/test_operations.hpp
Labels: value_high, urgency_normal, TESTING_CI_PASSED

#2389 CK kernel invocation refactoring - 3D convo BWD
  src/solver/conv_hip_implicit_gemm_3d_grouped_bwd_xdlops.cpp
Labels: performance, quality, urgency_high, TESTING_CI_PASSED

#2366 fix dropout unit test on Windows
  src/ocl/dropoutocl.cpp
  test/dropout_util.hpp
Labels: TESTING_CI_PASSED, windows

#2390 CK kernel invocation refactoring - 3D convo WRW
  src/solver/conv_hip_implicit_gemm_3d_grouped_bwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_3d_grouped_wrw_xdlops.cpp
Labels: performance, quality, urgency_high, TESTING_CI_PASSED

#2362 cmake: enable finding installed ZStd library
  cmake/Findzstd.cmake
  src/CMakeLists.txt
Labels: TESTING_CI_PASSED, windows

#2384 Add dnorm test convolution driver code
  driver/conv_driver.hpp
  driver/random.hpp
Labels: TESTING_CI_PASSED

#2391 [Mwootton] Add ability to log to roctx. Currently just for functions
  CMakeLists.txt
  src/CMakeLists.txt
  src/include/miopen/fusion/solvers.hpp
  src/include/miopen/logger.hpp
  src/logger.cpp
Labels: enhancement, value_high, urgency_normal, TESTING_CI_PASSED

#2337 [driver] [test] PRNG: allow custom\fixed seed
  driver/CBAInferFusion_driver.hpp
  driver/activ_driver.hpp
  driver/bn_driver.hpp
  driver/conv_driver.hpp
  driver/ctc_driver.hpp
  driver/dropout_driver.hpp
  driver/gemm_driver.hpp
  driver/lrn_driver.hpp
  driver/pool_driver.hpp
  driver/random.hpp
  driver/reduce_driver.hpp
  driver/rnn_driver.hpp
  driver/rnn_seq_driver.hpp
  driver/softmax_driver.hpp
  driver/tensorop_driver.hpp
  test/activation.cpp
  test/bn_3d_peract_test.cpp
  test/bn_3d_spatial_test.cpp
  test/bn_peract_test.cpp
  test/bn_spatial_nhwc_test.cpp
  test/bn_spatial_test.cpp
  test/cache.cpp
  test/cba_inference.cpp
  test/conv2d_bias.cpp
  test/conv3d_bias.cpp
  test/conv_common.hpp
  test/ctc.cpp
  test/driver.hpp
  test/dropout.cpp
  test/gpu_nchw_nhwc_transpose.cpp
  test/gpu_reference_kernel.cpp
  test/gru_common.hpp
  test/lstm_common.hpp
  test/main.cpp
  test/na_inference.cpp
  test/random.hpp
  test/reduce_test.cpp
  test/rnn_util.hpp
  test/rnn_vanilla_common.hpp
  test/tensor_holder.hpp
  test/tensor_reorder.cpp
Labels: urgency_blocker, quality, testing, TESTING_CI_PASSED, debugging

#2395 [CI][Jenkins] remove reboot, Vega, and Navi21 stages
  Dockerfile
  Jenkinsfile
Labels: urgency_normal

#2372 [pooling][backward][2D] Support wide pooling window. Fix FP16 correctness issues of Average pooling.
  driver/pool_driver.hpp
  src/kernels/MIOpenPoolingBwd.cl
  src/kernels/MIOpenPoolingBwdND.cl
  src/kernels/float_types.h
  src/ocl/pooling_ocl.cpp
  src/solver/batchnorm/forward_inference_ck.cpp
  src/solver/pooling/backwardNd.cpp
  src/solver/pooling/forwardNaive.cpp
  src/solver/pooling/forwardNd.cpp
  test/CMakeLists.txt
  test/pooling2d.cpp
  test/pooling_common.hpp
Labels: bug, enhancement, urgency_blocker, TESTING_CI_PASSED, correctness

#2398 [Doc] Update read the docs yaml configuration with build.os
  .readthedocs.yaml
Labels: documentation

#2320 Add support for layernorm primitive
  driver/driver.hpp
  driver/layernorm_driver.hpp
  driver/main.cpp
  driver/mloLayerNormHost.hpp
  driver/tensor_driver.hpp
  include/miopen/miopen.h
  src/CMakeLists.txt
  src/include/miopen/layernorm.hpp
  src/kernels/MIOpenLayerNorm.cpp
  src/layer_norm.cpp
  src/layernorm_api.cpp
  test/cpu_layernorm.hpp
  test/gtest/layernorm_test.cpp
  test/gtest/layernorm_test.hpp
Labels: enhancement, TESTING_CI_PASSED, IMPACTS_API, external_collaborator

#2404 [Windows] roctracer: disable on Windows (not supported)
  src/CMakeLists.txt
  src/include/miopen/logger.hpp
Labels: windows

#2411 [MI200] Refresh kdb using db_sync
  src/kernels/gfx90a.kdb.bz2
Labels: TESTING_CI_PASSED

#2412 [Jenkins][CI] clean workspace after each stage
  Jenkinsfile
Labels: urgency_high

#2420 Enable rebooting in CI stages for CI stages with GPU use
  Jenkinsfile
Labels: enhancement, value_high, urgency_blocker, complexity_low
