Repository ROCm/MIOpen, pull requests merged in 2023-04, with the labels that each got.

#2052 Fix local_work_size for col2im/im2col and layout transposing kernels
  src/ocl/utilocl.cpp
  test/CMakeLists.txt
Labels: workaround, urgency_high

#1889 Bg/lwpmiopen 99 : CK's Conv + bias + activation kernel integration into MIOpen
  driver/InputFlags.cpp
  driver/InputFlags.hpp
  driver/driver.hpp
  driver/random.hpp
  driver/tensor_driver.hpp
  src/CMakeLists.txt
  src/fusion.cpp
  src/include/miopen/fusion/solvers.hpp
  src/include/miopen/tensor.hpp
  src/solver.cpp
  src/solver/conv_ck_igemm_fwd_bias_activ_fused.cpp
  src/tensor.cpp
  test/gtest/cba.hpp
  test/gtest/cba_infer.cpp
  test/reduce_test.cpp
Labels: TESTING_CI_PASSED

#2065 Restructure find-db to match Find2.0 requirements
  driver/gemm_driver.hpp
  src/conv_algo_name.cpp
  src/db_record.cpp
  src/find_db.cpp
  src/gemm_v2.cpp
  src/hip/handlehip.cpp
  src/hipoc/hipoc_kernel.cpp
  src/include/miopen/conv_algo_name.hpp
  src/include/miopen/find_db.hpp
  src/include/miopen/finddb_kernel_cache_key.hpp
  src/include/miopen/fusion/solvers.hpp
  src/include/miopen/gemm_v2.hpp
  src/include/miopen/handle.hpp
  src/include/miopen/kernel_cache.hpp
  src/include/miopen/perf_field.hpp
  src/include/miopen/performance_config.hpp
  src/include/miopen/serializable.hpp
  src/kernel_cache.cpp
  src/nogpu/handle.cpp
  src/ocl/convolutionocl.cpp
  src/ocl/handleocl.cpp
  src/ocl/rnnocl.cpp
  src/ocl_kernel.cpp
  src/solver/conv_MP_bidirectional_winograd.cpp
  src/solver/conv_multipass_wino3x3WrW.cpp
  src/solver/gemm.cpp
  src/solver/gemm_bwd.cpp
  src/solver/gemm_wrw.cpp
  test/find_db.cpp
Labels: value_high, performance, quality, complexity_middle, urgency_high, TESTING_CI_PASSED

#2058 Enable docker building in the CI
  Jenkinsfile
Labels: value_high, complexity_middle, urgency_normal, TESTING_CI_PASSED

#2086 [LSTM] Perf fix for rnn_FP16
  src/ocl/rnnocl.cpp
Labels: bug, performance, urgency_high, TESTING_CI_PASSED

#2084 add applicability checks to fusion solver
  src/solver/conv_ck_igemm_fwd_bias_activ_fused.cpp
  test/gtest/bad_fusion_plan.cpp
Labels: bug, urgency_blocker, complexity_low, TESTING_CI_PASSED

#2090 [ROCm 5.6] Bump CK version to suppress gtest warning
  requirements.txt
Labels: value_low, non-miopen-bug, complexity_low

#2031 AI Based Heuristic for Kernel Parameter Prediction
  CMakeLists.txt
  include/miopen/config.h.in
  requirements.txt
  src/CMakeLists.txt
  src/conv/heuristic_model/tuning_heuristic.cpp
  src/include/miopen/conv/heuristic_model/tuning_heuristic.hpp
  src/include/miopen/fusion/solvers.hpp
  src/include/miopen/solver.hpp
  src/kernels/gfx908_ConvAsm1x1U_decoder.model
  src/kernels/gfx908_ConvAsm1x1U_encoder.model
  src/kernels/gfx908_ConvAsm1x1U_metadata.model
  src/solver/conv_asm_1x1u.cpp
  src/solver/conv_asm_1x1u_bias_activ_fused.cpp
  test/gtest/CMakeLists.txt
  test/gtest/kernel_tuning_net.cpp
Labels: value_high, urgency_high, TESTING_CI_PASSED

#2093 remove no-cache override
  Jenkinsfile
Labels: TESTING_CI_PASSED

#2100 Enabled static HIP igemm solver on MI300
  src/include/miopen/solver/implicitgemm_util.hpp
  src/solver/conv_hip_implicit_gemm_bwd_data_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_fwd_xdlops.cpp
Labels: urgency_blocker

#2103 [MI300][testing] Added base support & GPU detection. Enabled some custom tests.
  test/CMakeLists.txt
Labels: enhancement, urgency_blocker, testing

#2104 [API] Solver id getter from a solution and solver id to algo converter
  include/miopen/miopen.h
  src/api/find2_0_commons.cpp
  test/find_2_conv.cpp
Labels: enhancement, value_high, quality, complexity_low, urgency_normal, TESTING_CI_PASSED, IMPACTS_API

#2114 [W/A] Suppress safe-buffer-usage deprecated-declarations shadow-uncaptured-local with new compiler update
  CMakeLists.txt
  cmake/EnableCompilerWarnings.cmake
  requirements.txt
Labels: urgency_blocker

#2081 Deprecated some static solvers for new ASICs
  src/include/miopen/solver.hpp
  src/solver.cpp
  src/solver/conv_asm_1x1u.cpp
  src/solver/conv_asm_1x1u_stride2.cpp
  src/solver/conv_asm_3x3u.cpp
  src/solver/conv_asm_dir_BwdWrW1x1.cpp
  src/solver/conv_asm_dir_BwdWrW3x3.cpp
  src/solver/conv_ck_igemm_fwd_v6r1_dlops_nchw.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v1r1.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v1r1_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v4r1.cpp
  src/solver/conv_hip_implicit_gemm_bwd_v4r1_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r1.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops_padded_gemm.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r5_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops_padded_gemm.cpp
  src/solver/conv_ocl_dir2D11x11.cpp
  src/solver/conv_ocl_dir2D_bwdWrW_1x1.cpp
  src/solver/conv_ocl_dir2D_bwdWrW_2.cpp
  src/solver/conv_ocl_dir2D_bwdWrW_53.cpp
  src/solver/conv_ocl_dir2Dfwd.cpp
  src/solver/conv_ocl_dir2Dfwd1x1.cpp
  src/solver/conv_ocl_dir2Dfwdgen.cpp
  test/CMakeLists.txt
Labels: value_high, complexity_low, urgency_high, TESTING_CI_PASSED
