Repository ROCm/MIOpen, pull requests merged in 2023-02, with the labels that each got.

#1962 Bg/lwpmiopen 126 : Ignore running convbiasactive test on "gfx11" or "Navi3x"
  test/gtest/api_convbiasactiv.cpp
Labels: TESTING_CI_PASSED

#1972 [HOTFIX][CK] Do not call solver member functions in Invokers of ConvHipImplicitGemmFwd/BwdXdlops
  src/include/miopen/solver.hpp
  src/solver/conv_hip_implicit_gemm_bwd_data_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_fwd_xdlops.cpp
Labels: bug, urgency_blocker, TESTING_CI_PASSED

#1973 [tests] Add test for #1929
  test/gtest/CMakeLists.txt
  test/gtest/conv_api_strided_tensors.cpp
  test/gtest/platform.cpp
  test/gtest/platform.hpp
Labels: quality, testing, TESTING_CI_PASSED

#1951 [TensorDescriptor] Fix API description, add const for input data pointers
  include/miopen/miopen.h
  src/include/miopen/logger.hpp
  src/tensor_api.cpp
Labels: quality, TESTING_CI_PASSED, correctness

#1978 [W/A] disable group conv in asm igemm solver
  src/include/miopen/conv/asm_implicit_gemm.hpp
  src/solver/conv_asm_implicit_gemm_gtc_bwd_nhwc.cpp
  src/solver/conv_asm_implicit_gemm_gtc_fwd_nhwc.cpp
  src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp
  test/CMakeLists.txt
Labels: bug, urgency_blocker, workaround, TESTING_CI_PASSED

#1976 [gfx90a] Winograd multipass support
  src/kernels/xform_data_filter.inc
  src/kernels/xform_metadata.inc
  src/solver/conv_multipass_wino3x3WrW.cpp
  test/CMakeLists.txt
Labels: TESTING_CI_PASSED

#1966 [Fix issue #1956] use 64bit index in im2col3d.cl
  src/kernels/MIOpenCol2Im3d.cl
  src/ocl/utilocl.cpp
Labels: bug, urgency_blocker, TESTING_CI_PASSED

#1989 Guard Fusion API against unsuccessful Compile API Call.
  src/fusion.cpp
Labels: urgency_blocker

#1990 [ROCm 5.5] fix missing flag in conv_winoRxS_fused solver
  src/solver/conv_winoRxS_fused.cpp
Labels: urgency_blocker

#1965 [tests] Regression test for #1956. [debugging] Logging improvements.
  driver/conv_driver.hpp
  src/convolution.cpp
  test/CMakeLists.txt
  test/conv2d_bias.cpp
  test/conv3d_bias.cpp
  test/gpu_conv.hpp
Labels: enhancement, testing, urgency_normal, TESTING_CI_PASSED, debugging
