Repository ROCm/MIOpen, pull requests merged in 2023-08, with the labels that each got.

#2288 fix missing DetectRocm() in FindSolutionsImpl(), where options = nullptr
  src/problem.cpp
Labels: bug, urgency_blocker

#2293 [MI100] Remove Mlir entries from kdb
  src/kernels/gfx908.kdb.bz2
  src/kernels/gfx90a6e.kdb.bz2
Labels: urgency_blocker

#2175 [Tests] Add kernel fusion parameter change gtest.
  test/gtest/fusion_test.cpp
Labels: value_middle, quality, complexity_low, urgency_normal, TESTING_CI_PASSED

#2299 fix test after removal of mlir from gfx908 kdb
  test/gtest/cba_infer.cpp
Labels: urgency_blocker

#2298 [NFC][Tests] Use conv::ProblemDescription in test_sqlite_perfdb
  src/include/miopen/problem_description.hpp
  test/sqlite_perfdb.cpp
Labels: complexity_low, TESTING_CI_PASSED

#2297 [HOTFIX] Workaround for HIP iGEMM in buffer_load_max_length
  src/include/miopen/solver/implicitgemm_util.hpp
Labels: bug, value_high, workaround, urgency_high, TESTING_CI_PASSED

#2306 [HotFix] Disable HIP iGEMM V6R1 DLOps Kernels
  src/solver/conv_ck_igemm_fwd_v6r1_dlops_nchw.cpp
  test/CMakeLists.txt
Labels: bug, value_high, urgency_high, TESTING_CI_PASSED

#2287 Dont add librt to the MIOpen's interface
  src/CMakeLists.txt
Labels: quality, urgency_normal, TESTING_CI_PASSED

#2322 366827 - Disable file reorg backward compatibility support by default
  CMakeLists.txt
Labels: urgency_normal, TESTING_CI_PASSED, value_unknown

#2308 Reduce compile args to Im2Col kernel and add perf script
  src/kernels/MIOpenIm2d2Col.cl
  src/ocl/utilocl.cpp
  test/perf_models/resnet50_v1.5.sh
Labels: value_high, urgency_blocker, TESTING_CI_PASSED

#2286 3D group forward convolution solver
  src/CMakeLists.txt
  src/include/miopen/solver.hpp
  src/mlo_dir_conv.cpp
  src/solver.cpp
  src/solver/conv_hip_implicit_gemm_3d_grouped_fwd_xdlops.cpp
  test/gtest/group_conv3d_fwd.cpp
  test/gtest/group_conv3d_fwd.hpp
Labels: value_high, urgency_high, TESTING_CI_PASSED

#2328 [HotFix] Fix build issue after #2286
  test/gtest/group_conv3d_fwd.cpp
Labels: value_high, urgency_blocker

#2325 Fix ConvCkIgemmFwdV6r1DlopsNchw solver to reflect that its not dynamic
  src/include/miopen/solver.hpp
Labels: value_high, complexity_low, urgency_normal, TESTING_CI_PASSED

#2309 Remove target ids from kdb args
  src/kernels/gfx908.kdb.bz2
  src/kernels/gfx90a.kdb.bz2
Labels: TESTING_CI_PASSED

#2277 Dropout: make seed and states_num kernel arguments
  src/kernels/MIOpenDropout.cl
  src/ocl/dropoutocl.cpp
Labels: urgency_normal, TESTING_CI_PASSED

#2329 [MI250] Adding missing kernel objects
  src/kernels/gfx90a.kdb.bz2
Labels: TESTING_CI_PASSED

#2305 Post-merge fixups: Replace environment variable check with problem config check and reduce lambda capture for Invoker obj
  src/include/miopen/solver.hpp
  src/solver/conv_hip_implicit_gemm_fwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_grouped_fwd_xdlops.cpp
Labels: TESTING_CI_PASSED

#2335 [HotFix][CI] fix HIP tidy issue from #2277
  src/ocl/dropoutocl.cpp
Labels: urgency_blocker, TESTING_CI_PASSED

#2315 [NFC] Use conv::ProblemDescription for SQLitePerfDb
  src/include/miopen/mlo_internal.hpp
  src/include/miopen/problem_description.hpp
  src/sqlite_db.cpp
Labels: complexity_low, TESTING_CI_PASSED

#2265 Removed miopengemm and tensile
  CMakeLists.txt
  src/CMakeLists.txt
  src/gemm_v2.cpp
  src/include/miopen/fusion/solvers.hpp
  src/include/miopen/gemm_v2.hpp
  src/miopengemm.cpp
  src/ocl/rnnocl.cpp
  src/solver/conv_MP_bidirectional_winograd.cpp
  src/solver/conv_multipass_wino3x3WrW.cpp
  src/solver/gemm.cpp
  src/solver/gemm_bwd.cpp
  src/solver/gemm_wrw.cpp
Labels: urgency_normal, TESTING_CI_PASSED

#2318 Disable Op2dTensorLite kernel for the cases with wrong results
  src/ocl/tensorocl.cpp
Labels: bug, TESTING_CI_PASSED, correctness

#2307 HIP kernels may launch with non-uniform block size for backward compatibility
  CMakeLists.txt
  src/comgr.cpp
Labels: ON_HOLD, urgency_high, TESTING_CI_PASSED, value_unknown

#2330 Test to verify sync between various MIOpen DBs
  src/hip/handlehip.cpp
  src/include/miopen/find_solution.hpp
  src/include/miopen/readonlyramdb.hpp
  test/gtest/db_sync.cpp
Labels: TESTING_CI_PASSED

#2346 [bug fix]: add 2D constraint to Winograd solver
  src/solver/conv_wino_fury_RxS.cpp
Labels: bug, urgency_high, TESTING_CI_PASSED

#2339 Exclude squashed tensorop
  src/include/miopen/tensor_ops.hpp
  src/kernels/MIOpenTensorKernelsHip.cpp
  src/ocl/rnnocl.cpp
  src/ocl/tensorocl.cpp
  test/tensor_ops.cpp
Labels: TESTING_CI_PASSED

#2290 [tests] convert test_conv_trans to gTest
  test/CMakeLists.txt
  test/gtest/conv_trans.cpp
Labels: TESTING_CI_PASSED

#2343 RNN padding and SeqTensorDescriptor
  driver/driver.hpp
  driver/gru_verify_gemm.hpp
  driver/lstm_verify_gemm.hpp
  driver/main.cpp
  driver/rnn_driver.hpp
  driver/rnn_seq_driver.hpp
  driver/rnn_verify_gemm.hpp
  include/miopen/miopen.h
  src/CMakeLists.txt
  src/include/miopen/rnn.hpp
  src/include/miopen/rnn_util.hpp
  src/include/miopen/seq_tensor.hpp
  src/include/miopen/tensor_ops.hpp
  src/ocl/rnnocl.cpp
  src/ocl/tensorocl.cpp
  src/rnn.cpp
  src/rnn/Solutions/rnn_transformer.cpp
  src/rnn/rnn_util.cpp
  src/rnn_api.cpp
  src/seq_tensor.cpp
  src/tensor_api.cpp
  test/w_supertensor.cpp
Labels: value_high, urgency_blocker, testing, complexity_high, urgency_high, TESTING_CI_PASSED, IMPACTS_API
