Repository ROCm/MIOpen, pull requests merged in 2023-10, with the labels that each got.

#2414 [Bug Fixes] miopen_rocblas_gemm_ex3 call - invoker cache extra elements - conv direct naive input cast
  src/gemm_v2.cpp
  src/invoker_cache.cpp
  src/solver/conv_direct_naive_conv.cpp
Labels: bug, urgency_blocker

#2422 Disabling smoke stages for CI branch runs
  Jenkinsfile
Labels: enhancement, ON_HOLD, complexity_low, urgency_high

#2432 disable solver ConvHipImplicitGemm3DGroupWrwXdlops on Vega10
  src/solver/conv_hip_implicit_gemm_3d_grouped_wrw_xdlops.cpp
Labels: complexity_low

#2435 [Bug Fix] Compilation fix for -DMIOPEN_USE_ROCBLAS=Off
  src/hip/handlehip.cpp
Labels: bug, urgency_blocker

#2386 bg/LWPMIOPEN-192: Integrate CK's batch norm forward training into non-tunable MIOpen solver
  src/CMakeLists.txt
  src/include/miopen/batchnorm/solvers.hpp
  src/ocl/batchnormocl.cpp
  src/solver.cpp
  src/solver/batchnorm/forward_training_ck.cpp
  test/fusionHost.hpp
  test/gtest/bn.hpp
  test/gtest/bn_fwd_train.cpp
  test/gtest/bn_test_data.hpp
  test/gtest/test_operations.hpp
Labels: value_high, urgency_high, TESTING_CI_PASSED

#2334 Reference kernel for 3D convolution for non-packed tensors
  src/CMakeLists.txt
  src/hip/hip_build_utils.cpp
  src/include/miopen/hipoc_kernel.hpp
  src/include/miopen/solver/conv_direct_naive_conv.hpp
  src/kernels/gpu_reference_kernel/fp8_kern_types.h
  src/kernels/gpu_reference_kernel/naive_conv.cpp
  src/kernels/stride_array.hpp
  src/solver/conv_direct_naive_conv.cpp
  src/solver/conv_direct_naive_conv_bwd.cpp
  src/solver/conv_direct_naive_conv_fwd.cpp
  src/solver/conv_direct_naive_conv_wrw.cpp
  test/gpu_reference_kernel.cpp
  test/gtest/conv3d_test_case.hpp
  test/gtest/group_conv3d_bwd.cpp
  test/gtest/group_conv3d_bwd.hpp
  test/gtest/group_conv3d_fwd.cpp
  test/gtest/group_conv3d_fwd.hpp
  test/gtest/group_conv3d_wrw.cpp
  test/gtest/group_conv3d_wrw.hpp
  test/gtest/group_solver.hpp
Labels: performance, urgency_blocker, complexity_high, TESTING_CI_PASSED

#2436 Fix weight tensor intialization to replace old PR1950
  test/gtest/solver_f8.hpp
Labels: bug, urgency_high, TESTING_CI_PASSED

#2413 Add typecast to config key
  src/activ/problem_description.cpp
  src/conv/problem_description.cpp
  src/include/miopen/activ/problem_description.hpp
  src/include/miopen/conv/problem_description.hpp
  src/include/miopen/pooling/problem_description.hpp
  src/include/miopen/problem_description_base.hpp
  src/pooling/problem_description.cpp
Labels: bug, urgency_blocker

#2443 [Bugfix] Add cast swapping for swapped gemm inputs.
  src/gemm_v2.cpp
Labels: bug, urgency_blocker, TESTING_CI_PASSED

#2446 [Bugfix] Kernel name fix, compilation err fix
  src/kernels/gpu_reference_kernel/fp8_kern_types.h
  src/kernels/gpu_reference_kernel/fp8_naive_conv.cpp
Labels: bug, urgency_blocker, TESTING_CI_PASSED

#2441 Remove INT8x4 support
  docs/datatypes.md
  include/miopen/miopen.h
  src/check_numerics.cpp
  src/convolution.cpp
  src/gemm_v2.cpp
  src/hip/batched_transpose_sol.cpp
  src/include/miopen/datatype.hpp
  src/include/miopen/tensor.hpp
  src/include/miopen/visit_float.hpp
  src/kernels/MIOpenIm2d2Col.cl
  src/kernels/MIOpenIm3d2Col.cl
  src/kernels/MIOpenSubTensorOpWithScalarKernel.cl
  src/kernels/MIOpenSubTensorOpWithSubTensorKernel.cl
  src/kernels/MIOpenSubTensorOpWithTransformKernel.cl
  src/kernels/MIOpenUtilKernels4.cl
  src/ocl/convolutionocl.cpp
  src/ocl/tensorocl.cpp
  src/ocl/utilocl.cpp
  src/pooling_api.cpp
  src/reducetensor.cpp
  src/reducetensor_api.cpp
  src/solver/batchnorm/forward_inference_ck.cpp
  src/solver/conv_ck_igemm_fwd_bias_activ_fused.cpp
  src/solver/conv_direct_naive_conv.cpp
  src/solver/conv_hip_implicit_gemm_3d_grouped_bwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_3d_grouped_fwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_3d_grouped_wrw_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_bwd_data_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_fwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_grouped_fwd_xdlops.cpp
  src/solver/gemm.cpp
  src/solver/mlir_common.cpp
  src/tensor.cpp
  test/conv_common.hpp
  test/driver.hpp
  test/gpu_reference_kernel.cpp
  test/gtest/conv_embed_db.cpp
  test/gtest/conv_hip_igemm_xdlops.cpp
  test/gtest/conv_igemm_dynamic.cpp
  test/gtest/conv_igemm_mlir.cpp
  test/gtest/conv_igemm_mlir_xdlops.cpp
  test/gtest/conv_trans.cpp
  test/gtest/db_sync.cpp
  test/tensor_holder.hpp
  test/tensor_transform.cpp
Labels: urgency_blocker, TESTING_CI_PASSED

#2418 3D forward convolution solver with non-packed input tensors
  src/include/miopen/solver/ck_utility_common.hpp
  src/solver/conv_direct_naive_conv_bwd.cpp
  src/solver/conv_direct_naive_conv_fwd.cpp
  src/solver/conv_direct_naive_conv_wrw.cpp
  src/solver/conv_hip_implicit_gemm_3d_grouped_bwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_3d_grouped_fwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_3d_grouped_wrw_xdlops.cpp
  test/gpu_reference_kernel.cpp
  test/gtest/conv_api_strided_tensors.cpp
  test/gtest/nonpack_conv3d_fwd.cpp
  test/gtest/nonpack_conv3d_fwd.hpp
Labels: urgency_blocker

#2439 Bump CK comit for ROCm 6.0
  requirements.txt
Labels: urgency_blocker

#2437 Enabling Nightly Runs for Nightly Branch w/ build_smoke_(fp32 + aux1 + fp16_bf16_int8)
  Jenkinsfile
Labels: enhancement, urgency_blocker, testing, complexity_low, TESTING_CI_PASSED

#2438 remove ck solver's strides restriction
  src/include/miopen/solver/implicitgemm_ck_util.hpp
  src/solver/batchnorm/backward_ck.cpp
  src/solver/batchnorm/forward_training_ck.cpp
Labels: TESTING_CI_PASSED

#2400 [tests] remove std::rand usage
  src/solver/conv_ocl_dir2Dfwd_exhaustive_search.cpp
  test/gtest/mt_queue.cpp
Labels: testing, TESTING_CI_PASSED

#2450 [tests] test_tensor_api enhancement
  test/gtest/tensor_api.cpp
Labels: enhancement, quality, TESTING_CI_PASSED

#2454 [MI100][MI200] Kernel db updates
  src/kernels/gfx908.kdb.bz2
  src/kernels/gfx90a.kdb.bz2
Labels: performance, tuning

#2458 bg/ck_gfx_white_list : start using ck_utility::is_ck_whitelist to restrict
  src/include/miopen/solver/ck_utility_common.hpp
  src/solver/batchnorm/backward_ck.cpp
  src/solver/batchnorm/forward_inference_ck.cpp
  src/solver/batchnorm/forward_training_ck.cpp
  src/solver/conv_hip_implicit_gemm_3d_grouped_bwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_3d_grouped_fwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_3d_grouped_wrw_xdlops.cpp
  test/gtest/bn.hpp
Labels: urgency_blocker, testing

#2457 Rename function and return invalid solution instead of throwing an error
  src/include/miopen/solver/implicitgemm_ck_util.hpp
  src/solver/conv_hip_implicit_gemm_3d_grouped_bwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_3d_grouped_fwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_3d_grouped_wrw_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_bwd_data_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_fwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_grouped_fwd_xdlops.cpp
Labels: complexity_low, TESTING_CI_PASSED

#2460 Fix the return code on the workspace API
  src/convolution_api.cpp
Labels: value_high, urgency_blocker, complexity_low

#2425 regression: do not use file system symbolic/hard links
  driver/CMakeLists.txt
  driver/driver.hpp
  speedtests/CMakeLists.txt
  src/include/miopen/hip_f8_impl.hpp
  src/include/miopen/hip_float8.hpp
  test/CMakeLists.txt
  test/cpu_conv.hpp
  test/gtest/CMakeLists.txt
  test/gtest/solver_bwd.hpp
  test/gtest/solver_fwd.hpp
  test/gtest/solver_wrw.hpp
  test/tensor_holder.hpp
  test/verify.hpp
Labels: bug, urgency_blocker, windows

#2465 [Bugfix] Layernorm Test: add missing hip_runtime.h include
  src/kernels/MIOpenLayerNorm.cpp
Labels: bug, urgency_high, TESTING_CI_PASSED

#2364 comgr: fix compiling with HIP SDK 5.5+ on Windows
  src/comgr.cpp
Labels: TESTING_CI_PASSED, windows

#2361 cmake: add option for building shared libraries
  CMakeLists.txt
Labels: windows

#2359 fix sequences for Windows
  speedtests/sequences.cpp
  src/include/miopen/sequences.hpp
Labels: windows

#2449 [tests] tensor_holder enhancement
  driver/conv_driver.hpp
  src/include/miopen/tensor.hpp
  src/tensor.cpp
  test/conv_common.hpp
  test/driver.hpp
  test/fusionHost.hpp
  test/gtest/bn_test_data.hpp
  test/gtest/conv_test_base.hpp
  test/gtest/fusion_test.cpp
  test/gtest/group_conv3d_bwd.hpp
  test/gtest/group_conv3d_fwd.hpp
  test/gtest/group_conv3d_wrw.hpp
  test/gtest/group_solver.hpp
  test/gtest/kernel_tuning_net.cpp
  test/gtest/nonpack_conv3d_fwd.hpp
  test/gtest/tuna_net.cpp
  test/reduce_test.cpp
  test/tensor_holder.hpp
Labels: enhancement, quality, TESTING_CI_PASSED

#2356 cmake: bump up the minimum required version to 3.15
  CMakeLists.txt
  driver/CMakeLists.txt
  utils/CMakeLists.txt
Labels: windows

#2473 [HotFix] Missing MIO_BN_GFX110X building kernels
  src/solver/batchnorm/backward_per_activation_fused.cpp
  src/solver/batchnorm/forward_per_activation_fused.cpp
Labels: bug, urgency_blocker, TESTING_CI_PASSED

#2421 TunaNet Integration: MI250x
  src/conv/heuristics/ai_heuristics.cpp
  src/include/miopen/problem_description.hpp
  src/kernels/gfx90a.tn.model
  src/kernels/gfx90a_metadata.tn.model
Labels: enhancement, value_high, performance, TESTING_CI_PASSED

#2397 [tests] remove direct std::random_device usage.
  test/bn_3d_peract_test.cpp
  test/bn_3d_spatial_test.cpp
  test/bn_peract_test.cpp
  test/bn_spatial_test.cpp
  test/cba_inference.cpp
  test/gru_common.hpp
  test/gtest/bn.hpp
  test/gtest/bn_test_data.hpp
  test/gtest/group_conv3d_bwd.hpp
  test/gtest/group_conv3d_fwd.hpp
  test/gtest/group_conv3d_wrw.hpp
  test/gtest/group_solver.hpp
  test/gtest/log.cpp
  test/gtest/na.hpp
  test/lstm_common.hpp
  test/na_inference.cpp
  test/random.hpp
  test/rnn_vanilla_common.hpp
Labels: testing, TESTING_CI_PASSED

#2479 [Dependency][CK] Bump CK Commit Hash
  requirements.txt
Labels: urgency_normal, TESTING_CI_PASSED, dependencies

#2363 half: fix compiling with HIP SDK 5.7+ on Windows
  driver/driver.hpp
  driver/reduce_driver.hpp
  src/composable_kernel/host/driver_offline/src/conv_bwd_driver_offline.cpp
  src/composable_kernel/host/driver_offline/src/conv_fwd_driver_offline.cpp
  src/fusion.cpp
  src/gemm_v2.cpp
  src/include/miopen/op_kernel_args.hpp
  src/include/miopen/reduce_common.hpp
  src/include/miopen/visit_float.hpp
  src/solver/conv_asm_1x1u_bias_activ_fused.cpp
  src/solver/conv_ocl_dir2Dfwd_exhaustive_search.cpp
  test/cpu_reduce_util.hpp
  test/driver.hpp
  test/gpu_reference_kernel.cpp
  test/serialize.hpp
  test/tensor_holder.hpp
Labels: windows

#2448 Added an API function for find 2.0 activation problem creation.
  include/miopen/miopen.h
  src/activ.cpp
  src/activ_api.cpp
  src/api/find2_0_commons.cpp
  src/include/miopen/activ.hpp
  src/include/miopen/problem.hpp
  src/problem.cpp
  src/solution.cpp
Labels: value_high, complexity_low, urgency_high, TESTING_CI_PASSED, IMPACTS_API

#2348 cmake: generate export header function
  cmake/ExportHeader.cmake
  driver/conv_driver.hpp
  include/miopen/miopen.h
  src/CMakeLists.txt
  src/convolution_api.cpp
  src/tensor.cpp
  test/gtest/log.hpp
Labels: TESTING_CI_PASSED, windows

#1652 [tests] Refactor cache test to gTest
  test/gtest/CMakeLists.txt
  test/gtest/cache.cpp
Labels: enhancement, value_high, urgency_normal, TESTING_CI_PASSED

#2487 Fix transposed convolutions
  driver/conv_driver.hpp
  src/convolution_api.cpp
  src/driver_arguments.cpp
  src/include/miopen/conv/problem_description.hpp
  src/ocl/convolutionocl.cpp
  test/CMakeLists.txt
Labels: bug, urgency_blocker, TESTING_CI_PASSED

#2380 cmake: enable smoke testing on Windows
  test/CMakeLists.txt
Labels: TESTING_CI_PASSED, windows

#2401 write 3d ncdhw to ndhwc test that uses 2d gpu kernel
  test/gpu_nchw_nhwc_transpose.cpp
Labels: TESTING_CI_PASSED

#2490 [tests] Removed support for OCL backend. Do not print rocminfo output unless GPU detection failed. Some cleanup.
  test/CMakeLists.txt
Labels: quality, testing, urgency_normal, TESTING_CI_PASSED

#2350 cmake: fix cmake/googletest.cmake on Windows
  cmake/googletest.cmake
  cmake/gtest.cmake
  test/gtest/CMakeLists.txt
Labels: TESTING_CI_PASSED, windows

#2355 cmake: use imported target for threads library instead of variable
  CMakeLists.txt
  driver/CMakeLists.txt
  src/CMakeLists.txt
  test/CMakeLists.txt
Labels: TESTING_CI_PASSED, windows
