Repository ROCm/MIOpen, pull requests merged in 2023-01, with the labels that each got.

#1917 [API] API call to query spatial dimension of ConvolutionDescriptor
  include/miopen/miopen.h
  src/convolution_api.cpp
  test/gtest/conv_api.cpp
Labels: TESTING_CI_PASSED

#1922 [Ubuntu 22.04] Add include file for libstdc++-12
  src/include/miopen/sequences.hpp
Labels: TESTING_CI_PASSED

#1920 [GFX11] CK new target additional file changes
  src/composable_kernel/composable_kernel/include/utility/config.hpp
  src/include/miopen/solver/ck_utility_common.hpp
Labels: TESTING_CI_PASSED

#1925 [GFX11] Appropriate GFX10 workarounds and fixes reused for the new target. [GFX11][tests] Tests enabled.
  src/comgr.cpp
  src/reducetensor.cpp
  src/solver/conv_ocl_dir2D_bwdWrW_1x1.cpp
  src/solver/conv_ocl_dir2Dfwd1x1.cpp
  test/CMakeLists.txt
Labels: enhancement, testing, workaround, urgency_high

#1905 [issue 1902] Correct NCHWc solver config validation check restrictions.
  src/solver/conv_asm_implicit_gemm_gtc_fwd_nchwc.cpp
Labels: bug, urgency_blocker, TESTING_CI_PASSED, correctness

#1890 [NFC][Solvers] Rename base class for activation, batchnorm and pooling solvers
  src/include/miopen/activ/solvers.hpp
  src/include/miopen/batchnorm/solvers.hpp
  src/include/miopen/pooling/solvers.hpp
Labels: enhancement, quality, complexity_low, TESTING_CI_PASSED

#1893 [Fix][tests] Use MIOPEN_USER_DB_PATH to prevent potential performance degradation after tests.
  test/CMakeLists.txt
  test/gtest/CMakeLists.txt
Labels: performance, urgency_blocker, testing, TESTING_CI_PASSED

#1895 Only create kdb packages when kdb files are present
  CMakeLists.txt
Labels: quality, TESTING_CI_PASSED

#1929 [SWDEV-366865] Add check for convolution API that all tensors are packed
  src/ocl/convolutionocl.cpp
Labels: bug, quality, complexity_low, urgency_high, TESTING_CI_PASSED

#1915 [tests] Enable small MLIR test on Navi21. Mark test_conv_ck_igemm_fwd_v6r1_dlops_nchw as LONG test.
  test/CMakeLists.txt
Labels: quality, testing, urgency_low, TESTING_CI_PASSED

#1933 [HOTFIX][MI200][FP16] Disabled ConvHipImplicitGemmBwdXdlops when FP16_ALT is requried
  src/solver/conv_hip_implicit_gemm_bwd_data_xdlops.cpp
Labels: bug, urgency_blocker, TESTING_CI_PASSED, correctness

#1907 Fix the "deterministic" attribute in ConvHipImplicitGemmFwd/BwdXdlops
  src/solver/conv_hip_implicit_gemm_bwd_data_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_fwd_xdlops.cpp
Labels: bug, urgency_normal, TESTING_CI_PASSED, correctness

#1935 [SWDEV-375617] Fix 3d convolution Host API bug
  driver/tensor_driver.hpp
  test/CMakeLists.txt
Labels: bug, urgency_blocker, TESTING_CI_PASSED

#1936 Enable ConvHipImplicitGemmFwdXdlops for MI200 and hotfix for fp16_alt issue
  src/solver/conv_hip_implicit_gemm_fwd_xdlops.cpp
  test/CMakeLists.txt
Labels: bug, urgency_blocker, TESTING_CI_PASSED, correctness

#1939 [NFC] Bumping MLIR commit to 5.5.0 release tag
  Jenkinsfile
  requirements.txt
Labels: TESTING_CI_PASSED

#1928 [TensorDescriptor] Add input parameters validation
  include/miopen/miopen.h
  src/batch_norm.cpp
  src/convolution_api.cpp
  src/include/miopen/tensor.hpp
  src/include/miopen/tensor_ops.hpp
  src/ocl/ctcocl.cpp
  src/ocl/rnnocl.cpp
  src/ocl/tensorocl.cpp
  src/rnn.cpp
  src/tensor.cpp
  src/tensor_api.cpp
  test/gru_common.hpp
  test/lstm_common.hpp
  test/pooling_common.hpp
  test/rnn_vanilla_common.hpp
  test/solver.cpp
  test/tensor_cast.cpp
  test/tensor_copy.cpp
  test/tensor_holder.hpp
  test/tensor_scale.cpp
  test/tensor_set.cpp
  test/tensor_transform.cpp
Labels: enhancement, urgency_blocker, quality, TESTING_CI_PASSED

#1940 [NFC] Add missing header guards.
  src/include/miopen/tensor_extra.hpp
  src/kernels/math_ops.h
  src/kernels/pooling_functions.h
  src/kernels/precalc_xorwow_skipahead_matrices_kernel.h
  src/kernels/precalc_xorwow_skipahead_sequence_matrices_kernel.h
  src/kernels/reduction_functions.h
  test/args.hpp
  test/driver.hpp
Labels: TESTING_CI_PASSED

#1943 [NFC] Comgr include header reorg
  src/comgr.cpp
Labels: value_middle, quality, complexity_low, urgency_low, TESTING_CI_PASSED

#1942 [NFC] Remove -Wno-deprecated warning suppression
  CMakeLists.txt
  cmake/EnableCompilerWarnings.cmake
  speedtests/sequences.cpp
  src/include/miopen/sequences.hpp
  src/ocl/handleocl.cpp
Labels: quality, TESTING_CI_PASSED

#1948 [HOTFIX] Fix COMGR build error with ROCm 4.4.x...5.2.x due to an issue in #1943
  src/comgr.cpp
Labels: urgency_blocker

#1947 [GFX11] Add support for gfx1101 target ID
  src/composable_kernel/composable_kernel/include/utility/config.hpp
  src/include/miopen/solver/ck_utility_common.hpp
  test/CMakeLists.txt
  test/handle_test.cpp
Labels: complexity_low, urgency_high

#1898 [tests] Added smoke tests for conv solvers (ConvAsmImplicitGemmGTCDynamic*Xdlops and more). Added MIOPEN_DEBUG_TUNING_ITERATIONS_MAX. Some improvements and refactorings.
  src/CMakeLists.txt
  src/generic_search.cpp
  src/include/miopen/generic_search.hpp
  src/solver/conv_asm_1x1u_stride2.cpp
  src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp
  test/CMakeLists.txt
Labels: testing, urgency_high, TESTING_CI_PASSED

#1953 [HotFix] Fix build warnings introduced by #1875
  src/fusion.cpp
  src/include/miopen/fusion_plan.hpp
  test/gtest/na_infer.cpp
Labels: urgency_blocker, complexity_low, TESTING_CI_PASSED
