Repository ROCm/MIOpen, pull requests merged in 2023-03, with the labels that each got.

#1839 [Find 2.0] Added support for attaching pre-allocated buffers to find options
  addkernels/addkernels.cpp
  include/miopen/miopen.h
  src/api/find2_0_commons.cpp
  src/batchnorm/problem_description.cpp
  src/conv/invokers/gcn_asm_1x1u_us.cpp
  src/include/miopen/handle.hpp
  src/include/miopen/oclkernel.hpp
  src/include/miopen/problem.hpp
  src/include/miopen/search_options.hpp
  src/include/miopen/sequences.hpp
  src/include/miopen/stringutils.hpp
  src/include/miopen/tensor.hpp
  src/include/miopen/tensor_ops.hpp
  src/problem.cpp
  test/conv_common.hpp
  test/find_2_conv.cpp
Labels: enhancement, complexity_low, TESTING_CI_PASSED, IMPACTS_API

#1906 [tests] Added smoke tests for conv solvers (ConvAsmBwdWrW1x1 and more). Some fixes.
  CMakeLists.txt
  src/solver/conv_hip_implicit_gemm_bwd_v1r1.cpp
  test/CMakeLists.txt
Labels: testing, urgency_high, TESTING_CI_PASSED

#1983 [Driver] BN verification fixes/improvements
  driver/bn_driver.hpp
  driver/main.cpp
Labels: enhancement, testing, urgency_normal, TESTING_CI_PASSED, debugging

#1998 [SWDEV-385188] Guard HIP tests to enable building on OpenCL
  test/gtest/api_convbiasactiv.cpp
  test/gtest/log_test.cpp
  test/gtest/log_test_neg.cpp
Labels: bug, value_middle, testing, urgency_normal, TESTING_CI_PASSED

#2040 CMakeList fix for backward compatibility
  CMakeLists.txt
Labels: bug

#2043 [HOTFIX][tests] WORKAROUND_ISSUE_2038: Disable validation of FP16 and BF16 in the smoke test of ConvHipImplicitGemmV4R1Fwd
  test/CMakeLists.txt
Labels: urgency_blocker, workaround, TESTING_CI_PASSED, correctness

#2035 [tests] Removed W/A for issue 936 from jenkinsfile
  Jenkinsfile
Labels: testing, TESTING_CI_PASSED

#2011 Fix for Issue 1992
  src/solver/conv_asm_implicit_gemm_gtc_fwd.cpp
  test/CMakeLists.txt
Labels: TESTING_CI_PASSED

#1957 [ROCm 5.6] bump CK commit hash, fix a few deprecated, cmake, and Ubuntu 22.04 related warnings
  CMakeLists.txt
  Dockerfile
  cmake/googletest.cmake
  requirements.txt
  src/binary_cache.cpp
  src/include/miopen/db_record.hpp
  src/include/miopen/execution_context.hpp
  src/include/miopen/generic_search.hpp
  src/include/miopen/mlo_internal.hpp
  src/include/miopen/problem_description.hpp
  src/include/miopen/solver/implicitgemm_util.hpp
  src/include/miopen/solver/problem_description_interpreter.hpp
  src/include/miopen/sqlite_db.hpp
  src/include/miopen/write_file.hpp
  src/kernel_warnings.cpp
  src/load_file.cpp
  src/lrn_api.cpp
  src/md5.cpp
  src/solver/conv_asm_dir_BwdWrW3x3.cpp
  test/cache.cpp
  test/custom_allocator.cpp
  test/ford.hpp
Labels: value_middle, urgency_blocker

#2034 LSTM multi-stream solver
  src/hip/handlehip.cpp
  src/include/miopen/handle.hpp
  src/include/miopen/nogpu/handle_impl.hpp
  src/include/miopen/rnn.hpp
  src/include/miopen/rnn_util.hpp
  src/nogpu/handle.cpp
  src/ocl/handleocl.cpp
  src/ocl/rnnocl.cpp
  src/ocl/tensorocl.cpp
  src/rnn.cpp
Labels: performance, TESTING_CI_PASSED

#2042 Faster batchsize split
  src/include/miopen/conv/asm_implicit_gemm.hpp
Labels: value_high, performance, quality, TESTING_CI_PASSED

#2057 add parenthesis to node name labels
  Jenkinsfile
Labels: value_high, complexity_low, urgency_high, TESTING_CI_PASSED
