Repository ROCm/MIOpen, pull requests merged in 2024-04, with the labels that each got.

#2810 [Tests] Convert three regression tests to gTests
  test/CMakeLists.txt
  test/gtest/regression_half_mi200.cpp
  test/gtest/regression_half_vega.cpp
  test/gtest/regression_issue_2012.cpp
Labels: TESTING_CI_PASSED, GTest

#2807 Use standard C++ streams to access files
  src/include/miopen/write_file.hpp
Labels: windows

#2819 Forward MHA find2.0 interface and implementation
  include/miopen/miopen.h
  src/CMakeLists.txt
  src/api/find2_0_commons.cpp
  src/include/miopen/mha/invoke_params.hpp
  src/include/miopen/mha/mha.hpp
  src/include/miopen/mha/mha_descriptor.hpp
  src/include/miopen/mha/problem_description.hpp
  src/include/miopen/mha/solvers.hpp
  src/include/miopen/problem.hpp
  src/include/miopen/solution.hpp
  src/include/miopen/solver_id.hpp
  src/kernels/MIOpenSoftmaxAttn.cpp
  src/kernels/miopen_rocrand.hpp
  src/mha/mha_descriptor.cpp
  src/mha/problem_description.cpp
  src/problem.cpp
  src/solution.cpp
  src/solver.cpp
  src/solver/mha/mha_solver.cpp
  src/solver/softmax/attn_softmax.cpp
Labels: value_high, urgency_blocker, complexity_high, TESTING_CI_PASSED, IMPACTS_API

#2854 [MHA] Implement MIOPEN_BACKEND_POINTWISE_DESCRIPTOR
  include/miopen/miopen.h
  src/CMakeLists.txt
  src/graphapi/graphapi.cpp
  src/graphapi/pointwise.cpp
  src/include/miopen/graphapi/pointwise.hpp
  test/gtest/graphapi_pointwise.cpp
Labels: enhancement, value_high, urgency_blocker, TESTING_CI_PASSED

#2826 Find 2.0 scalar run-time parameters
  include/miopen/miopen.h
  src/api/find2_0_commons.cpp
  src/problem.cpp
Labels: enhancement, IMPACTS_API

#2870 Skip fusions tests when xnack is enabled
  test/conv_common.hpp
  test/gtest/CMakeLists.txt
  test/gtest/cba_find2_infer.cpp
  test/gtest/conv_common.cpp
  test/gtest/conv_igemm_dynamic.cpp
  test/gtest/conv_igemm_dynamic_dlops.cpp
  test/gtest/fusion_test.cpp
  test/gtest/smoke_solver_ConvAsmImplicitGemmGTCDynamicFwdDlopsNCHWC.cpp
  test/gtest/smoke_solver_ConvAsmImplicitGemmGTCDynamicXdlops.cpp
  test/gtest/smoke_solver_ConvAsmImplicitGemmGTCDynamicXdlopsNHWC_bf16.cpp
  test/gtest/smoke_solver_ConvAsmImplicitGemmGTCDynamicXdlopsNHWC_fp32_fp16.cpp
  test/gtest/smoke_solver_ConvAsmImplicitGemmV4R1Dynamic.cpp
  test/gtest/smoke_solver_ConvAsm_5x10_7x7.cpp
  test/gtest/smoke_solver_ConvBinWinograd3x3U.cpp
  test/gtest/smoke_solver_ConvBinWinogradRxS_fp16.cpp
  test/gtest/smoke_solver_ConvBinWinogradRxS_fp32.cpp
  test/gtest/smoke_solver_ConvBinWinogradRxSf2x3.cpp
  test/gtest/smoke_solver_ConvBinWinogradRxSf2x3g1.cpp
  test/gtest/smoke_solver_ConvBinWinogradRxSf2x3g1_3x2_f16.cpp
  test/gtest/smoke_solver_ConvBinWinogradRxSf2x3g1_3x2_f32.cpp
  test/gtest/smoke_solver_ConvBinWinogradRxSf3x2.cpp
  test/gtest/smoke_solver_ConvCkIgemmFwdV6r1DlopsNchw.cpp
  test/gtest/smoke_solver_ConvHipImplicitGemmBwdDataV1R1.cpp
  test/gtest/smoke_solver_ConvHipImplicitGemmBwdDataV1R1Xdlops.cpp
  test/gtest/smoke_solver_ConvHipImplicitGemmBwdDataV4R1.cpp
  test/gtest/smoke_solver_ConvHipImplicitGemmDataV4RxXdlops.cpp
  test/gtest/smoke_solver_ConvHipImplicitGemmV4R1Fwd_fp16_bf16.cpp
  test/gtest/smoke_solver_ConvHipImplicitGemmV4R1Fwd_fp32.cpp
  test/gtest/smoke_solver_ConvHipImplicitGemmV4R1WrW.cpp
  test/gtest/smoke_solver_ConvHipImplicitGemmV4R4.cpp
  test/gtest/smoke_solver_ConvWinogradFuryRxSf2x3_f16.cpp
  test/gtest/smoke_solver_convasm.cpp
  test/gtest/smoke_solver_convasm1x1u.cpp
  test/gtest/smoke_solver_convasmbwdwrw.cpp
  test/gtest/smoke_solver_convasmbwdwrw3x3_fp16.cpp
  test/gtest/smoke_solver_convasmbwdwrw3x3_fp32.cpp
Labels: value_high, urgency_blocker, complexity_middle

#2862 [MHA] Implement MIOPEN_BACKEND_REDUCTION_DESCRIPTOR
  src/CMakeLists.txt
  src/graphapi/graphapi.cpp
  src/graphapi/reduction.cpp
  src/include/miopen/graphapi/reduction.hpp
  test/gtest/graphapi_reduction.cpp
Labels: enhancement, value_high, urgency_blocker, TESTING_CI_PASSED

#2874 [MHA] Implement MIOPEN_BACKEND_OPERATION_RNG_DESCRIPTOR C API Class
  src/graphapi/graphapi.cpp
  src/graphapi/rng.cpp
  src/graphapi/tensor.cpp
  src/include/miopen/graphapi/rng.hpp
  src/include/miopen/graphapi/tensor.hpp
  test/gtest/graphapi_gtest_common.hpp
  test/gtest/graphapi_operation_rng.cpp
Labels: enhancement, value_high, urgency_normal, TESTING_CI_PASSED

#2563 Cpu multi head attention
  src/CMakeLists.txt
  test/gtest/attention_golden.hpp
  test/gtest/cpu_multi_head_attention.cpp
  test/gtest/cpu_multi_head_attention.hpp
  test/gtest/mha_helper.hpp
  test/tensor_util.hpp
Labels: value_high, urgency_high, TESTING_CI_PASSED, GTest

#2872 MHA Forward Find 2.0 Wrapper Test
  src/include/miopen/mha/invoke_params.hpp
  src/solution.cpp
  test/gtest/mha_find20.cpp
Labels: urgency_high, TESTING_CI_PASSED

#2858 [MHA] Implement MIOPEN_BACKEND_VARIANT_PACK_DESCRIPTOR API Class
  src/CMakeLists.txt
  src/graphapi/graphapi.cpp
  src/graphapi/variant_pack.cpp
  src/include/miopen/graphapi/variant_pack.hpp
  test/gtest/graphapi_variant_pack.cpp
Labels: enhancement, value_high, urgency_normal, TESTING_CI_PASSED

#2856 [driver][NFC] Modular: Split MIOpenDriver to improve build time
  driver/CBAInferFusion_driver.hpp
  driver/CMakeLists.txt
  driver/activ_driver.hpp
  driver/bn_driver.hpp
  driver/conv_common.cpp
  driver/conv_common.hpp
  driver/conv_driver.hpp
  driver/ctc_driver.hpp
  driver/dm_activ.cpp
  driver/dm_argmax.cpp
  driver/dm_bnorm.cpp
  driver/dm_cat.cpp
  driver/dm_conv.cpp
  driver/dm_convbfp16.cpp
  driver/dm_convbfp8.cpp
  driver/dm_convfp16.cpp
  driver/dm_convfp8.cpp
  driver/dm_convint8.cpp
  driver/dm_dropout.cpp
  driver/dm_fusion.cpp
  driver/dm_gemm.cpp
  driver/dm_groupnorm.cpp
  driver/dm_layernorm.cpp
  driver/dm_lrn.cpp
  driver/dm_pool.cpp
  driver/dm_reduce.cpp
  driver/dm_rnn.cpp
  driver/dm_softmax.cpp
  driver/dm_sum.cpp
  driver/dm_tensorop.cpp
  driver/dropout_driver.hpp
  driver/dropout_gpu_emulator.hpp
  driver/gemm_driver.hpp
  driver/gru_verify_gemm.hpp
  driver/lrn_driver.hpp
  driver/lstm_verify_gemm.hpp
  driver/main.cpp
  driver/miopen_ConvBatchNormActivHost.hpp
  driver/mloGroupNormHost.hpp
  driver/mloNeuronHost.hpp
  driver/mloSoftmaxHost.hpp
  driver/pool_driver.hpp
  driver/random.hpp
  driver/reduce_driver.hpp
  driver/registry_driver_maker.cpp
  driver/registry_driver_maker.hpp
  driver/rnn_driver.hpp
  driver/rnn_seq_driver.hpp
  driver/rnn_verify_gemm.hpp
  driver/softmax_driver.hpp
  driver/tensorop_driver.hpp
  driver/util_driver.hpp
  driver/util_file.hpp
  driver/xorwow_skipahead_generator.hpp
  src/include/miopen/gemm_v2.hpp
Labels: enhancement, value_high, urgency_high, TESTING_CI_PASSED, debugging

#2823 Add filesystem utility functions
  src/binary_cache.cpp
  src/db_path.cpp.in
  src/expanduser.cpp
  src/find_db.cpp
  src/hip/handlehip.cpp
  src/hip/hip_build_utils.cpp
  src/hipoc/hipoc_program.cpp
  src/include/miopen/batch_norm.hpp
  src/include/miopen/execution_context.hpp
  src/include/miopen/filesystem.hpp
  src/include/miopen/hipoc_kernel.hpp
  src/include/miopen/sqlite_db.hpp
  src/lock_file.cpp
  src/nogpu/handle.cpp
  src/ocl/convolutionocl.cpp
  src/readonlyramdb.cpp
  src/sqlite_db.cpp
  src/tmp_dir.cpp
  test/embed_sqlite.cpp
  test/gtest/cache.cpp
  test/gtest/db_sync.cpp
  test/include_inliner.cpp
  test/perfdb.cpp
  test/sqlite_perfdb.cpp
Labels: TESTING_CI_PASSED, windows

#2848 Convert reduce tests to gTests
  test/CMakeLists.txt
  test/gtest/reduce_custom_fp32.cpp
  test/gtest/reduce_custom_fp32_fp16.cpp
  test/reduce_test.cpp
  test/reduce_test.hpp
Labels: TESTING_CI_PASSED, GTest

#2879 [MHA] Implement MIOPEN_BACKEND_OPERATION_POINTWISE_DESCRIPTOR Builder
  src/graphapi/pointwise.cpp
  src/include/miopen/graphapi/pointwise.hpp
  test/gtest/graphapi_operation_pointwise.cpp
  test/gtest/graphapi_pointwise.cpp
Labels: enhancement, value_high, urgency_blocker

#2884 Remove extra db path quotes introduced in #2823
  src/find_db.cpp
Labels: bug, urgency_blocker, TESTING_CI_PASSED

#2875 [MHA] Added forward numeric test. Fix some bugs in cpu and gpu implementations. Resolved some post-merge comments.
  src/kernels/MIOpenSoftmaxAttn.cpp
  src/mha/problem_description.cpp
  src/solver/mha/mha_solver.cpp
  test/gtest/cpu_multi_head_attention.hpp
  test/gtest/gpu_multi_head_attention.cpp
  test/gtest/mha_helper.hpp
Labels: value_high, complexity_high, urgency_high, TESTING_CI_PASSED

#2873 [MHA] Implement MIOPEN_BACKEND_OPERATION_RNG_DESCRIPTOR
  src/graphapi/graphapi.cpp
  src/graphapi/rng.cpp
  src/graphapi/tensor.cpp
  src/include/miopen/graphapi/operation.hpp
  src/include/miopen/graphapi/rng.hpp
  src/include/miopen/graphapi/tensor.hpp
  test/gtest/graphapi_gtest_common.hpp
  test/gtest/graphapi_operation_rng.cpp
  test/gtest/graphapi_rng.cpp
Labels: enhancement, value_high, urgency_high, TESTING_CI_PASSED

#2811 [conv][FP32] Extend applicability of GemmBwdRest and GemmFwdRest for big WS sizes
  driver/conv_driver.hpp
  driver/driver.hpp
  src/CMakeLists.txt
  src/include/miopen/solver/gemm_common.hpp
  src/solver/gemm.cpp
  src/solver/gemm_bwd.cpp
  src/solver/gemm_common.cpp
  src/solver/gemm_wrw.cpp
Labels: enhancement, workaround, urgency_high, TESTING_CI_PASSED

#2880 [MHA] Implement MIOPEN_BACKEND_OPERATION_REDUCTION_DESCRIPTOR
  src/graphapi/graphapi.cpp
  src/graphapi/reduction.cpp
  src/include/miopen/errors.hpp
  src/include/miopen/graphapi/reduction.hpp
  test/gtest/graphapi_operation_reduction.cpp
  test/gtest/graphapi_reduction.cpp
Labels: enhancement, value_high, urgency_high, TESTING_CI_PASSED

#2877 [CK] Update requirements.txt for next staging
  requirements.txt
Labels: TESTING_CI_PASSED

#2886 [MHA] Implement MIOPEN_BACKEND_OPERATION_POINTWISE_DESCRIPTOR API Class
  src/graphapi/graphapi.cpp
  src/graphapi/pointwise.cpp
  src/graphapi/reduction.cpp
  src/graphapi/rng.cpp
  src/include/miopen/graphapi/convolution.hpp
  src/include/miopen/graphapi/opgraph.hpp
  src/include/miopen/graphapi/pointwise.hpp
  src/include/miopen/graphapi/reduction.hpp
  src/include/miopen/graphapi/rng.hpp
  test/gtest/graphapi_operation_pointwise.cpp
Labels: enhancement, value_high, urgency_high, TESTING_CI_PASSED

#2818 Graph API: Operation Graph creation and interface
  src/CMakeLists.txt
  src/graphapi/opgraph.cpp
  src/include/miopen/graphapi/opgraph.hpp
  test/gtest/graphapi_opgraph.cpp
Labels: TESTING_CI_PASSED

#2876 removing gfx908 and vega builds node from smoke tests
  Jenkinsfile
Labels: workaround

#2892 Unify 'include <half/half.hpp>' across Windows and Linux
  driver/conv_common.hpp
  driver/driver.hpp
  driver/reduce_driver.hpp
  driver/rocrand_wrapper.hpp
  src/fusion.cpp
  src/gemm_v2.cpp
  src/include/miopen/op_kernel_args.hpp
  src/include/miopen/reduce_common.hpp
  src/include/miopen/visit_float.hpp
  src/solver/conv_asm_1x1u_bias_activ_fused.cpp
  src/solver/conv_ocl_dir2Dfwd_exhaustive_search.cpp
  test/cpu_reduce_util.hpp
  test/driver.hpp
  test/gpu_reference_kernel.cpp
  test/serialize.hpp
  test/tensor_holder.hpp
Labels: TESTING_CI_PASSED, windows

#2895 [MHA] backward pass
  include/miopen/miopen.h
  src/CMakeLists.txt
  src/api/find2_0_commons.cpp
  src/include/miopen/mha/invoke_params.hpp
  src/include/miopen/mha/mha.hpp
  src/include/miopen/mha/problem_description.hpp
  src/include/miopen/mha/solvers.hpp
  src/kernels/MIOpenSoftmaxAttn.cpp
  src/kernels/miopen_rocrand.hpp
  src/mha/problem_description.cpp
  src/problem.cpp
  src/solution.cpp
  src/solver.cpp
  src/solver/mha/mha_solver_backward.cpp
  src/solver/mha/mha_solver_forward.cpp
  src/solver/softmax/attn_softmax.cpp
  test/gtest/cpu_multi_head_attention.hpp
  test/gtest/gpu_multi_head_attention.cpp
  test/gtest/mha_find20.cpp
  test/gtest/mha_helper.hpp
Labels: value_high, complexity_high, urgency_high, TESTING_CI_PASSED

#2898 KernelTuningNet for MI300/200 ConvHipIGemmGrouped Solvers
  src/conv/heuristics/ai_heuristics.cpp
  src/include/miopen/conv/heuristics/ai_heuristics.hpp
  src/include/miopen/solver.hpp
  src/kernels/gfx908_ConvAsm1x1U_metadata.ktn.model
  src/kernels/gfx90a_ConvHipIgemmGroupFwdXdlops_metadata.ktn.model
  src/kernels/gfx90a_ConvHipIgemmGroupXdlops_decoder.ktn.model
  src/kernels/gfx90a_ConvHipIgemmGroupXdlops_encoder.ktn.model
  src/kernels/gfx90a_ConvHipIgemmGroupXdlops_metadata.ktn.model
  src/kernels/gfx942_ConvHipIgemmGroupXdlops_decoder.ktn.model
  src/kernels/gfx942_ConvHipIgemmGroupXdlops_encoder.ktn.model
  src/kernels/gfx942_ConvHipIgemmGroupXdlops_metadata.ktn.model
  src/solver/conv_asm_1x1u.cpp
  src/solver/conv_hip_implicit_gemm_grouped_bwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_grouped_fwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_grouped_wrw_xdlops.cpp
  test/gtest/ai_heuristics.hpp
  test/gtest/kernel_tuning_net.cpp
  test/gtest/tuna_net.cpp
Labels: value_high, complexity_middle, urgency_high, TESTING_CI_PASSED

#2899 Unify 'include amd_comgr.h' between Windows and Linux
  src/comgr.cpp
Labels: TESTING_CI_PASSED, windows

#2903 make rocMLIR required package on Windows
  CMakeLists.txt
Labels: TESTING_CI_PASSED, windows

#2901 [NFC] Fix leftover of #2251 (Remove src/kernels/MIOpenCheckNumerics.cl)
  src/kernels/MIOpenCheckNumerics.cl
Labels: quality, urgency_low, TESTING_CI_PASSED

#2855 Graph API: Operation Graph matching
  src/graphapi/opgraph.cpp
  src/include/miopen/graphapi/opgraph.hpp
  test/gtest/graphapi_opgraph.cpp
  test/gtest/graphapi_opgraph_common.hpp
  test/gtest/graphapi_opgraph_matching.cpp
Labels: urgency_blocker, TESTING_CI_PASSED

#2829 [MAH] [test] mha CPU backward test
  test/gtest/attention_golden.hpp
  test/gtest/cpu_multi_head_attention.cpp
  test/gtest/cpu_multi_head_attention.hpp
  test/gtest/gpu_multi_head_attention.cpp
  test/gtest/mha_helper.hpp
  test/tensor_util.hpp
Labels: value_high, testing, urgency_high, TESTING_CI_PASSED

#2816 [NFC] Removed WORKAROUND_SWDEV_227826 macro and MIOPEN_DEBUG_IMPLICIT_GEMM_FIND_ALL_SOLUTIONS envvar
  src/mlo_dir_conv.cpp
Labels: quality, urgency_low, TESTING_CI_PASSED

#2908 update test include_inliner to pass on Windows
  test/include_inliner.cpp
Labels: windows

#2838 Fixes to support huge tensors. Enable huge tensors in ConvDirectNaive*. miopenSetTensorDescriptorV2 (BETA).
  driver/argmax_driver.hpp
  driver/conv_driver.hpp
  driver/ctc_driver.hpp
  driver/rnn_driver.hpp
  driver/rnn_seq_driver.hpp
  driver/sum_driver.hpp
  driver/tensor_driver.hpp
  include/miopen/miopen.h
  src/include/miopen/conv/problem_description.hpp
  src/include/miopen/oclkernel.hpp
  src/include/miopen/rnn_util.hpp
  src/include/miopen/tensor.hpp
  src/include/miopen/tensor_layout.hpp
  src/ocl/tensorocl.cpp
  src/rnn.cpp
  src/solver/conv_direct_naive_conv_bwd.cpp
  src/solver/conv_direct_naive_conv_fwd.cpp
  src/solver/conv_direct_naive_conv_wrw.cpp
  src/tensor.cpp
  src/tensor_api.cpp
  test/conv3d.hpp
  test/conv3d_find2.cpp
  test/conv_common.hpp
  test/cpu_argmax.hpp
  test/cpu_sum.hpp
  test/ctc.cpp
  test/lstm_common.hpp
  test/pooling_common.hpp
  test/rnn_util.hpp
  test/tensor_holder.hpp
  test/tensor_layout.hpp
Labels: bug, enhancement, urgency_high, TESTING_CI_PASSED, IMPACTS_API

#2888 Consider workspace constraints when loading convolution solutions from database
  src/ocl/convolutionocl.cpp
Labels: value_high, urgency_high, TESTING_CI_PASSED

#2909 [Tests] Make would fail with no device error without GPUs
  test/gtest/CMakeLists.txt
Labels: TESTING_CI_PASSED, GTest

#2902 [MHA] Implement MIOPEN_BACKEND_OPERATION_MATMUL_DESCRIPTOR
  src/graphapi/graphapi.cpp
  src/graphapi/matmul.cpp
  src/include/miopen/graphapi/matmul.hpp
  test/gtest/graphapi_operation_matmul.cpp
Labels: enhancement, value_high, urgency_high, TESTING_CI_PASSED

#2905 fix execution of a HIP compiler on Windows
  src/hip/hip_build_utils.cpp
  src/process.cpp
Labels: TESTING_CI_PASSED, windows

#2894 [MHA] Implement MIOPEN_BACKEND_OPERATIONGRAPH_DESCRIPTOR C API Interface
  src/graphapi/graphapi.cpp
  src/graphapi/opgraph.cpp
  src/include/miopen/graphapi/engine.hpp
  src/include/miopen/graphapi/opgraph.hpp
  test/gtest/graphapi_operationgraph_descriptor.cpp
  test/gtest/graphapi_opgraph.cpp
  test/gtest/graphapi_opgraph_common.hpp
Labels: enhancement, value_high, urgency_blocker, TESTING_CI_PASSED

#2934 [HOTFIX] Fix typo introduced by #2894 and #2902
  src/graphapi/graphapi.cpp
Labels: value_high, urgency_blocker, TESTING_CI_PASSED

#2891 Adjustments for the latest assembler (e.g. latest changes in the upstream clang)
  src/comgr.cpp
  src/hip/handlehip.cpp
  src/hip/hip_build_utils.cpp
  src/ocl/gcn_asm_utils.cpp
Labels: enhancement, urgency_high
