Repository ROCm/MIOpen, pull requests merged in 2024-07, with the labels that each got.

#3082 [MHA] Implement MIOPEN_BACKEND_OPERATION_RESHAPE_DESCRIPTOR
  include/miopen/miopen.h
  src/CMakeLists.txt
  src/graphapi/graphapi.cpp
  src/graphapi/reshape.cpp
  src/include/miopen/graphapi/reshape.hpp
  test/gtest/graphapi_operation_reshape.cpp
Labels: enhancement, value_high, urgency_blocker, TESTING_CI_PASSED

#3030 Enable hipBLASLt backend for GEMM, and make it the default option for RNN's under specific conditions
  CMakeLists.txt
  README.md
  docs/how-to/debug-log.rst
  docs/install/install.rst
  include/miopen/config.h.in
  src/CMakeLists.txt
  src/gemm_v2.cpp
  src/hip/handlehip.cpp
  src/hipoc/hipoc_kernel.cpp
  src/include/miopen/gemm_v2.hpp
  src/include/miopen/handle.hpp
  src/include/miopen/hipoc_kernel.hpp
  src/include/miopen/nogpu/handle_impl.hpp
  src/include/miopen/solver/implicitgemm_ck_util.hpp
  src/nogpu/handle.cpp
  src/solver/mha/mha_solver_backward.cpp
  src/solver/mha/mha_solver_forward.cpp
  test/gtest/CMakeLists.txt
  test/gtest/gemm_cpu_util.hpp
  test/gtest/hipblaslt_gemm.cpp
  test/rnn_util.hpp
Labels: value_middle, complexity_low, urgency_normal, TESTING_CI_PASSED, uai

#3092 Regenerate gfx908.kdb
  src/kernels/gfx908.kdb.bz2
Labels: TESTING_CI_PASSED

#3095 Support for invoker caching and find modes to fusion find
  src/fusion.cpp
  src/include/miopen/find_solution.hpp
  src/include/miopen/fusion/problem_description.hpp
  src/include/miopen/solution.hpp
Labels: value_high, performance, complexity_middle, urgency_high, TESTING_CI_PASSED

#3042 [NFC] Move convolution solvers to solver/conv directory (part 2)
  src/CMakeLists.txt
  src/solver/conv/conv_MP_bidirectional_winograd.cpp
  src/solver/conv/conv_ck_igemm_fwd_v6r1_dlops_nchw.cpp
  src/solver/conv/conv_direct_naive_conv.cpp
  src/solver/conv/conv_direct_naive_conv_bwd.cpp
  src/solver/conv/conv_direct_naive_conv_fwd.cpp
  src/solver/conv/conv_direct_naive_conv_wrw.cpp
  src/solver/conv/conv_hip_implicit_gemm_3d_grouped_bwd_xdlops.cpp
  src/solver/conv/conv_hip_implicit_gemm_3d_grouped_fwd_xdlops.cpp
  src/solver/conv/conv_hip_implicit_gemm_3d_grouped_wrw_xdlops.cpp
  src/solver/conv/conv_hip_implicit_gemm_bwd_data_xdlops.cpp
  src/solver/conv/conv_hip_implicit_gemm_bwd_v1r1.cpp
  src/solver/conv/conv_hip_implicit_gemm_bwd_v1r1_xdlops.cpp
  src/solver/conv/conv_hip_implicit_gemm_bwd_v4r1.cpp
  src/solver/conv/conv_hip_implicit_gemm_bwd_v4r1_xdlops.cpp
  src/solver/conv/conv_hip_implicit_gemm_f16f8f16_bwd_xdlops.cpp
  src/solver/conv/conv_hip_implicit_gemm_f16f8f16_fwd_xdlops.cpp
  src/solver/conv/conv_hip_implicit_gemm_f16f8f16_wrw_xdlops.cpp
  src/solver/conv/conv_hip_implicit_gemm_fwd_v4r1.cpp
  src/solver/conv/conv_hip_implicit_gemm_fwd_v4r4.cpp
  src/solver/conv/conv_hip_implicit_gemm_fwd_v4r4_xdlops.cpp
  src/solver/conv/conv_hip_implicit_gemm_fwd_v4r4_xdlops_padded_gemm.cpp
  src/solver/conv/conv_hip_implicit_gemm_fwd_v4r5_xdlops.cpp
  src/solver/conv/conv_hip_implicit_gemm_fwd_xdlops.cpp
  src/solver/conv/conv_hip_implicit_gemm_grouped_bwd_xdlops.cpp
  src/solver/conv/conv_hip_implicit_gemm_grouped_fwd_xdlops.cpp
  src/solver/conv/conv_hip_implicit_gemm_grouped_wrw_xdlops.cpp
  src/solver/conv/conv_hip_implicit_gemm_nonxdlops_common.cpp
  src/solver/conv/conv_hip_implicit_gemm_wrw_v4r4.cpp
  src/solver/conv/conv_hip_implicit_gemm_wrw_v4r4_xdlops.cpp
  src/solver/conv/conv_hip_implicit_gemm_wrw_v4r4_xdlops_padded_gemm.cpp
  src/solver/conv/conv_multipass_wino3x3WrW.cpp
  src/solver/conv/gemm.cpp
  src/solver/conv/gemm_bwd.cpp
  src/solver/conv/gemm_common.cpp
  src/solver/conv/gemm_wrw.cpp
Labels: quality, complexity_low, TESTING_CI_PASSED

#3114 [Fixes CI] Fixed tidy hang
  cmake/ClangTidy.cmake
Labels: urgency_high, TESTING_CI_PASSED

#3103 Find: Optimize benchmarking for long execution times.
  src/conv/solver_finders.cpp
Labels: enhancement, urgency_normal, TESTING_CI_PASSED

#3113 [ROCm 6.2] add change log
  CHANGELOG.md
Labels: documentation

#3117 [WA] Remove exception checking tests for unsupported hardware
  test/gtest/hipblaslt_gemm.cpp
Labels: bug, value_high, workaround, urgency_high, TESTING_CI_PASSED

#3112 Add tests for ConvBiasResAddActivation forward using Graph API
  test/gtest/graphapi_conv_bias_res_add_activ_fwd.cpp
Labels: value_middle, complexity_low, urgency_normal, TESTING_CI_PASSED, GTest

#3109 [gfx12] add support of gfx12 platforms
  src/composable_kernel/composable_kernel/include/utility/config.hpp
  src/include/miopen/solver/ck_utility_common.hpp
  src/kernels/MIOpenBatchNormActivBwdPerAct.cl
  src/kernels/MIOpenBatchNormActivBwdSpatial.cl
  src/kernels/MIOpenBatchNormActivFwdTrainSpatial.cl
  src/kernels/MIOpenBatchNormBwdSpatial.cl
  src/kernels/MIOpenBatchNormFwdTrainSpatial.cl
  src/kernels/batchnorm_functions.h
  src/solver/batchnorm/backward_per_activation.cpp
  src/solver/batchnorm/backward_per_activation_fused.cpp
  src/solver/batchnorm/backward_spatial_multiple.cpp
  src/solver/batchnorm/backward_spatial_single.cpp
  src/solver/batchnorm/forward_inference.cpp
  src/solver/batchnorm/forward_per_activation.cpp
  src/solver/batchnorm/forward_per_activation_fused.cpp
  src/solver/batchnorm/forward_spatial_multiple.cpp
  src/solver/batchnorm/forward_spatial_single.cpp
  test/CMakeLists.txt
  test/handle_test.cpp
Labels: value_high, urgency_high

#3119 Update GraphAPI Tensor to inherit from TensorDescriptor
  src/graphapi/find_engine.cpp
  src/graphapi/matmul.cpp
  src/graphapi/pointwise.cpp
  src/graphapi/reduction.cpp
  src/graphapi/reshape.cpp
  src/graphapi/rng.cpp
  src/graphapi/tensor.cpp
  src/include/miopen/graphapi/engine.hpp
  src/include/miopen/graphapi/tensor.hpp
  src/include/miopen/graphapi/util.hpp
  src/include/miopen/tensor.hpp
  src/tensor.cpp
  test/gtest/graphapi_conv_bias_res_add_activ_fwd.cpp
  test/gtest/graphapi_gtest_common.hpp
  test/gtest/graphapi_mha_fwd_f8.cpp
  test/gtest/graphapi_operationgraph_descriptor.cpp
  test/gtest/graphapi_tensor.cpp
Labels: value_middle, complexity_low, urgency_normal, TESTING_CI_PASSED

#3107 [COMgr] Prepare for COMgr 3.x
  CMakeLists.txt
  src/comgr.cpp
  src/hipoc/hipoc_program.cpp
  src/include/miopen/comgr.hpp
  src/solver/conv/conv_wino_fury_RxS.cpp
Labels: enhancement, value_high, urgency_high, TESTING_CI_PASSED

#3111 [debugging] Make naive conv solvers obey MIOPEN_DEBUG_HIP_KERNELS
  src/solver/conv/conv_direct_naive_conv_bwd.cpp
  src/solver/conv/conv_direct_naive_conv_fwd.cpp
  src/solver/conv/conv_direct_naive_conv_wrw.cpp
Labels: bug, urgency_low, TESTING_CI_PASSED, debugging

#3105 Added missing weight sorting as WTI calculation in fusion
  src/fusion.cpp
  src/include/miopen/conv_solution.hpp
  src/include/miopen/fusion/solvers.hpp
  src/include/miopen/solver.hpp
  src/solver/conv_asm_1x1u_bias_activ_fused.cpp
  src/solver/conv_bin_winoRxS_fused.cpp
  src/solver/conv_ocl_dir2Dfwd_fused.cpp
  src/solver/conv_winoRxS_fused.cpp
Labels: value_high, performance, complexity_low, urgency_high, TESTING_CI_PASSED

#3124 GTests renaming: filename starting letters A-B
  test/gtest/adam.cpp
  test/gtest/addlayernorm.cpp
  test/gtest/api_convbiasactiv.cpp
  test/gtest/bad_fusion_plan.cpp
  test/gtest/bn_bwd.cpp
  test/gtest/bn_fwd_train.cpp
  test/gtest/bn_infer.cpp
Labels: TESTING_CI_PASSED

#3123 [bug][tests] Fix broken tests
  test/driver.hpp
  test/gtest/conv3d_codecov.cpp
  test/gtest/conv3d_test.cpp
  test/gtest/conv_3d.cpp
  test/gtest/conv_embed_db.cpp
  test/gtest/conv_extra.cpp
  test/gtest/conv_for_implicit_gemm.cpp
  test/gtest/conv_group.cpp
  test/gtest/conv_hip_igemm_xdlops.cpp
  test/gtest/conv_trans.cpp
  test/gtest/deepbench_gru.cpp
  test/gtest/deepbench_rnn.cpp
  test/gtest/gru_extra.cpp
  test/gtest/gtest_common.hpp
  test/gtest/immed_conv2d_codecov.cpp
  test/gtest/immed_conv3d_codecov.cpp
  test/gtest/miopen_conv.cpp
  test/gtest/pooling2d_asymmetric.cpp
  test/gtest/pooling2d_codecov.cpp
  test/gtest/pooling2d_wide.cpp
  test/gtest/reduce_custom_fp32.cpp
  test/gtest/regression_half_vega.cpp
  test/gtest/rnn_extra.cpp
  test/gtest/smoke_solver_ConvWinogradFuryRxSf2x3_f16.cpp
Labels: bug, value_high, urgency_blocker, TESTING_CI_PASSED, GTest

#3121 Changed Fusion to have a separate find mode env variable and default to fast
  src/find_controls.cpp
  src/fusion.cpp
  src/include/miopen/env.hpp
  src/include/miopen/find_controls.hpp
  src/include/miopen/handle.hpp
Labels: value_high, complexity_low, initial iteration time, TESTING_CI_PASSED

#3110 [debugging][NFC] Added logging of paths and versions of several packages (HIP, HIPRTC, COMgr, rocBlas, rocMLIR, rocRand, frugally-deep, Eigen3)
  CMakeLists.txt
Labels: enhancement, urgency_normal, debugging

#3131 Fixed redundant find on failed fusion fallback
  src/fusion.cpp
Labels: bug, value_high, complexity_low, urgency_high

#3150 [gtest] Fix log test error
  test/gtest/log.cpp
Labels: complexity_low, GTest

#3164 Temporary workaround on the rocMLIR linking issue
  src/CMakeLists.txt
Labels: non-miopen-bug, workaround, urgency_high, windows, uai
