Repository ROCm/MIOpen, pull requests merged in 2024-05, with the labels that each got.

#2937 [Doc] Fix extra space in doc link
  docs/conceptual/perfdb.rst
Labels: value_low, urgency_normal, documentation

#2942 [Doc] Fix extra space in doc link (#2937)
  docs/conceptual/perfdb.rst
Labels: complexity_low, documentation

#2943 [Doc] Fix extra space in doc link (#2937)
  docs/conceptual/perfdb.rst
Labels: complexity_low, documentation

#2944 Fix docs structure and broken link in Log & Debug and Argmax
  docs/how-to/debug-log.rst
  docs/reference/argmax.rst
  docs/reference/index.rst
  include/miopen/miopen.h
Labels: value_low, urgency_normal, documentation

#2946 [Doc] 6.1.1 - Fix docs structure and broken link in Log & Debug and Argmax (#…
  docs/how-to/debug-log.rst
  docs/reference/argmax.rst
  docs/reference/index.rst
  include/miopen/miopen.h
Labels: value_low, complexity_low, urgency_normal, documentation

#2945 [Doc] 6.1.0 - Fix docs structure and broken link in Log & Debug and Argmax (#…
  docs/how-to/debug-log.rst
  docs/reference/argmax.rst
  docs/reference/index.rst
  include/miopen/miopen.h
Labels: value_low, complexity_low, urgency_normal, documentation

#2778 [gfx11][Solvers][Winograd] ConvWinoFuryRxS v2.4
  src/CMakeLists.txt
  src/conv/invokers/gcn_asm_wino.cpp
  src/conv/kernel_interface/winograd_kernel_interface.cpp
  src/hip/handlehip.cpp
  src/hipoc/hipoc_kernel.cpp
  src/include/miopen/conv/invokers/gcn_asm_wino.hpp
  src/include/miopen/conv/kernel_interface/winograd_kernel_interface.hpp
  src/include/miopen/conv/problem_description.hpp
  src/include/miopen/handle.hpp
  src/include/miopen/hipoc_kernel.hpp
  src/include/miopen/solver.hpp
  src/kernels/Conv_Winograd_Fury_v1_1_1_gfx11_fp16_fp16acc_f2x3_stride1.inc
  src/kernels/Conv_Winograd_Fury_v1_1_1_metadata.inc
  src/kernels/winograd/Conv_Winograd_Fury_v2_4_1_fp16_fp16acc_f2x3_c16_stride1.s
  src/kernels/winograd/Conv_Winograd_Fury_v2_4_1_fp16_fp16acc_f2x3_c32_stride1.s
  src/kernels/winograd/Conv_Winograd_Fury_v2_4_1_gfx11_1024vgprs_fp16_fp16acc_f2x3_c16_stride1.inc
  src/kernels/winograd/Conv_Winograd_Fury_v2_4_1_gfx11_1536vgprs_fp16_fp16acc_f2x3_c16_stride1.inc
  src/kernels/winograd/Conv_Winograd_Fury_v2_4_1_gfx11_1536vgprs_fp16_fp16acc_f2x3_c32_stride1.inc
  src/kernels/winograd/Conv_Winograd_Fury_v2_4_1_metadata.inc
  src/mlo_dir_conv.cpp
  src/nogpu/handle.cpp
  src/ocl/handleocl.cpp
  src/ocl/utilocl.cpp
  src/solver/conv/conv_wino_fury_RxS.cpp
  src/solver/conv_winoRxS.cpp
  src/solver/conv_wino_fury_RxS.cpp
Labels: enhancement, performance, TESTING_CI_PASSED

#2929 [MHA] add test for the backward pass
  test/gtest/gpu_mha_backward.cpp
  test/gtest/gpu_mha_forward.cpp
Labels: value_high, testing, urgency_high, TESTING_CI_PASSED

#2907 Fixed test_perfdb and test_sqlite_perfdb to propertly use mutex
  test/perfdb.cpp
  test/sqlite_perfdb.cpp
Labels: enhancement, testing, complexity_low, TESTING_CI_PASSED, correctness

#2948 [gTest] Reduce_custom_fp32 skips on MI200/gfx90a
  test/gtest/gtest_common.hpp
  test/gtest/reduce_custom_fp32.cpp
Labels: testing, TESTING_CI_PASSED, GTest

#2952 fix compilation on Windows
  src/graphapi/execution_plan.cpp
  src/graphapi/opgraph.cpp
Labels: urgency_blocker, workaround, TESTING_CI_PASSED, windows

#2940 [CK] Bump CK commit hash by updating requirements.txt
  requirements.txt
Labels: urgency_high, TESTING_CI_PASSED

#2868 Add adam and amp adam optimizer
  docs/reference/index.rst
  driver/CMakeLists.txt
  driver/adam_driver.hpp
  driver/dm_adam.cpp
  driver/driver.hpp
  include/miopen/miopen.h
  src/CMakeLists.txt
  src/adam.cpp
  src/adam/problem_description.cpp
  src/adam_api.cpp
  src/include/miopen/adam.hpp
  src/include/miopen/adam/invoke_params.hpp
  src/include/miopen/adam/problem_description.hpp
  src/include/miopen/adam/solvers.hpp
  src/include/miopen/solver_id.hpp
  src/kernels/MIOpenAdam.cpp
  src/solver.cpp
  src/solver/adam/adam.cpp
  test/cpu_adam.hpp
  test/gtest/adam.cpp
  test/gtest/adam.hpp
Labels: enhancement, complexity_high, urgency_normal, TESTING_CI_PASSED, external_collaborator

#2953 [Windows] fix NOGPU backend compilation
  CMakeLists.txt
  src/include/miopen/conv/kernel_interface/winograd_kernel_interface.hpp
Labels: urgency_blocker, TESTING_CI_PASSED, windows

#2904 unblock gtest tests discovering on Windows
  src/CMakeLists.txt
  test/CMakeLists.txt
  test/gtest/CMakeLists.txt
Labels: TESTING_CI_PASSED, windows

#2959 Fix MIOpen throw message when MIOPEN_OFFLINE_COMPILER_PATHS_V2 is enabled
  src/hip/hip_build_utils.cpp
Labels: urgency_blocker, TESTING_CI_PASSED

#2947 [conv] miopenFindConvolution: Officially allow smaller workspace than GWSS returns.
  driver/conv_driver.hpp
  include/miopen/miopen.h
  src/conv/solver_finders.cpp
  src/fusion.cpp
  src/include/miopen/conv/solver_finders.hpp
  src/include/miopen/convolution.hpp
  src/include/miopen/find_db.hpp
  src/include/miopen/logger.hpp
  src/logger.cpp
  src/ocl/convolutionocl.cpp
Labels: enhancement, urgency_normal, IMPACTS_API

#2906 fix lock file path creation on Windows
  src/lock_file.cpp
Labels: TESTING_CI_PASSED, windows

#2825 Find 2.0 bnorm fusions
  include/miopen/miopen.h
  src/api/find2_0_commons.cpp
  src/driver_arguments.cpp
  src/include/miopen/problem.hpp
  src/include/miopen/solution.hpp
  src/problem.cpp
  src/solution.cpp
  test/na_inference_find2.cpp
  test/na_train_find2.cpp
Labels: complexity_middle, TESTING_CI_PASSED

#2936 [Workaround] Disable conv_hip_implicit_gemm_grouped_bwd_xdlops
  src/solver/conv_hip_implicit_gemm_grouped_bwd_xdlops.cpp
Labels: bug, urgency_blocker, workaround, TESTING_CI_PASSED

#2950 Enable bf16 support for ck-based convolution solvers in MIOpen
  src/include/miopen/solver/implicitgemm_ck_util.hpp
  src/solver/conv_hip_implicit_gemm_3d_grouped_bwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_3d_grouped_fwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_3d_grouped_wrw_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_grouped_bwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_grouped_fwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_grouped_wrw_xdlops.cpp
  test/gtest/group_conv.hpp
  test/gtest/group_conv2d_bwd.cpp
  test/gtest/group_conv2d_fwd.cpp
  test/gtest/group_conv2d_wrw.cpp
  test/gtest/group_conv3d_bwd.cpp
  test/gtest/group_conv3d_fwd.cpp
  test/gtest/group_conv3d_wrw.cpp
Labels: value_high, urgency_blocker

#2963 TunaNetv2.0 for MI300 with CK solvers fix
  src/conv/heuristics/ai_heuristics.cpp
  src/kernels/gfx942.tn.model
  src/kernels/gfx942_metadata.tn.model
Labels: value_high, urgency_blocker

#2965 [Windows] graphapi: fix compilation due to conflicting definitions of std::min between MSVC and Clang
  src/graphapi/convolution.cpp
  src/graphapi/engineheur.cpp
  src/graphapi/execution_plan.cpp
  src/graphapi/opgraph.cpp
  src/graphapi/tensor.cpp
  src/graphapi/variant_pack.cpp
  src/include/miopen/graphapi/graphapi.hpp
Labels: urgency_blocker, workaround, windows

#2518 [gfx94x] Enable and enhance gfx94x nodes in CI
  Jenkinsfile
Labels: TESTING_CI_PASSED

#2974 [HotFix] for_each_n not available on RHEL 8 or SLES and bump CK to avoid ENV conflicts
  requirements.txt
  src/graphapi/opgraph.cpp
Labels: urgency_blocker

#2983 Update RTD config to use Python 3.10 and rocm-docs-core 1.1.2
  .github/CODEOWNERS
  .readthedocs.yaml
  docs/sphinx/requirements.in
  docs/sphinx/requirements.txt
Labels: documentation, dependencies

#2917 Basic mechanism for tuning in ExecutePrimitive
  CMakeLists.txt
  src/include/miopen/batchnorm/problem_description.hpp
  src/include/miopen/execution_context.hpp
  src/include/miopen/find_solution.hpp
  src/include/miopen/fusion/solvers.hpp
  src/include/miopen/solver.hpp
  src/ocl/batchnormocl.cpp
  test/gtest/execute_primitive.cpp
Labels: enhancement, performance, complexity_middle, tuning, TESTING_CI_PASSED

#2986 Fix excessive IsEnoughWorkspace warning messages after #2947
  src/ocl/convolutionocl.cpp
Labels: quality, urgency_high, TESTING_CI_PASSED

#2976 [HotFix] add two missing cases in #2869
  src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp
Labels: value_low, workaround, urgency_high, TESTING_CI_PASSED

#2987 Upgrade to latest CK libs.
  Dockerfile
  requirements.txt
Labels: TESTING_CI_PASSED

#2985 fix ck instance
  src/solver/conv_hip_implicit_gemm_3d_grouped_fwd_xdlops.cpp
Labels: urgency_high, TESTING_CI_PASSED

#2999 [CI] Temporarily disable gfx94X stages
  Jenkinsfile
Labels: complexity_low, urgency_high

#2991 Int64 type introduction and basic support
  include/miopen/miopen.h
  src/check_numerics.cpp
  src/convolution_api.cpp
  src/gemm_v2.cpp
  src/include/miopen/datatype.hpp
  src/include/miopen/problem_description_base.hpp
  src/include/miopen/solver/implicitgemm_ck_util.hpp
  src/include/miopen/tensor.hpp
  src/include/miopen/visit_float.hpp
  src/ocl/tensorocl.cpp
  src/pooling_api.cpp
  src/reducetensor.cpp
  src/reducetensor_api.cpp
  src/solver/batchnorm/backward_ck.cpp
  src/solver/batchnorm/forward_inference_ck.cpp
  src/solver/batchnorm/forward_training_ck.cpp
  src/solver/conv_ck_igemm_fwd_bias_activ_fused.cpp
  src/solver/conv_ck_igemm_fwd_bias_res_add_activ_fused.cpp
  src/solver/conv_hip_implicit_gemm_3d_grouped_bwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_3d_grouped_fwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_3d_grouped_wrw_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_bwd_data_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_fwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_grouped_bwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_grouped_fwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_grouped_wrw_xdlops.cpp
  src/solver/layernorm/forward_layernorm2d_ck.cpp
  src/solver/layernorm/forward_layernorm4d_ck.cpp
  src/solver/mlir_common.cpp
  src/tensor.cpp
  test/driver.hpp
  test/gtest/conv3d_codecov.cpp
  test/gtest/conv3d_test.cpp
  test/gtest/conv_embed_db.cpp
  test/gtest/conv_for_implicit_gemm.cpp
  test/gtest/conv_hip_igemm_xdlops.cpp
  test/gtest/conv_igemm_dynamic_xdlops_half.cpp
  test/gtest/conv_igemm_dynamic_xdlops_nhwc_bf16.cpp
  test/gtest/conv_igemm_dynamic_xdlops_nhwc_nchw.cpp
  test/gtest/conv_trans.cpp
  test/gtest/immed_conv2d_codecov.cpp
  test/gtest/immed_conv3d_codecov.cpp
  test/gtest/miopen_conv.cpp
  test/gtest/pooling2d_asymmetric.cpp
  test/gtest/pooling2d_codecov.cpp
  test/gtest/pooling2d_wide.cpp
  test/gtest/reduce_custom_fp32_fp16.cpp
  test/gtest/tensor_api.cpp
  test/tensor_holder.hpp
Labels: urgency_blocker, complexity_low, TESTING_CI_PASSED, IMPACTS_API

#2997 Fixed build error in gtest/execute_primitive.cpp with sqlite perfdb
  test/gtest/execute_primitive.cpp
Labels: complexity_low, urgency_high, TESTING_CI_PASSED

#2984 [Testing] Convert MIOpenDriver tests to gTest framework
  src/include/miopen/process.hpp
  src/process.cpp
  test/CMakeLists.txt
  test/gtest/miopendriver_common.hpp
  test/gtest/miopendriver_conv2d_trans.cpp
  test/gtest/miopendriver_gemm.cpp
  test/gtest/miopendriver_regression_big_tensor.cpp
  test/gtest/miopendriver_regression_float_half_gfx10.cpp
  test/gtest/miopendriver_regression_half.cpp
  test/gtest/miopendriver_regression_half_gfx9.cpp
  test/gtest/miopendriver_regression_int8.cpp
  test/gtest/miopendriver_regression_issue_1576.cpp
  test/gtest/miopendriver_regression_issue_2047.cpp
Labels: testing

#2969 Find: Improve precision of benchmarking
  Jenkinsfile
  driver/conv_driver.hpp
  driver/timer.hpp
  src/conv/solver_finders.cpp
  src/gemm_v2.cpp
  src/include/miopen/gemm_v2.hpp
  src/include/miopen/invoke_params.hpp
  src/ocl/convolutionocl.cpp
  src/solver/conv_MP_bidirectional_winograd.cpp
  src/solver/gemm.cpp
  src/solver/gemm_bwd.cpp
  src/solver/gemm_wrw.cpp
Labels: enhancement, value_high, performance, urgency_high, TESTING_CI_PASSED

#2994 Enable external CI pipeline triggers
  .azuredevops/rocm-ci.yml
Labels: TESTING_CI_PASSED

#2992 Fix multiple softmax issues
  src/softmax/problem_description.cpp
Labels: bug, complexity_low, TESTING_CI_PASSED

#2971 [MHA] turn on fp8 matmul for mha
  src/kernels/MIOpenSoftmaxAttn.cpp
  src/solver/mha/mha_common.hpp
  src/solver/mha/mha_solver_backward.cpp
  src/solver/mha/mha_solver_forward.cpp
  test/gtest/gpu_mha_forward.cpp
Labels: value_high, urgency_blocker

#3002 [WORKAROUND] Disable the fix for #2851 implemented in #2891
  src/comgr.cpp
  src/hip/handlehip.cpp
  src/include/miopen/target_properties.hpp
  src/ocl/gcn_asm_utils.cpp
Labels: urgency_blocker, workaround

#2979 ExecutionContext: remove save_srch_req and use_binaries
  docs/conceptual/porting-guide.rst
  docs/how-to/debug-log.rst
  src/execution_context.cpp
  src/include/miopen/execution_context.hpp
  src/rnn.cpp
  test/conv_common.hpp
Labels: quality, TESTING_CI_PASSED

#2980 Fusion solvers: use context.use_asm_kernels instead of MIOPEN_DEBUG_GCN_ASM_KERNELS
  docs/conceptual/porting-guide.rst
  src/solver/conv_asm_1x1u_bias_activ_fused.cpp
  src/solver/conv_bin_winoRxS_fused.cpp
Labels: quality, TESTING_CI_PASSED

#2995 RNN MS solution env update
  src/ocl/rnnocl.cpp
Labels: urgency_blocker

#3004 [MHA] [GTEST] Add Tests for Several Graph API Descriptors
  src/graphapi/graphapi.cpp
  test/gtest/graphapi_enginecfg.cpp
  test/gtest/graphapi_engineheur.cpp
  test/gtest/graphapi_execution_plan.cpp
Labels: enhancement, value_high, urgency_high, TESTING_CI_PASSED, GTest

#3007 [W/A] Link dl to MIOpen tests and fix GTest version in requirements
  dev-requirements.txt
  requirements.txt
  test/gtest/CMakeLists.txt
Labels: bug, value_high, urgency_blocker, complexity_low, workaround

#2982 Rs/layout transpose
  src/include/miopen/tensor.hpp
  src/tensor.cpp
  test/gpu_nchw_nhwc_transpose.cpp
  test/gpu_reference_kernel.cpp
  test/gtest/layout_transpose.cpp
  test/tensor_holder.hpp
  test/tensor_reorder.cpp
Labels: value_middle, urgency_high, TESTING_CI_PASSED

#3003 [MHA] turn on 'negative zero as nan' for FP8 numbers
  src/CMakeLists.txt
  src/kernels/gfx90a.kdb.bz2
Labels: value_high, urgency_blocker, complexity_low, TESTING_CI_PASSED

#2962 [NFC] Move convolution solvers to solver/conv directory (part 1)
  src/CMakeLists.txt
  src/include/miopen/sequences.hpp
  src/solver/conv/conv_asm_1x1u.cpp
  src/solver/conv/conv_asm_1x1u_stride2.cpp
  src/solver/conv/conv_asm_3x3u.cpp
  src/solver/conv/conv_asm_5x10u2v2b1.cpp
  src/solver/conv/conv_asm_5x10u2v2f1.cpp
  src/solver/conv/conv_asm_7x7c3h224w224k64u2v2p3q3f1.cpp
  src/solver/conv/conv_asm_dir_BwdWrW1x1.cpp
  src/solver/conv/conv_asm_dir_BwdWrW3x3.cpp
  src/solver/conv/conv_asm_implicit_gemm_bwd_v4r1_dynamic.cpp
  src/solver/conv/conv_asm_implicit_gemm_gtc_bwd.cpp
  src/solver/conv/conv_asm_implicit_gemm_gtc_bwd_nhwc.cpp
  src/solver/conv/conv_asm_implicit_gemm_gtc_fwd.cpp
  src/solver/conv/conv_asm_implicit_gemm_gtc_fwd_nchwc.cpp
  src/solver/conv/conv_asm_implicit_gemm_gtc_fwd_nhwc.cpp
  src/solver/conv/conv_asm_implicit_gemm_gtc_perf_config.cpp
  src/solver/conv/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp
  src/solver/conv/conv_asm_implicit_gemm_v4r1_dynamic.cpp
  src/solver/conv/conv_asm_implicit_gemm_wrw_gtc_dynamic_xdlops.cpp
  src/solver/conv/conv_asm_implicit_gemm_wrw_v4r1_dynamic.cpp
  src/solver/conv/conv_bin_wino3x3U.cpp
  src/solver/conv/conv_bin_winoRxS.cpp
  src/solver/conv/conv_mlir_igemm_bwd.cpp
  src/solver/conv/conv_mlir_igemm_bwd_xdlops.cpp
  src/solver/conv/conv_mlir_igemm_fwd.cpp
  src/solver/conv/conv_mlir_igemm_fwd_xdlops.cpp
  src/solver/conv/conv_mlir_igemm_wrw.cpp
  src/solver/conv/conv_mlir_igemm_wrw_xdlops.cpp
  src/solver/conv/conv_ocl_dir2D11x11.cpp
  src/solver/conv/conv_ocl_dir2D_bwdWrW_1x1.cpp
  src/solver/conv/conv_ocl_dir2D_bwdWrW_2.cpp
  src/solver/conv/conv_ocl_dir2D_bwdWrW_53.cpp
  src/solver/conv/conv_ocl_dir2Dfwd.cpp
  src/solver/conv/conv_ocl_dir2Dfwd1x1.cpp
  src/solver/conv/conv_ocl_dir2Dfwd_exhaustive_search.cpp
  src/solver/conv/conv_ocl_dir2Dfwdgen.cpp
  src/solver/conv/conv_winoRxS.cpp
  src/solver/conv/fft.cpp
  src/solver/conv/mlir_common.cpp
Labels: quality, complexity_low, TESTING_CI_PASSED
