Repository ROCm/MIOpen, pull requests merged in 2024-08, with the labels that each got.

#3169 [RNN] BWD concurrent imp
  src/CMakeLists.txt
  src/include/miopen/rnn.hpp
  src/include/miopen/rnn/base_ops.hpp
  src/include/miopen/rnn/multi_stream_utils.hpp
  src/include/miopen/rnn/solvers.hpp
  src/include/miopen/rnn/tmp_buffer_utils.hpp
  src/ocl/rnnocl.cpp
  src/rnn.cpp
  src/rnn/Solutions/bwd_multi_stream.cpp
  src/rnn/Solutions/bwd_s_stream.cpp
  src/rnn/Solutions/modular_base.cpp
  src/rnn/selector.cpp
Labels: enhancement, value_high, urgency_blocker, TESTING_CI_PASSED

#3153 GTests renaming: filenames which start with letter C
  test/gtest/cache.cpp
  test/gtest/cat.cpp
  test/gtest/cba_find2_infer.cpp
  test/gtest/cba_infer.cpp
  test/gtest/conv3d_codecov.cpp
  test/gtest/conv3d_test.cpp
  test/gtest/conv_3d.cpp
  test/gtest/conv_api.cpp
  test/gtest/conv_api_strided_tensors.cpp
  test/gtest/conv_ck_igemm_fwd_v6r1_dlops_nchw.cpp
  test/gtest/conv_embed_db.cpp
  test/gtest/conv_extra.cpp
  test/gtest/conv_f8_bwd.cpp
  test/gtest/conv_f8_fwd.cpp
  test/gtest/conv_f8_wrw.cpp
  test/gtest/conv_for_implicit_gemm.cpp
  test/gtest/conv_group.cpp
  test/gtest/conv_hip_igemm_xdlops.cpp
  test/gtest/conv_igemm_dynamic.cpp
  test/gtest/conv_igemm_dynamic_dlops.cpp
  test/gtest/conv_igemm_dynamic_xdlops.cpp
  test/gtest/conv_igemm_dynamic_xdlops_half.cpp
  test/gtest/conv_igemm_dynamic_xdlops_nhwc_bf16.cpp
  test/gtest/conv_igemm_dynamic_xdlops_nhwc_nchw.cpp
  test/gtest/conv_igemm_mlir_bwd_wrw.cpp
  test/gtest/conv_igemm_mlir_fwd.cpp
  test/gtest/conv_igemm_mlir_xdlops_bwd_wrw.cpp
  test/gtest/conv_igemm_mlir_xdlops_fwd.cpp
  test/gtest/conv_trans.cpp
  test/gtest/cpu_multi_head_attention.cpp
Labels: TESTING_CI_PASSED

#3158 Implemented find modes and fallback for FusionPlanDescriptor::Compile
  cmake/ClangTidy.cmake
  src/find_controls.cpp
  src/fusion.cpp
  src/include/miopen/conv_solution.hpp
  src/include/miopen/env.hpp
  src/include/miopen/find_controls.hpp
  src/include/miopen/find_solution.hpp
  src/include/miopen/fusion/problem_description.hpp
  src/include/miopen/fusion/solvers.hpp
  src/include/miopen/handle.hpp
  src/include/miopen/solver.hpp
  src/solver/conv_asm_1x1u_bias_activ_fused.cpp
  src/solver/conv_bin_winoRxS_fused.cpp
  src/solver/conv_ocl_dir2Dfwd_fused.cpp
  src/solver/conv_winoRxS_fused.cpp
Labels: TESTING_CI_PASSED

#3128 [MHA] Implement MHA backward pattern
  src/graphapi/find_engine.cpp
  src/include/miopen/graphapi/opgraph.hpp
  test/gtest/graphapi_capi_mha_backward.cpp
  test/gtest/graphapi_capi_mha_common.hpp
  test/gtest/graphapi_capi_mha_forward.cpp
Labels: enhancement, value_high, TESTING_CI_PASSED

#2970 Reduce calculation prod enhancement in case of inner dim
  docs/reference/index.rst
  driver/CMakeLists.txt
  driver/dm_reducecalculation.cpp
  driver/driver.hpp
  driver/reducecalculation_driver.hpp
  include/miopen/miopen.h
  src/CMakeLists.txt
  src/include/miopen/reduce/invoke_params.hpp
  src/include/miopen/reduce/problem_description.hpp
  src/include/miopen/reduce/solvers.hpp
  src/include/miopen/reduce/utils.hpp
  src/include/miopen/reducecalculation.hpp
  src/kernels/MIOpenReduceCalculation.cpp
  src/kernels/MIOpenReduceCalculation.hpp
  src/kernels/MIOpenSum.cpp
  src/reduce/problem_description.cpp
  src/reducecalculation.cpp
  src/reducecalculation_api.cpp
  src/reduceextreme.cpp
  src/reduceextreme_api.cpp
  src/solver/reduce/forward_argmax.cpp
  src/solver/reduce/forward_argmin.cpp
  src/solver/reduce/forward_max.cpp
  src/solver/reduce/forward_min.cpp
  src/solver/reduce/forward_prod.cpp
  src/sum.cpp
  src/sum_api.cpp
  test/gtest/reducecalculation.cpp
  test/gtest/reducecalculation.hpp
  test/gtest/sum.cpp
  test/gtest/sum.hpp
Labels: enhancement, TESTING_CI_PASSED, external_collaborator

#3177 Deduplicated ValidateGroupCount and fixed incorrect usage
  src/ocl/convolutionocl.cpp
  src/problem.cpp
Labels: bug, value_high, urgency_blocker, complexity_low, TESTING_CI_PASSED

#3154 [WORKAROUND] Allow to use boost:filesystem instead of std::filesystem, [BUGFIX] check_cxx_linker_flag
  CMakeLists.txt
  addkernels/CMakeLists.txt
  cmake/CheckCXXLinkerFlag.cmake
  include/miopen/config.h.in
  src/db.cpp
  src/include/miopen/filesystem.hpp
  src/include/miopen/sqlite_db.hpp
  src/load_file.cpp
  src/lock_file.cpp
Labels: non-miopen-bug, workaround, urgency_high

#3178 GTests renaming: filenames which start with letters D-G
  test/gtest/cache.cpp
  test/gtest/db_sync.cpp
  test/gtest/deepbench_conv.cpp
  test/gtest/deepbench_gru.cpp
  test/gtest/deepbench_lstm.cpp
  test/gtest/deepbench_rnn.cpp
  test/gtest/dumpTensorTest.cpp
  test/gtest/execute_primitive.cpp
  test/gtest/fused_conv_bias_res_add_activ.cpp
  test/gtest/fusion_test.cpp
  test/gtest/getitem.cpp
  test/gtest/gpu_mha_backward.cpp
  test/gtest/gpu_mha_forward.cpp
  test/gtest/graphapi_capi_mha_backward.cpp
  test/gtest/graphapi_capi_mha_forward.cpp
  test/gtest/graphapi_conv_bias_res_add_activ_fwd.cpp
  test/gtest/graphapi_convolution.cpp
  test/gtest/graphapi_engine.cpp
  test/gtest/graphapi_enginecfg.cpp
  test/gtest/graphapi_engineheur.cpp
  test/gtest/graphapi_execution_plan.cpp
  test/gtest/graphapi_matmul.cpp
  test/gtest/graphapi_mha_fwd_f8.cpp
  test/gtest/graphapi_operation_matmul.cpp
  test/gtest/graphapi_operation_pointwise.cpp
  test/gtest/graphapi_operation_reduction.cpp
  test/gtest/graphapi_operation_reshape.cpp
  test/gtest/graphapi_operation_rng.cpp
  test/gtest/graphapi_operationgraph_descriptor.cpp
  test/gtest/graphapi_opgraph.cpp
  test/gtest/graphapi_opgraph_matching.cpp
  test/gtest/graphapi_pointwise.cpp
  test/gtest/graphapi_reduction.cpp
  test/gtest/graphapi_rng.cpp
  test/gtest/graphapi_tensor.cpp
  test/gtest/graphapi_variant_pack.cpp
  test/gtest/group_conv.hpp
  test/gtest/group_conv2d_bwd.cpp
  test/gtest/group_conv2d_fwd.cpp
  test/gtest/group_conv2d_wrw.cpp
  test/gtest/group_conv3d_bwd.cpp
  test/gtest/group_conv3d_fwd.cpp
  test/gtest/group_conv3d_wrw.cpp
  test/gtest/groupnorm.cpp
  test/gtest/gru_extra.cpp
  test/gtest/gtest_activation.cpp
Labels: TESTING_CI_PASSED

#3180 RNN wall clock timer update
  driver/rnn_driver.hpp
  driver/rnn_seq_driver.hpp
  driver/timer.hpp
Labels: complexity_low, urgency_normal, TESTING_CI_PASSED

#3161 Add pattern and executor for ConvBiasResAddActiv GraphAPI
  src/CMakeLists.txt
  src/graphapi/conv_bias_res_add_activ_forward_executor.cpp
  src/graphapi/find_engine.cpp
  src/include/miopen/graphapi/conv_bias_res_add_activ_forward_executor.hpp
  src/include/miopen/graphapi/variant_pack.hpp
  test/gtest/graphapi_conv_bias_res_add_activ_fwd.cpp
  test/gtest/graphapi_variant_pack.cpp
Labels: value_middle, complexity_middle, urgency_normal, TESTING_CI_PASSED

#3186 [RNN] WA for tensors with more than 3 dims.
  src/include/miopen/rnn/tmp_buffer_utils.hpp
  test/rnn_seq_api.cpp
  test/rnn_seq_api.hpp
Labels: urgency_blocker, complexity_low, TESTING_CI_PASSED

#3184 [Fix][TransformTensor] Ignore output buffer when BETA=0
  src/kernels/MIOpenSubTensorOpWithTransformKernel.cl
  src/ocl/tensorocl.cpp
Labels: bug, urgency_blocker, TESTING_CI_PASSED, correctness

#3130 MI300 TunaNet Update: CK FWD and WRW Solvers Updated
  src/conv/heuristics/ai_heuristics.cpp
  src/kernels/gfx942.tn.model
  src/kernels/gfx942_metadata.tn.model
Labels: urgency_high, TESTING_CI_PASSED, IMPACTS_API

#3088 Dropout kernel OpenCL to HIP + gtest
  src/CMakeLists.txt
  src/kernels/MIOpenDropoutHIP.cpp
  test/gtest/dropout_ocl_hip.cpp
  test/gtest/perf_helper.hpp
Labels: TESTING_CI_PASSED

#3187 [RNN] MS heuristic update
  src/include/miopen/rnn/multi_stream_utils.hpp
Labels: complexity_low, TESTING_CI_PASSED

#3162 Update Conv3DTestCase to use structs
  test/gtest/conv3d_test_case.hpp
  test/gtest/conv_f8_bwd.cpp
  test/gtest/conv_f8_fwd.cpp
  test/gtest/conv_f8_wrw.cpp
  test/gtest/fused_conv_bias_res_add_activ.cpp
  test/gtest/graphapi_conv_bias_res_add_activ_fwd.cpp
  test/gtest/nonpack_conv3d_fwd.hpp
Labels: value_low, complexity_low, urgency_low, TESTING_CI_PASSED, GTest

#3097 Backward MHA test using C++ API
  test/gtest/graphapi_mha_bwd.cpp
  test/gtest/graphapi_mha_cpp_common.hpp
  test/gtest/graphapi_mha_fwd_f8.cpp
  test/gtest/gtest_common.hpp
Labels: urgency_blocker, TESTING_CI_PASSED

#3194 Revert "[Fix][TransformTensor] Ignore output buffer when BETA=0 (#3184)"
  src/kernels/MIOpenSubTensorOpWithTransformKernel.cl
  src/ocl/tensorocl.cpp
Labels: urgency_blocker

#3191 Update CK without new base ROCm renew
  requirements.txt
Labels: urgency_blocker, TESTING_CI_PASSED

#3175 [gtest] Unit test for ConvWinoFuryRxS
  src/include/miopen/handle.hpp
  src/include/miopen/solver.hpp
  src/solver/conv/conv_wino_fury_RxS.cpp
  test/get_handle.hpp
  test/gtest/CMakeLists.txt
  test/gtest/bn.hpp
  test/gtest/cba.hpp
  test/gtest/cba_find2.hpp
  test/gtest/cba_find2_infer.cpp
  test/gtest/cba_infer.cpp
  test/gtest/conv_test_base.hpp
  test/gtest/db_sync.cpp
  test/gtest/gtest_common.cpp
  test/gtest/gtest_common.hpp
  test/gtest/smoke_solver_ConvWinogradFuryRxSf2x3_f16.cpp
  test/gtest/solver_bwd.hpp
  test/gtest/solver_bwd_f8.cpp
  test/gtest/solver_convasm3x3u.cpp
  test/gtest/solver_fwd.hpp
  test/gtest/solver_fwd_f8.cpp
  test/gtest/solver_wrw.hpp
  test/gtest/solver_wrw_f8.cpp
  test/gtest/unit_conv_solver.cpp
  test/gtest/unit_conv_solver.hpp
  test/gtest/unit_conv_solver_ConvWinoFuryRxS.cpp
Labels: enhancement, value_high, quality, testing, urgency_high, TESTING_CI_PASSED, correctness

#3195 Update CK commit hash to include fix for gfx12
  requirements.txt
Labels: urgency_blocker, TESTING_CI_PASSED

#3196 Replace sync hipMemset with async hipMemset
  src/include/miopen/solver/implicitgemm_ck_util.hpp
Labels: bug, urgency_high

#3200 [WA] Disable MLIR when building debug to workaround sanitizer issue
  Jenkinsfile
  test/nightlies/JenkinsfileNightlyAux
  test/nightlies/JenkinsfileNightlyConv2D
  test/nightlies/JenkinsfileNightlyConv2Daux
  test/nightlies/JenkinsfileNightlyFastFullConv2D
  test/nightlies/JenkinsfileNightlyFusions
  test/nightlies/JenkinsfileNightlyRNN
  test/nightlies/JenkinsfileNightlyReduce
  test/nightlies/JenkinsfileNightlyTensorOps
Labels: non-miopen-bug, urgency_blocker, complexity_low, workaround, TESTING_CI_PASSED

#3181 Update docker ROCm version for CI
  .clang-tidy
  CMakeLists.txt
  Dockerfile
  Jenkinsfile
  src/comgr.cpp
Labels: urgency_blocker, TESTING_CI_PASSED

#3203 fix bn layout network config caching issue
  src/batchnorm/problem_description.cpp
  src/include/miopen/batchnorm/problem_description.hpp
Labels: urgency_high, TESTING_CI_PASSED

#3211 Reapplied and fixed #3194
  src/kernels/MIOpenSubTensorOpWithTransformKernel.cl
  src/ocl/tensorocl.cpp
Labels: urgency_blocker, complexity_low

#3157 Fixed Find 2.0 fusion ignoring miopenSetFindOptionTuning
  src/fusion.cpp
  src/include/miopen/fusion/context.hpp
Labels: value_middle, complexity_low, TESTING_CI_PASSED

#3202 [Tests]All tests in the same test suite must use the same test fixture class
  test/gtest/conv3d_codecov.cpp
  test/gtest/conv3d_test.cpp
Labels: TESTING_CI_PASSED, GTest

#3209 GTests renaming: filenames which start with letters H-M
  test/gtest/hipblaslt_gemm.cpp
  test/gtest/immed_conv2d_codecov.cpp
  test/gtest/immed_conv3d_codecov.cpp
  test/gtest/kernel_tuning_net.cpp
  test/gtest/layernorm.cpp
  test/gtest/layout_transpose.cpp
  test/gtest/log_test.cpp
  test/gtest/log_test_neg.cpp
  test/gtest/lstm_extra.cpp
  test/gtest/mha_find20.cpp
  test/gtest/miopen_conv.cpp
  test/gtest/miopendriver_conv2d_trans.cpp
  test/gtest/miopendriver_gemm.cpp
  test/gtest/miopendriver_regression_big_tensor.cpp
  test/gtest/miopendriver_regression_float_half_gfx10.cpp
  test/gtest/miopendriver_regression_half.cpp
  test/gtest/miopendriver_regression_half_gfx9.cpp
  test/gtest/miopendriver_regression_int8.cpp
  test/gtest/miopendriver_regression_issue_1576.cpp
  test/gtest/mt_queue.cpp
Labels: TESTING_CI_PASSED

#3216 GTests renaming: filenames which start with letters N-R
  test/gtest/na_infer.cpp
  test/gtest/nonpack_conv3d_fwd.cpp
  test/gtest/pooling2d_asymmetric.cpp
  test/gtest/pooling2d_codecov.cpp
  test/gtest/pooling2d_wide.cpp
  test/gtest/reduce_custom_fp32.cpp
  test/gtest/reduce_custom_fp32_fp16.cpp
  test/gtest/reducecalculation.cpp
  test/gtest/reduceextreme.cpp
  test/gtest/regression_float_mi100.cpp
  test/gtest/regression_half_mi100.cpp
  test/gtest/regression_half_mi200.cpp
  test/gtest/regression_half_vega_gfx908.cpp
  test/gtest/regression_issue_2012.cpp
  test/gtest/rnn_extra.cpp
  test/gtest/rope.cpp
Labels: TESTING_CI_PASSED

#3218 Add gtest name checker
  Jenkinsfile
  test/gtest/CMakeLists.txt
  test/gtest/check_names.py
Labels: complexity_low, TESTING_CI_PASSED, GTest

#3221 GTests renaming: filenames which start with letter S
  test/gtest/smoke_solver_ConvAsmImplicitGemmGTCDynamicFwdDlopsNCHWC.cpp
  test/gtest/smoke_solver_ConvAsmImplicitGemmGTCDynamicXdlops.cpp
  test/gtest/smoke_solver_ConvAsmImplicitGemmGTCDynamicXdlopsNHWC_bf16.cpp
  test/gtest/smoke_solver_ConvAsmImplicitGemmGTCDynamicXdlopsNHWC_fp32_fp16.cpp
  test/gtest/smoke_solver_ConvAsmImplicitGemmV4R1Dynamic.cpp
  test/gtest/smoke_solver_ConvAsm_5x10_7x7.cpp
  test/gtest/smoke_solver_ConvBinWinograd3x3U.cpp
  test/gtest/smoke_solver_ConvBinWinogradRxS_fp16.cpp
  test/gtest/smoke_solver_ConvBinWinogradRxS_fp32.cpp
  test/gtest/smoke_solver_ConvBinWinogradRxSf2x3.cpp
  test/gtest/smoke_solver_ConvBinWinogradRxSf2x3g1.cpp
  test/gtest/smoke_solver_ConvBinWinogradRxSf2x3g1_3x2_f16.cpp
  test/gtest/smoke_solver_ConvBinWinogradRxSf2x3g1_3x2_f32.cpp
  test/gtest/smoke_solver_ConvBinWinogradRxSf3x2.cpp
  test/gtest/smoke_solver_ConvCkIgemmFwdV6r1DlopsNchw.cpp
  test/gtest/smoke_solver_ConvDirectNaiveConv_Bw.cpp
  test/gtest/smoke_solver_ConvDirectNaiveConv_F.cpp
  test/gtest/smoke_solver_ConvFFT.cpp
  test/gtest/smoke_solver_ConvHipImplicitGemmBwdDataV1R1.cpp
  test/gtest/smoke_solver_ConvHipImplicitGemmBwdDataV1R1Xdlops.cpp
  test/gtest/smoke_solver_ConvHipImplicitGemmBwdDataV4R1.cpp
  test/gtest/smoke_solver_ConvHipImplicitGemmDataV4RxXdlops.cpp
  test/gtest/smoke_solver_ConvHipImplicitGemmV4R1Fwd_fp16_bf16.cpp
  test/gtest/smoke_solver_ConvHipImplicitGemmV4R1Fwd_fp32.cpp
  test/gtest/smoke_solver_ConvHipImplicitGemmV4R1WrW.cpp
  test/gtest/smoke_solver_ConvHipImplicitGemmV4R4.cpp
  test/gtest/smoke_solver_ConvOclBwdWrW1x1.cpp
  test/gtest/smoke_solver_ConvOcl_Fwd11x11_FwdGen_WrW53.cpp
  test/gtest/smoke_solver_convasm.cpp
  test/gtest/smoke_solver_convasm1x1u.cpp
  test/gtest/smoke_solver_convasmbwdwrw.cpp
  test/gtest/smoke_solver_convasmbwdwrw3x3_fp16.cpp
  test/gtest/smoke_solver_convasmbwdwrw3x3_fp32.cpp
  test/gtest/softmax_find20.cpp
  test/gtest/solver_bwd_f8.cpp
  test/gtest/solver_convasm3x3u.cpp
  test/gtest/solver_fwd_f8.cpp
  test/gtest/solver_wrw_f8.cpp
Labels: TESTING_CI_PASSED, GTest
