Repository ROCm/MIOpen, pull requests merged in 2024-10, with the labels that each got.

#3287 Cherry-pick to release/rocm-rel-6.2: [Doc] Add reference to find modes to the performance database topic (…
  docs/conceptual/perfdb.rst
  docs/how-to/find-and-immediate.rst
Labels: documentation

#3288 Cherry-pick to docs/6.2.2: [Doc] Add reference to find modes to the performance database topic (…
  docs/conceptual/perfdb.rst
  docs/how-to/find-and-immediate.rst
Labels: documentation

#3289 Cherry-pick to docs/6.2.1: [Doc] Add reference to find modes to the performance database topic (…
  docs/conceptual/perfdb.rst
  docs/how-to/find-and-immediate.rst
Labels: documentation

#3290 Cherry-pick to docs/6.2.0: [Doc] Add reference to find modes to the performance database topic (…
  docs/conceptual/perfdb.rst
  docs/how-to/find-and-immediate.rst
Labels: documentation

#3283 Fix driver being leaked in MIOpenDriver
  driver/main.cpp
Labels: bug, value_middle, complexity_low, urgency_normal, TESTING_CI_PASSED

#3284 [BugFix] Fix ConvDirectNaiveConvFwd not applicable after #3213
  src/conv/problem_description.cpp
  src/include/miopen/conv/problem_description.hpp
Labels: bug, urgency_high, TESTING_CI_PASSED

#3282 [TEST] forbid GPU tests without explicit datatypes
  test/gtest/check_names.py
  test/gtest/kernel_tuning_net.cpp
Labels: urgency_high, TESTING_CI_PASSED, GTest

#3285 Fixed incorrect transpose in find 2.0
  src/problem.cpp
Labels: bug, value_high, complexity_low, urgency_high

#3204 Impl Kthvalue operation
  docs/reference/index.rst
  driver/CMakeLists.txt
  driver/dm_kthvalue.cpp
  driver/driver.hpp
  driver/kthvalue_driver.hpp
  include/miopen/miopen.h
  src/CMakeLists.txt
  src/include/miopen/kthvalue.hpp
  src/include/miopen/kthvalue/invoke_params.hpp
  src/include/miopen/kthvalue/problem_description.hpp
  src/include/miopen/kthvalue/solvers.hpp
  src/include/miopen/reduce/problem_description.hpp
  src/include/miopen/solver_id.hpp
  src/include/miopen/tensor_view_utils.hpp
  src/kernels/MIOpenKthvalue.cpp
  src/kernels/radix.hpp
  src/kthvalue.cpp
  src/kthvalue/problem_description.cpp
  src/kthvalue_api.cpp
  src/solver.cpp
  src/solver/kthvalue/forward_kthvalue.cpp
  test/cpu_kthvalue.hpp
  test/gtest/kthvalue.cpp
  test/gtest/kthvalue.hpp
Labels: enhancement, TESTING_CI_PASSED, external_collaborator

#3269 [GTests Refactoring] Removing MIOPEN_TEST_ALL and MIOPEN_TEST_FLOAT_ARG env variables. Part 1.
  test/gtest/adam.cpp
  test/gtest/addlayernorm.cpp
  test/gtest/cat.cpp
  test/gtest/conv_3d.cpp
  test/gtest/conv_ck_igemm_fwd_v6r1_dlops_nchw.cpp
  test/gtest/conv_extra.cpp
  test/gtest/conv_for_implicit_gemm.cpp
  test/gtest/conv_group.cpp
  test/gtest/conv_hip_igemm_xdlops.cpp
  test/gtest/conv_igemm_dynamic.cpp
  test/gtest/conv_igemm_dynamic_dlops.cpp
  test/gtest/conv_igemm_dynamic_xdlops.cpp
Labels: TESTING_CI_PASSED

#3278 [GTests Refactoring] Removing MIOPEN_TEST_ALL and MIOPEN_TEST_FLOAT_ARG env variables. Part 3.
  test/gtest/getitem.cpp
  test/gtest/gpu_mha_backward.cpp
  test/gtest/gpu_mha_forward.cpp
  test/gtest/groupnorm.cpp
  test/gtest/gru_extra.cpp
  test/gtest/lstm_extra.cpp
  test/gtest/pooling2d_asymmetric.cpp
  test/gtest/pooling2d_wide.cpp
  test/gtest/prelu.cpp
Labels: TESTING_CI_PASSED

#3286 [GTests Refactoring] Removing MIOPEN_TEST_ALL and MIOPEN_TEST_FLOAT_ARG env variables. Part 4.
  test/gtest/reduce_custom_fp32.cpp
  test/gtest/reduce_custom_fp32_fp16.cpp
  test/gtest/reducecalculation.cpp
  test/gtest/reduceextreme.cpp
  test/gtest/regression_float_mi100.cpp
  test/gtest/regression_half_mi100.cpp
  test/gtest/rnn_extra.cpp
  test/gtest/rope.cpp
  test/gtest/t5layernorm.cpp
  test/gtest/transformers_adam_w.cpp
  test/gtest/unit_ActivationDescriptor.cpp
Labels: TESTING_CI_PASSED

#3291 Fix ReadonlyRamDb memory leak
  src/readonlyramdb.cpp
Labels: TESTING_CI_PASSED

#3277 Add ck mha fp16 solver
  CMakeLists.txt
  requirements.txt
  src/CMakeLists.txt
  src/include/miopen/mha/solvers.hpp
  src/problem.cpp
  src/solution.cpp
  src/solver.cpp
  src/solver/mha/mha_ck_fa_v2_solver_forward.cpp
Labels: value_middle, complexity_middle, urgency_normal

#3226 Implement SoftMarginLoss
  driver/CMakeLists.txt
  driver/dm_softmarginloss.cpp
  driver/driver.hpp
  driver/softmarginloss_driver.hpp
  include/miopen/miopen.h
  src/CMakeLists.txt
  src/include/miopen/softmarginloss.hpp
  src/include/miopen/softmarginloss/invoke_params.hpp
  src/include/miopen/softmarginloss/problem_description.hpp
  src/include/miopen/softmarginloss/solvers.hpp
  src/include/miopen/solver_id.hpp
  src/include/miopen/tensor_view_utils.hpp
  src/kernels/MIOpenReduceSum.cpp
  src/kernels/MIOpenSoftMarginLoss.cpp
  src/softmarginloss.cpp
  src/softmarginloss/problem_description.cpp
  src/softmarginloss_api.cpp
  src/solver.cpp
  src/solver/softmarginloss/backward_softmarginloss.cpp
  src/solver/softmarginloss/forward_softmarginloss.cpp
  test/cpu_softmarginloss.hpp
  test/gtest/softmarginloss.cpp
  test/gtest/softmarginloss.hpp
Labels: enhancement, external_collaborator

#3299 [BUG] fix for memcopy data race
  src/hip/handlehip.cpp
Labels: bug, complexity_low, TESTING_CI_PASSED

#3293 [Docs] Cherry pick - Bump rocm-docs-core[api_reference] from 1.7.2 to 1.8.2 in /docs/sphinx (#3271)
  docs/sphinx/requirements.in
  docs/sphinx/requirements.txt
Labels: documentation

#3166 Implement MultiMarginLoss forward
  driver/CMakeLists.txt
  driver/dm_multimarginloss.cpp
  driver/driver.hpp
  driver/multimarginloss_driver.hpp
  driver/softmarginloss_driver.hpp
  include/miopen/miopen.h
  src/CMakeLists.txt
  src/include/miopen/multimarginloss.hpp
  src/include/miopen/multimarginloss/invoke_params.hpp
  src/include/miopen/multimarginloss/problem_description.hpp
  src/include/miopen/multimarginloss/solvers.hpp
  src/include/miopen/solver_id.hpp
  src/include/miopen/tensor_view_utils.hpp
  src/kernels/MIOpenMultiMarginLoss.cpp
  src/multimarginloss.cpp
  src/multimarginloss/problem_description.cpp
  src/multimarginloss_api.cpp
  src/solver.cpp
  src/solver/multimarginloss/forward_multimarginloss.cpp
  src/solver/prelu/backward_prelu_multi_weights.cpp
  src/solver/prelu/backward_prelu_single_weight.cpp
  test/cpu_multimarginloss.hpp
  test/gtest/multimarginloss.cpp
  test/gtest/multimarginloss.hpp
  test/gtest/softmarginloss.hpp
  test/tensor_holder.hpp
Labels: enhancement, TESTING_CI_PASSED, external_collaborator

#3275 Merging forward and backward kernels into one
  src/dropout_api.cpp
  src/include/miopen/dropout.hpp
  src/kernels/MIOpenDropoutHIP.cpp
  src/ocl/dropoutocl.cpp
  src/ocl/rnnocl.cpp
  src/rnn/Solutions/Base/bw_data_modular.cpp
  test/dropout.cpp
Labels: quality, TESTING_CI_PASSED

#3300 [GTests Refactoring] Removing MIOPEN_TEST_ALL and MIOPEN_TEST_FLOAT_ARG env variables. Part 6 (small)
  test/gtest/regression_half_mi200.cpp
  test/gtest/regression_issue_2012.cpp
  test/gtest/softmarginloss.cpp
Labels: TESTING_CI_PASSED

#3281 Update output expectations for ck tests.
  test/gtest/kernel_tuning_net.cpp
Labels: TESTING_CI_PASSED

#3304 Add tests for ck mha fp16 solver
  src/solver/mha/mha_ck_fa_v2_solver_forward.cpp
  test/gtest/gpu_mha_forward.cpp
  test/gtest/graphapi_capi_mha_common.hpp
  test/gtest/graphapi_capi_mha_forward.cpp
  test/gtest/mha_helper.hpp
Labels: value_middle, complexity_middle, urgency_normal, TESTING_CI_PASSED

#3306 Setting MIOPEN_TEST_ALL and MIOPEN_TEST_FLOAT_ARG env variables is removed in cmake
  test/gtest/CMakeLists.txt
Labels: TESTING_CI_PASSED

#3307 Update package name from miopen-hip-client to miopen-hip-clients
  CMakeLists.txt
Labels: TESTING_CI_PASSED

#3302 Update CK commit hash for staging
  Dockerfile
  Jenkinsfile
  requirements.txt
Labels: TESTING_CI_PASSED

#3309 GTests Refactoring: Merge to Develop From Integration branch
  test/gtest/CMakeLists.txt
  test/gtest/adam.cpp
  test/gtest/addlayernorm.cpp
  test/gtest/cat.cpp
  test/gtest/conv3d_test.cpp
  test/gtest/conv_3d.cpp
  test/gtest/conv_ck_igemm_fwd_v6r1_dlops_nchw.cpp
  test/gtest/conv_extra.cpp
  test/gtest/conv_for_implicit_gemm.cpp
  test/gtest/conv_group.cpp
  test/gtest/conv_hip_igemm_xdlops.cpp
  test/gtest/conv_igemm_dynamic.cpp
  test/gtest/conv_igemm_dynamic_dlops.cpp
  test/gtest/conv_igemm_dynamic_xdlops.cpp
  test/gtest/conv_igemm_dynamic_xdlops_half.cpp
  test/gtest/conv_igemm_dynamic_xdlops_nhwc_bf16.cpp
  test/gtest/conv_igemm_dynamic_xdlops_nhwc_nchw.cpp
  test/gtest/conv_igemm_mlir_bwd_wrw.cpp
  test/gtest/conv_igemm_mlir_fwd.cpp
  test/gtest/conv_igemm_mlir_xdlops_bwd_wrw.cpp
  test/gtest/conv_igemm_mlir_xdlops_fwd.cpp
  test/gtest/conv_trans.cpp
  test/gtest/deepbench_rnn.cpp
  test/gtest/fused_conv_bias_res_add_activ.cpp
  test/gtest/getitem.cpp
  test/gtest/gpu_mha_backward.cpp
  test/gtest/gpu_mha_forward.cpp
  test/gtest/groupnorm.cpp
  test/gtest/gru_extra.cpp
  test/gtest/gtest_env_check_common.hpp
  test/gtest/kthvalue.cpp
  test/gtest/layernorm.cpp
  test/gtest/lstm_extra.cpp
  test/gtest/miopendriver_common.hpp
  test/gtest/miopendriver_conv2d_trans.cpp
  test/gtest/miopendriver_gemm.cpp
  test/gtest/miopendriver_regression_big_tensor.cpp
  test/gtest/miopendriver_regression_float_half_gfx10.cpp
  test/gtest/miopendriver_regression_half.cpp
  test/gtest/miopendriver_regression_half_gfx9.cpp
  test/gtest/miopendriver_regression_int8.cpp
  test/gtest/miopendriver_regression_issue_1576.cpp
  test/gtest/pooling2d_asymmetric.cpp
  test/gtest/pooling2d_wide.cpp
  test/gtest/prelu.cpp
  test/gtest/reduce_custom_fp32.cpp
  test/gtest/reduce_custom_fp32_fp16.cpp
  test/gtest/reducecalculation.cpp
  test/gtest/reduceextreme.cpp
  test/gtest/regression_float_mi100.cpp
  test/gtest/regression_half_mi100.cpp
  test/gtest/regression_half_mi200.cpp
  test/gtest/regression_issue_2012.cpp
  test/gtest/rnn_extra.cpp
  test/gtest/rope.cpp
  test/gtest/softmarginloss.cpp
  test/gtest/t5layernorm.cpp
  test/gtest/transformers_adam_w.cpp
  test/gtest/unit_ActivationDescriptor.cpp
Labels: TESTING_CI_PASSED

#3305 Op2dTensorGeneric kernel upgrade
  src/kernels/MIOpenTensorKernels.cl
  src/kernels/MIOpenTensorKernelsHip.cpp
  src/ocl/tensorocl.cpp
  test/gtest/tensor_2d_gen_ocl_hip.cpp
Labels: performance, quality, complexity_middle, TESTING_CI_PASSED

#3315 Update CK commit hash to resolve build issues with examples
  requirements.txt
Labels: TESTING_CI_PASSED

#3319 gfx942kdb update
  CMakeLists.txt
  src/kernels/gfx942.kdb.bz2
Labels: urgency_high, TESTING_CI_PASSED

#3308 Merge CK fwd mha FP16 solver
  CMakeLists.txt
  src/CMakeLists.txt
  src/include/miopen/mha/solvers.hpp
  src/problem.cpp
  src/solution.cpp
  src/solver.cpp
  src/solver/mha/mha_ck_fa_v2_solver_forward.cpp
  test/gtest/cpu_multi_head_attention.hpp
  test/gtest/gpu_mha_backward.cpp
  test/gtest/gpu_mha_forward.cpp
  test/gtest/graphapi_capi_mha_backward.cpp
  test/gtest/graphapi_capi_mha_common.hpp
  test/gtest/graphapi_capi_mha_forward.cpp
  test/gtest/graphapi_mha_cpp_common.hpp
  test/gtest/mha_helper.hpp
Labels: value_middle, complexity_middle, urgency_normal, TESTING_CI_PASSED

#3320 [RNN] LSTM fwd
  src/CMakeLists.txt
  src/include/miopen/rnn.hpp
  src/include/miopen/rnn/base_ops.hpp
  src/include/miopen/rnn/solvers.hpp
  src/ocl/rnnocl.cpp
  src/rnn/Solutions/Base/fw_data_modular.cpp
  src/rnn/Solutions/fwd_s_stream.cpp
  src/rnn/selector.cpp
Labels: TESTING_CI_PASSED

#3316 Updating CK commit and fix dockerfile out of sync issue
  Dockerfile
  requirements.txt
Labels: TESTING_CI_PASSED

#3324 Initial porting of Op3dTensorGeneric kernel from OCL ot HIP
  src/kernels/MIOpenTensorKernelsHip.cpp
  test/gtest/tensor_3d_generic_ocl_hip.cpp
Labels: complexity_low, TESTING_CI_PASSED

#3328 [DOC] Add readme note and metadata
  README.md
  docs/license.md
Labels: documentation

#3317 Tensor 1d generic kernel 64b support
  src/kernels/MIOpenTensorKernelsHip.cpp
  src/ocl/tensorocl.cpp
Labels: TESTING_CI_PASSED

#3313 Dropout kernel 64b support
  src/kernels/MIOpenDropoutHIP.cpp
  src/ocl/dropoutocl.cpp
Labels: TESTING_CI_PASSED

#3329 [GTests refactoring] Removing usage of environment variables for DISCRETE tests
  Jenkinsfile
  include/miopen/config.h.in
  test/gtest/CMakeLists.txt
  test/gtest/conv3d_codecov.cpp
  test/gtest/conv_embed_db.cpp
  test/gtest/conv_hip_igemm_xdlops.cpp
  test/gtest/conv_igemm_mlir_bwd_wrw.cpp
  test/gtest/conv_igemm_mlir_fwd.cpp
  test/gtest/conv_igemm_mlir_xdlops_bwd_wrw.cpp
  test/gtest/conv_igemm_mlir_xdlops_fwd.cpp
  test/gtest/db_sync.cpp
  test/gtest/deepbench_conv.cpp
  test/gtest/deepbench_gru.cpp
  test/gtest/deepbench_lstm.cpp
  test/gtest/deepbench_rnn.cpp
  test/gtest/immed_conv2d_codecov.cpp
  test/gtest/immed_conv3d_codecov.cpp
  test/gtest/miopen_conv.cpp
  test/gtest/miopendriver_common.hpp
  test/gtest/pooling2d_asymmetric.cpp
  test/gtest/pooling2d_codecov.cpp
  test/gtest/pooling2d_wide.cpp
Labels: TESTING_CI_PASSED, GTest

#3326 Enable tuning in Batch norm CK solver
  src/batchnorm/problem_description.cpp
  src/include/miopen/batchnorm/invoke_params.hpp
  src/include/miopen/batchnorm/problem_description.hpp
  src/include/miopen/batchnorm/solvers.hpp
  src/include/miopen/conv/problem_description.hpp
  src/include/miopen/problem_description_base.hpp
  src/ocl/batchnormocl.cpp
  src/solver/batchnorm/backward_ck.cpp
  src/solver/batchnorm/forward_inference_ck.cpp
  src/solver/batchnorm/forward_per_activation.cpp
  src/solver/batchnorm/forward_spatial_multiple.cpp
  src/solver/batchnorm/forward_spatial_single.cpp
  src/solver/batchnorm/forward_training_ck.cpp
  src/solver/conv_ck_igemm_fwd_bias_activ_fused.cpp
  src/solver/mha/mha_ck_fa_v2_solver_forward.cpp
Labels: urgency_high, TESTING_CI_PASSED

#3336 Update license file
  LICENSE.txt
Labels: documentation

#3334 [GTEST]Fix miopen_gtest missing from package
  test/gtest/CMakeLists.txt
Labels: TESTING_CI_PASSED, GTest

#3332 Merge all bn ck nchw branches
  driver/bn_driver.hpp
  src/include/miopen/batchnorm/problem_description.hpp
  src/ocl/batchnormocl.cpp
  src/solver/batchnorm/backward_ck.cpp
  src/solver/batchnorm/forward_inference_ck.cpp
  src/solver/batchnorm/forward_training_ck.cpp
  test/bn_3d_spatial_test.cpp
  test/bn_spatial_test.cpp
  test/gtest/bn.hpp
  test/gtest/bn_bwd.cpp
  test/gtest/bn_fwd_train.cpp
  test/gtest/bn_infer.cpp
Labels: TESTING_CI_PASSED

#3340 Cherry-pick to docs/6.2.4: [Doc] Update license file (#3336)
  LICENSE.txt
Labels: documentation

#3338 Cherry-pick to release/rocm-rel-6.3: [Doc] Update license file (#3336)
  LICENSE.txt
Labels: documentation

#3339 Cherry-pick to release/rocm-rel-6.2: [Doc] Update license file (#3336)
  LICENSE.txt
Labels: documentation

#3347 fix driver for old ocl kernel
  driver/bn_driver.hpp
  driver/dm_bnorm.cpp
  test/gtest/bn_bwd.cpp
Labels: urgency_high, TESTING_CI_PASSED
