Repository ROCm/MIOpen, pull requests merged in 2024-09, with the labels that each got.

#3224 [Tests] skip cba test for unsupported platforms
  test/gtest/cba_find2_infer.cpp
  test/gtest/fusion_test.cpp
  test/gtest/graphapi_conv_bias_res_add_activ_fwd.cpp
  test/gtest/gtest_common.cpp
  test/gtest/gtest_common.hpp
  test/gtest/unit_conv_solver_GemmBwd1x1_stride1.cpp
  test/gtest/unit_conv_solver_GemmBwd1x1_stride2.cpp
  test/gtest/unit_conv_solver_GemmBwdRest.cpp
  test/gtest/unit_conv_solver_GemmFwd1x1_0_1.cpp
  test/gtest/unit_conv_solver_GemmFwd1x1_0_1_int8.cpp
  test/gtest/unit_conv_solver_GemmFwd1x1_0_2.cpp
  test/gtest/unit_conv_solver_GemmFwdRest.cpp
  test/gtest/unit_conv_solver_GemmWrw1x1_stride1.cpp
  test/gtest/unit_conv_solver_GemmWrwUniversal.cpp
Labels: urgency_blocker, TESTING_CI_PASSED

#3231 Fix implementation with average and update reference links
  src/CMakeLists.txt
  src/process.cpp
  test/driver.hpp
Labels: urgency_blocker, complexity_low

#3220 [gTests]Fix GTEST_SKIP kills all gtests in miopen_gtest
  test/gtest/api_convbiasactiv.cpp
Labels: TESTING_CI_PASSED, GTest

#3219 [RNN] LSTM backward weight update
  src/CMakeLists.txt
  src/include/miopen/rnn.hpp
  src/include/miopen/rnn/base_ops.hpp
  src/include/miopen/rnn/solvers.hpp
  src/include/miopen/rnn/tmp_buffer_utils.hpp
  src/ocl/rnnocl.cpp
  src/rnn/Solutions/Base/bw_weights_modular.cpp
  src/rnn/Solutions/bww_s_steam.cpp
  src/rnn/Solutions/modular_base.cpp
  src/rnn/selector.cpp
  test/rnn_seq_api.cpp
Labels: TESTING_CI_PASSED

#3206 KTN accounts for CK Fwd type additn
  src/kernels/gfx942_ConvHipIgemmGroupFwdXdlops_decoder.ktn.model
  src/kernels/gfx942_ConvHipIgemmGroupFwdXdlops_encoder.ktn.model
  src/kernels/gfx942_ConvHipIgemmGroupFwdXdlops_metadata.ktn.model
Labels: TESTING_CI_PASSED

#3222 Initial porting of Op2dTensorGeneric kernel from OpenCL to HIP
  src/kernels/MIOpenTensorKernelsHip.cpp
  test/gtest/tensor_2d_gen_ocl_hip.cpp
Labels: TESTING_CI_PASSED

#3213 TensorDescriptor refactoring & enhancements
  driver/conv_driver.hpp
  src/conv/problem_description.cpp
  src/convolution.cpp
  src/driver_arguments.cpp
  src/include/miopen/batchnorm/problem_description.hpp
  src/include/miopen/conv/problem_description.hpp
  src/include/miopen/graphapi/tensor.hpp
  src/include/miopen/tensor.hpp
  src/include/miopen/utility/transposing_solver.hpp
  src/ocl/convolutionocl.cpp
  src/problem.cpp
  src/solver/pooling/backward2d.cpp
  src/solver/pooling/backwardNd.cpp
  src/solver/pooling/forward2d.cpp
  src/solver/pooling/forwardNaive.cpp
  src/solver/pooling/forwardNd.cpp
  src/tensor.cpp
  test/conv_common.hpp
  test/gpu_reference_kernel.cpp
  test/gtest/graphapi_tensor.cpp
  test/gtest/layout_transpose.cpp
  test/gtest/tensor_api.cpp
  test/gtest/unit_TensorDescriptor.cpp
  test/gtest/unit_TensorDescriptor.hpp
  test/gtest/unit_conv_ConvolutionDescriptor.hpp
  test/gtest/unit_conv_ProblemDescription.cpp
  test/gtest/unit_conv_solver.cpp
  test/tensor_reorder.cpp
Labels: value_high, quality, urgency_high, TESTING_CI_PASSED, GTest

#3239 Fix ConvBiasResAddActivation_fwd tests failing on Navi
  test/gtest/fused_conv_bias_res_add_activ.cpp
  test/gtest/graphapi_conv_bias_res_add_activ_fwd.cpp
  test/gtest/gtest_ck_common.hpp
Labels: bug, urgency_high, GTest

#3243 Fix stream not being set when calling hipMemsetAsync
  src/include/miopen/solver/implicitgemm_ck_util.hpp
Labels: bug, value_high, complexity_low, urgency_high, TESTING_CI_PASSED

#3244 Fix stream not being set when calling hipMemsetAsync
  src/include/miopen/solver/implicitgemm_ck_util.hpp
Labels: bug, value_high, complexity_low, urgency_high, TESTING_CI_PASSED

#3245 Fix gfx908 timing out during pipeline stages
  Jenkinsfile
Labels: complexity_low, workaround, TESTING_CI_PASSED

#3241 [RNN] LSTM backward weight MS
  src/CMakeLists.txt
  src/include/miopen/rnn/multi_stream_utils.hpp
  src/include/miopen/rnn/solvers.hpp
  src/rnn/Solutions/Base/bw_data_modular.cpp
  src/rnn/Solutions/Base/bw_weights_modular.cpp
  src/rnn/Solutions/bwd_multi_stream.cpp
  src/rnn/Solutions/bww_multi_stream.cpp
  src/rnn/selector.cpp
Labels: TESTING_CI_PASSED

#3236 Update CK branch to include CK Fwd changes
  requirements.txt
  src/kernels/gfx90a.kdb.bz2
  src/kernels/gfx90a68.HIP.fdb.txt.bz2
  test/gtest/kernel_tuning_net.cpp
Labels: urgency_blocker, TESTING_CI_PASSED

#3240 Add Mha Bias to Find 2.0 for forward pass
  include/miopen/miopen.h
  src/api/find2_0_commons.cpp
  src/include/miopen/graphapi/util.hpp
  src/include/miopen/mha/mha.hpp
  src/problem.cpp
  src/solution.cpp
  test/gtest/mha_find20.cpp
Labels: TESTING_CI_PASSED

#3248 [Bug] Get kernel after the stream change
  src/solver/mha/mha_solver_backward.cpp
Labels: bug, value_high, urgency_blocker, complexity_low, TESTING_CI_PASSED

#3228 Dropout replacement finish
  driver/dropout_driver.hpp
  driver/dropout_gpu_emulator.hpp
  driver/gru_verify_gemm.hpp
  driver/lstm_verify_gemm.hpp
  driver/rnn_driver.hpp
  driver/rnn_seq_driver.hpp
  driver/rnn_verify_gemm.hpp
  driver/xorwow_skipahead_generator.hpp
  src/CMakeLists.txt
  src/dropout_api.cpp
  src/include/miopen/precalc_xorwow_skipahead_matrices.hpp
  src/include/miopen/precalc_xorwow_skipahead_sequence_matrices.hpp
  src/kernels/MIOpenDropout.cl
  src/kernels/precalc_xorwow_skipahead_matrices_kernel.h
  src/kernels/precalc_xorwow_skipahead_sequence_matrices_kernel.h
  src/ocl/dropoutocl.cpp
  test/cpu_rnn.hpp
  test/dropout.cpp
  test/dropout_util.hpp
  test/gru_common.hpp
  test/gtest/dropout_ocl_hip.cpp
  test/rnn_vanilla_common.hpp
  test/tensor_holder.hpp
Labels: enhancement, complexity_low, TESTING_CI_PASSED

#3252 TunaNet Update for MI300
  src/conv/heuristics/ai_heuristics.cpp
  src/kernels/gfx942.tn.model
  src/kernels/gfx942_metadata.tn.model
Labels: urgency_high, TESTING_CI_PASSED

#3251 [MHA] add bias
  src/kernels/MIOpenSoftmaxAttn.cpp
  src/solver/mha/mha_solver_forward.cpp
  src/solver/softmax/attn_softmax.cpp
Labels: complexity_low, urgency_high, TESTING_CI_PASSED

#3249 [Bug] missing split_k from end of kernel_id in ck wrw
  src/solver/conv/conv_hip_implicit_gemm_grouped_wrw_xdlops.cpp
Labels: bug, TESTING_CI_PASSED

#3262 [MHA] Add bias for CPU verification code
  test/gtest/mha_helper.hpp
Labels: TESTING_CI_PASSED

#3253 [testing] Speed up test_activation, convert to GTest
  src/include/miopen/activ.hpp
  src/ocl/activ_ocl.cpp
  test/CMakeLists.txt
  test/activation.cpp
  test/gtest/activ_common.hpp
  test/gtest/unit_ActivationDescriptor.cpp
  test/network_data.hpp
  test/nightlies/JenkinsfileNightlyTensorOps
Labels: enhancement, value_high, testing, TESTING_CI_PASSED, GTest

#3268 [TEST] enable gtest filter
  test/CMakeLists.txt
  test/gtest/CMakeLists.txt
Labels: value_high, urgency_blocker, complexity_low, TESTING_CI_PASSED, GTest

#3256 Remove unused hip-config.cmake
  cmake/hip-config.cmake
Labels: TESTING_CI_PASSED

#3254 [Mha] Mask is added for Forward pass
  include/miopen/miopen.h
  src/api/find2_0_commons.cpp
  src/include/miopen/graphapi/util.hpp
  src/include/miopen/mha/mha.hpp
  src/solution.cpp
  test/gtest/mha_find20.cpp
Labels: TESTING_CI_PASSED

#3270 Update CK commit hash to latest 09242024
  requirements.txt
Labels: TESTING_CI_PASSED

#3263 fix compilation with HIP SDK 6.2 on Windows
  CMakeLists.txt
  cmake/EnableCompilerWarnings.cmake
  driver/conv_driver.hpp
  driver/mloConvHost.hpp
Labels: windows

#3264 Use `bzip2 -dc` instead of `bzcat` for better compatibility
  CMakeLists.txt
Labels: TESTING_CI_PASSED, windows

#3265 Use package config for Boost instead of module
  CMakeLists.txt
Labels: TESTING_CI_PASSED, windows

#3272 Timing accuracy for EvaluteInvokers
  src/conv/solver_finders.cpp
Labels: urgency_high, TESTING_CI_PASSED

#3246 Auto-Prune for db_sync
  test/gtest/db_sync.cpp
Labels: enhancement, TESTING_CI_PASSED

#3273 Increase test accuracy for generic search.
  src/include/miopen/generic_search.hpp
Labels: TESTING_CI_PASSED

#3151 Batchnorm Fused Inference OpenCL to HIP
  src/CMakeLists.txt
  src/kernels/MIOpenBatchNormActivInferHIP.cpp
  src/kernels/activation_functions.hpp
  test/gtest/bn_infer_fused_ocl_hip.cpp
  test/gtest/na.hpp
Labels: TESTING_CI_PASSED
