Repository ROCm/MIOpen, pull requests merged in 2024-02, with the labels that each got.

#2719 Do not use HIP runtime headers on Windows
  CMakeLists.txt
  src/comgr.cpp
Labels: bug, urgency_blocker, TESTING_CI_PASSED, windows

#2562 Add cat forward operation
  docs/apireference.rst
  docs/cat.rst
  driver/cat_driver.hpp
  driver/driver.hpp
  driver/main.cpp
  include/miopen/miopen.h
  src/CMakeLists.txt
  src/cat.cpp
  src/cat/problem_description.cpp
  src/cat_api.cpp
  src/include/miopen/cat.hpp
  src/include/miopen/cat/cat_invoke_params.hpp
  src/include/miopen/cat/problem_description.hpp
  src/include/miopen/cat/solvers.hpp
  src/include/miopen/solver_id.hpp
  src/kernels/MIOpenCat.cpp
  src/solver/cat/forward_cat.cpp
  test/cpu_cat.hpp
  test/gtest/cat.cpp
  test/gtest/cat.hpp
Labels: TESTING_CI_PASSED, external_collaborator

#2725 [HotFix] Fix namespace conflict issue in gtest after #2562
  test/gtest/cat.cpp
  test/gtest/groupnorm.cpp
Labels: urgency_blocker, complexity_low, TESTING_CI_PASSED, value_unknown

#2728 [DB Install] fix for missing installation of *.fdb.txt and *.db files
  CMakeLists.txt
  src/CMakeLists.txt
Labels: bug, urgency_blocker

#2718 Create CODEOWNERS
  .github/CODEOWNERS
Labels: TESTING_CI_PASSED, documentation

#2732 fix build after #2657 and #2690 (boost::filesystem)
  src/hip/handlehip.cpp
  src/include/miopen/execution_context.hpp
  src/nogpu/handle.cpp
  src/ocl/handleocl.cpp
Labels: bug, complexity_low, TESTING_CI_PASSED

#2429 Update CK-based 2d/3d convolution solvers to support nchw/ncdhw layout
  src/buffer_info.cpp
  src/conv/invokers/impl_gemm_dynamic.cpp
  src/include/miopen/batched_transpose_sol.hpp
  src/include/miopen/buffer_info.hpp
  src/include/miopen/conv/tensors.hpp
  src/include/miopen/errors.hpp
  src/include/miopen/handle.hpp
  src/include/miopen/solver.hpp
  src/include/miopen/solver/implicitgemm_ck_util.hpp
  src/include/miopen/util_sol.hpp
  src/solver/conv_asm_implicit_gemm_gtc_bwd_nhwc.cpp
  src/solver/conv_asm_implicit_gemm_gtc_fwd_nchwc.cpp
  src/solver/conv_asm_implicit_gemm_gtc_fwd_nhwc.cpp
  src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp
  src/solver/conv_hip_implicit_gemm_3d_grouped_bwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_3d_grouped_fwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_3d_grouped_wrw_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_bwd_data_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_f16f8f16_bwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_f16f8f16_fwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_f16f8f16_wrw_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_fwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_grouped_bwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_grouped_fwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_grouped_wrw_xdlops.cpp
  test/gpu_nchw_nhwc_transpose.cpp
  test/gtest/group_conv.hpp
Labels: value_high, urgency_blocker, complexity_high, TESTING_CI_PASSED

#2724 [BugFix] Set System KDB journal_mode to Off
  src/kernels/gfx908.kdb.bz2
  src/kernels/gfx90a.kdb.bz2
  test/gtest/db_sync.cpp
Labels: bug, complexity_low, TESTING_CI_PASSED

#2550 [Test] Convert test_rnn_vanilla , test_gru, test_rnn_extra and test_gru_extra gTests
  test/CMakeLists.txt
  test/gru.cpp
  test/gru.hpp
  test/gtest/deepbench_gru.cpp
  test/gtest/deepbench_rnn.cpp
  test/gtest/gru_extra.cpp
  test/gtest/rnn_extra.cpp
  test/rnn_vanilla.cpp
  test/rnn_vanilla.hpp
Labels: TESTING_CI_PASSED, GTest

#2747 [CK] Update CK commit in requirements.txt for staging
  requirements.txt
Labels: TESTING_CI_PASSED

#2545 [gtest] conversion for lstm
  test/CMakeLists.txt
  test/gtest/deepbench_lstm.cpp
  test/gtest/lstm_extra.cpp
  test/lstm.cpp
  test/lstm.hpp
Labels: urgency_high, TESTING_CI_PASSED, GTest

#2743 Fix for issue #2734: Detect if "-fno-offload-uniform-block" works in HIP compiler.
  CMakeLists.txt
  include/miopen/config.h.in
  src/comgr.cpp
Labels: enhancement, urgency_blocker, TESTING_CI_PASSED

#2741 [6.0.x] Fix for issue #2734: Detect if "-fno-offload-uniform-block" works in HIP compiler.
  CMakeLists.txt
  include/miopen/config.h.in
  src/comgr.cpp
  src/solver/batchnorm/backward_ck.cpp
  src/solver/batchnorm/forward_training_ck.cpp
Labels: enhancement, urgency_blocker

#2737 enable softmax solver based on attention-softmax implementation
  src/CMakeLists.txt
  src/include/miopen/softmax/solvers.hpp
  src/kernels/MIOpenSoftmaxAttn.cpp
  src/softmax.cpp
  src/solver/softmax/attn_softmax.cpp
  src/solver/softmax/softmax.cpp
Labels: enhancement, performance, TESTING_CI_PASSED

#2409 Replace test_conv_igemm_dynamic_xdlops_bwd with gtest
  test/CMakeLists.txt
  test/gtest/conv_igemm_dynamic_xdlops.cpp
  test/gtest/conv_igemm_dynamic_xdlops_half.cpp
  test/gtest/conv_igemm_dynamic_xdlops_nhwc_bf16.cpp
  test/gtest/conv_igemm_dynamic_xdlops_nhwc_nchw.cpp
  test/gtest/smoke_solver_ConvAsmImplicitGemmGTCDynamicXdlops.cpp
Labels: GTest

#2513 Converting Cmake test to gtest for test_conv_for_implicit_gemm
  test/CMakeLists.txt
  test/gtest/conv_for_implicit_gemm.cpp
Labels: GTest

#2754 [Tuning][MI300] for m9 tickets
  src/kernels/gfx942.kdb.bz2
  src/kernels/gfx942130.HIP.fdb.txt.bz2
  src/kernels/gfx942130.db.bz2
Labels: tuning, urgency_high

#2753 [hipRTC] add lowest() for float to MIOpen custom limits
  src/kernels/miopen_limits.hpp
Labels: urgency_blocker

#2694 [Linux] Enhance Compiler flags to avoid Hardcoded ROCm Path (Part 1)
  CMakeLists.txt
  include/miopen/config.h.in
  src/hip/hip_build_utils.cpp
Labels: urgency_high, TESTING_CI_PASSED, value_unknown

#2761 [hot fix] enable 2d grouped fwd convolution support on mi300
  src/solver/conv_hip_implicit_gemm_grouped_fwd_xdlops.cpp
Labels: TESTING_CI_PASSED

#2722 Implemented preparsing sqlite db to text format
  CMakeLists.txt
  Jenkinsfile
  include/miopen/config.h.in
  src/CMakeLists.txt
  src/binary_cache.cpp
  src/db.cpp
  src/include/miopen/conv/problem_description.hpp
  src/include/miopen/db.hpp
  src/include/miopen/db_record.hpp
  src/include/miopen/execution_context.hpp
  src/include/miopen/find_db.hpp
  src/include/miopen/fusion/problem_description.hpp
  src/include/miopen/kern_db.hpp
  src/include/miopen/mlo_internal.hpp
  src/include/miopen/ramdb.hpp
  src/include/miopen/readonlyramdb.hpp
  src/include/miopen/sqlite_db.hpp
  src/kern_db.cpp
  src/mlo_dir_conv.cpp
  src/ramdb.cpp
  src/readonlyramdb.cpp
  src/sqlite_db.cpp
  test/gtest/cache.cpp
  test/gtest/db_sync.cpp
  test/perfdb.cpp
  test/solver.cpp
  test/sqlite.cpp
  test/sqlite_perfdb.cpp
  tools/sqlite2txt/CMakeLists.txt
  tools/sqlite2txt/main.cpp
Labels: urgency_blocker, TESTING_CI_PASSED

#2769 Fixed incorrectly generated files
  CMakeLists.txt
  src/include/miopen/execution_context.hpp
  tools/sqlite2txt/main.cpp
Labels: urgency_blocker, TESTING_CI_PASSED

#2727 RNN Inference MS
  src/include/miopen/rnn.hpp
  src/include/miopen/rnn_util.hpp
  src/kernels/MIOpenRNNHiddenStateUpdate.cl
  src/ocl/rnnocl.cpp
  src/rnn.cpp
Labels: enhancement, TESTING_CI_PASSED
