Repository ROCm/MIOpen, pull requests merged in 2024-01, with the labels that each got.

#2644 [ROCm 6.0.1] Automatically activate the new HIPRTC PCH adaptations starting from the 6.0.24000 version. Fix some build errors.
  src/kernels/MIOpenLayerNorm.cpp
  src/kernels/miopen_cstdint.hpp
  src/kernels/miopen_type_traits.hpp
  src/kernels/static_composable_kernel/include/utility/static_kernel_config.hpp
Labels: urgency_blocker, TESTING_CI_PASSED

#2652 [HOTFIX] Adapt to changes in HIP Mainline 417 (possibly future 6.1 RC)
  src/comgr.cpp
  src/hip/hip_build_utils.cpp
  src/kernel_warnings.cpp
  src/kernels/miopen_limits.hpp
  src/kernels/miopen_type_traits.hpp
  test/handle_test.cpp
Labels: bug, non-miopen-bug, urgency_blocker

#2653 correct parameter which prints unused flag in log fusion cmd
  src/fusion.cpp
Labels: TESTING_CI_PASSED

#2654 [MI300][Tuning] Tunings for SWDEV tickets
  src/kernels/gfx942.kdb.bz2
  src/kernels/gfx942130.HIP.fdb.txt.bz2
  src/kernels/gfx942130.db.bz2
  test/gtest/db_sync.cpp
Labels: tuning, urgency_high

#2658 [ROCm 6.0.1] Fix merge error in #2652 that affects #2644.
  src/kernels/miopen_type_traits.hpp
Labels: bug, urgency_normal

#2656 replace [[gnu::noreturn]] with [[noreturn]]
  addkernels/addkernels.cpp
  driver/InputFlags.cpp
  driver/InputFlags.hpp
  driver/driver.hpp
  test/test.hpp
Labels: windows

#2657 addkernels: fix operations on path for Windows
  addkernels/addkernels.cpp
  addkernels/include_inliner.cpp
  addkernels/include_inliner.hpp
  addkernels/source_file_desc.hpp
Labels: windows

#2655 clean up the setting of environment variables cross-platform
  test/env_utils.hpp
  test/find_db.cpp
  test/gtest/bad_fusion_plan.cpp
  test/gtest/cba_infer.cpp
  test/gtest/db_sync.cpp
  test/gtest/log.cpp
Labels: bug, windows

#2553 [Test] Convert conv_igemm_dynamic_dlops etc to gTest
  test/CMakeLists.txt
  test/gtest/CMakeLists.txt
  test/gtest/conv_ck_igemm_fwd_v6r1_dlops_nchw.cpp
  test/gtest/conv_igemm_dynamic.cpp
  test/gtest/conv_igemm_dynamic_dlops.cpp
  test/gtest/conv_igemm_dynamic_xdlops.cpp
  test/gtest/conv_igemm_mlir.cpp
  test/gtest/conv_igemm_mlir_bwd_wrw.cpp
  test/gtest/conv_igemm_mlir_fwd.cpp
  test/gtest/conv_igemm_mlir_xdlops.cpp
  test/gtest/conv_igemm_mlir_xdlops_bwd_wrw.cpp
  test/gtest/conv_igemm_mlir_xdlops_fwd.cpp
  test/gtest/deepbench_conv.cpp
  test/gtest/gtest_common.hpp
  test/gtest/immed_conv2d_codecov.cpp
  test/gtest/miopen_conv.cpp
  test/gtest/regression_float_mi100.cpp
  test/gtest/regression_half_mi100.cpp
  test/gtest/regression_half_vega_gfx908.cpp
  test/gtest/smoke_solver_ConvAsmImplicitGemmGTCDynamicFwdDlopsNCHWC.cpp
  test/gtest/smoke_solver_ConvAsmImplicitGemmGTCDynamicXdlops.cpp
  test/gtest/smoke_solver_ConvAsmImplicitGemmGTCDynamicXdlopsNHWC_bf16.cpp
  test/gtest/smoke_solver_ConvAsmImplicitGemmGTCDynamicXdlopsNHWC_fp32_fp16.cpp
  test/gtest/smoke_solver_ConvAsmImplicitGemmV4R1Dynamic.cpp
  test/gtest/smoke_solver_ConvAsm_5x10_7x7.cpp
  test/gtest/smoke_solver_ConvBinWinograd3x3U.cpp
  test/gtest/smoke_solver_ConvBinWinogradRxS_fp16.cpp
  test/gtest/smoke_solver_ConvBinWinogradRxS_fp32.cpp
  test/gtest/smoke_solver_ConvBinWinogradRxSf2x3.cpp
  test/gtest/smoke_solver_ConvBinWinogradRxSf2x3g1.cpp
  test/gtest/smoke_solver_ConvBinWinogradRxSf2x3g1_3x2_f16.cpp
  test/gtest/smoke_solver_ConvBinWinogradRxSf2x3g1_3x2_f32.cpp
  test/gtest/smoke_solver_ConvBinWinogradRxSf3x2.cpp
  test/gtest/smoke_solver_ConvCkIgemmFwdV6r1DlopsNchw.cpp
  test/gtest/smoke_solver_ConvDirectNaiveConv_Bw.cpp
  test/gtest/smoke_solver_ConvDirectNaiveConv_F.cpp
  test/gtest/smoke_solver_ConvFFT.cpp
  test/gtest/smoke_solver_ConvHipImplicitGemmBwdDataV1R1.cpp
  test/gtest/smoke_solver_ConvHipImplicitGemmBwdDataV1R1Xdlops.cpp
  test/gtest/smoke_solver_ConvHipImplicitGemmBwdDataV4R1.cpp
  test/gtest/smoke_solver_ConvHipImplicitGemmDataV4RxXdlops.cpp
  test/gtest/smoke_solver_ConvHipImplicitGemmV4R1Fwd_fp16_bf16.cpp
  test/gtest/smoke_solver_ConvHipImplicitGemmV4R1Fwd_fp32.cpp
  test/gtest/smoke_solver_ConvHipImplicitGemmV4R1WrW.cpp
  test/gtest/smoke_solver_ConvHipImplicitGemmV4R4.cpp
  test/gtest/smoke_solver_ConvOclBwdWrW1x1.cpp
  test/gtest/smoke_solver_ConvOcl_Fwd11x11_FwdGen_WrW53.cpp
  test/gtest/smoke_solver_ConvWinogradFuryRxSf2x3_f16.cpp
  test/gtest/smoke_solver_convasm.cpp
  test/gtest/smoke_solver_convasm1x1u.cpp
  test/gtest/smoke_solver_convasmbwdwrw.cpp
  test/gtest/smoke_solver_convasmbwdwrw3x3_fp16.cpp
  test/gtest/smoke_solver_convasmbwdwrw3x3_fp32.cpp
Labels: complexity_middle, urgency_high, TESTING_CI_PASSED, GTest

#2677 fix compilation on Windows
  test/cpu_rnn.hpp
Labels: windows

#2347 cmake: unpack kernels into a build directory
  CMakeLists.txt
  src/CMakeLists.txt
  test/CMakeLists.txt
Labels: TESTING_CI_PASSED, windows

#2627 Remove FIN_OLD_HANDLE_COMPAT and FIN_OLD_BINARY_CACHE_COMPAT
  src/include/miopen/binary_cache.hpp
  src/include/miopen/handle.hpp
Labels: quality, TESTING_CI_PASSED

#2673 Rename transpose* kernels (leftover of #2613)
  src/kernels/MIOpenUtilKernels4.cl
  src/ocl/utilocl.cpp
Labels: quality, urgency_high, TESTING_CI_PASSED

#2686 [zlib] Update rocm-recipes for more reliable zlib link
  dev-requirements.txt
  install_deps.cmake
  rbuild.ini
Labels: non-miopen-bug, urgency_blocker, dependencies

#2691 [OCL] Use OpenCL 2.0 while compiling kernels
  src/hipoc/hipoc_program.cpp
  src/ocl/clhelper.cpp
Labels: urgency_high, TESTING_CI_PASSED

#2669 [BF16][FP8][BF8] Fixed some specializations from `<limits>` and `<cmath>`
  src/include/miopen/bfloat16.hpp
  src/kernels/hip_float8.hpp
Labels: bug, value_high, urgency_high, TESTING_CI_PASSED, correctness

#2695 [HOTFIX] Disable "granularity loss" W/A for #2492 and add a new, "tiny tensor" based one.
  src/solver/conv_winoRxS.cpp
  test/gtest/db_sync.cpp
Labels: performance, urgency_blocker, workaround

#2697 [MI300][Tuning] gold 20
  include/miopen/config.h.in
  src/kernels/gfx942.kdb.bz2
  src/kernels/gfx942130.HIP.fdb.txt.bz2
  src/kernels/gfx942130.db.bz2
Labels: urgency_high

#2665 Remove support for ROCm < 5.6.0
  driver/driver.hpp
  driver/reduce_driver.hpp
  src/CMakeLists.txt
  src/comgr.cpp
  src/composable_kernel/composable_kernel/include/utility/reduction_operator.hpp
  src/composable_kernel/host/driver_offline/src/conv_bwd_driver_offline.cpp
  src/composable_kernel/host/driver_offline/src/conv_fwd_driver_offline.cpp
  src/fusion.cpp
  src/gemm_v2.cpp
  src/hip/handlehip.cpp
  src/hip/hip_build_utils.cpp
  src/hipoc/hipoc_program.cpp
  src/include/miopen/ocldeviceinfo.hpp
  src/include/miopen/op_kernel_args.hpp
  src/include/miopen/reduce_common.hpp
  src/include/miopen/rocm_features.hpp
  src/include/miopen/solver.hpp
  src/include/miopen/solver/ck_utility_common.hpp
  src/include/miopen/solver/implicitgemm_util.hpp
  src/include/miopen/visit_float.hpp
  src/kernels/detect_llvm_amdgcn_buffer_atomic_fadd_f32_float.cpp
  src/kernels/static_composable_kernel/include/utility/static_kernel_reduction_operator.hpp
  src/ocl/clhelper.cpp
  src/ocl/gcn_asm_utils.cpp
  src/ocl/handleocl.cpp
  src/solver/conv_asm_1x1u_bias_activ_fused.cpp
  src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops_padded_gemm.cpp
  src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops_padded_gemm.cpp
  src/solver/conv_ocl_dir2Dfwd_exhaustive_search.cpp
  src/solver/mlir_common.cpp
  test/conv_common.hpp
  test/cpu_reduce_util.hpp
  test/driver.hpp
  test/ford.hpp
  test/gpu_reference_kernel.cpp
  test/serialize.hpp
  test/tensor_holder.hpp
Labels: urgency_normal, TESTING_CI_PASSED

#2705 [COMGR] Use OpenCL 2.0. [HIPRTC] Provide min/max limits for int. Fix build errors related to min/max limits for BF16.
  src/comgr.cpp
  src/kernels/miopen_limits.hpp
Labels: value_high, urgency_blocker, TESTING_CI_PASSED

#2696 [DOC] fix broken links in docs
  README.md
  docs/citation.md
  docs/driver.md
  docs/install.md
  docs/sphinx/_toc.yml.in
Labels: TESTING_CI_PASSED, documentation

#2702 [HotFix] Fix DB install after #2347
  CMakeLists.txt
  driver/CMakeLists.txt
  src/CMakeLists.txt
Labels: bug, urgency_blocker, TESTING_CI_PASSED
