Repository ROCm/MIOpen, pull requests merged in 2024-11, with the labels that each got.

#3357 fix test issue, was testing nhwc for OCL
  test/gtest/bn_fwd_train.cpp
Labels: urgency_high

#3373 SWDEV-485839: Replace asm version of readfirstlane with its builtin version
  src/kernels/MIOpenConvDirBatchNormActiv.cl
  src/kernels/MIOpenConvDirUni.cl
  src/kernels/MIOpenConvDirUni_Vec2.cl
  src/kernels/MIOpenConvFwd_LxL_11.cl
Labels: TESTING_CI_PASSED

#3376 [gtest] move cpu-based ctest to gtest
  test/CMakeLists.txt
  test/gtest/CMakeLists.txt
  test/gtest/include_inliner.cpp
  test/gtest/kernel_build_params.cpp
  test/gtest/miopendriver_regression_big_tensor.cpp
  test/gtest/sequences.cpp
  test/gtest/tensor_test.cpp
  test/gtest/test_errors.cpp
  test/gtest/type_name.cpp
  test/include_inliner.cpp
  test/sequences.cpp
  test/tensor_test.cpp
  test/test_errors.cpp
  test/type_name.cpp
Labels: urgency_blocker, quality, complexity_middle, TESTING_CI_PASSED, GTest

#3363 Update db_sync to work with db.txt
  test/gtest/db_sync.cpp
Labels: TESTING_CI_PASSED

#3335 Support for 64b tensors - Op2dTensorGeneric
  src/kernels/MIOpenDropoutHIP.cpp
  src/kernels/MIOpenTensorKernelsHip.cpp
  src/ocl/dropoutocl.cpp
  src/ocl/tensorocl.cpp
Labels: TESTING_CI_PASSED

#3372 fix bn 3d issue
  src/batch_norm.cpp
  src/batch_norm_api.cpp
Labels: bug, quality, complexity_low, TESTING_CI_PASSED

#3368 fix batch norm driver command for some configs that were failing
  driver/bn_driver.hpp
Labels: TESTING_CI_PASSED

#3352 [GTests] Remove Codecov
  Jenkinsfile
  test/CMakeLists.txt
  test/gtest/CMakeLists.txt
  test/gtest/conv3d_codecov.cpp
  test/gtest/conv_igemm_dynamic.cpp
  test/gtest/immed_conv2d_codecov.cpp
  test/gtest/immed_conv3d_codecov.cpp
  test/gtest/pooling2d_asymmetric.cpp
  test/gtest/pooling2d_codecov.cpp
  test/gtest/pooling2d_wide.cpp
Labels: TESTING_CI_PASSED, GTest

#3378 Fix the fwd convolution Nan output issue
  src/include/miopen/solver/implicitgemm_ck_util.hpp
  test/gtest/group_conv.hpp
Labels: bug, urgency_blocker, urgency_high, TESTING_CI_PASSED

#3342 Op3dTensorGeneric kernel upgrade
  src/kernels/MIOpenTensorKernels.cl
  src/kernels/MIOpenTensorKernelsHip.cpp
  src/ocl/tensorocl.cpp
  test/gtest/tensor_3d_generic_ocl_hip.cpp
Labels: performance, quality, TESTING_CI_PASSED

#3380 Simplify TensorDescriptor::GetElementSpace()
  src/tensor.cpp
Labels: value_middle, performance, quality, complexity_low, TESTING_CI_PASSED

#3390 Staging fixes for BN and find2.0 issues
  src/batch_norm.cpp
  src/batch_norm_api.cpp
  src/problem.cpp
Labels: urgency_high, TESTING_CI_PASSED
