Repository ROCm/MIOpen, pull requests merged in 2024-12, with the labels that each got.

#3411 Fix kernel time not accumulating properly for gemm wrw
  src/solver/conv/gemm_wrw.cpp
Labels: bug, complexity_low, urgency_high, TESTING_CI_PASSED

#3407 [Bug] Fix issue with WRW heuristics instance selection
  src/include/miopen/solver/implicitgemm_ck_util.hpp
  src/solver/conv/conv_hip_implicit_gemm_grouped_wrw_xdlops.cpp
  test/gtest/kernel_tuning_net.cpp
  test/gtest/unit_implicitgemm_ck_util.cpp
Labels: bug, complexity_middle, urgency_high

#3423 Fix hip-tidy build
  src/include/miopen/problem.hpp
Labels: value_high, urgency_blocker, complexity_low

#3389 Remove our own implementation of `std::index_sequence`
  src/include/miopen/each_args.hpp
  src/include/miopen/functional.hpp
  src/include/miopen/tensor.hpp
  test/args.hpp
Labels: quality, complexity_low, TESTING_CI_PASSED

#3416 Move tensor_set/scale/cast/copy to gtest
  src/ocl/tensorocl.cpp
  test/CMakeLists.txt
  test/conv2d_bias.cpp
  test/conv3d_bias.cpp
  test/gtest/binary_tensor_ops.cpp
  test/gtest/unary_tensor_ops.cpp
  test/network_data.hpp
  test/tensor_cast.cpp
  test/tensor_copy.cpp
  test/tensor_holder.hpp
  test/tensor_scale.cpp
  test/tensor_set.cpp
  test/tensor_transform.cpp
  test/tensor_util.hpp
Labels: bug, enhancement, urgency_blocker, quality, testing, complexity_middle, TESTING_CI_PASSED, GTest

#3330 [tuning] Interface for Fin
  CMakeLists.txt
  Jenkinsfile
  include/miopen/config.h.in
  src/CMakeLists.txt
  src/api/find2_0_commons.cpp
  src/fin/fin_interface.cpp
  src/include/miopen/batchnorm/solvers.hpp
  src/include/miopen/conv/solvers.hpp
  src/include/miopen/fin/fin_interface.hpp
  src/include/miopen/find_solution.hpp
  src/include/miopen/solver.hpp
  src/include/miopen/solver_id.hpp
  src/include/miopen/type_name.hpp
  src/solver.cpp
  src/solver/conv/conv_ocl_dir2D_bwdWrW_2.cpp
  test/gtest/unit_FinInterface.cpp
  test/gtest/unit_conv_solver.cpp
  test/gtest/unit_conv_solver.hpp
Labels: value_high, urgency_blocker, tuning, TESTING_CI_PASSED

#3435 [HotFix] Fix Fin interface
  src/fin/fin_interface.cpp
  test/gtest/unit_FinInterface.cpp
Labels: urgency_blocker

#3437 Fix kernel cache threading
  src/hip/handlehip.cpp
  src/include/miopen/handle.hpp
  src/include/miopen/kernel_cache.hpp
  src/kernel_cache.cpp
  src/nogpu/handle.cpp
  src/ocl/handleocl.cpp
Labels: bug, urgency_blocker, complexity_middle

#3428 [BUG] Fix memory leak in GraphExecutorFind20
  src/graphapi/engine.cpp
  src/graphapi/find_engine.cpp
  src/include/miopen/graphapi/engine.hpp
  src/include/miopen/utility/scope.hpp
Labels: bug, urgency_blocker

#3430 [GRAPHAPI] Implement MIOPEN_BACKEND_EXECUTION_PLAN_DESCRIPTOR Serialization
  src/CMakeLists.txt
  src/base64.cpp
  src/graphapi/conv_bias_res_add_activ_forward_executor.cpp
  src/graphapi/convolution.cpp
  src/graphapi/engine.cpp
  src/graphapi/execution_plan.cpp
  src/graphapi/find_engine.cpp
  src/graphapi/tensor.cpp
  src/include/miopen/graphapi/conv_bias_res_add_activ_forward_executor.hpp
  src/include/miopen/graphapi/convolution.hpp
  src/include/miopen/graphapi/engine.hpp
  src/include/miopen/graphapi/enginecfg.hpp
  src/include/miopen/graphapi/execution_plan.hpp
  src/include/miopen/graphapi/tensor.hpp
  src/include/miopen/utility/base64.hpp
  test/gtest/graphapi_conv_bias_res_add_activ_fwd.cpp
  test/gtest/graphapi_engine.cpp
  test/gtest/graphapi_mha_cpp_common.hpp
Labels: enhancement
