Repository ROCm/MIOpen, pull requests merged in 2024-06, with the labels that each got.

#3012 Fix for Find 2.0 Mha test
  test/gtest/mha_find20.cpp
Labels: complexity_low, TESTING_CI_PASSED

#3006 [MHA] [GTEST] Add MIOPEN_BACKEND_ENGINE_DESCRIPTOR tests
  src/graphapi/engine.cpp
  test/gtest/graphapi_engine.cpp
Labels: enhancement, value_high, urgency_high, TESTING_CI_PASSED, GTest

#3019 rs/transpose refactor
  src/hip/batched_transpose_sol.cpp
  src/include/miopen/batched_transpose_sol.hpp
  test/gtest/layout_transpose.cpp
Labels: value_middle, complexity_low, urgency_normal, TESTING_CI_PASSED

#3017 Remove redundant link to CK device_contraction_operations lib.
  CMakeLists.txt
  src/CMakeLists.txt
Labels: enhancement, value_middle, quality, urgency_low, TESTING_CI_PASSED

#3026 Remove gfx942 kernel cache
  CMakeLists.txt
  src/kernels/gfx942.kdb.bz2
Labels: value_low, urgency_blocker

#3008 Up CK version in requirements
  requirements.txt
Labels: TESTING_CI_PASSED

#3011 [gTest] Fix environment variables not being set in CICD
  src/kernels/MIOpenAdam.cpp
  src/kernels/MIOpenLayerNorm.cpp
  src/solver/adam/adam.cpp
  test/CMakeLists.txt
  test/gtest/CMakeLists.txt
  test/gtest/gtest_env_check_common.hpp
  test/gtest/miopendriver_common.hpp
  test/gtest/miopendriver_conv2d_trans.cpp
  test/gtest/miopendriver_gemm.cpp
  test/gtest/miopendriver_regression_big_tensor.cpp
  test/gtest/miopendriver_regression_float_half_gfx10.cpp
  test/gtest/miopendriver_regression_half.cpp
  test/gtest/miopendriver_regression_half_gfx9.cpp
  test/gtest/miopendriver_regression_int8.cpp
  test/gtest/miopendriver_regression_issue_1576.cpp
  test/gtest/miopendriver_regression_issue_2047.cpp
Labels: value_middle, complexity_low, urgency_normal, TESTING_CI_PASSED, GTest

#3031 Bump CK to latest CVT kernels and change CI timeout
  Jenkinsfile
  requirements.txt
Labels: value_high, complexity_low, urgency_high

#3016 fix embeded kernels on Windows
  addkernels/addkernels.cpp
  src/CMakeLists.txt
  src/comgr.cpp
  src/hip/hip_build_utils.cpp
  src/hipoc/hipoc_program.cpp
  src/include/miopen/comgr.hpp
  src/include/miopen/gcn_asm_utils.hpp
  src/include/miopen/hip_build_utils.hpp
  src/include/miopen/hipoc_program_impl.hpp
  src/include/miopen/kern_db.hpp
  src/include/miopen/kernel.hpp
  src/include/miopen/kernel_cache.hpp
  src/kernels/kernel.cpp.in
  src/kernels/kernel_includes.cpp.in
  src/ocl/clhelper.cpp
  src/ocl/gcn_asm_utils.cpp
Labels: TESTING_CI_PASSED, windows

#2972 [CONV] Follow up for conv bilinear
  Dockerfile
  src/convolution_api.cpp
  src/include/miopen/miopen_internal.h
  src/include/miopen/scalar.hpp
  src/include/miopen/solver/implicitgemm_ck_util.hpp
  src/kernels/gpu_reference_kernel/naive_conv.cpp
  src/solver/conv_direct_naive_conv.cpp
  src/solver/conv_hip_implicit_gemm_3d_grouped_bwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_3d_grouped_fwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_3d_grouped_wrw_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_bwd_data_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_f16f8f16_bwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_f16f8f16_fwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_f16f8f16_wrw_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_fwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_grouped_bwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_grouped_fwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_grouped_wrw_xdlops.cpp
  test/gpu_conv.hpp
  test/gtest/group_conv.hpp
  test/gtest/group_conv2d_bwd.cpp
  test/gtest/group_conv2d_fwd.cpp
  test/gtest/group_conv2d_wrw.cpp
  test/gtest/group_conv3d_bwd.cpp
  test/gtest/group_conv3d_fwd.cpp
  test/gtest/group_conv3d_wrw.cpp
Labels: urgency_blocker

#3025 [MHA] enable fp8 for backward mha pass
  src/kernels/MIOpenSoftmaxAttn.cpp
  src/solver/mha/mha_common.hpp
  src/solver/mha/mha_solver_backward.cpp
  src/solver/mha/mha_solver_forward.cpp
  test/gtest/gpu_mha_backward.cpp
  test/gtest/gpu_mha_forward.cpp
  test/gtest/mha_helper.hpp
Labels: value_high, complexity_middle, TESTING_CI_PASSED

#3033 Fix memory leak when using deref()
  src/activ_api.cpp
  src/api/find2_0_commons.cpp
  src/convolution_api.cpp
  src/ctc_api.cpp
  src/dropout_api.cpp
  src/fused_api.cpp
  src/handle_api.cpp
  src/lrn_api.cpp
  src/pooling_api.cpp
  src/reducetensor_api.cpp
  src/rnn_api.cpp
  src/tensor_api.cpp
Labels: bug

#3035 Workaround: Ubuntu 20.04 and RHEL no standard hash for std::filesystem::path
  src/kernels/kernel.cpp.in
  src/kernels/kernel_includes.cpp.in
Labels: urgency_blocker, TESTING_CI_PASSED

#3038 Add FP8 Support For Mha Forward C API Test
  test/gtest/gpu_mha_forward.cpp
  test/gtest/graphapi_capi_mha_forward.cpp
Labels: TESTING_CI_PASSED

#3018 Change std::string to fs::path for handling files
  cmake/embed.cmake
  src/anyramdb.cpp
  src/binary_cache.cpp
  src/conv/heuristics/ai_heuristics.cpp
  src/db.cpp
  src/db_path.cpp.in
  src/expanduser.cpp
  src/find_db.cpp
  src/hip/general_tensor_reorder_sol.cpp
  src/hip/handlehip.cpp
  src/hip/hip_build_utils.cpp
  src/hipoc/hipoc_program.cpp
  src/include/miopen/anyramdb.hpp
  src/include/miopen/binary_cache.hpp
  src/include/miopen/convolution.hpp
  src/include/miopen/db.hpp
  src/include/miopen/db_path.hpp
  src/include/miopen/execution_context.hpp
  src/include/miopen/expanduser.hpp
  src/include/miopen/find_db.hpp
  src/include/miopen/general_tensor_reorder_sol.hpp
  src/include/miopen/handle.hpp
  src/include/miopen/hip_build_utils.hpp
  src/include/miopen/hipoc_program.hpp
  src/include/miopen/hipoc_program_impl.hpp
  src/include/miopen/kern_db.hpp
  src/include/miopen/kernel_cache.hpp
  src/include/miopen/kernel_info.hpp
  src/include/miopen/lock_file.hpp
  src/include/miopen/ramdb.hpp
  src/include/miopen/readonlyramdb.hpp
  src/include/miopen/simple_hash.hpp
  src/include/miopen/solver.hpp
  src/include/miopen/sqlite_db.hpp
  src/include/miopen/temp_file.hpp
  src/kern_db.cpp
  src/kernel_cache.cpp
  src/lock_file.cpp
  src/nogpu/handle.cpp
  src/ocl/clhelper.cpp
  src/ocl/convolutionocl.cpp
  src/ocl/gcn_asm_utils.cpp
  src/ocl/handleocl.cpp
  src/ramdb.cpp
  src/readonlyramdb.cpp
  src/solver/conv_direct_naive_conv.cpp
  src/sqlite_db.cpp
  test/embed_sqlite.cpp
  test/gtest/cache.cpp
  test/gtest/db_sync.cpp
  test/gtest/execute_primitive.cpp
  test/perfdb.cpp
  test/solver.cpp
  test/sqlite_perfdb.cpp
  test/tensor_util.hpp
Labels: value_high, TESTING_CI_PASSED, windows, uai

#3040 Follow up fix for #3025
  test/gtest/gpu_mha_backward.cpp
  test/gtest/gpu_mha_forward.cpp
  test/gtest/mha_helper.hpp
Labels: quality, TESTING_CI_PASSED

#3028 Improve stability of addkernels utility
  addkernels/addkernels.cpp
Labels: TESTING_CI_PASSED, windows, uai

#3043 fix compilation without rocblas
  src/conv/solver_finders.cpp
  src/ocl/rnnocl.cpp
  src/solver/mha/mha_solver_backward.cpp
  src/solver/mha/mha_solver_forward.cpp
Labels: urgency_blocker, TESTING_CI_PASSED, windows, uai

#3052 Fixes for FP8 Test for C Api Mha Forward
  test/gtest/graphapi_capi_mha_forward.cpp
Labels: TESTING_CI_PASSED

#3054 [WA] Fix build issue on SLES RHEL8 by removing std::exclusive_scan
  src/include/miopen/graphapi/util.hpp
Labels: urgency_blocker, complexity_low

#3010 Follow up fixes for 2913 (Graph API find solution and execute plan)
  src/graphapi/engine.cpp
  src/graphapi/execution_plan.cpp
  src/graphapi/find_engine.cpp
  src/graphapi/graphapi.cpp
  src/graphapi/opgraph.cpp
  src/graphapi/pointwise.cpp
  src/include/miopen/graphapi/opgraph.hpp
  src/include/miopen/graphapi/util.hpp
  src/include/miopen/graphapi/variant_pack.hpp
Labels: TESTING_CI_PASSED

#2146 [Find2.0][API] Invoker caching and binaries serialization in miopen::Solution
  include/miopen/miopen.h
  src/api/find2_0_commons.cpp
  src/binary_cache.cpp
  src/conv/solver_finders.cpp
  src/find_db.cpp
  src/fusion.cpp
  src/hip/handlehip.cpp
  src/hipoc/hipoc_program.cpp
  src/include/miopen/any_solver.hpp
  src/include/miopen/binary_cache.hpp
  src/include/miopen/conv/solver_finders.hpp
  src/include/miopen/conv_solution.hpp
  src/include/miopen/convolution.hpp
  src/include/miopen/find_db.hpp
  src/include/miopen/find_solution.hpp
  src/include/miopen/fusion/problem_description.hpp
  src/include/miopen/fusion_plan.hpp
  src/include/miopen/handle.hpp
  src/include/miopen/hipoc_program.hpp
  src/include/miopen/hipoc_program_impl.hpp
  src/include/miopen/invoker_cache.hpp
  src/include/miopen/kernel_cache.hpp
  src/include/miopen/kernel_info.hpp
  src/include/miopen/load_file.hpp
  src/include/miopen/problem.hpp
  src/include/miopen/search_options.hpp
  src/include/miopen/solution.hpp
  src/include/miopen/solver.hpp
  src/include/miopen/write_file.hpp
  src/invoker_cache.cpp
  src/kernel_cache.cpp
  src/load_file.cpp
  src/nogpu/handle.cpp
  src/ocl/convolutionocl.cpp
  src/ocl/handleocl.cpp
  src/problem.cpp
  src/solution.cpp
  src/solver.cpp
  test/find_2_conv.cpp
Labels: enhancement, value_high, performance, complexity_high, initial iteration time, urgency_normal, TESTING_CI_PASSED, IMPACTS_API

#3055 [HotFix] Fix environment variable build errors
  src/conv/solver_finders.cpp
  src/hipoc/hipoc_program.cpp
  test/find_2_conv.cpp
Labels: urgency_blocker

#3057 [HotFix] fix the setworkspace issue for ck wrw solvers
  src/convolution_api.cpp
  src/include/miopen/solver/implicitgemm_ck_util.hpp
  src/solver/conv_hip_implicit_gemm_3d_grouped_wrw_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_grouped_wrw_xdlops.cpp
Labels: urgency_blocker, TESTING_CI_PASSED

#3059 fix wrw hip error
  src/convolution_api.cpp
  src/include/miopen/miopen_internal.h
  src/include/miopen/solver/implicitgemm_ck_util.hpp
  src/solver/conv_hip_implicit_gemm_3d_grouped_wrw_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_grouped_wrw_xdlops.cpp
Labels: value_high, urgency_blocker, TESTING_CI_PASSED

#3058 fix network config issue in batch norm
  src/batch_norm_api.cpp
  src/batchnorm/problem_description.cpp
  src/include/miopen/batchnorm/problem_description.hpp
  src/solver/batchnorm/backward_ck.cpp
  src/solver/batchnorm/forward_inference.cpp
  src/solver/batchnorm/forward_inference_ck.cpp
  src/solver/batchnorm/forward_training_ck.cpp
  test/gtest/bn.hpp
  test/gtest/bn_bwd.cpp
  test/gtest/bn_fwd_train.cpp
  test/gtest/bn_infer.cpp
  test/gtest/bn_test_data.hpp
Labels: TESTING_CI_PASSED

#3060 [gfx11][Solvers][Winograd] ConvWinoFuryRxSFused (convolution+bias+activation)
  src/conv/invokers/gcn_asm_wino.cpp
  src/conv/kernel_interface/winograd_kernel_interface.cpp
  src/fusion.cpp
  src/include/miopen/conv/invokers/gcn_asm_wino.hpp
  src/include/miopen/conv/kernel_interface/winograd_kernel_interface.hpp
  src/include/miopen/fusion.hpp
  src/include/miopen/fusion/solvers.hpp
  src/include/miopen/fusion_ops.hpp
  src/ocl/fusionopbiasbnactivocl.cpp
  src/operator.cpp
  src/solver.cpp
  src/solver/conv/conv_wino_fury_RxS.cpp
  test/gtest/cba_find2_infer.cpp
  test/gtest/cba_infer.cpp
Labels: enhancement, urgency_high, TESTING_CI_PASSED

#3070 [HotFix] Fix compilation on Windows after #3060
  src/include/miopen/fusion/solvers.hpp
  src/solver/conv/conv_wino_fury_RxS.cpp
Labels: urgency_blocker, windows

#3061 fix kdb issue caused by naive alpha and beta support
  src/kernels/gpu_reference_kernel/naive_conv.cpp
  src/solver/conv_direct_naive_conv.cpp
Labels: TESTING_CI_PASSED

#3069 Fix "Crunching the latest data, just for you. Hang tight…"
  .gitattributes
Labels: enhancement, quality

#2957 Impl adam_w
  driver/adam_driver.hpp
  driver/dm_adam.cpp
  driver/driver.hpp
  include/miopen/miopen.h
  src/adam/problem_description.cpp
  src/include/miopen/adam/problem_description.hpp
  src/include/miopen/tensor.hpp
  src/kernels/MIOpenAdam.cpp
  src/solver/adam/adam.cpp
  src/tensor.cpp
  test/cpu_adam.hpp
  test/gtest/adam.cpp
  test/gtest/adam.hpp
Labels: enhancement, TESTING_CI_PASSED, external_collaborator

#3080 [RNN] MS algorithm update
  src/ocl/rnnocl.cpp
Labels: TESTING_CI_PASSED

#3073 C API Mha Backward Test (raw code)
  test/gtest/graphapi_capi_mha_backward.cpp
  test/gtest/graphapi_capi_mha_common.hpp
  test/gtest/graphapi_capi_mha_forward.cpp
Labels: TESTING_CI_PASSED

#3085 [HotFix] Fix build errors on SLES due to incomplete C++17 support
  test/gtest/execute_primitive.cpp
Labels: urgency_blocker

#3068 Fix MIOpenDriver gemm with column ordering
  driver/gemm_driver.hpp
Labels: bug, value_low, urgency_low, TESTING_CI_PASSED

#3091 Merge Fwd Wrw KTN with refactored Adding split_k Wrw for OOTB CVT Performance Improvement
  src/conv/heuristics/ai_heuristics.cpp
  src/include/miopen/conv/heuristics/ai_heuristics.hpp
  src/include/miopen/solver.hpp
  src/include/miopen/solver/implicitgemm_ck_util.hpp
  src/kernels/gfx908_ConvAsm1x1U_metadata.ktn.model
  src/kernels/gfx90a_ConvHipIgemmGroupFwdXdlops_metadata.ktn.model
  src/kernels/gfx90a_ConvHipIgemmGroupXdlops_metadata.ktn.model
  src/kernels/gfx942_ConvHipIgemmGroupFwdXdlops_decoder.ktn.model
  src/kernels/gfx942_ConvHipIgemmGroupFwdXdlops_encoder.ktn.model
  src/kernels/gfx942_ConvHipIgemmGroupFwdXdlops_metadata.ktn.model
  src/kernels/gfx942_ConvHipIgemmGroupWrwXdlops_decoder.ktn.model
  src/kernels/gfx942_ConvHipIgemmGroupWrwXdlops_encoder.ktn.model
  src/kernels/gfx942_ConvHipIgemmGroupWrwXdlops_metadata.ktn.model
  src/kernels/gfx942_ConvHipIgemmGroupXdlops_metadata.ktn.model
  src/solver/conv_hip_implicit_gemm_grouped_bwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_grouped_fwd_xdlops.cpp
  src/solver/conv_hip_implicit_gemm_grouped_wrw_xdlops.cpp
  test/gtest/kernel_tuning_net.cpp
Labels: urgency_blocker
