Repository ROCm/MIOpen, pull requests merged in 2025-06, with the labels that each got.

#3720 [Solvers][Winograd][Gtest] Add fused Winograd Rage solver
  src/conv/kernel_interface/winograd_kernel_interface.cpp
  src/fusion.cpp
  src/include/miopen/conv/kernel_interface/winograd_kernel_interface.hpp
  src/include/miopen/fusion/solvers.hpp
  src/solver.cpp
  src/solver/conv/conv_wino_rage_RxS.cpp
  test/gtest/cba.hpp
  test/gtest/cba_find2.hpp
  test/gtest/cba_find2_infer.cpp
  test/gtest/cba_infer.cpp
Labels: enhancement

#3711 Add sql2text missing header and simplify build.
  tools/sqlite2txt/CMakeLists.txt
  tools/sqlite2txt/main.cpp
Labels: windows

#3705 Docs: Add NHWC Batchnorm documentation
  docs/how-to/use-nhwc-batchnorm-in-pytorch.rst
  docs/index.rst
  docs/sphinx/_toc.yml.in
Labels: documentation

#3838 Resolve issue with gfx90a transpose
  src/hip/batched_transpose_sol.cpp
Labels: bug, urgency_high

#3841 [NFC] Remove static reduction
  src/kernels/static_composable_kernel/include/kernel_algorithm/static_kernel_gridwise_generic_2d_reduction_blockwise.hpp
  src/kernels/static_composable_kernel/include/kernel_algorithm/static_kernel_gridwise_generic_2d_reduction_direct_threadwise.hpp
  src/kernels/static_composable_kernel/include/kernel_algorithm/static_kernel_gridwise_generic_2d_reduction_direct_warpwise.hpp
  src/kernels/static_composable_kernel/include/kernel_algorithm/static_kernel_gridwise_generic_2d_reduction_multiblock.hpp
  src/kernels/static_composable_kernel/include/kernel_algorithm/static_kernel_gridwise_generic_reduction.hpp
  src/kernels/static_composable_kernel/include/kernel_algorithm/static_kernel_reduction_functions.hpp
  src/kernels/static_composable_kernel/include/kernel_algorithm/static_kernel_reduction_kernel_simple_configurator.hpp
  src/kernels/static_composable_kernel/include/utility/static_kernel_reduction_common.hpp
  src/kernels/static_composable_kernel/include/utility/static_kernel_reduction_operator.hpp
  src/kernels/static_composable_kernel/src/kernel_wrapper/static_kernel_gridwise_generic_reduction.cpp
  src/kernels/static_composable_kernel/src/kernel_wrapper/static_kernel_gridwise_generic_reduction_first_call.cpp
  src/kernels/static_composable_kernel/src/kernel_wrapper/static_kernel_gridwise_generic_reduction_second_call.cpp
  src/reducetensor.cpp
Labels: TESTING_CI_PASSED

#3847 [HOTFIX] Fix Wino Rage applicability
  src/conv/invokers/gcn_asm_wino.cpp
  src/conv/kernel_interface/winograd_kernel_interface.cpp
  src/include/miopen/conv/kernel_interface/winograd_kernel_interface.hpp
  src/solver/conv/conv_wino_fury_RxS.cpp
  src/solver/conv/conv_wino_rage_RxS.cpp
  test/gtest/cba_infer.cpp
Labels: bug, urgency_blocker, TESTING_CI_PASSED

#3846 Fix layout calculation logic to match for Enum & String
  src/conv/problem_description.cpp
  src/convolution.cpp
  src/include/miopen/tensor.hpp
  src/tensor.cpp
  test/gtest/unit_conv_ProblemDescription.cpp
Labels: bug, complexity_middle, urgency_high

#3852 Fix no ck build
  src/include/miopen/solver/implicitgemm_ck_util.hpp
Labels: bug
