Repository ROCm/MIOpen, pull requests merged in 2025-01, with the labels that each got.

#3456 Update rocm-recipes for boost link (#3453)
  dev-requirements.txt
  install_deps.cmake
  rbuild.ini
Labels: bug, urgency_blocker, complexity_low

#3457 Update rocm-recipes for boost link (#3453)
  dev-requirements.txt
  install_deps.cmake
  rbuild.ini
Labels: bug, urgency_blocker, complexity_low

#3462 Update license file for 2025
  LICENSE.txt
Labels: documentation

#3406 RNN Dynamic algo single stream
  include/miopen/miopen.h
  src/include/miopen/rnn.hpp
  src/include/miopen/rnn/algorithms/default_algo_utils.hpp
  src/include/miopen/rnn/algorithms/dynamic_algo_utils.hpp
  src/include/miopen/rnn/solvers.hpp
  src/include/miopen/rnn/tmp_buffer_utils.hpp
  src/ocl/rnnocl.cpp
  src/rnn.cpp
  src/rnn/Solutions/Base/bw_data_modular.cpp
  src/rnn/Solutions/Base/bw_weights_modular.cpp
  src/rnn/Solutions/Base/fw_data_modular.cpp
  src/rnn/Solutions/bwd_s_stream.cpp
  src/rnn/Solutions/bww_multi_stream.cpp
  src/rnn/Solutions/bww_s_steam.cpp
  src/rnn/Solutions/fwd_s_stream.cpp
  src/rnn/selector.cpp
  test/rnn_seq_api.cpp
  test/rnn_seq_api.hpp
Labels: urgency_blocker, complexity_middle, urgency_high, TESTING_CI_PASSED

#3455 Fix tensor casting happening in all cases (#3443)
  src/conv/invokers/impl_gemm_dynamic.cpp
Labels: bug, value_high, complexity_low, urgency_high

#3429 Refactor the remaining topics and copy editing
  docs/conceptual/MI200-alt-implementation.rst
  docs/conceptual/cache.rst
  docs/conceptual/finddb.rst
  docs/conceptual/perfdb.rst
  docs/conceptual/porting-guide.rst
  docs/how-to/debug-log.rst
  docs/how-to/find-and-immediate.rst
  docs/how-to/use-fusion-api.rst
Labels: documentation

#3409 Refactor and reformat MIOpen index and install docs
  docs/index.rst
  docs/install/build-source.rst
  docs/install/docker-build.rst
  docs/install/embed.rst
  docs/install/install.rst
  docs/install/prerequisites.rst
  docs/sphinx/_toc.yml.in
  docs/what-is-miopen.rst
Labels: documentation

#3466 Refactor the remaining topics and copy editing (#3429)
  docs/conceptual/MI200-alt-implementation.rst
  docs/conceptual/cache.rst
  docs/conceptual/finddb.rst
  docs/conceptual/perfdb.rst
  docs/conceptual/porting-guide.rst
  docs/how-to/debug-log.rst
  docs/how-to/find-and-immediate.rst
  docs/how-to/use-fusion-api.rst
Labels: documentation

#3461 Fix tensor casting happening in all cases for BF16 & FP16 WRW
  src/solver/conv/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp
  test/gtest/unit_conv_solver.cpp
  test/gtest/unit_conv_solver.hpp
  test/gtest/unit_conv_solver_ConvAsmImplicitGemmGTCDynamicBwdXdlopsNHWC.cpp
  test/gtest/unit_conv_solver_ConvAsmImplicitGemmGTCDynamicFwdXdlopsNHWC.cpp
  test/gtest/unit_conv_solver_ConvAsmImplicitGemmGTCDynamicWrwXdlopsNHWC.cpp
  test/verify.hpp
Labels: bug, value_high, complexity_middle, urgency_high

#3460 Fix tuning timing results
  src/conv/solver_finders.cpp
  src/include/miopen/solver/implicitgemm_ck_util.hpp
Labels: bug, value_middle, performance, complexity_middle, TESTING_CI_PASSED

#3444 [gTest] Add more test coverage for Batchnorm Forward Training
  test/gtest/bn_fwd_train.cpp
  test/gtest/bn_test_data.hpp
Labels: GTest

#3471 Minor post-refactoring edits to documentation
  docs/index.rst
  docs/install/prerequisites.rst
Labels: documentation

#3472 [Bug] Fix tensor casting happening for BF16 BWDs when not using a split-k kernel
  src/conv/invokers/impl_gemm_dynamic.cpp
  test/gtest/unit_conv_solver_ConvAsmImplicitGemmGTCDynamicBwdXdlopsNHWC.cpp
Labels: bug, complexity_low, urgency_high

#3473 [tests] Remove global variables from unit tests
  src/include/miopen/conv/solvers.hpp
  src/include/miopen/solver.hpp
  src/solver.cpp
  src/solver/conv/conv_ocl_dir2Dfwd1x1.cpp
  test/gtest/unit_conv_solver.cpp
  test/gtest/unit_conv_solver.hpp
  test/gtest/unit_conv_solver_ConvOclDirectFwd1x1.cpp
Labels: quality, GTest

#3476 Move miopenSetConvolutionFindMode to the public API
  CMakeLists.txt
  driver/conv_driver.hpp
  include/miopen/miopen.h
  src/find_controls.cpp
  src/include/miopen/generic_search.hpp
  src/include/miopen/miopen_internal.h
  test/gtest/conv_api_find_mode.cpp
Labels: value_middle, complexity_low, tuning, urgency_normal

#3482 Follow up changes for FindMode API
  Jenkinsfile
  include/miopen/config.h.in
  include/miopen/miopen.h
  src/CMakeLists.txt
  src/convolution_api.cpp
  src/include/miopen/find_controls.hpp
  test/gtest/conv_api_find_mode.cpp
Labels: value_middle, complexity_middle, urgency_normal

#3481 Update ci docker to use ROCm 6.3.1 as base image
  Dockerfile
  Jenkinsfile
  test/main.cpp
Labels: complexity_low, urgency_normal

#3427 Softmax log backward : Increase precision of fp16's accumulator to fp32
  driver/softmax_driver.hpp
  src/kernels/MIOpenSoftmax.cl
  test/gtest/softmax_find20.cpp
Labels: TESTING_CI_PASSED
