Repository ROCm/MIOpen, pull requests merged in 2025-02, with the labels that each got.

#3385 adding 3d bn gtest
  test/gtest/bn.hpp
  test/gtest/bn_bwd.cpp
  test/gtest/bn_fwd_train.cpp
  test/gtest/bn_infer.cpp
  test/gtest/bn_test_data.hpp
  test/gtest/test_operations.hpp
Labels: GTest

#3487 Use state for disabling deterministic instead of environment variable
  src/solver/conv/conv_hip_implicit_gemm_3d_grouped_bwd_xdlops.cpp
  src/solver/conv/conv_hip_implicit_gemm_3d_grouped_fwd_xdlops.cpp
  src/solver/conv/conv_hip_implicit_gemm_3d_grouped_wrw_xdlops.cpp
  src/solver/conv/conv_hip_implicit_gemm_grouped_bwd_xdlops.cpp
  src/solver/conv/conv_hip_implicit_gemm_grouped_fwd_xdlops.cpp
  src/solver/conv/conv_hip_implicit_gemm_grouped_wrw_xdlops.cpp
Labels: bug, complexity_middle, urgency_high

#3485 Update Performance Test Pipeline
  .jenkins/perf_test
  Dockerfile
  Jenkinsfile
  test/CMakeLists.txt
  test/test_perf.py
  vars/utils.groovy
Labels: TESTING_CI_PASSED

#3479 Convert softmax from CTest to GTest
  test/gtest/check_names.py
  test/gtest/soft_max.cpp
  test/network_data.hpp
Labels: TESTING_CI_PASSED, GTest

#3494 [tests] Unit tests non-tunable conv asm solvers
  src/hip/handlehip.cpp
  src/include/miopen/conv/solvers.hpp
  src/include/miopen/fusion/utils.hpp
  src/include/miopen/handle.hpp
  src/include/miopen/target_properties.hpp
  src/nogpu/handle.cpp
  src/ocl/handleocl.cpp
  src/solver/conv/conv_MP_bidirectional_winograd.cpp
  src/solver/conv/conv_asm_1x1u.cpp
  src/solver/conv/conv_asm_1x1u_stride2.cpp
  src/solver/conv/conv_asm_3x3u.cpp
  src/solver/conv/conv_asm_5x10u2v2b1.cpp
  src/solver/conv/conv_asm_5x10u2v2f1.cpp
  src/solver/conv/conv_asm_7x7c3h224w224k64u2v2p3q3f1.cpp
  src/solver/conv/conv_asm_dir_BwdWrW1x1.cpp
  src/solver/conv/conv_asm_dir_BwdWrW3x3.cpp
  src/solver/conv/conv_asm_implicit_gemm_bwd_v4r1_dynamic.cpp
  src/solver/conv/conv_asm_implicit_gemm_gtc_bwd.cpp
  src/solver/conv/conv_asm_implicit_gemm_gtc_bwd_nhwc.cpp
  src/solver/conv/conv_asm_implicit_gemm_gtc_fwd.cpp
  src/solver/conv/conv_asm_implicit_gemm_gtc_fwd_nchwc.cpp
  src/solver/conv/conv_asm_implicit_gemm_gtc_fwd_nhwc.cpp
  src/solver/conv/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp
  src/solver/conv/conv_asm_implicit_gemm_v4r1_dynamic.cpp
  src/solver/conv/conv_asm_implicit_gemm_wrw_gtc_dynamic_xdlops.cpp
  src/solver/conv/conv_asm_implicit_gemm_wrw_v4r1_dynamic.cpp
  src/solver/conv/conv_bin_wino3x3U.cpp
  src/solver/conv/conv_bin_winoRxS.cpp
  src/solver/conv/conv_multipass_wino3x3WrW.cpp
  src/solver/conv/conv_winoRxS.cpp
  test/gtest/conv_igemm_dynamic_xdlops.cpp
  test/gtest/conv_igemm_dynamic_xdlops_half.cpp
  test/gtest/conv_igemm_dynamic_xdlops_nhwc_bf16.cpp
  test/gtest/conv_igemm_dynamic_xdlops_nhwc_nchw.cpp
  test/gtest/gtest_common.cpp
  test/gtest/gtest_common.hpp
  test/gtest/smoke_solver_ConvAsm_5x10_7x7.cpp
  test/gtest/unit_conv_solver.cpp
  test/gtest/unit_conv_solver_ConvAsm5x10u2v2b1.cpp
  test/gtest/unit_conv_solver_ConvAsm5x10u2v2f1.cpp
  test/gtest/unit_conv_solver_ConvAsm7x7c3h224w224k64u2v2p3q3f1.cpp
Labels: quality, TESTING_CI_PASSED, GTest

#3509 [hotfix] Temporary disable unit test for ConvAsm5x10u2v2b1
  test/gtest/unit_conv_solver_ConvAsm5x10u2v2b1.cpp
Labels: urgency_blocker

#3508 Fix package stage not running properly
  Jenkinsfile
Labels: bug, value_middle, complexity_low, urgency_normal

#3507 Set mFinalized to true in BackendEngineDescriptor contructor
  src/include/miopen/graphapi/engine.hpp
Labels: bug, TESTING_CI_PASSED

#3514 [HotFix] Fix Windows build after #3494
  src/include/miopen/conv/solvers.hpp
Labels: urgency_blocker

#3504 [RNN][gtest] GRU test fix
  test/gru_common.hpp
  test/gtest/deepbench_gru.cpp
  test/gtest/deepbench_rnn.cpp
Labels: testing, urgency_normal, GTest

#3515 Swap to using median value with outliers removed for deciding on best solution to run
  src/conv/solver_finders.cpp
  src/include/miopen/generic_search.hpp
  src/include/miopen/utility/modified_z.hpp
  test/gtest/unit_modified_z.cpp
Labels: value_middle, complexity_middle, urgency_high

#3399 [BN] Enable NHWC in OCL
  driver/bn_driver.hpp
  src/batch_norm.cpp
  src/driver_arguments.cpp
  src/kernels/MIOpenBatchNormBwdSpatial.cl
  src/kernels/MIOpenBatchNormFwdInferPerAct.cl
  src/kernels/MIOpenBatchNormFwdInferSpatial.cl
  src/kernels/MIOpenBatchNormFwdTrainSpatial.cl
  src/kernels/batchnorm_functions.h
  src/kernels/reduction_functions.h
  src/ocl/batchnormocl.cpp
  src/solver/batchnorm/backward_spatial_multiple.cpp
  src/solver/batchnorm/backward_spatial_single.cpp
  src/solver/batchnorm/forward_inference.cpp
  src/solver/batchnorm/forward_spatial_multiple.cpp
  src/solver/batchnorm/forward_spatial_single.cpp
  test/fusionHost.hpp
  test/gtest/bn.hpp
  test/gtest/bn_bwd.cpp
  test/gtest/bn_fwd_train.cpp
  test/gtest/bn_infer.cpp
  test/gtest/bn_test_data.hpp
  test/gtest/test_operations.hpp
  test/random.hpp
Labels: urgency_high

#3557 Fix docker build
  Dockerfile
  vars/utils.groovy
Labels: urgency_blocker, complexity_middle

#3556 Remove phantom example text from API documentation
  include/miopen/miopen.h
Labels: documentation

#3560 Revert CK hash changes and docker fixes
  Dockerfile
  requirements.txt
  vars/utils.groovy
Labels: urgency_blocker, complexity_middle
