Repository ROCm/MIOpen, pull requests merged in 2025-03, with the labels that each got.

#3570 [GTest] Disable DBSync test for gfx11 and gfx12
  test/gtest/db_sync.cpp
Labels: TESTING_CI_PASSED

#3581 Fix SWDEV-518994
  src/solver.cpp
Labels: urgency_blocker, TESTING_CI_PASSED

#3565 Dockerfile/Jenkins Improvements.
  Dockerfile
  vars/utils.groovy
Labels: complexity_middle, urgency_high

#3598 [tests] Unit tests for ConvAsmImplicitGemm solvers
  test/CMakeLists.txt
  test/gtest/conv_igemm_dynamic.cpp
  test/gtest/conv_igemm_dynamic_xdlops.cpp
  test/gtest/conv_igemm_dynamic_xdlops_half.cpp
  test/gtest/smoke_solver_ConvAsmImplicitGemmGTCDynamicXdlops.cpp
  test/gtest/smoke_solver_ConvAsmImplicitGemmV4R1Dynamic.cpp
  test/gtest/unit_conv_solver_ConvAsmImplicitGemmGTCDynamicBwdXdlops.cpp
  test/gtest/unit_conv_solver_ConvAsmImplicitGemmGTCDynamicFwdXdlops.cpp
  test/gtest/unit_conv_solver_ConvAsmImplicitGemmGTCDynamicWrwXdlops.cpp
  test/gtest/unit_conv_solver_ConvAsmImplicitGemmV4R1DynamicBwd.cpp
  test/gtest/unit_conv_solver_ConvAsmImplicitGemmV4R1DynamicFwd.cpp
  test/gtest/unit_conv_solver_ConvAsmImplicitGemmV4R1DynamicFwd_1x1.cpp
  test/gtest/unit_conv_solver_ConvAsmImplicitGemmV4R1DynamicWrw.cpp
Labels: quality, TESTING_CI_PASSED, GTest

#3586 [tests] Unit test for #3572
  test/gtest/unit_lib_env_var.cpp
  test/lib_env_var.hpp
Labels: quality, TESTING_CI_PASSED, GTest

#3628 Fix hipRTC compilation issue for float8
  src/include/miopen/datatype.hpp
  src/kernels/gpu_reference_kernel/fp8_kern_types.h
Labels: bug, urgency_blocker, complexity_low

#3609 [tests] Unit tests for ConvWinograd3x3MultipassWrW
  src/env_debug.cpp
  src/include/miopen/conv/solvers.hpp
  src/solver/conv/conv_multipass_wino3x3WrW.cpp
  test/CMakeLists.txt
  test/gtest/unit_conv_solver_ConvWinograd3x3MultipassWrWF1x1x7x2.cpp
  test/gtest/unit_conv_solver_ConvWinograd3x3MultipassWrWF1x1x7x3.cpp
  test/gtest/unit_conv_solver_ConvWinograd3x3MultipassWrWF3x2.cpp
  test/gtest/unit_conv_solver_ConvWinograd3x3MultipassWrWF3x3.cpp
  test/gtest/unit_conv_solver_ConvWinograd3x3MultipassWrWF3x4.cpp
  test/gtest/unit_conv_solver_ConvWinograd3x3MultipassWrWF3x5.cpp
  test/gtest/unit_conv_solver_ConvWinograd3x3MultipassWrWF3x6.cpp
  test/gtest/unit_conv_solver_ConvWinograd3x3MultipassWrWF5x3.cpp
  test/gtest/unit_conv_solver_ConvWinograd3x3MultipassWrWF5x4.cpp
  test/gtest/unit_conv_solver_ConvWinograd3x3MultipassWrWF7x2.cpp
  test/gtest/unit_conv_solver_ConvWinograd3x3MultipassWrWF7x2x1x1.cpp
  test/gtest/unit_conv_solver_ConvWinograd3x3MultipassWrWF7x3.cpp
  test/gtest/unit_conv_solver_ConvWinograd3x3MultipassWrWF7x3x1x1.cpp
Labels: quality, TESTING_CI_PASSED, GTest

#3637 [tests] Fix tolerance for miopenConvolutionAlgoImplicitGEMM on MI100
  test/gtest/unit_conv_solver.cpp
Labels: TESTING_CI_PASSED, GTest

#3636 remove variant calculation in batch norm's network config
  src/batchnorm/problem_description.cpp
  src/include/miopen/batchnorm/problem_description.hpp
Labels: TESTING_CI_PASSED

#3583 fix bn tuning issue with CK batchnorm solvers
  driver/bn_driver.hpp
  src/include/miopen/solver/implicitgemm_ck_util.hpp
Labels: TESTING_CI_PASSED

#3654 [GTests] Fix for SWDEV-522871
  test/gtest/unit_conv_solver_ConvHipImplicitGemmBwdXdlops.cpp
  test/gtest/unit_conv_solver_ConvHipImplicitGemmFwdXdlops.cpp
Labels: workaround, TESTING_CI_PASSED, GTest

#3655 Swap to hipMemcpyWithStream to ensure correct stream usage in all cases
  src/hip/handlehip.cpp
  src/ocl/ctcocl.cpp
Labels: correctness
