Repository ROCm/MIOpen, pull requests merged in 2025-05, with the labels that each got.

#3717 mainline rocblas cherrypicks
  src/gemm_v2.cpp
  src/include/miopen/gemm_v2.hpp
  src/solver/conv/gemm.cpp
  src/solver/conv/gemm_bwd.cpp
  src/solver/conv/gemm_wrw.cpp
  src/solver/mha/mha_common.hpp
  test/gtest/gpu_mha_backward.cpp
  test/gtest/gpu_mha_forward.cpp
  test/gtest/graphapi_capi_mha_backward.cpp
  test/gtest/graphapi_capi_mha_forward.cpp
  test/gtest/mha_helper.hpp
Labels: urgency_blocker

#3724 Fix static tests failing due to missing rocBLAS linkage when MIOpen is built as a static lib
  test/CMakeLists.txt
  test/gtest/CMakeLists.txt
Labels: bug, urgency_blocker

#3715 Skip FindCore when user specified workspace is smaller than required
  src/include/miopen/generic_search.hpp
Labels: bug
