Repository ROCm/MIOpen, pull requests merged in 2025-04, with the labels that each got.

#3663 Update 6.4 change log to include batchnorm changes
  CHANGELOG.md
Labels: complexity_low, documentation

#3670 [FIX] replacement for deprecated intrinsics.
  src/include/miopen/solver/implicitgemm_util.hpp
  src/kernels/gfx908.kdb.bz2
  src/kernels/gfx90a.kdb.bz2
  src/kernels/gfx942.kdb.bz2
  src/kernels/static_composable_kernel/include/utility/amd_buffer_intrinsics.hpp
  src/kernels/static_composable_kernel/include/utility/static_kernel_amd_buffer_addressing.hpp
  src/kernels/static_composable_kernel/include/utility/static_kernel_config.hpp
  src/solver/conv/conv_hip_implicit_gemm_bwd_v1r1.cpp
  src/solver/conv/conv_hip_implicit_gemm_bwd_v1r1_xdlops.cpp
  src/solver/conv/conv_hip_implicit_gemm_bwd_v4r1.cpp
  src/solver/conv/conv_hip_implicit_gemm_bwd_v4r1_xdlops.cpp
  src/solver/conv/conv_hip_implicit_gemm_fwd_v4r1.cpp
  src/solver/conv/conv_hip_implicit_gemm_fwd_v4r4.cpp
  src/solver/conv/conv_hip_implicit_gemm_fwd_v4r4_xdlops.cpp
  src/solver/conv/conv_hip_implicit_gemm_fwd_v4r4_xdlops_padded_gemm.cpp
  src/solver/conv/conv_hip_implicit_gemm_fwd_v4r5_xdlops.cpp
  src/solver/conv/conv_hip_implicit_gemm_wrw_v4r4.cpp
  src/solver/conv/conv_hip_implicit_gemm_wrw_v4r4_xdlops.cpp
  src/solver/conv/conv_hip_implicit_gemm_wrw_v4r4_xdlops_padded_gemm.cpp
  test/gtest/unit_conv_solver_ConvHipImplicitGemmBwdDataV1R1.cpp
  test/gtest/unit_conv_solver_ConvHipImplicitGemmBwdDataV1R1Xdlops.cpp
  test/gtest/unit_conv_solver_ConvHipImplicitGemmBwdDataV4R1.cpp
  test/gtest/unit_conv_solver_ConvHipImplicitGemmBwdDataV4R1Xdlops.cpp
  test/gtest/unit_conv_solver_ConvHipImplicitGemmForwardV4R4Xdlops.cpp
  test/gtest/unit_conv_solver_ConvHipImplicitGemmForwardV4R4Xdlops_Padded_Gemm.cpp
  test/gtest/unit_conv_solver_ConvHipImplicitGemmForwardV4R5Xdlops.cpp
  test/gtest/unit_conv_solver_ConvHipImplicitGemmV4R1Fwd.cpp
  test/gtest/unit_conv_solver_ConvHipImplicitGemmV4R1WrW.cpp
  test/gtest/unit_conv_solver_ConvHipImplicitGemmV4R4Fwd.cpp
  test/gtest/unit_conv_solver_ConvHipImplicitGemmV4R4WrW.cpp
  test/gtest/unit_conv_solver_ConvHipImplicitGemmWrwV4R4Xdlops.cpp
  test/gtest/unit_conv_solver_ConvHipImplicitGemmWrwV4R4Xdlops_Padded_Gemm.cpp
Labels: IMPACTS_FIND_DB

#3674 Docs: Fix a few errors in the Table of Contents
  docs/sphinx/_toc.yml.in
Labels: documentation

#3678 [tests] Fix SWDEV-527347
  test/gtest/unit_conv_solver_ConvAsmImplicitGemmGTCDynamicBwdXdlopsNHWC.cpp
  test/gtest/unit_conv_solver_ConvAsmImplicitGemmGTCDynamicFwdXdlopsNHWC.cpp
  test/gtest/unit_conv_solver_ConvAsmImplicitGemmGTCDynamicWrwXdlopsNHWC.cpp
Labels: GTest

#3689 [FIX] HipImplicitGemm add atomics intrinsic
  src/kernels/gfx908.kdb.bz2
  src/kernels/static_composable_kernel/include/utility/amd_buffer_intrinsics.hpp
  src/kernels/static_composable_kernel/include/utility/static_kernel_amd_buffer_addressing.hpp
Labels: TESTING_CI_PASSED

#3676 Cherry-pick to docs/6.4.0: Docs Fix a few errors in the Table of Contents (#3674)
  docs/sphinx/_toc.yml.in
Labels: documentation

#3675 Cherry-pick to rocm-rel-6.4: Docs: Fix a few errors in the Table of Contents (#3674)
  docs/sphinx/_toc.yml.in
Labels: documentation

#3697 [Hotfix]delete the buggy mha f8 code section
  src/solver/mha/mha_common.hpp
Labels: bug, urgency_blocker

#3698 Suppress new appearing compilation warnings for Clang from HIP SDK/ROCm 6.4
  cmake/EnableCompilerWarnings.cmake
Labels: urgency_blocker, windows, uai
