Repository ROCm/MIOpen, pull requests merged in 2025-07, with the labels that each got.

#3854 [DRIVER] Fix inconsistent and incorrect conv stats prints
  driver/conv_driver.hpp
Labels: TESTING_CI_PASSED

#3833 Fix NCHW precision issues for fused CBA/CA solvers
  driver/CBAInferFusion_driver.hpp
  driver/tensor_driver.hpp
  include/miopen/miopen.h
  src/fused_api.cpp
  src/fusion.cpp
  src/include/miopen/fusion_plan.hpp
  src/solver/conv_ck_igemm_grp_fwd_activ_fused.cpp
  src/solver/conv_ck_igemm_grp_fwd_bias_activ_fused.cpp
  test/cba_inference.cpp
  test/gtest/cba_infer.cpp
  test/gtest/conv_activ_infer.cpp
Labels: TESTING_CI_PASSED

#3857 Use legacy fusion solvers iff modern solvers aren't applicable
  src/include/miopen/fusion/utils.hpp
  src/solver/conv_asm_1x1u_bias_activ_fused.cpp
  src/solver/conv_ocl_dir2Dfwd_fused.cpp
Labels: TESTING_CI_PASSED

#3604 Find Mode TrustVerify
  docs/conceptual/tuningdb.rst
  docs/how-to/find-and-immediate.rst
  driver/util_driver.hpp
  include/miopen/miopen.h
  src/conv/solver_finders.cpp
  src/convolution.cpp
  src/find_controls.cpp
  src/generic_search.cpp
  src/include/miopen/conv/solver_finders.hpp
  src/include/miopen/convolution.hpp
  src/include/miopen/find_controls.hpp
  src/include/miopen/generic_search.hpp
  src/include/miopen/generic_search_controls.hpp
  src/ocl/convolutionocl.cpp
  test/conv_common.hpp
  test/gtest/conv_api_find_mode.cpp
  test/gtest/find_mode_trust_verify.cpp
Labels: TESTING_CI_PASSED

#3885 Igemm asm solver update
  src/kernels/gfx908.kdb.bz2
  src/kernels/gfx90a.kdb.bz2
  src/kernels/gfx942.kdb.bz2
  src/solver/conv/conv_asm_implicit_gemm_gtc_bwd_nhwc.cpp
  src/solver/conv/conv_asm_implicit_gemm_gtc_fwd_nhwc.cpp
  src/solver/conv/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp
Labels: TESTING_CI_PASSED

#3870 Docs: Update fusion API doc and add link to samples
  docs/data/how-to/bn_activ_fused.png
  docs/data/how-to/cba.png
  docs/data/how-to/na.png
  docs/how-to/use-fusion-api.rst
  docs/how-to/use-nhwc-batchnorm-in-pytorch.rst
  docs/index.rst
  docs/sphinx/_toc.yml.in
Labels: documentation

#3880 Fix or remove Intersphinx links on API reference page
  docs/reference/index.rst
Labels: documentation

#3897 Cherry-pick to release/rocm-rel-70: Fix or remove Intersphinx links on API reference page (#3880)
  docs/reference/index.rst
Labels: documentation

#3888 Enable Batchnorm tests on Navi3x 4x
  test/gtest/bn.hpp
Labels: GTest

#3906 Export directive added for GetWorkspaceSize function for Windows build
  driver/sys_info.hpp
  src/include/miopen/fusion/solvers.hpp
Labels: urgency_high

#3924 Fix or remove Intersphinx links on API reference page (#3880)
  docs/reference/index.rst
Labels: documentation
